add fine_grained_shuffle doc
pingcap/docs-cn pull request #10515
Opened 2022-07-14 03:21 UTC by guo-shaoge

Signed-off-by: guo-shaoge <shaoge1994@163.com>

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

Add two system vars description.
### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [ ] v6.2 (TiDB 6.2 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-07-14 03:29 UTC, shichun-0415 commented
/cc @moyun

2022-07-14 06:27 UTC, hfxsd commented on system-variables.md
> +    * -1: 表示使用细粒度 shuffle 功能。如果 `tidb_max_tiflash_threads` 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min
```suggestion
    * -1: 表示使用细粒度 shuffle 功能。如果 `tidb_max_tiflash_threads` 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min(`tiflash_fine_grained_shuffle_stream_count`，TiFlash 节点物理线程数)
```
```suggestion
    * -1: 表示使用细粒度 shuffle 功能。如果 `tidb_max_tiflash_threads` 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min(`tiflash_fine_grained_shuffle_stream_count`,     TiFlash 节点物理线程数)
```

2022-07-14 06:28 UTC, hfxsd commented on system-variables.md
> +- 对性能影响：该值设置过小，会导致数据发送过于频繁，降低向量化效果。如果设置过大会导致发送频率过低，接收端大部分时间在等待数据，影响性能。
```suggestion
- 对性能影响：请根据业务情况设置合理的大小，设置不当会影响性能。如果该值设置过小，会导致数据发送过于频繁，降低向量化效果。如果设置过大，会导致发送频率过低，接收端大部分时间在等待数据，影响性能。
```

2022-07-15 02:06 UTC, hfxsd commented on system-variables.md
> +- 建议：WindowFunction 的性能应该随着该值的增加线性提升。但是如果设置过大，超过实际的物理线程数，反而会导致性能下降。
```suggestion
- 建议：WindowFunction 的性能应该随着该值的增加线性提升。但是如果设置的值超过实际的物理线程数，反而会导致性能下降。
```

2022-07-15 02:29 UTC, hfxsd commented on system-variables.md
> +    * -1: 表示使用细粒度 shuffle 功能。如果 `tidb_max_tiflash_threads` 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min
```suggestion
    * 0: 表示不使用细粒度 shuffle 功能，下推到 TiFlash 的 WindowFunction 以单线程方式执行。
    * 大于 0: 表示使用细粒度 shuffle 功能，下推到 TiFlash 的 WindowFunction 会以多线程方式执行，并发度为： min(`tiflash_fine_grained_shuffle_stream_count`, TiFlash 节点物理线程数)。
    * -1: 表示使用细粒度 shuffle 功能。如果 `tidb_max_tiflash_threads` 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min(`tiflash_fine_grained_shuffle_stream_count`，TiFlash 节点物理线程数)。
```

2022-07-15 03:46 UTC, ran-huang commented on system-variables.md
> +- 当 WindowFunction 下推到 TiFlash 执行时，可以通过该变量控制 WindowFunction 执行的并行度。不同取值含义：
WindowFunction 可以直接写窗口函数吗

2022-07-15 03:47 UTC, ran-huang commented on system-variables.md
> +- 当 WindowFunction 下推到 TiFlash 执行时，可以通过该变量控制 WindowFunction 执行的并行度。不同取值含义：
建议把变量按字母顺序排列

2022-07-15 05:43 UTC, ran-huang commented on system-variables.md
> +    * -1: 表示使用细粒度 shuffle 功能。如果 `tidb_max_tiflash_threads` 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min
`tidb_max_tiflash_threads` 的链接可以附上

2022-07-15 06:03 UTC, hfxsd commented on system-variables.md
> +    * -1: 表示使用细粒度 shuffle 功能。如果 `tidb_max_tiflash_threads` 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min
```suggestion
    * -1: 表示使用细粒度 shuffle 功能。如果 [`tidb_max_tiflash_threads`](/system-variables.md#tidb_max_tiflash_threads-从-v610-版本开始引入) 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min(`tiflash_fine_grained_shuffle_stream_count`，TiFlash 节点物理线程数)。
```

2022-07-15 06:03 UTC, hfxsd commented on system-variables.md
> +- 当 WindowFunction 下推到 TiFlash 执行时，可以通过该变量控制 WindowFunction 执行的并行度。不同取值含义：
@guo-shaoge 麻烦看下？

2022-07-15 06:08 UTC, guo-shaoge commented on system-variables.md
> +- 当 WindowFunction 下推到 TiFlash 执行时，可以通过该变量控制 WindowFunction 执行的并行度。不同取值含义：
done

2022-07-15 06:13 UTC, guo-shaoge commented on system-variables.md
> +    * -1: 表示使用细粒度 shuffle 功能。如果 `tidb_max_tiflash_threads` 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 `tidb_max_tiflash_threads` ，否则为默认值 8 。最终在 TiFlash 上 WindowFunction 的实际并发度为：min
done

2022-07-15 10:06 UTC, ran-huang approved these changes

2022-07-18 02:08 UTC, hfxsd approved these changes
LGTM

2022-07-25 08:10 UTC, guo-shaoge commented on system-variables.md
> +- 建议窗口函数的性能应该随着该值的增加线性提升。但是如果设置的值超过实际的物理线程数，反而会导致性能下降。
```suggestion
- 理论上窗口函数的性能会随着该值的增加线性提升。但是如果设置的值超过实际的物理线程数，反而会导致性能下降。
```

2022-07-26 12:49 UTC, moyun requested changes

2022-07-26 12:49 UTC, moyun commented on system-variables.md
> +
这段话稍微修改一下吧，这么写别人比较难理解到底应该怎么设置，那个取值域那么宽，都是有意义的吗？假如取极端值会有什么具体的意义？
建议这么描述改变这个值的效果： 缩小此数值，可以导致`正反两方面的什么样的影响`；此值增大，可导致`正反两方面的什么样的影响`。建议用户`如何调整`此数值（给一个怎么样观测效果调整数值方法）。

2022-07-26 12:49 UTC, moyun commented on system-variables.md
> +    * -1: 表示使用细粒度 shuffle 功能。如果 [`tidb_max_tiflash_threads`](/system-variables.md#tidb_max_tiflash_threads-从-v610-版本开始引入) 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 [`tidb_max_tifl
这几个数值代表的意义不太合乎常规习惯吧？ -1 == enable， 0 == disable ？ ... > 0 又代表 enable && parallelism, 这是不是混乱了点？ disable 和 enable 映射到取值范围上还不连续呀？

2022-07-28 06:00 UTC, guo-shaoge commented on system-variables.md
> +    * -1: 表示使用细粒度 shuffle 功能。如果 [`tidb_max_tiflash_threads`](/system-variables.md#tidb_max_tiflash_threads-从-v610-版本开始引入) 有效（大于 0），则 `tiflash_fine_grained_shuffle_stream_count` 会自动取值为 [`tidb_max_tifl
working on it:https://github.com/pingcap/tidb/pull/36621

2022-07-29 03:01 UTC, moyun commented on system-variables.md
> +    * 大于 0: 表示使用细粒度 shuffle 功能，下推到 TiFlash 的窗口函数会以多线程方式执行，并发度为： min(`tiflash_fine_grained_shuffle_stream_count`, TiFlash 节点物理线程数)
描述的顺序可否调整一下？

1. `-1`， 
2. `0`， 
3. `>0`

2022-07-29 03:04 UTC, guo-shaoge commented on system-variables.md
> +    * 大于 0: 表示使用细粒度 shuffle 功能，下推到 TiFlash 的窗口函数会以多线程方式执行，并发度为： min(`tiflash_fine_grained_shuffle_stream_count`, TiFlash 节点物理线程数)
done

2022-08-01 03:15 UTC, moyun commented
LGTM

2022-08-01 03:15 UTC, moyun approved these changes

2022-08-01 03:27 UTC, hfxsd commented
/merge

2022-08-01 03:28 UTC, merged