Update tiflash-620-upgrade-guide.md
pingcap/docs-cn pull request #10866
Opened 2022-08-11 08:05 UTC by joey-yez

add new statement for experiment feature: fastscan.

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)
Only documents modified.

Add new statement for the experimental feature: FastScan.
### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v6.2 (TiDB 6.2 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-08-11 08:29 UTC, hfxsd commented
/verify

2022-08-11 13:17 UTC, shichun-0415 commented
@joey-yez @hfxsd Refined the structure to better fit the whole guide. PTAL.

2022-08-12 01:16 UTC, moyun commented on tiflash-620-upgrade-guide.md
> +从 v6.1 升级至 v6.2 时，需要注意 v6.2.0 PageStorage 变更数据版本和引入实验特性 FastScan 带来的影响。具体请参考 [PageStorage](#pagestorage) 和 [FastScan](#fastscan)。
这个说法按下面改一下，这里只是需要提醒用户实验功能是可能发生形态改变的，不必再提 “PageStorage 变更数据版本”了，这个不是实验功能。 参考一下这个：[PR](https://github.com/pingcap/docs-cn/pull/10831)

> ### 关于 v6.2.0 的新增实验功能
> 
> v6.2.0 新增了一项名为[fastScan｜fastmode](/tiflash/？？？) 的实验功能。该实验功能在牺牲强一致性保证的前提下可以大幅提升扫表性能。相关实验功能的形态和使用方式有可能在后续版本中发生变化，提请用户在使用中注意。

2022-08-12 01:16 UTC, moyun requested changes
please update accordingly

2022-08-12 06:52 UTC, shichun-0415 commented on tiflash-620-upgrade-guide.md
> +TiFlash 在 v6.2.0 将数据格式升级到 V3 版本，同时，引入了一个新的实验特性 [FastScan](/develop/dev-guide-use-fastscan.md)，因此，从 v5.x 或 v6.0 升级至 v6.2 时，除了需要注意 [TiFlash Proxy](#tiflash-proxy) 和[动态分区裁剪](#动态分区裁剪)的变化，还应注意 PageStorage
```suggestion
TiFlash 在 v6.2.0 将数据格式升级到 V3 版本，因此，从 v5.x 或 v6.0 升级至 v6.2 时，除了需要注意 [TiFlash Proxy](#tiflash-proxy) 和[动态分区裁剪](#动态分区裁剪)的变化，还应注意 PageStorage 和 FastScan 功能的变化。
```

2022-08-12 06:52 UTC, shichun-0415 commented on tiflash-620-upgrade-guide.md
> +
```suggestion
```

2022-08-12 06:52 UTC, shichun-0415 commented on tiflash-620-upgrade-guide.md
> +从 v6.1 升级至 v6.2 时，需要注意 v6.2.0 PageStorage 变更数据版本和引入实验特性 FastScan 带来的影响。具体请参考 [PageStorage](#pagestorage) 和 [FastScan](#fastscan)。
```suggestion
从 v6.1 升级至 v6.2 时，需要注意 PageStorage 变更数据版本带来的影响。具体请参考 [PageStorage](#pagestorage)。
```

2022-08-12 07:21 UTC, shichun-0415 approved these changes
LGTM

2022-08-12 07:33 UTC, moyun commented on tiflash-620-upgrade-guide.md
> -TiFlash 在 v6.2.0 将数据格式升级到 V3 版本，因此，从 v5.x.x 或 v6.0.0 升级至 v6.2.0 时，除了需要注意 [TiFlash Proxy](#tiflash-proxy) 和[动态分区裁剪](#动态分区裁剪)的变化，还应注意 PageStorage 功能的变化。
这句话精简一下吧：
TiFlash 在 v6.2.0 将数据格式升级到 V3 版本，因此从 v5.x 或 v6.0 升级至 v6.2 时，除了需要注意 [TiFlash Proxy](https://github.com/pingcap/docs-cn/blob/79b423973f32f4e7e2c26df77e41a253428a1720/tiflash-620-upgrade-guide.md#tiflash-proxy) 和[动态分区裁剪](https://github.com/pingcap/docs-cn/blob/79b423973f32f4e7e2c26df77e41a253428a1720/tiflash-620-upgrade-guide.md#%E5%8A%A8%E6%80%81%E5%88%86%E5%8C%BA%E8%A3%81%E5%89%AA)的变化，还应注意 以下几点注意事项。

2022-08-12 07:53 UTC, shichun-0415 commented on tiflash-620-upgrade-guide.md
> +从 v6.1 升级至 v6.2 时，需要注意 PageStorage 变更数据版本带来的影响。具体请参考 [PageStorage](#pagestorage)。
```suggestion
从 v6.1 升级至 v6.2 时，需要注意 PageStorage 变更数据版本带来的影响。具体请参考 [从 v5.x 或 v6.0 升级至 v6.2](#从-v5x-或-v60-升级至-v62) 中关于 PageStorage 的描述。
```

2022-08-12 09:42 UTC, moyun reviewed
LGTM

2022-08-12 10:45 UTC, moyun approved these changes

2022-08-16 05:44 UTC, hfxsd approved these changes
LGTM

2022-08-17 01:25 UTC, shichun-0415 commented
/merge

2022-08-17 01:26 UTC, merged