br: update pitr docs
pingcap/docs-cn pull request #11184
Opened 2022-09-02 07:56 UTC by Leavrth

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [ ] master (the latest development version)
- [ ] v6.3 (TiDB 6.3 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-09-06 08:03 UTC, shichun-0415 commented on tikv-configuration-file.md
> ++ 日志备份任务的备份数据在合并过程中的划分阈值。
感觉目前这个描述太简略了，尝试加了点说明，请看看对不对。 @Leavrth 
```suggestion
+ 日志备份任务中，合并备份数据的阈值。如果已经备份的数据大小达到该配置项的取值，则将这些备份数据合并为一个备份文件，从而避免产生过多小文件。
```

2022-09-06 08:03 UTC, shichun-0415 commented on tikv-configuration-file.md
> ++ 默认值：256MB
标准写法似乎是 MiB
```suggestion
+ 默认值：256MiB
```

2022-09-06 08:29 UTC, shichun-0415 commented on tikv-configuration-file.md
> ++ 日志备份任务中，合并备份数据的阈值。如果待上传的备份数据文件大小总和达到该配置项的取值，则将这些备份数据文件合并为一个备份文件，从而避免产生过多小文件。
“则将这些备份数据文件合并为一个备份文件” 请问执行主体是哪个呢？BR 么？或者这个操作是自动进行的？

2022-09-06 08:29 UTC, shichun-0415 commented on tikv-configuration-file.md
> ++ 注意：`merged-file-size-limit` 的值一般情况下会大于存储系统上备份文件显示的大小，这是因为在上传备份文件前进行了压缩。
参数取值大跟上传备份文件进行压缩的因果关系没太明白

2022-09-06 08:32 UTC, Leavrth commented on tikv-configuration-file.md
> ++ 日志备份任务中，合并备份数据的阈值。如果待上传的备份数据文件大小总和达到该配置项的取值，则将这些备份数据文件合并为一个备份文件，从而避免产生过多小文件。
执行主体是 TiKV。这是 TiKV 的行为，也就是从`以前的每个小文件都各自上传到外部存储`转变为`将经过压缩的一部分小文件上传到外部存储上的同一个备份文件中去`。

2022-09-06 08:41 UTC, Leavrth commented on tikv-configuration-file.md
> ++ 注意：`merged-file-size-limit` 的值一般情况下会大于存储系统上备份文件显示的大小，这是因为在上传备份文件前进行了压缩。
比如有 5 个小文件，它们分别为 `f1-128MiB`、`f2-64MiB`、`f3-72MiB`、`f4-32MiB` 和 `f5-16MiB`。其中 `f1-128MiB` 的格式为 `小文件名-小文件大小`。
如果 `merged-file-size-limit` 的值为 256 MiB，那么 TiKV 就会发现 `f1`、`f2` 和 `f3` 的大小总和为 264 MiB，大于 `merged-file-size-limit` 的值，则上传到外部存储的文件为 `F1`，其中 `F1` 包含了 `f1`、`f2` 和 `f3` 的数据内容。因此 `F1` 的大小为 `264 MiB`。
但这里又加了层压缩过程，也就是在上传前，`f1`、`f2` 和 `f3` 会被压缩为 `cf1`、`cf2` 和 `cf3`，它们的大小就可能变为 `28 MiB`、`10 MiB` 和 `16 MiB`，那么上传到外部存储的文件就为 `CF1`，其中 `CF1` 包含了 `cf1`、`cf2` 和 `cf3` 的数据内容。因此 `CF1` 的大小为 `54 MiB`。

2022-09-06 11:22 UTC, shichun-0415 approved these changes
Rest LGTM

2022-09-06 11:22 UTC, shichun-0415 commented on tikv-configuration-file.md
> ++ 日志备份任务中，合并备份数据的阈值。如果待上传的备份数据文件大小总和达到该配置项的取值，则将这些备份数据文件合并为一个备份文件，从而避免产生过多小文件。
```suggestion
+ 日志备份任务中，合并备份数据的阈值。如果待上传的备份数据文件大小总和达到该配置项的取值，TiKV 会将这些备份数据文件合并为一个备份文件进行上传，从而避免上传过多小文件。
```

2022-09-06 11:22 UTC, shichun-0415 commented on tikv-configuration-file.md
> ++ 注意：`merged-file-size-limit` 的值一般情况下会大于存储系统上备份文件显示的大小，这是因为在上传备份文件前进行了压缩。
```suggestion
+ 注意：一般情况下，`merged-file-size-limit` 的值会大于存储系统上显示的备份文件大小，这是因为备份文件在上传时会被压缩。
```

2022-09-07 02:55 UTC, IANTHEREAL commented on tikv-configuration-file.md
> ++ 日志备份任务中，合并备份数据的阈值。如果待上传的备份数据文件大小总和达到该配置项的取值，则将这些备份数据文件合并为一个备份文件，从而避免产生过多小文件。
这个跟 `file-size-limi` 冲突不，这两个参数是不是可以合并成一个？

2022-09-08 01:54 UTC, IANTHEREAL requested changes
please confirm the new added parameters

2022-09-08 01:54 UTC, IANTHEREAL requested changes
please confirm the new added parameters

2022-09-08 02:27 UTC, Leavrth commented on tikv-configuration-file.md
> ++ 日志备份任务中，合并备份数据的阈值。如果待上传的备份数据文件大小总和达到该配置项的取值，则将这些备份数据文件合并为一个备份文件，从而避免产生过多小文件。
> 从名称上，这个跟 `file-size-limit` 冲突不，这两个参数是不是可以合并成一个？

应该不能合并。`file-size-limit` 是小文件的大小限制，避免单个小文件太大，`merged_file_size_limit` 是多个小文件合并后的大小总和限制，避免合并后的文件太大。

2022-09-08 03:24 UTC, Leavrth commented on tikv-configuration-file.md
> ++ 日志备份任务中，合并备份数据的阈值。如果待上传的备份数据文件大小总和达到该配置项的取值，则将这些备份数据文件合并为一个备份文件，从而避免产生过多小文件。
> > 从名称上，这个跟 `file-size-limit` 冲突不，这两个参数是不是可以合并成一个？
> 
> 应该不能合并。`file-size-limit` 是小文件的大小限制，避免单个小文件太大，`merged_file_size_limit` 是多个小文件合并后的大小总和限制，避免合并后的文件太大。

通过保持两个参数的值相同来合并这两个参数。

2022-09-08 03:35 UTC, IANTHEREAL commented on tikv-configuration-file.md
> ++ 日志备份任务中，合并备份数据的阈值。如果待上传的备份数据文件大小总和达到该配置项的取值，TiKV 会将这些备份数据文件合并为一个备份文件进行上传，从而避免上传过多小文件。
```suggestion
+ 日志备份任务中，保存到备份的备份文件大小。
```

2022-09-08 03:36 UTC, IANTHEREAL commented
Rest LGTM

2022-09-08 03:41 UTC, shichun-0415 commented on tikv-configuration-file.md
> ++ 日志备份任务中，保存到备份的备份文件大小。
```suggestion
+ 日志备份任务中，保存到存储的备份文件大小。
```

2022-09-08 03:45 UTC, IANTHEREAL approved these changes

2022-09-08 03:46 UTC, shichun-0415 commented
/remove status LGT1
/status LGT2

2022-09-08 03:47 UTC, shichun-0415 commented
/merge

2022-09-08 04:02 UTC, merged