add v6.5.0 release notes
pingcap/docs-cn pull request #12100
Opened 2022-11-23 14:16 UTC by qiancai

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v6.5 (TiDB 6.5 versions)
- [ ] v6.4 (TiDB 6.4 versions)
- [ ] v6.3 (TiDB 6.3 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-11-25 09:13 UTC, sticnarf commented on releases/release-6.5.0.md
> +
```suggestion
    - 改进持续对特定行只加锁但不更新情况下的读写性能 [#13694](https://github.com/tikv/tikv/issues/13694) [@sticnarf](https://github.com/sticnarf)
```

2022-11-30 02:19 UTC, Frank945946 commented on releases/release-6.5.0.md
> +
* 支持导出和导入压缩后的 CSV、SQL 文件 [#38514](https://github.com/pingcap/tidb/issues/38514) @[lichunzhu](https://github.com/lichunzhu)

功能描述：支持导出和导入压缩后的 CSV 文件
        功能简介：Dumpling 支持将数据导出为 SQL、CSV 的压缩文件，支持 gzip/snappy/zstd 三种压缩格式。Lightning 支持导入压缩后的 SQL、CSV 文件，支持gzip/snappy/zstd 三种压缩格式。
        功能价值：之前用户导出数据或者导入数据都需要提供较大的存储空间，用于存储导出或者即将导入的非压缩后的 csv 、sql文件，导致存储成本增加。该功能发布后，通过压缩存储空间，可以大大降低用户的存储成本。
        如何使用：参考用户文档
    更多信息，请参考[用户文档](https://github.com/pingcap/tidb/issues/38514)。


* 优化了 binlog 解析能力 [#无](无) @[gmhdbjd](https://github.com/GMHDBJD)

功能描述：优化了 binlog 解析能力
        功能简介： 可将不在迁移任务里的库、表对象的 binlog event 过滤掉不做解析，从而提升解析效率和稳定性。 
        功能价值： 原先用户仅迁移少数几张表，也需要解析上游整个 binlog 文件，即仍需要解析该 binlog 文件中不需要迁移的表的 binlog event，效率会比较低，同时如果不在迁移任务里的库表的 binlog event 不支持解析，还会导致任务失败。通过只解析在迁移任务里的库表对象的 binlog event 可以大大提升 binlog 解析效率，提升任务稳定性。
        如何使用：该策略在 6.5 版本默认生效，用户不感知。

* Lightning 支持  disk quota 特性 GA，可避免 Lightning 任务写满本地磁盘 [#无](无) @[buchuitoudegou](https://github.com/buchuitoudegou)
功能描述：Lightning 支持  disk quota 特性 GA，可避免写 Lightning 任务满本地磁盘
        功能简介：你可以为 TiDB Lightning 配置磁盘配额 (disk quota)。当磁盘配额不足时，TiDB Lightning 会暂停读取源数据以及写入临时文件的过程，优先将已经完成排序的 key-value 写入到 TiKV，TiDB Lightning 删除本地临时文件后，再继续导入过程。
        功能价值： 没有这个功能之前，TiDB Lightning 在使用物理模式导入数据时，会在本地磁盘创建大量的临时文件，用来对原始数据进行编码、排序、分割。当用户本地磁盘空间不足时，TiDB Lightning 会由于写入文件失败而报错退出。 
        如何使用：参考用户文档
    更多信息，请参考[用户文档]( https://docs.pingcap.com/tidb/v6.4/tidb-lightning-physical-import-mode-usage#configure-disk-quota-new-in-v620)。


* GA DM 增量数据校验的功能 [#4426](https://github.com/pingcap/tiflow/issues/4426) @[[D3Hunter](https://github.com/D3Hunter)
功能描述： GA DM 增量数据校验的功能
        功能简介： 在将增量数据从上游迁移到下游数据库的过程中，数据的流转有小概率导致错误或者丢失的情况。对于需要依赖于强数据一致的场景，如信贷、证券等业务，你可以在数据迁移完成之后对数据进行全量校验，确保数据的一致性。然而，在某些增量复制的业务场景下，上游和下游的写入是持续的、不会中断的，因为上下游的数据在不断变化，导致用户难以对表里面的全部数据进行一致性校验。
        功能价值： 过去，需要中断业务，做全量数据校验，会影响用户业务。现在推出该功能后，在一些不可中断的业务场景，无需中断业务，通过该功能就可以实现增量数据校验。
        如何使用：参考用户文档
    更多信息，请参考[用户文档]( https://docs.pingcap.com/tidb/v6.4/dm-continuous-data-validation)。

2022-11-30 13:15 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +* 功能标题 [#issue号](链接) @[贡献者 GitHub ID](链接)
* TiCDC 支持输出 storage sink [tiflow#6797](https://github.com/pingcap/tiflow/issues/6797) @[zhaoxinyu](https://github.com/zhaoxinyu)

    TiCDC 支持将 changed log 输出到 S3/Azure Blob Storage/NFS，以及兼容 S3 协议的存储服务中。Cloud Storage 价格便宜，使用方便。对于不希望使用 Kafka 的用户，可以选择使用 storage sink。 TiCDC 将 changed log 保存到文件，然后发送到 storage 中；消费程序定时从 storage 读取新产生的 changed log files 进行处理。

    Storage sink 支持 changed log 格式位 canal-json/csv，此外 changed log 从 TiCDC 同步到 storage 的延迟可以达到 xx，支持更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12151/files)。

2022-11-30 13:16 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +* 功能标题 [#issue号](链接) @[贡献者 GitHub ID](链接)
* TiDB 快照备份支持断点续传 [#38647](https://github.com/pingcap/tidb/issues/38647) @[Leavrth](https://github.com/Leavrth)

    TiDB 快照备份功能支持断点续传。当 BR 遇到对可恢复的错误时会进行重试，但是超过固定重试次数之后会备份退出。断点续传功能允许对持续更长时间的可恢复故障进行重试恢复，比如几十分钟的的网络故障。 

    需要注意的是，如果你没有在 BR 退出后一个小时内完成故障恢复，那么还未备份的快照数据可能会被 GC 机制回收，而造成备份失败。更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12075)。

2022-11-30 15:38 UTC, benmaoer commented on releases/release-6.5.0.md
> +|        |                              |      |
```suggestion
|  [`tidb_enable_amend_pessimistic_txn`](system-variables.md#tidb_enable_amend_pessimistic_txn-span-classversion-mark从-v407-版本开始引入span)  |  删除                             |   即将废弃 amending transaction 特性   |
```

2022-11-30 15:51 UTC, benmaoer commented on releases/release-6.5.0.md
> +
```suggestion
即将于 6.6.0 版本废弃 4.0.7 版本引入的 Amending Transaction 机制，并使用[元数据锁](/metadata-lock.md) 替代。


```

2022-11-30 15:56 UTC, benmaoer commented on releases/release-6.5.0.md
> +- ......
```suggestion
- TiDB 添加索引的速度提升为原来的 10 倍。
```

2022-11-30 17:23 UTC, benmaoer requested changes
add v6.5 new feature

2022-12-01 03:37 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`tidb_cost_model_version`](/system-variables.md#tidbcostmodelversion-span-classversion-mark从-v620-版本开始引入span) | 修改 | 优化器模型 V2 GA， 变量默认值改为`2`。   |
```suggestion
| [`tidb_cost_model_version`](/system-variables.md#tidb_cost_model_version-从-v620-版本开始引入) | 修改 | 该变量默认值从 `1` 修改为 `2`，表示默认使用 Cost Model Version 2 进行索引选择和算子选择。 |
| [`tidb_enable_metadata_lock`](/system-variables.md#tidb_enable_metadata_lock-从-v630-版本开始引入) | 修改 | 该变量默认值从 `OFF` 修改为 `ON`，表示默认开启元数据锁。 |
| [`tidb_ddl_enable_fast_reorg`](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入) | 修改 | 该变量默认值从 `OFF` 修改为 `ON`，表示默认开启创建索引加速功能。 |
```

2022-12-01 16:09 UTC, lilyjazz commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](链接)。
```suggestion
* TiDB Dashboard 在 Kubernetes 环境支持独立 Pod 部署 [#1447](https://github.com/pingcap/tidb-dashboard/issues/1447) @[SabaPing](https://github.com/SabaPing)

    TiDB v6.5.0 且 TiDB Operator v1.4.0 之后，在 Kubernetes 上支持将 TiDB Dashboard 作为独立的 Pod 部署。在 TiDB Operator 环境，可直接访问该 Pod 的 IP 来打开 TiDB Dashboard。
    
    独立部署 TiDB Dashboard 后，用户将获得这些收益：1. 该组件的计算将不会再对 PD 节点有压力，更好的保障集群运行；2. 如果 PD 节点因异常不可访问，也还可以继续使用 Dashboard 进行集群诊断；3. 在开放 TiDB Dashboard 到外网时，不用担心 PD 中的特权端口的权限问题，降低集群的安全风险。
    
    具体信息，参考 [TiDB Operator 部署独立的 TiDB Dashboard](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/get-started#部署独立的-tidb-dashboard)
```

2022-12-01 16:16 UTC, lilyjazz commented on releases/release-6.5.0.md
> +
```suggestion

    + TiDB Dashboard

        - 在慢查询页面新增三个字段描述。 [#1445](https://github.com/pingcap/tidb-dashboard/pull/1445/files) @[shhdgit](https://github.com/shhdgit)

```

2022-12-02 03:31 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +* TiDB 快照备份支持断点续传 [#38647](https://github.com/pingcap/tidb/issues/38647) @[Leavrth](https://github.com/Leavrth) **tw@shichun-0415**
删除

2022-12-02 03:38 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +
```suggestion

* TiCDC 性能提升

    在 TiDB 场景测试验证中， TiCDC 的性能得到了比较大提升，单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s，即使在常规的 TiKV/TiCDC 滚动升级场景同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC Redo log 和 Sync point 后，吞吐 xx rows/s 时，容灾复制延迟可以保持在 x s。
```

2022-12-02 05:29 UTC, qiancai commented on releases/release-6.5.0.md
> +    需要注意的是，如果你没有在 BR 退出后一个小时内完成故障恢复，那么还未备份的快照数据可能会被 GC 机制回收，而造成备份失败。更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12075)。
```suggestion
* 功能标题 [#issue号](链接) @[贡献者 GitHub ID](链接)

    功能描述（需要包含这个功能是什么、在什么场景下对用户有什么价值、怎么用）

    更多信息，请参考[用户文档](链接)。
```

2022-12-02 05:32 UTC, qiancai commented on releases/release-6.5.0.md
> +* TiDB Dashboard 在 Kubernetes 环境支持独立 Pod 部署 [#1447](https://github.com/pingcap/tidb-dashboard/issues/1447) @[SabaPing](https://github.com/SabaPing)
```suggestion
* TiDB Dashboard 在 Kubernetes 环境支持独立 Pod 部署 [#1447](https://github.com/pingcap/tidb-dashboard/issues/1447) @[SabaPing](https://github.com/SabaPing) **tw@shichun-0415
```

2022-12-02 05:33 UTC, qiancai commented on releases/release-6.5.0.md
> +### 部署及运维
```suggestion

### 部署及运维
```

2022-12-02 05:34 UTC, qiancai commented on releases/release-6.5.0.md
> +
具体是哪三个字段，可以在这里说明下吗？

2022-12-02 07:51 UTC, SunRunAway commented on releases/release-6.5.0.md
> +
* 完整支持非事务 DML 语句，包括 `INSERT`、`REPLACE`、`UPDATE` 和 `DELETE`。[#33485](https://github.com/pingcap/tidb/issues/33485)  @[ekexium](https://github.com/ekexium)

    其中 非事务 `DELETE` 在 v6.1.0 已经支持，非事务 `INSERT`、`REPLACE` 和 `UPDATE` 在 v6.5.0 支持。

    更多信息，请参考[用户文档](/non-transactional-dml.md)。

2022-12-02 08:52 UTC, SunRunAway commented on releases/release-6.5.0.md
> +
```suggestion
* 完整支持非事务 DML 语句，包括 `INSERT`、`REPLACE`、`UPDATE` 和 `DELETE`。[#33485](https://github.com/pingcap/tidb/issues/33485)  @[ekexium](https://github.com/ekexium)

    在大批量的数据处理场景，单一大事务 SQL 处理有可能对集群稳定性和性能造成影响。非事务 DML 语句将一个 DML 语句拆成多个语句在内部执行。拆分后的语句将牺牲事务原子性和隔离性，但是对于集群的稳定性有很大提升。
    其中非事务 `DELETE` 在 v6.1.0 已经支持，非事务 `INSERT`、`REPLACE` 和 `UPDATE` 在 v6.5.0 支持。

    更多信息，请参考[非事务 DML 语句](/non-transactional-dml.md) 和 [BATCH](/sql-statements/sql-statemetn-batch.md)。
```

2022-12-02 14:37 UTC, benmaoer commented on releases/release-6.5.0.md
> +
```suggestion
* 支持高性能、全局单调递增的 AUTO_INCREMENT 列属性 [#38442](https://github.com/pingcap/tidb/issues/38442) @[tiancaiamao](https://github.com/tiancaiamao)

    TiDB v6.4.0 引入了 AUTO_INCREMENT 的 MySQL 兼容模式，通过中心化分配自增 ID，实现了自增 ID 在所有 TiDB 实例上单调递增，v6.5.0 版本该功能正式 GA，使用该兼容模式的单表写入 TPS 预期超过 2 万，并支持通过弹性扩容提升单表和整个集群的写入吞吐。使用该特性能够更容易地实现查询结果按自增 ID 排序。要使用 MySQL 兼容模式，你需要在建表时将 AUTO_ID_CACHE 设置为 1。
`
CREATE TABLE t(a int AUTO_INCREMENT key) AUTO_ID_CACHE 1;
`
更多信息，请参考[用户文档](/auto-increment.md#mysql-兼容模式)。
```

2022-12-05 03:08 UTC, lilyjazz commented on releases/release-6.5.0.md
> +
更新了。

2022-12-05 03:31 UTC, qiancai commented on releases/release-6.5.0.md
> +* GA DM 增量数据校验的功能 [#4426](https://github.com/pingcap/tiflow/issues/4426) @[[D3Hunter](https://github.com/D3Hunter) **tw@hfxsd**
```suggestion
* GA DM 增量数据校验的功能 [#4426](https://github.com/pingcap/tiflow/issues/4426) @[D3Hunter](https://github.com/D3Hunter) **tw@hfxsd**
```

2022-12-05 03:49 UTC, xzhangxian1008 approved these changes

2022-12-05 03:56 UTC, fzzf678 commented on releases/release-6.5.0.md
> +    在新版本中，TiDB 扩展了执行计划的打印格式。 通过 `explain format = tidb_json <SQL语句> ` 能够将 SQL 的执行计划以 JSON 格式输出。 借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
```suggestion
    在新版本中，TiDB 扩展了执行计划的打印格式。 通过 `explain format = tidb_json <SQL语句> ` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
```

2022-12-05 03:58 UTC, Leavrth commented on releases/release-6.5.0.md
> +    需要注意的是，如果你没有在 BR 退出后一个小时内完成故障恢复，那么还未备份的快照数据可能会被 GC 机制回收，而造成备份失败。更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12075)。
链接是否需要改为 /br/br-checkpoint.md

2022-12-05 04:07 UTC, lcwangchao commented on releases/release-6.5.0.md
> +    更多信息请参考[Time to live(TTL)](/ttl.md)
现在这个文件名是 `/ttl-time-to-live.md`

2022-12-05 04:51 UTC, CbcWestwolf approved these changes

2022-12-05 05:00 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +|          |          |          |          |
```suggestion
| TiKV | [`cdc.min-ts-interval`](/tikv-configuration-file.md#min-ts-interval) | 修改 | 默认值从 `1s` 修改为 `200ms` |
```

2022-12-05 05:42 UTC, D3Hunter approved these changes

2022-12-05 05:52 UTC, SunRunAway commented on releases/release-6.5.0.md
> +* 支持 Time to live (TTL)（实验特性）**tw@ran-huang**
```suggestion
* 支持 Time to live (TTL)（实验特性）[#39262](https://github.com/pingcap/tidb/issues/39262)  @[lcwangchao](https://github.com/lcwangchao) **tw@ran-huang**
```

2022-12-05 06:10 UTC, buchuitoudegou approved these changes

2022-12-05 06:33 UTC, time-and-fate commented on releases/release-6.5.0.md
> +* 完整支持索引合并[INDEX MERGE](/glossary.md#index-merge)功能 [#39333](https://github.com/pingcap/tidb/issues/39333) @[guo-shaoge](https://github.com/guo-shaoge) @[@time-and-fate](https://github.com/time-and-f
1. 跟下一段写的一样，这次主要是的支持了对于 `AND` 过滤条件使用 Index Merge 的基本能力，目前还没法自动选择。用“完整支持”来表述是不是比较宽泛？
2. hailanwhu 参与了最初 `OR` Index Merge 的工作，但是没参与这个 sprint 的内容。这种情况需要写吗？

2022-12-05 06:33 UTC, time-and-fate commented on releases/release-6.5.0.md
> +    新增了对在 WHERE 语句中使用 `AND` 联结的过滤条件的索引合并能力（v6.5 之前的版本只支持 `OR` 连接词的情况），TiDB 的索引合并至此可以覆盖更一般的查询过滤条件组合，不再限定于并集（`OR`）关系。用户可以通过使用 使用 [`USE_INDEX_MERGE`](/optimizer-hints.md#use_index_merget1_name-idx1_name
```suggestion
    新增了对在 WHERE 语句中使用 `AND` 联结的过滤条件的索引合并能力（v6.5 之前的版本只支持 `OR` 连接词的情况），TiDB 的索引合并至此可以覆盖更一般的查询过滤条件组合，不再限定于并集（`OR`）关系。用户可以通过使用 [`USE_INDEX_MERGE`](/optimizer-hints.md#use_index_merget1_name-idx1_name--idx2_name-) Hint 来开启对于 AND 联结的索引合并。
```

2022-12-05 06:45 UTC, HuSharp commented on releases/release-6.5.0.md
> +    - 改进持续对特定行只加锁但不更新情况下的读写性能 [#13694](https://github.com/tikv/tikv/issues/13694) [@sticnarf](https://github.com/sticnarf)
- tikv-ctl 支持查询某个 key 范围中包含哪些 Region  [#13768](https://github.com/tikv/tikv/pull/13768) [@HuSharp](https://github.com/HuSharp)

2022-12-05 07:06 UTC, GMHDBJD approved these changes

2022-12-05 07:40 UTC, songrijie commented on releases/release-6.5.0.md
> +* 新增支持下推[JSON 函数](/tiflash/tiflash-supported-pushdown-calculations.md) 至 TiFlash [#39458](https://github.com/pingcap/tidb/issues/39458) @[yibin87](https://github.com/yibin87) **tw@qiancai**
@joey-yez  建议这个描述稍微扩展一些，基于 JSON 格式的数据分析能够推到 TiFlash， 算是个里程碑的起点。  另外，我把这个feature 放到 key features了

2022-12-05 08:09 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* 完整支持非事务 DML 语句。其中包括非事务 `INSERT`、`REPLACE`、`UPDATE` 和 `DELETE`。[#33485](https://github.com/pingcap/tidb/issues/33485)  @[ekexium](https://github.com/ekexium) **tw@ran-huang**
```suggestion
* 完整支持非事务 DML 语句。其中包括非事务 `INSERT`、`REPLACE`、`UPDATE` 和 `DELETE`。[#33485](https://github.com/pingcap/tidb/issues/33485)  @[ekexium](https://github.com/ekexium) **tw@Oreoxmt**
```

2022-12-05 08:22 UTC, cfzjywxk commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
-  修复 chunk reuse 功能部分情况下内存 chunk 被错误使用的问题 [#38917](https://github.com/pingcap/tidb/issues/38917) @[keeplearning20221](https://github.com/keeplearning20221)
- 修复 `tidb_constraint_check_in_place_pessimistic` 可能被全局设置影响内部 session 的问题 [#38766](https://github.com/pingcap/tidb/issues/38766) @[ekexium](https://github.com/ekexium)

2022-12-05 09:53 UTC, flowbehappy commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复 TiFlash 重启不能正确合并小文件的问题 [#6159](https://github.com/pingcap/tiflash/issues/6159) @[lidezhu](https://github.com/lidezhu)
    - 修复 TiFlash Open File OPS 过高的问题 [#6345](https://github.com/pingcap/tiflash/issues/6345) @[JaySon-Huang](https://github.com/JaySon-Huang)
```

2022-12-05 09:56 UTC, flowbehappy commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复 TiFlash 重启不能正确合并小文件的问题 [#6159](https://github.com/pingcap/tiflash/issues/6159) @[lidezhu](https://github.com/lidezhu)
    - 修复 TiFlash Open File OPS 过高的问题 [#6345](https://github.com/pingcap/tiflash/issues/6345) @[JaySon-Huang](https://github.com/JaySon-Huang)
```

2022-12-05 09:58 UTC, lcwangchao commented on releases/release-6.5.0.md
> +    更多信息请参考[Time to live(TTL)](/ttl.md)
```suggestion
    更多信息请参考[Time to live(TTL)](/time-to-live.md)
```

2022-12-06 01:58 UTC, yibin87 approved these changes
LGTM

2022-12-06 02:19 UTC, tiancaiamao commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](/auto-increment.md#mysql-兼容模式)。
LGTM

2022-12-06 02:42 UTC, joey-yez commented on releases/release-6.5.0.md
> +    TiDB 通过将函数下推至 TiFlash 加速分析计算。JSON 数据类型非常灵活，常用于快速发展的行业，如 WEB3 等。支持下推 JSON 函数至 TiFlash 可以更好的满足此类业务需求。
@songrijie 这里补充了两段，请确认一下。涉及太多业务行业，感觉会有点奇怪。

2022-12-06 02:51 UTC, songrijie commented on releases/release-6.5.0.md
> +    TiDB 通过将函数下推至 TiFlash 加速分析计算。JSON 数据类型非常灵活，常用于快速发展的行业，如 WEB3 等。支持下推 JSON 函数至 TiFlash 可以更好的满足此类业务需求。
我觉得不需要提及行业。 就是对于 JSON 格式存储的数据，可以直接利用 TiFlash 进行实时分析。

2022-12-06 03:21 UTC, XuHuaiyu commented on releases/release-6.5.0.md
> +    需要注意的是， 会话中事务所消耗的内存 (由配置项 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit) 设置最大值) 如今会被内存管理模块跟踪： 当单个会话的内存消耗达到系统变量 [`tidb_mem_quota_query`](/system-variables.md#tidbmemquo
``` suggestion
    需要注意的是， 会话中事务所消耗的内存 (由配置项 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit) 设置最大值) 如今会被内存管理模块跟踪： 当单个会话的内存消耗达到系统变量 [`tidb_mem_quota_query`](/system-variables.md#tidbmemquotaquery) 所定义的阈值时，将会触发系统变量 [tidb_mem_oom_action](/system-variables.md#tidbmemoomaction-span-classversion-mark从-v610-版本开始引入span) 所定义的行为 (默认为 `CANCEL` ，即停止会话)。  为了保证行为向前兼容，当配置 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit) 为非默认值时， TiDB 仍旧会保证事务使用到这么大的内存而不被停掉。 
```

2022-12-06 03:21 UTC, XuHuaiyu commented on releases/release-6.5.0.md
> +    需要注意的是， 会话中事务所消耗的内存 (由配置项 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit) 设置最大值) 如今会被内存管理模块跟踪： 当单个会话的内存消耗达到系统变量 [`tidb_mem_quota_query`](/system-variables.md#tidbmemquo
『停止会话』似乎不太准确，会话会保留， sql 会被停止并对外报错

2022-12-06 03:56 UTC, tiancaiamao commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
修复了 AUTO_INCREMENT 列无法和 Check 约束一起使用的问题 [#38894](https://github.com/pingcap/tidb/issues/38894) @[YangKeao](https://github.com/YangKeao)
修复使用 'insert ignore into' 往 smallint 类型 auto increment 的列插入 string 类型数据会报错的问题 [#38483](https://github.com/pingcap/tidb/issues/38483) @[hawkingrei](https://github.com/hawkingrei)
修复了重命名分区表的分区列操作出现空指针报错的问题 [#38932](https://github.com/pingcap/tidb/issues/38932) @[mjonss](https://github.com/mjonss)
修复了一个修改分区表的分区列导致 DDL 卡死的问题 [#38530](https://github.com/pingcap/tidb/issues/38530) @[mjonss](https://github.com/mjonss)
修复了从 v4.0 升级到 v6.4 后 'admin show job' 操作崩溃的问题 [#38980](https://github.com/pingcap/tidb/issues/38980) @[tangenta](https://github.com/tangenta)
修复了 `tidb_decode_key` 函数未正确处理分区表编码的问题 [#39304](https://github.com/pingcap/tidb/issues/39304) @[Defined2014](https://github.com/Defined2014)
修复了 log rotate 时，grpc 的错误日志信息未被重定向到正确的日志文件的问题 [#38941](https://github.com/pingcap/tidb/issues/38941) @[xhebox](https://github.com/xhebox)

=================

Fix the issue that the auto increment column cannot be used with check constraint. [#38894](https://github.com/pingcap/tidb/issues/38894) @[YangKeao](https://github.com/YangKeao)
Fix panic when rename partition table columns [#38932](https://github.com/pingcap/tidb/issues/38932) @[mjonss](https://github.com/mjonss)
Fix a bug that modify column on partition columns makes DDL hang [#38530](https://github.com/pingcap/tidb/issues/38530) @[mjonss](https://github.com/mjonss)
Fix a bug that 'insert ignore' a string value into smallint auto_increment column returns error which should not [#38483](https://github.com/pingcap/tidb/issues/38483) @[hawkingrei](https://github.com/hawkingrei)
Fix admin show job panic when upgrade from v4.0 to v6.4 [#38980](https://github.com/pingcap/tidb/issues/38980) @[tangenta](https://github.com/tangenta)
Fix `tidb_decode_key` function to make it work on partition table [#39304](https://github.com/pingcap/tidb/issues/39304) @[Defined2014](https://github.com/Defined2014)
Fix broken log rotation of grpc [#38941](https://github.com/pingcap/tidb/issues/38941) @[xhebox](https://github.com/xhebox)

2022-12-06 03:57 UTC, tiancaiamao commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
对于 `bit` and `char` 类型的列，使 `INFORMATION_SCHEMA.COLUMNS` 的显示结果与 MySQL 一致 [#25472](https://github.com/pingcap/tidb/issues/25472) @[hawkingrei](https://github.com/hawkingrei)

2022-12-06 10:29 UTC, songrijie commented on releases/release-6.5.0.md
> +    需要注意的是， 会话中事务所消耗的内存 (由配置项 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit) 设置最大值) 如今会被内存管理模块跟踪： 当单个会话的内存消耗达到系统变量 [`tidb_mem_quota_query`](/system-variables.md#tidbmemquo
@XuHuaiyu  https://github.com/pingcap/docs-cn/pull/12100/commits/4b9846b4052cfb3107d816746cf78f884bfe09f6

2022-12-07 05:11 UTC, TomShawn commented on releases/release-6.5.0.md
> +| [`tidb_cdc_write_source`](/system-variables.md#tidb_cdc_write_source-从-v650-版本开始引入) | 新增 | 当变量非 `0` 时，该 SESSION 写入的数据将被视为是由 TiCDC 写入的。这个变量仅由 TiCDC 设置，任何时候都不应该手动调整该变量。 |
```suggestion
| [`tidb_cdc_write_source`](/system-variables.md#tidb_cdc_write_source-从-v650-版本开始引入) | 新增 | 当变量非 `0` 时，该 SESSION 写入的数据将被视为是由 TiCDC 写入的。这个变量仅由 TiCDC 设置，任何时候都不应该手动调整该变量。 |
| [`tidb_index_merge_intersection_concurrency`](/system-variables.md#tidb_index_merge_intersection_concurrency-从-v650-版本开始引入) | 新增 | 这个变量用来设置索引合并进行交集操作时的最大并发度，仅在以动态裁剪模式访问分区表时有效。 |
```

2022-12-07 05:16 UTC, TomShawn commented on releases/release-6.5.0.md
> +| [`tidb_ddl_enable_fast_reorg`](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入) | 修改 | 该变量默认值从 `OFF` 修改为 `ON`，表示默认开启创建索引加速功能。 |
```suggestion
| [`tidb_ddl_enable_fast_reorg`](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入) | 修改 | 该变量默认值从 `OFF` 修改为 `ON`，表示默认开启创建索引加速功能。 |
| [`tidb_server_memory_limit`](/system-variables.md#tidb_server_memory_limit-从-v640-版本开始引入) |  修改 | 该变量默认值由 `0` 修改为 `80%`，表示默认将 TiDB 实例的内存限制设为总内存的 80%。|
```

2022-12-07 05:18 UTC, TomShawn commented on releases/release-6.5.0.md
> +| TiDB | [`disconnect-on-expired-password`](/tidb-configuration-file.md#disconnect-on-expired-password`-从-v650-版本开始引入) | 新增 | 该配置用于控制 TiDB 服务端是否直接断开密码已过期用户的连接，默认值为 "true" ，表示 TiDB 服务端将直接断开密码已过期用户的连接
```suggestion
| TiDB | [`disconnect-on-expired-password`](/tidb-configuration-file.md#disconnect-on-expired-password`-从-v650-版本开始引入) | 新增 | 该配置用于控制 TiDB 服务端是否直接断开密码已过期用户的连接，默认值为 "true" ，表示 TiDB 服务端将直接断开密码已过期用户的连接 |
| TiDB | [`server-memory-quota`](/tidb-configuration-file.md#server-memory-quota-从-v409-版本开始引入) | 废弃 | 自 v6.5.0 起，该配置项被废弃。请使用 [`tidb_server_memory_limit`](/system-variables.md#tidb_server_memory_limit-从-v640-版本开始引入) 系统变量进行设置。 |
```

2022-12-07 06:13 UTC, qiancai commented on releases/release-6.5.0.md
> +    需要注意的是，如果你没有在 BR 退出后一个小时内完成故障恢复，那么还未备份的快照数据可能会被 GC 机制回收，而造成备份失败。更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12075)。
```suggestion
    需要注意的是，如果你没有在 BR 退出后一个小时内完成故障恢复，那么还未备份的快照数据可能会被 GC 机制回收，而造成备份失败。更多信息，请参考[用户文档](/br/br-checkpoint.md)。
```

2022-12-07 06:14 UTC, qiancai commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 对于 `bit` and `char` 类型的列，使 `INFORMATION_SCHEMA.COLUMNS` 的显示结果与 MySQL 一致 [#25472](https://github.com/pingcap/tidb/issues/25472) @[hawkingrei](https://github.com/hawkingrei)
```

2022-12-07 06:14 UTC, qiancai commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - tikv-ctl 支持查询某个 key 范围中包含哪些 Region  [#13768](https://github.com/tikv/tikv/pull/13768) [@HuSharp](https://github.com/HuSharp)
```

2022-12-07 06:17 UTC, qiancai commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
added in https://github.com/pingcap/docs-cn/pull/12100/commits/98eac5aa68748e4b11f44331eabfa8c44e47063f

2022-12-07 06:19 UTC, qiancai commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复了 AUTO_INCREMENT 列无法和 Check 约束一起使用的问题 #38894 @YangKeao
    - 修复使用 'insert ignore into' 往 smallint 类型 auto increment 的列插入 string 类型数据会报错的问题 #38483 @hawkingrei
    - 修复了重命名分区表的分区列操作出现空指针报错的问题 #38932 @mjonss
    - 修复了一个修改分区表的分区列导致 DDL 卡死的问题 #38530 @mjonss
    - 修复了从 v4.0 升级到 v6.4 后 'admin show job' 操作崩溃的问题 #38980 @tangenta
    - 修复了 tidb_decode_key 函数未正确处理分区表编码的问题 #39304 @Defined2014
    - 修复了 log rotate 时，grpc 的错误日志信息未被重定向到正确的日志文件的问题 #38941 @xhebox
```

2022-12-07 06:21 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 修复了 log rotate 时，grpc 的错误日志信息未被重定向到正确的日志文件的问题 #38941 @xhebox
```suggestion
    - 修复了 AUTO_INCREMENT 列无法和 Check 约束一起使用的问题 [#38894](https://github.com/pingcap/tidb/issues/38894) @[YangKeao](https://github.com/YangKeao)
    - 修复使用 'insert ignore into' 往 smallint 类型 auto increment 的列插入 string 类型数据会报错的问题 [#38483](https://github.com/pingcap/tidb/issues/38483) @[hawkingrei](https://github.com/hawkingrei)
    - 修复了重命名分区表的分区列操作出现空指针报错的问题 [#38932](https://github.com/pingcap/tidb/issues/38932) @[mjonss](https://github.com/mjonss)
    - 修复了一个修改分区表的分区列导致 DDL 卡死的问题 [#38530](https://github.com/pingcap/tidb/issues/38530) @[mjonss](https://github.com/mjonss)
    - 修复了从 v4.0 升级到 v6.4 后 'admin show job' 操作崩溃的问题 [#38980](https://github.com/pingcap/tidb/issues/38980) @[tangenta](https://github.com/tangenta)
    - 修复了 `tidb_decode_key` 函数未正确处理分区表编码的问题 [#39304](https://github.com/pingcap/tidb/issues/39304) @[Defined2014](https://github.com/Defined2014)
    - 修复了 log rotate 时，grpc 的错误日志信息未被重定向到正确的日志文件的问题 [#38941](https://github.com/pingcap/tidb/issues/38941) @[xhebox](https://github.com/xhebox)
```

2022-12-07 06:23 UTC, qiancai commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
Thanks for providing both Chinese and English versions. The Chinese version has been committed to https://github.com/pingcap/docs-cn/pull/12100/commits/f9c2b7fd488f1be5a5bec11d8889c169dc9f3fe7.

2022-12-07 06:35 UTC, joey-yez commented on releases/release-6.5.0.md
> +    TiDB 通过将函数下推至 TiFlash 加速分析计算。JSON 数据类型非常灵活，常用于快速发展的行业，如 WEB3 等。支持下推 JSON 函数至 TiFlash 可以更好的满足此类业务需求。
```suggestion
    TiDB 通过将函数下推至 TiFlash 加速分析计算。JSON 数据类型非常灵活。支持下推 JSON 函数至 TiFlash 可以使 TiDB 利用 TiFlash 进行包含 JSON 类型数据的实时分析。
```

2022-12-07 06:37 UTC, pingyu commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - `cdc.min-ts-interval` 默认值从 1s 改为 200ms 以降低 CDC 延迟 [#12840](https://github.com/tikv/tikv/issues/12840) @[hicqu](https://github.com/hicqu)
    - 引入 witness peer [#12876](https://github.com/tikv/tikv/issues/12876) @[Connor1996](https://github.com/Connor1996)
    - 当剩余空间不足时停止 Raft Engine 的写入以避免硬盘空间耗尽 [#13642](https://github.com/tikv/tikv/issues/13642) @[jiayang-zheng](https://github.com/jiayang-zheng)
    - 实现 `json_valid` 函数下推 [#13571](https://github.com/tikv/tikv/issues/13571) @[lizhenhuan](https://github.com/lizhenhuan)
    - 支持在一个备份请求中同时备份多个范围的数据 [#13701](https://github.com/tikv/tikv/issues/13701) @[Leavrth](https://github.com/Leavrth)
    - 更新 rusoto 库以支持备份到 ap-southeast-3 [#13751](https://github.com/tikv/tikv/issues/13751) @[3pointer](https://github.com/3pointer)
    - 减少悲观事务冲突 [#13298](https://github.com/tikv/tikv/issues/13298) @[MyonKeminta](https://github.com/MyonKeminta)
    - 减少不必要的检查以提升 flashback 的性能 [#13800](https://github.com/tikv/tikv/issues/13800) @[JmPotato](https://github.com/JmPotato)
    - 缓存外部存储对象以提升恢复性能 [#13798](https://github.com/tikv/tikv/issues/13798) @[YuJuncen](https://github.com/YuJuncen)
    - PiTR 支持批量写入 kv 文件以提升恢复速度 [#13788](https://github.com/tikv/tikv/issues/13788) @[joccau](https://github.com/joccau)
    - 在专用线程中运行 CheckLeader 以缩短 TiCDC 的复制延迟 [#13774](https://github.com/tikv/tikv/issues/13774) @[overvenus](https://github.com/overvenus)
    - PiTR 允许复用已下载的 kv 文件以提升恢复性能 [#13788](https://github.com/tikv/tikv/issues/13788) @[joccau](https://github.com/joccau)
    - Checkpoint 支持拉取模式 [#13824](https://github.com/tikv/tikv/issues/13824) @[YuJuncen](https://github.com/YuJuncen)
    - 优化 flashback 的稳定性 [#13827](https://github.com/tikv/tikv/issues/13827) @[BusyJay](https://github.com/BusyJay)
    - 升级 crossbeam-channel 以优化发送端的自旋问题 [#13815](https://github.com/tikv/tikv/issues/13815) @[sticnarf](https://github.com/sticnarf)
    - Coprocessor 支持批量处理 [#13849](https://github.com/tikv/tikv/issues/13849) @[cfzjywxk](https://github.com/cfzjywxk)
    - PiTR 在写入 kv 文件时过滤无效的 kv 事件 [#13853](https://github.com/tikv/tikv/issues/13853) @[joccau](https://github.com/joccau)
    - 故障恢复时通知 TiKV 唤醒休眠的 region 以减少等待时间 [#13648](https://github.com/tikv/tikv/issues/13648) @[LykxSassinator](https://github.com/LykxSassinator)
    - 通过代码优化减少内存申请 [#13836](https://github.com/tikv/tikv/pull/13836) @[BusyJay](https://github.com/BusyJay)
    - 优化 flashback 与 CDC 特性的兼容性 [#13823](https://github.com/tikv/tikv/pull/13823)  @[JmPotato](https://github.com/JmPotato)
    - 引入 raft extension 以提升代码可扩展性 [#13864](https://github.com/tikv/tikv/pull/13864) @[BusyJay](https://github.com/BusyJay)
    - 通过引入 `hint_min_ts` 加速 flashback [#13842](https://github.com/tikv/tikv/pull/13842)  @[JmPotato](https://github.com/JmPotato)
```

2022-12-07 06:37 UTC, pingyu commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复 raft engine ctl 中的错误 [#13108](https://github.com/tikv/tikv/issues/13108) @[tabokie](https://github.com/tabokie)
    - 修复 tikv-ctl 中 compact raft 命令的错误 [#13515](https://github.com/tikv/tikv/issues/13515) @[guoxiangCN](https://github.com/guoxiangCN)
    - 修复当启用 TLS 时 log backup 无法使用的问题 [#13851](https://github.com/tikv/tikv/issues/13851) @[YuJuncen](https://github.com/YuJuncen)
    - 修复对 Geometry 字段类型的支持 [#13651](https://github.com/tikv/tikv/issues/13651) @[dveeden](https://github.com/dveeden)
    - 修复由于删除引起的 flashback 死循环问题 [#13743](https://github.com/tikv/tikv/issues/13743) @[JmPotato](https://github.com/JmPotato)
    - 修复当未使用 new collation 时 `like` 无法处理 `_` 中非 ASCII 字符的问题 [#13769](https://github.com/tikv/tikv/issues/13769) @[YangKeao](https://github.com/YangKeao)
    - 修复 tikv-ctl 执行 reset-to-version 时出现 segfault 的问题 [#13829](https://github.com/tikv/tikv/issues/13829) @[tabokie](https://github.com/tabokie)
    - 修复 flashback 可能覆盖错误的写记录的问题 [#13844](https://github.com/tikv/tikv/issues/13844) @[JmPotato](https://github.com/JmPotato)
```

2022-12-07 06:54 UTC, songrijie commented on releases/release-6.5.0.md
> +    TiDB 通过将函数下推至 TiFlash 加速分析计算。JSON 数据类型非常灵活。支持下推 JSON 函数至 TiFlash 可以使 TiDB 利用 TiFlash 进行包含 JSON 类型数据的实时分析。
```suggestion
    JSON 格式为应用设计提供了更灵活的建模方式， 目前越来越多的应用采用 JSON 格式进行数据交换和数据存储。 把 JSON 函数下推至 TiFlash 将会加速对大量 JSON 类型数据的分析效率，拓展 TiDB 实时分析的应用场景。 TiDB 将持续完善，在未来版本支持更多的 JSON 函数下推至 TiFlash。
```

2022-12-07 06:59 UTC, joey-yez commented on releases/release-6.5.0.md
> +    JSON 格式为应用设计提供了更灵活的建模方式，目前越来越多的应用采用 JSON 格式进行数据交换和数据存储。 把 JSON 函数下推至 TiFlash 可以加速对 JSON 类型数据的分析效率，拓展 TiDB 实时分析的应用场景。 TiDB 将持续完善，在未来版本支持更多的 JSON 函数下推至 TiFlash。
```suggestion
    JSON 格式为应用设计提供了更灵活的建模方式，目前越来越多的应用采用 JSON 格式进行数据交换和数据存储。 把 JSON 函数下推至 TiFlash 可以加速对 JSON 类型数据的分析效率，拓展 TiDB 实时分析的应用场景。TiDB 将持续完善，在未来版本支持更多的 JSON 函数下推至 TiFlash。
```

2022-12-07 07:56 UTC, hfxsd commented on releases/release-6.5.0.md
> +| [`tidb_source_id`](/system-variables.md#tidb_source_id-从-v650-版本开始引入) | 新增 | 设置在[双向复制](/ticdc/ticdc-bidirectional-replication.md)系统内不同集群的 ID。|
```suggestion
| [`tidb_mem_quota_query`](/system-variables.md#tidb_mem_quota_query) | 修改 | 在 v6.5.0 之前的版本中，该变量用来设置单条查询的内存使用限制。在 v6.5.0 及之后的版本中，该变量用来设置单个会话整体的内存使用限制。 |
| [`tidb_source_id`](/system-variables.md#tidb_source_id-从-v650-版本开始引入) | 新增 | 设置在[双向复制](/ticdc/ticdc-bidirectional-replication.md)系统内不同集群的 ID。|
```

2022-12-07 08:32 UTC, nongfushanquan commented on releases/release-6.5.0.md
> +    + TiCDC
* 修复 PD leader crash时 CDC 卡住的问题[#7470](https://github.com/pingcap/tiflow/issues/7470)
* 修复在执行drop table 时用户快速暂停恢复同步任务导致可能的数据丢失问题[#7682](https://github.com/pingcap/tiflow/issues/7682)
*  兼容上游开启 TiFlash 时版本兼容性问题 [#7744](https://github.com/pingcap/tiflow/issues/7744)
* 修复下游网络出现故障导致cdc 卡住的问题 [#7706](https://github.com/pingcap/tiflow/issues/7706)
* 修复用户快速删除、创建同名同步任务可能导致的数据丢失问题 [#7657](https://github.com/pingcap/tiflow/issues/7657)

2022-12-07 08:39 UTC, nongfushanquan commented on releases/release-6.5.0.md
> +    + TiCDC
* 采用并发的方式对数据进行编码，极大提升了同步到 kafka 的吞吐能力[#7532](https://github.com/pingcap/tiflow/issues/7532)[#7543](https://github.com/pingcap/tiflow/issues/7543)[#7540](https://github.com/pingcap/tiflow/issues/7540)

2022-12-07 08:53 UTC, TomShawn commented on releases/release-6.5.0.md
> +    需要注意的是， 会话中事务所消耗的内存 (由配置项 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit) 设置最大值) 如今会被内存管理模块跟踪： 当单个会话的内存消耗达到系统变量 [`tidb_mem_quota_query`](/system-variables.md#tidbmemquo
```suggestion
    需要注意的是， 会话中事务所消耗的内存 (由配置项 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit) 设置最大值) 如今被内存管理模块跟踪：当单个会话的内存消耗达到系统变量 [`tidb_mem_quota_query`](/system-variables.md#tidbmemquotaquery) 所定义的阀值时，将会触发系统变量 [tidb-mem-oom-action](/system-variables.md#tidbmemoomaction-span-classversion-mark从-v610-版本开始引入span) 所定义的行为 (默认为 `CANCEL` ，即取消操作)。 为了保证向前兼容，当配置 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit) 为非默认值时，TiDB 仍旧会保证事务使用到 `txn-total-size-limit` 所设定的内存而不被取消。
```

2022-12-07 08:59 UTC, lichunzhu commented on releases/release-6.5.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
        - 通过不再解析黑名单表的数据提升了 dm 同步数据的性能[#7622](https://github.com/pingcap/tiflow/pull/7622) @[GMHDBJD](https://github.com/GMHDBJD)
        - 通过异步写与批量写的方式提升 dm relay 写数据效率[#7580](https://github.com/pingcap/tiflow/pull/7580) @[GMHDBJD](https://github.com/GMHDBJD)
        - 改进 DM 前置检查的错误提示信息[#7696](https://github.com/pingcap/tiflow/pull/7696) @[buchuitoudegou](https://github.com/buchuitoudegou)
        - 改进 DM 针对老版本 MySQL 使用 `SHOW SLAVE HOSTS` 获取结果时的兼容性[#7373](https://github.com/pingcap/tiflow/pull/7372) @[lyzx2001](https://github.com/lyzx2001)
```

2022-12-07 08:59 UTC, lichunzhu commented on releases/release-6.5.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
```suggestion
        - 修复 TiDB Lightning 导入巨大数据源文件时的内存泄漏问题 [#39331](https://github.com/pingcap/tidb/issues/39331) @[dsdashun](https://github.com/dsdashun)
        - 修复 TiDB Lightning 在并行导入冲突检测时无法正确检测的问题 [#39476](https://github.com/pingcap/tidb/issues/39476) @[dsdashun](https://github.com/dsdashun)
```
```

2022-12-07 09:58 UTC, qiancai commented on releases/release-6.5.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
        - 采用并发的方式对数据进行编码，极大提升了同步到 kafka 的吞吐能力[#7532](https://github.com/pingcap/tiflow/issues/7532)[#7543](https://github.com/pingcap/tiflow/issues/7543)[#7540](https://github.com/pingcap/tiflow/issues/7540)
```

2022-12-07 10:01 UTC, qiancai commented on releases/release-6.5.0.md
> +    + TiCDC
added in https://github.com/pingcap/docs-cn/pull/12100/commits/4c95cff427e5248c789e6a63be036fadcb018e3d

2022-12-07 10:02 UTC, qiancai commented on releases/release-6.5.0.md
> +    + TiCDC
added in https://github.com/pingcap/docs-cn/pull/12100/commits/4c95cff427e5248c789e6a63be036fadcb018e3d

2022-12-07 10:46 UTC, 3pointer commented on releases/release-6.5.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
- 修复清理备份日志数据时错误删除数据导致数据丢失的问题（https://github.com/pingcap/tidb/issues/38939） @Leavrth (https://github.com/Leavrth)
- 修复在大于 6.1 版本关闭 new_collation 设置，仍然恢复失败的问题（https://github.com/pingcap/tidb/issues/39150） @MoCuishle28  (https://github.com/MoCuishle28)
- 修复因非 s3 存储的不兼容请求导致备份 panic 的问题(https://github.com/pingcap/tidb/issues/39545) @3pointer (https://github.com/3pointer)

2022-12-07 10:46 UTC, 3pointer commented on releases/release-6.5.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
- 优化清理备份日志数据是 BR 的内存使用(https://github.com/pingcap/tidb/issues/38869) @Leavrth （https://github.com/Leavrth）
- 提升在恢复时的稳定性，允许 PD leader 切换的情况发生（https://github.com/pingcap/tidb/issues/36910） @MoCuishle28 （https://github.com/MoCuishle28）
- 日志备份的 tls 功能使用 openssl 协议，提升 tls 兼容性。(https://github.com/tikv/tikv/issues/13867)
@YuJuncen (https://github.com/YuJuncen)

2022-12-07 11:14 UTC, qiancai commented on releases/release-6.5.0.md
> +```suggestion
```suggestion
```

2022-12-07 12:06 UTC, chrysan commented on releases/release-6.5.0.md
> +    - 修复了 log rotate 时，grpc 的错误日志信息未被重定向到正确的日志文件的问题 [#38941](https://github.com/pingcap/tidb/issues/38941) @[xhebox](https://github.com/xhebox)
- 修复了 `begin; select... for update;` 点查在 read engines 未配置 TiKV 时生成非预期执行计划的问题 [#39344](https://github.com/pingcap/tidb/issues/39344) @[Yisaer](https://github.com/Yisaer)
- 修复了错误地下推 `StreamAgg` 到 TiFlash 导致结果错误的问题 [#39266](https://github.com/pingcap/tidb/issues/39266) @[fixdb](https://github.com/fixdb)

2022-12-08 02:23 UTC, qiancai commented on releases/release-6.5.0.md
> +- JSON 抽取函数下推至 TiFlash
```suggestion
- 支持通过 `INSERT INTO SELECT` 语句保存 TiFlash 查询结果（实验特性）
- JSON 抽取函数下推至 TiFlash
```

2022-12-08 03:23 UTC, hfxsd commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](https://github.com/pingcap/tidb/issues/38514)。
```suggestion
* 支持导出和导入 gzip、snappy、zstd 三种压缩格式的 SQL、CSV 文件 [#38514](https://github.com/pingcap/tidb/issues/38514) @[lichunzhu](https://github.com/lichunzhu) **tw@hfxsd**

    Dumpling 支持将数据导出为 SQL、CSV 的压缩文件，支持 gzip、snappy、zstd 三种压缩格式。TiDB Lightning 支持导入压缩后的 SQL、CSV 文件，支持 gzip、snappy、zstd 三种压缩格式。

    之前用户导出数据或者导入数据都需要提供较大的存储空间，用于存储导出或者即将导入的非压缩后的 csv 、sql文件，导致存储成本增加。该功能发布后，通过压缩存储空间，可以大大降低用户的存储成本。

    更多信息，请参考[用户文档](/dumpling-overview.md#通过并发提高-dumpling-的导出效率)。
```

2022-12-08 03:32 UTC, hfxsd commented on releases/release-6.5.0.md
> +    有这个功能之前，TiDB Lightning 在使用物理模式导入数据时，会在本地磁盘创建大量的临时文件，用来对原始数据进行编码、排序、分割。当用户本地磁盘空间不足时，TiDB Lightning 会由于写入文件失败而报错退出。
```suggestion
* TiDB Lightning 支持 disk quota 特性 GA，可避免 TiDB Lightning 任务写满本地磁盘 [#无](无) @[buchuitoudegou](https://github.com/buchuitoudegou) **tw@hfxsd**

    你可以为 TiDB Lightning 配置磁盘配额 (disk quota)。当磁盘配额不足时，TiDB Lightning 会暂停读取源数据以及写入临时文件的过程，优先将已经完成排序的 key-value 写入到 TiKV。TiDB Lightning 删除本地临时文件后，再继续导入过程。

    有这个功能之前，TiDB Lightning 在使用物理模式导入数据时，会在本地磁盘创建大量的临时文件，用来对原始数据进行编码、排序、分割。当用户本地磁盘空间不足时，TiDB Lightning 会由于写入文件失败而报错退出。
```

2022-12-08 03:40 UTC, hfxsd commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档]( https://docs.pingcap.com/tidb/v6.4/dm-continuous-data-validation)。
```suggestion
    更多信息，请参考[用户文档](/tidb-lightning-physical-import-mode-usage.md#磁盘资源配额-从-v6.2.0-版本开始引入)。

* DM 增量数据校验的功能 GA [#4426](https://github.com/pingcap/tiflow/issues/4426) @[D3Hunter](https://github.com/D3Hunter) **tw@hfxsd**

    在将增量数据从上游迁移到下游数据库的过程中，数据的流转有小概率导致错误或者丢失的情况。对于需要依赖强数据一致的场景，如信贷、证券等业务，你可以在数据迁移完成之后对数据进行全量校验，确保数据的一致性。然而，在某些增量复制的业务场景下，上游和下游的写入是持续的、不会中断的。由于上下游的数据在不断变化，导致用户难以对表里面的全部数据进行一致性校验。

    过去，需要中断业务才能进行全量数据校验，会影响用户业务。推出该功能后，你无需中断业务即可实现增量数据校验。

    更多信息，请参考[用户文档](/dm/dm-continuous-data-validation.md)。
```

2022-12-08 03:54 UTC, time-and-fate approved these changes

2022-12-08 03:54 UTC, hfxsd commented on releases/release-6.5.0.md
> +    原先用户仅迁移少数几张表，也需要解析上游整个 binlog 文件，即仍需要解析该 binlog 文件中不需要迁移的表的 binlog event，效率会比较低，同时如果不在迁移任务里的库表的 binlog event 不支持解析，还会导致任务失败。通过只解析在迁移任务里的库表对象的 binlog event 可以大大提升 binlog 解析效率，提升任务稳定性。
```suggestion
* 优化了 binlog 解析能力 [#无](无) @[gmhdbjd](https://github.com/GMHDBJD) **tw@hfxsd**

    可将不在迁移任务里的库、表对象的 binlog event 过滤掉不做解析，从而提升解析效率和稳定性。该策略在 v6.5.0 版本默认生效，你无需额外操作。

    原先即使仅迁移几张表，也需要解析上游整个 binlog 文件，即仍要解析该 binlog 文件中不需要迁移的表的 binlog event，效率较低。同时，如果不在迁移任务里的库表的 binlog event 不支持解析，还会导致任务失败。通过只解析在迁移任务里的库表对象的 binlog event，可以大大提升 binlog 解析效率，提升任务稳定性。
```

2022-12-08 08:13 UTC, nolouch commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 优化锁的粒度以减少锁争用，提升高并发下心跳的处理能力 [#5586](https://github.com/tikv/pd/issues/5586) @[rleungx](https://github.com/rleungx)
 - 优化调度器在大规模集群下的性能问题，提升调度策略生产速度 [#5473](https://github.com/tikv/pd/issues/5473) @[bufferflies](https://github.com/bufferflies)
 - 增加 btree 的泛型性支持，提升其性能 [#5606](https://github.com/tikv/pd/issues/5606) @[rleungx](https://github.com/rleungx)
 - 优化心跳处理过程，减少一些不要的开销 [#5648](https://github.com/tikv/pd/issues/5648)@[rleungx](https://github.com/rleungx)
```

2022-12-08 08:17 UTC, nolouch commented on releases/release-6.5.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复热点调度配置在没有修改的情况下不持久化的问题 [#5701](https://github.com/tikv/pd/issues/5701)  @[HunDunDM](https://github.com/HunDunDM)
    - 修复 rank-formula-version 在升级过程中没有保持升级前的配置的问题 [#5699](https://github.com/tikv/pd/issues/5698) @[HunDunDM](https://github.com/HunDunDM)
```

2022-12-08 09:40 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +- 优化器代价模型 V2 GA
- TiDB 支持通过 TiCDC 将实时变更数据保存到存储服务(S3/Azure Blob Storage/NFS)
- 支持两套或者多套 TiDB 集群之间进行相互复制
- PITR 的恢复性能提升 x 倍，RPO 降低到 x min
- TiCDC 同步数据到 Kafka 吞吐提升 x 倍，复制延迟降低到 x 秒

2022-12-08 10:04 UTC, pingyu commented on releases/release-6.5.0.md
> +    TiKV-BR 是一个 TiKV 集群的备份和恢复工具。TiKV 可以独立于 TiDB，与 PD 构成 KV 数据库，此时的产品形态为 RawKV。TiKV-BR 工具支持对使用 RawKV 的产品进行备份和恢复，也支持将 TiKV 集群中的数据从 `API V1` 备份为 `API V2` 数据， 以实现 TiKV 集群 [`api-version`](https://docs.pin
```suggestion
    TiKV-BR 是一个 TiKV 集群的备份和恢复工具。TiKV 可以独立于 TiDB，与 PD 构成 KV 数据库，此时的产品形态为 RawKV。TiKV-BR 工具支持对使用 RawKV 的产品进行备份和恢复，也支持将 TiKV 集群中的数据从 `API V1` 备份为 `API V2` 数据， 以实现 TiKV 集群 [`api-version`](/tikv-configuration-file.md#api-version-从-v610-版本开始引入) 的升级。
```

2022-12-08 15:24 UTC, qiancai commented on releases/release-6.5.0.md
> +    [`EXPLAIN ANALYZE`] 语句可以输出执行计划及运行时的统计信息。在 v6.5.0 中，TiFlash 对 TableFullScan 算子的执行信息进行了完善，补充了 DMFile 相关的执行信息。你可以更加直观地查看 TiFlash 的数据扫描状态信息，方便进行性能分析。
```suggestion
    [`EXPLAIN ANALYZE`] 语句可以输出执行计划及运行时的统计信息。在 v6.5.0 中，TiFlash 对 TableFullScan 算子的执行信息进行了完善，补充了 DMFile 相关的执行信息。你可以更加直观地查看 TiFlash 的数据扫描状态信息，方便进行性能分析。
```
```suggestion
    `EXPLAIN ANALYZE` 语句可以输出执行计划及运行时的统计信息。在 v6.5.0 中，TiFlash 对 TableFullScan 算子的执行信息进行了完善，补充了 DMFile 相关的执行信息。你可以更加直观地查看 TiFlash 的数据扫描状态信息，方便进行性能分析。
```

2022-12-09 10:03 UTC, pingyu commented on releases/release-6.5.0.md
> +    - 引入 witness peer [#12876](https://github.com/tikv/tikv/issues/12876) @[Connor1996](https://github.com/Connor1996)
```suggestion
```

Not released in v6.5.0 yet.

2022-12-09 10:20 UTC, Yui-Song commented on releases/release-6.5.0.md
> +    TiDB v6.2.0 引入了代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2) 作为实验特性，通过更准确的代价估算方式，有利于最优执行计划的选择。尤其在部署了 TiFlash 的情况下，Cost Model Version 2 自动选择合理的存储引擎，避免过多的人工介入。经过一段时间真实场景的测试，这个模型在
觉得可以加一句，对于升级到 v6.5.0 的集群默认仍然使用 Cost  Model Version 1。其他的 LGTM

2022-12-12 02:33 UTC, hfxsd commented on releases/release-6.5.0.md
> +    - 增加了 TableFullScan 的输出信息 [#5926](https://github.com/pingcap/tiflash/issues/5926) @[hongyunyan](https://github.com/hongyunyan)
```suggestion
    - 优化锁的粒度以减少锁争用，提升高并发下心跳的处理能力 [#5586](https://github.com/tikv/pd/issues/5586) @[rleungx](https://github.com/rleungx)
    - 优化调度器在大规模集群下的性能，提升调度策略生产速度 [#5473](https://github.com/tikv/pd/issues/5473) @[bufferflies](https://github.com/bufferflies)
    - 增加 B-tree 的泛型性支持 [#5606](https://github.com/tikv/pd/issues/5606) @[rleungx](https://github.com/rleungx)
    - 优化心跳处理过程，减少一些不必要的开销 [#5648](https://github.com/tikv/pd/issues/5648)@[rleungx](https://github.com/rleungx)
    - 增加了自动清理 tombstone store 的功能 [#5348](https://github.com/tikv/pd/issues/5348) @[nolouch](https://github.com/nolouch)

+ TiFlash

    - 提升了 TiFlash 在 SQL 端没有攒批的场景的写入性能 [#6404](https://github.com/pingcap/tiflash/issues/6404) @[lidezhu](https://github.com/lidezhu)
    - 增加了 TableFullScan 的输出信息 [#5926](https://github.com/pingcap/tiflash/issues/5926) @[hongyunyan](https://github.com/hongyunyan)
```

2022-12-12 02:33 UTC, hfxsd commented on releases/release-6.5.0.md
> +        - 在慢查询页面新增三个字段 `是否由 prepare 语句生成`，`查询计划是否来自缓存`，`查询计划是否来自绑定` 的描述。 [#1445](https://github.com/pingcap/tidb-dashboard/pull/1445/files) @[shhdgit](https://github.com/shhdgit)
```suggestion
        - 在慢查询页面新增以下三个字段的描述：`是否由 prepare 语句生成`、`查询计划是否来自缓存`、`查询计划是否来自绑定` 的描述。[#1445](https://github.com/pingcap/tidb-dashboard/pull/1445/files) @[shhdgit](https://github.com/shhdgit)
```

2022-12-12 02:33 UTC, hfxsd commented on releases/release-6.5.0.md
> +    - 修复 TiFlash Open File OPS 过高的问题 [#6345](https://github.com/pingcap/tiflash/issues/6345) @[JaySon-Huang](https://github.com/JaySon-Huang)
```suggestion
    - 修复热点调度配置在没有修改的情况下不持久化的问题 [#5701](https://github.com/tikv/pd/issues/5701)  @[HunDunDM](https://github.com/HunDunDM)
    - 修复 `rank-formula-version` 在升级过程中没有保持升级前的配置的问题 [#5699](https://github.com/tikv/pd/issues/5698) @[HunDunDM](https://github.com/HunDunDM)

+ TiFlash

    - 修复 TiFlash 重启不能正确合并小文件的问题 [#6159](https://github.com/pingcap/tiflash/issues/6159) @[lidezhu](https://github.com/lidezhu)
    - 修复 TiFlash Open File OPS 过高的问题 [#6345](https://github.com/pingcap/tiflash/issues/6345) @[JaySon-Huang](https://github.com/JaySon-Huang)
```

2022-12-12 07:04 UTC, hfxsd commented on releases/release-6.5.0.md
> +* TiDB Lightning 支持 disk quota 特性 GA，可避免 TiDB Lightning 任务写满本地磁盘 [#无](无) @[buchuitoudegou](https://github.com/buchuitoudegou) **tw@hfxsd**
```suggestion
* TiDB Lightning 支持 disk quota 特性 GA，可避免 TiDB Lightning 任务写满本地磁盘 [#446](https://github.com/pingcap/tidb-lightning/issues/446) @[buchuitoudegou](https://github.com/buchuitoudegou) **tw@hfxsd**
```

2022-12-12 07:51 UTC, hfxsd commented on releases/release-6.5.0.md
> +    有这个功能之前，TiDB Lightning 在使用物理模式导入数据时，会在本地磁盘创建大量的临时文件，用来对原始数据进行编码、排序、分割。当用户本地磁盘空间不足时，TiDB Lightning 会由于写入文件失败而报错退出。
```suggestion
    有这个功能之前，TiDB Lightning 在使用物理模式导入数据时，会在本地磁盘创建大量的临时文件，用来对原始数据进行编码、排序、分割。当用户本地磁盘空间不足时，TiDB Lightning 会由于写入文件失败而报错退出。推出该功能后，可避免 TiDB Lightning 任务写满本地磁盘。
```

2022-12-13 03:43 UTC, SunRunAway commented on releases/release-6.5.0.md
> +
```suggestion
- [非事务 DML 语句](/non-transactional-dml.md)
- 支持 [Time to live (TTL)](/time-to-live.md)（实验特性）

```

2022-12-13 08:17 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 修复对 Geometry 字段类型的支持 [#13651](https://github.com/tikv/tikv/issues/13651) @[dveeden](https://github.com/dveeden)
```suggestion
    - 修复对 Geometry 字段类型的支持问题 [#13651](https://github.com/tikv/tikv/issues/13651) @[dveeden](https://github.com/dveeden)
```

2022-12-13 08:17 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 修复 tikv-ctl 执行 reset-to-version 时出现 segfault 的问题 [#13829](https://github.com/tikv/tikv/issues/13829) @[tabokie](https://github.com/tabokie)
```suggestion
    - 修复 tikv-ctl 执行 `reset-to-version` 命令时被终止的问题 [#13829](https://github.com/tikv/tikv/issues/13829) @[tabokie](https://github.com/tabokie)
```

2022-12-13 08:17 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 修复当未使用 new collation 时 `like` 无法处理 `_` 中非 ASCII 字符的问题 [#13769](https://github.com/tikv/tikv/issues/13769) @[YangKeao](https://github.com/YangKeao)
```suggestion
    - 修复当未启用 new collation 时 `LIKE` 操作符中的 `_` 无法匹配非 ASCII 字符的问题 [#13769](https://github.com/tikv/tikv/issues/13769) @[YangKeao](https://github.com/YangKeao)
```

2022-12-13 09:17 UTC, ChenPeng2013 commented on releases/release-6.5.0.md
> +    TiDB v6.2.0 引入了代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2) 作为实验特性，通过更准确的代价估算方式，有利于最优执行计划的选择。尤其在部署了 TiFlash 的情况下，Cost Model Version 2 自动选择合理的存储引擎，避免过多的人工介入。经过一段时间真实场景的测试，这个模型在
@Yui-Song 也可能小概率之前就设置了 cost model version 2，虽然是实验特性

2022-12-13 11:16 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 引入 raft extension 以提升代码可扩展性 [#13864](https://github.com/tikv/tikv/pull/13864) @[BusyJay](https://github.com/BusyJay)
```suggestion
    - 引入 raft extension 以提升代码可扩展性 [#13827](https://github.com/tikv/tikv/issues/13827) @[BusyJay](https://github.com/BusyJay)
```

2022-12-13 11:20 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 通过代码优化减少内存申请 [#13836](https://github.com/tikv/tikv/pull/13836) @[BusyJay](https://github.com/BusyJay)
```suggestion
    - 通过代码优化减少内存申请 [#13827](https://github.com/tikv/tikv/issues/13827) @[BusyJay](https://github.com/BusyJay)
```

2022-12-13 11:34 UTC, ran-huang commented on releases/release-6.5.0.md
> +        - 通过不再解析黑名单表的数据提升了 dm 同步数据的性能 [#7622](https://github.com/pingcap/tiflow/pull/7622) @[GMHDBJD](https://github.com/GMHDBJD)
```suggestion
        - 通过不再解析黑名单表的数据提升了 DM 同步数据的性能 [#7622](https://github.com/pingcap/tiflow/pull/7622) @[GMHDBJD](https://github.com/GMHDBJD)
```

2022-12-13 11:34 UTC, ran-huang commented on releases/release-6.5.0.md
> +        - 改进 DM 针对老版本 MySQL 使用 `SHOW SLAVE HOSTS` 获取结果时的兼容性 [#7373](https://github.com/pingcap/tiflow/pull/7372) @[lyzx2001](https://github.com/lyzx2001)
```suggestion
        - 通过异步写与批量写的方式提升 DM relay 的写数据效率 [#7580](https://github.com/pingcap/tiflow/pull/7580) @[GMHDBJD](https://github.com/GMHDBJD)
        - 改进 DM 前置检查的错误提示信息 [#7621](https://github.com/pingcap/tiflow/issues/7621) @[buchuitoudegou](https://github.com/buchuitoudegou)
        - 改进 DM 针对老版本 MySQL 使用 `SHOW SLAVE HOSTS` 获取结果时的兼容性 [#5017](https://github.com/pingcap/tiflow/issues/5017) @[lyzx2001](https://github.com/lyzx2001)
```

2022-12-13 11:34 UTC, ran-huang commented on releases/release-6.5.0.md
> +        - 修复无法在上游开启 gtid mode 且无数据时启动 all mode 任务的错误 [#7037](https://github.com/pingcap/tiflow/issues/7037) @[liumengya94](https://github.com/liumengya94)
```suggestion
        - 修复在上游开启 GTID mode 且无数据时，无法启动 all mode 任务的问题 [#7037](https://github.com/pingcap/tiflow/issues/7037) @[liumengya94](https://github.com/liumengya94)
```

2022-12-13 11:34 UTC, ran-huang commented on releases/release-6.5.0.md
> +        - 修复上游数据库使用正则匹配授权时 DM 前置检查不通过的错误[#7645](https://github.com/pingcap/tiflow/issues/7645) @[lance6716](https://github.com/lance6716)
```suggestion
        - 修复当 DM worker 即将退出时新 worker 调度过快导致数据被重复同步的问题 [#7658](https://github.com/pingcap/tiflow/issues/7658) @[GMHDBJD](https://github.com/GMHDBJD)
        - 修复上游数据库使用正则匹配授权时 DM 前置检查不通过的错误 [#7645](https://github.com/pingcap/tiflow/issues/7645) @[lance6716](https://github.com/lance6716)
```

2022-12-13 12:33 UTC, pingyu commented on releases/release-6.5.0.md
> +    - 通过引入 `hint_min_ts` 加速 flashback [#13842](https://github.com/tikv/tikv/pull/13842)  @[JmPotato](https://github.com/JmPotato)
这个可以删掉，前边有一块专门介绍 flashback 特性的。

2022-12-13 14:15 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 通过引入 `hint_min_ts` 加速 flashback [#13842](https://github.com/tikv/tikv/pull/13842)  @[JmPotato](https://github.com/JmPotato)
```suggestion
```

2022-12-13 15:20 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 修复 raft engine ctl 中的错误 [#11119](https://github.com/tikv/tikv/issues/11119) @[tabokie](https://github.com/tabokie)
```suggestion
    - 修复 Raft Engine ctl 中的错误 [#11119](https://github.com/tikv/tikv/issues/11119) @[tabokie](https://github.com/tabokie)
```

2022-12-14 03:48 UTC, qiancai commented on releases/release-6.5.0.md
> +
```suggestion

* 新增支持绑定历史执行计划(实验特性) [#39199](https://github.com/pingcap/tidb/issues/39199) @[fzzf678](https://github.com/fzzf678) 

在 v6.5.0 中，TiDB 扩展了 `CREATE [GLOBAL | SESSION] BINDING FROM` 语句，支持通过指定 `plan_digest` 创建绑定。

受 SQL 语句运行时各种因素的影响，好的执行计划偶尔会被替代，进而影响 SQL 性能。此时，只要原来的执行计划仍旧在 SQL 执行历史内存表尚未被清除，你就可以使用 `plan_digest` 为该 SQL 语句绑定原来的的执行计划，快速恢复 SQL 性能。此方式只需要用一条命令绑定这个计划，简化了处理执行计划突变这类问题的过程，提升了运维效率。

    更多信息，请参考[用户文档](/tiflash/tiflash-results-materialization.md)。

```

2022-12-14 06:20 UTC, qiancai commented on releases/release-6.5.0.md
> +* 新增支持绑定历史执行计划（实验特性）[#39199](https://github.com/pingcap/tidb/issues/39199) @[fzzf678](https://github.com/fzzf678)
```suggestion
* 新增支持绑定历史执行计划（实验特性）[#39199](https://github.com/pingcap/tidb/issues/39199) @[fzzf678](https://github.com/fzzf678) **tw@qiancai**
```

2022-12-14 06:58 UTC, TomShawn commented on releases/release-6.5.0.md
> +    对于在 `WHERE` 子句中使用 `AND` 联结的过滤条件，现已支持使用索引合并特性（v6.5 之前的版本只支持对 `OR` 联结词的过滤条件使用索引合并），TiDB 的索引合并至此可以覆盖更一般的查询过滤条件组合，不再限定于并集（`OR`）关系。当前版本仅支持优化器自动选择 `OR` 条件下的索引合并。要开启对于 `AND` 联结的索引合并，用户须使用 [`USE_INDEX_ME
```suggestion
    在 v6.5.0 前，TiDB 只支持对 `OR` 联结词的过滤条件使用索引合并特性。自 v6.5.0 起，对于在 `WHERE` 子句中使用 `AND` 联结的过滤条件，TiDB 已支持使用索引合并特性，TiDB 的索引合并至此可以覆盖更一般的查询过滤条件组合，不再限定于并集（`OR`）关系。当前 v6.5.0 版本仅支持优化器自动选择 `OR` 条件下的索引合并。要开启对于 `AND` 联结的索引合并，你需要使用 [`USE_INDEX_MERGE`](/optimizer-hints.md#use_index_merget1_name-idx1_name--idx2_name-) Hint。
```

2022-12-14 07:12 UTC, qiancai commented on releases/release-6.5.0.md
> +    [`EXPLAIN ANALYZE`] 语句可以输出执行计划及运行时的统计信息。在 v6.5.0 中，TiFlash 对 TableFullScan 算子的执行信息进行了完善，补充了 DMFile 相关的执行信息。你可以更加直观地查看 TiFlash 的数据扫描状态信息，方便进行性能分析。
```suggestion
    `EXPLAIN ANALYZE` 语句可以输出执行计划及运行时的统计信息。在 v6.5.0 中，TiFlash 对 TableFullScan 算子的执行信息进行了完善，补充了 DMFile 相关的执行信息。你可以更加直观地查看 TiFlash 的数据扫描状态信息，方便进行性能分析。
```

2022-12-14 08:05 UTC, TomShawn commented on releases/release-6.5.0.md
> +    对于运行 v6.5.0 及以上版本的用户，建议移除配置项 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit)，取消对事务内存做单独的限制，转而使用系统变量 [`tidb_mem_quota_query`](/system-variables.md#tidbmemquotaquery) 和 [
```suggestion
    对于运行 v6.5.0 及以上版本的用户，建议移除配置项 [`txn-total-size-limit`](/tidb-configuration-file.md#txn-total-size-limit)，取消对事务内存做单独的限制，转而使用系统变量 [`tidb_mem_quota_query`](/system-variables.md#tidb_mem_quota_query) 和 [`tidb_server_memory_limit`](/system-variables.md#tidb_server_memory_limit-从-v640-版本开始引入) 对全局内存进行管理，从而提高内存的使用效率。
```

2022-12-14 08:42 UTC, qiancai commented on releases/release-6.5.0.md
> +* 执行计划支持打印 JSON 格式 [#39261](https://github.com/pingcap/tidb/issues/39261) @[fzzf678](https://github.com/fzzf678) **tw@ran-huang**
```suggestion
* 支持将执行计划打印为 JSON 格式 [#39261](https://github.com/pingcap/tidb/issues/39261) @[fzzf678](https://github.com/fzzf678) **tw@ran-huang**
```

2022-12-14 08:42 UTC, qiancai commented on releases/release-6.5.0.md
> +    在新版本中，TiDB 扩展了执行计划的打印格式。 通过 `EXPLAIN FORMAT=tidb_json <SQL语句>` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
```suggestion
    在 v6.5.0 中，TiDB 扩展了执行计划的打印格式。通过 `EXPLAIN FORMAT=tidb_json <SQL语句>` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
```

2022-12-14 09:18 UTC, TomShawn commented on releases/release-6.5.0.md
> +    - 修复了错误地下推 `StreamAgg` 到 TiFlash 导致结果错误的问题 [#39266](https://github.com/pingcap/tidb/issues/39266) @[fixdb](https://github.com/fixdb)
```suggestion
    - 修复 `tidb_constraint_check_in_place_pessimistic` 可能被全局设置影响内部 session 的问题 [#38766](https://github.com/pingcap/tidb/issues/38766) @[ekexium](https://github.com/ekexium)
    - 修复了 `AUTO_INCREMENT` 列无法和 `Check` 约束一起使用的问题 [#38894](https://github.com/pingcap/tidb/issues/38894) @[YangKeao](https://github.com/YangKeao)
    - 修复使用 `INSERT IGNORE INTO` 往 `SMALLINT` 类型的自增列插入 `STRING` 类型的数据会报错的问题 [#38483](https://github.com/pingcap/tidb/issues/38483) @[hawkingrei](https://github.com/hawkingrei)
    - 修复了重命名分区表的分区列操作出现空指针报错的问题 [#38932](https://github.com/pingcap/tidb/issues/38932) @[mjonss](https://github.com/mjonss)
    - 修复了一个修改分区表的分区列导致 DDL 卡死的问题 [#38530](https://github.com/pingcap/tidb/issues/38530) @[mjonss](https://github.com/mjonss)
    - 修复了从 v4.0 升级到 v6.4 后 `ADMIN SHOW JOB` 操作崩溃的问题 [#38980](https://github.com/pingcap/tidb/issues/38980) @[tangenta](https://github.com/tangenta)
    - 修复了 `tidb_decode_key` 函数未正确处理分区表编码的问题 [#39304](https://github.com/pingcap/tidb/issues/39304) @[Defined2014](https://github.com/Defined2014)
    - 修复了日志轮转时，gRPC 的错误日志信息未被重定向到正确的日志文件的问题 [#38941](https://github.com/pingcap/tidb/issues/38941) @[xhebox](https://github.com/xhebox)
    - 修复了 `BEGIN; SELECT... FOR UPDATE;` 点查在 read engines 未配置 TiKV 时生成非预期执行计划的问题 [#39344](https://github.com/pingcap/tidb/issues/39344) @[Yisaer](https://github.com/Yisaer)
    - 修复了错误地下推 `StreamAgg` 到 TiFlash 导致结果错误的问题 [#39266](https://github.com/pingcap/tidb/issues/39266) @[fixdb](https://github.com/fixdb)
```

2022-12-14 11:07 UTC, ran-huang commented on releases/release-6.5.0.md
> +* 支持将 [分区表](/partitioned-table.md)的排序操作下推至 TiKV [#26166](https://github.com/pingcap/tidb/issues/26166) @[winoros](https://github.com/winoros) **tw@qiancai**
```suggestion
* 支持将[分区表](/partitioned-table.md)的排序操作下推至 TiKV [#26166](https://github.com/pingcap/tidb/issues/26166) @[winoros](https://github.com/winoros) **tw@qiancai**
```

2022-12-15 02:46 UTC, TomShawn commented on releases/release-6.5.0.md
> +    - `cdc.min-ts-interval` 默认值从 `1s` 改为 `200ms` 以降低 CDC 延迟 [#12840](https://github.com/tikv/tikv/issues/12840) @[hicqu](https://github.com/hicqu)
前面兼容性变更部分已经有这一条了，这里是否可以删掉呢？
```suggestion
```

2022-12-15 02:47 UTC, qiancai commented on releases/release-6.5.0.md
> +        - 通过不再解析黑名单表的数据提升了 DM 同步数据的性能 [#7622](https://github.com/pingcap/tiflow/pull/7622) @[GMHDBJD](https://github.com/GMHDBJD)
```suggestion
        - 通过不再解析黑名单中表的数据提升 DM 同步数据的性能 [#4287](https://github.com/pingcap/tiflow/issues/4287) @[GMHDBJD](https://github.com/GMHDBJD)
```

2022-12-15 02:47 UTC, qiancai commented on releases/release-6.5.0.md
> +        - 通过异步写与批量写的方式提升 DM relay 的写数据效率 [#7580](https://github.com/pingcap/tiflow/pull/7580) @[GMHDBJD](https://github.com/GMHDBJD)
```suggestion
        - 通过异步写与批量写的方式提升 DM relay 的写数据效率 [#4287](https://github.com/pingcap/tiflow/issues/4287) @[GMHDBJD](https://github.com/GMHDBJD)
```

2022-12-15 02:47 UTC, qiancai commented on releases/release-6.5.0.md
> +        - 修复在上游开启 GTID mode 且无数据时，无法启动 all mode 任务的问题 [#7037](https://github.com/pingcap/tiflow/issues/7037) @[liumengya94](https://github.com/liumengya94)
```suggestion
        - 修复在上游开启 `GTID` mode 且无数据时，无法启动 `all` mode 任务的问题 [#7037](https://github.com/pingcap/tiflow/issues/7037) @[liumengya94](https://github.com/liumengya94)
```

2022-12-15 02:47 UTC, qiancai commented on releases/release-6.5.0.md
> +        - (dup) 修复当 DM worker 即将退出时新 worker 调度过快导致数据被重复同步的问题 [#7658](https://github.com/pingcap/tiflow/issues/7658) @[GMHDBJD](https://github.com/GMHDBJD)
```suggestion
        - 修复当 DM worker 即将退出时新 worker 调度过快导致数据被重复同步的问题 [#7658](https://github.com/pingcap/tiflow/issues/7658) @[GMHDBJD](https://github.com/GMHDBJD)
```

2022-12-15 02:50 UTC, ran-huang commented on releases/release-6.5.0.md
> +        - 通过不再解析黑名单表的数据提升了 DM 同步数据的性能 [#7622](https://github.com/pingcap/tiflow/pull/7622) @[GMHDBJD](https://github.com/GMHDBJD)
@qiancai 这里不建议用 issue，因为那个 issue 没有任何内容，而且关联了很多个 PR

2022-12-15 02:50 UTC, ran-huang commented on releases/release-6.5.0.md
> +        - 通过异步写与批量写的方式提升 DM relay 的写数据效率 [#7580](https://github.com/pingcap/tiflow/pull/7580) @[GMHDBJD](https://github.com/GMHDBJD)
同上

2022-12-15 02:58 UTC, TomShawn commented on releases/release-6.5.0.md
> +    - 实现 `json_valid` 函数下推 [#13571](https://github.com/tikv/tikv/issues/13571) @[lizhenhuan](https://github.com/lizhenhuan)
```suggestion
    - 支持将 `json_valid` 函数下推至 TiKV [#13571](https://github.com/tikv/tikv/issues/13571) @[lizhenhuan](https://github.com/lizhenhuan)
```

2022-12-15 02:58 UTC, TomShawn commented on releases/release-6.5.0.md
> +    - Coprocessor 支持批量处理 [#13849](https://github.com/tikv/tikv/issues/13849) @[cfzjywxk](https://github.com/cfzjywxk)
```suggestion
    - TiKV 支持批量处理 Coprocessor 任务 [#13849](https://github.com/tikv/tikv/issues/13849) @[cfzjywxk](https://github.com/cfzjywxk)
```

2022-12-15 02:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +    独立部署 TiDB Dashboard 后，用户将获得这些收益：1. 该组件的计算将不会再对 PD 节点有压力，更好的保障集群运行；2. 如果 PD 节点因异常不可访问，也还可以继续使用 Dashboard 进行集群诊断；3. 在开放 TiDB Dashboard 到外网时，不用担心 PD 中的特权端口的权限问题，降低集群的安全风险。
```suggestion
    独立部署 TiDB Dashboard，可以获得以下收益：

        - 该组件的计算将不会再对 PD 节点有压力，可以更好的保障集群运行。
        - 如果 PD 节点因异常不可访问，也还可以继续使用 TiDB Dashboard 进行集群诊断。
        - 在开放 TiDB Dashboard 到外网时，不用担心 PD 中的特权端口的权限问题，降低集群的安全风险。
```

2022-12-15 02:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +    具体信息，参考 [TiDB Operator 部署独立的 TiDB Dashboard](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/get-started#部署独立的-tidb-dashboard)
```suggestion
    更多信息，参考 [TiDB Operator 部署独立的 TiDB Dashboard](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/get-started#部署独立的-tidb-dashboard)。
```

2022-12-15 02:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +* TiCDC 支持输出 storage sink [tiflow#6797](https://github.com/pingcap/tiflow/issues/6797) @[zhaoxinyu](https://github.com/zhaoxinyu) **tw@shichun-0415**
```suggestion
* TiCDC 支持输出变更数据至 storage sink [tiflow#6797](https://github.com/pingcap/tiflow/issues/6797) @[zhaoxinyu](https://github.com/zhaoxinyu) **tw@shichun-0415**
```

2022-12-15 02:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +    TiCDC 支持将 changed log 输出到 S3/Azure Blob Storage/NFS，以及兼容 S3 协议的存储服务中。Cloud Storage 价格便宜，使用方便。对于不希望使用 Kafka 的用户，可以选择使用 storage sink。 TiCDC 将 changed log 保存到文件，然后发送到 storage 中；消费程序定时从 storage 读取新产生
```suggestion
    TiCDC 支持将 changed log 输出到 S3、Azure Blob Storage、NFS，以及兼容 S3 协议的存储服务中。云存储价格便宜，使用方便。对于不希望使用 Kafka 的用户，可以选择使用 storage sink。TiCDC 将 changed log 保存到文件，然后发送到存储系统中；消费程序定时从存储系统读取新产生的 changed log files 进行处理。
```

2022-12-15 02:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +    Storage sink 支持 changed log 格式位 canal-json/csv，此外 changed log 从 TiCDC 同步到 storage 的延迟可以达到 xx，支持更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12151/files)。
```suggestion
    存储 sink 支持格式为 canal-json 和 csv 的 changed log，此外 changed log 从 TiCDC 同步到存储的延迟可以达到 xx。更多信息，请参考[用户文档](/ticdc/ticdc-sink-to-cloud-storage.md)。
```

2022-12-15 02:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +    在 TiDB 场景测试验证中， TiCDC 的性能得到了比较大提升，单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s，即使在常规的 TiKV/TiCDC 滚动升级场景同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC Redo log 和 Sync point 后，吞吐 xx rows/s 时，容灾复制延迟可以保持在 x s。
```suggestion
    在 TiDB 场景测试验证中， TiCDC 的性能得到了比较大提升。

    单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s。即使在常规的 TiKV/TiCDC 滚动升级场景，同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC Redo log 和 Syncpoint 后，吞吐为 xx rows/s 时，容灾复制延迟可以保持在 x s。
```

2022-12-15 02:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +* PITR 性能大幅提升提升 **tw@shichun-0415
```suggestion
* PITR 性能大幅提升 **tw@shichun-0415
```

2022-12-15 02:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +  PITR 恢复的日志恢复阶单台 TiKV 的恢复速度可以达到 xx MB/s，提升了 x 倍，恢复速度可扩展，有效地降低容灾场景的 RTO 指标；容灾场景的 RPO 优化到 5 min，在常规的集群运维，如滚动升级，单 TiKV 故障等场景下，可以达到 RPO = 5 min 目标。
```suggestion
  PITR 恢复的日志恢复阶段，单台 TiKV 的恢复速度可以达到 xx MB/s，提升了 x 倍。恢复速度可扩展，有效地降低容灾场景的 RTO 指标；容灾场景的 RPO 优化到 5 min，在常规的集群运维，如滚动升级，单 TiKV 故障等场景下，可以达到 RPO = 5 min 目标。
```

2022-12-15 03:27 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    - 修复了一个修改分区表的分区列导致 DDL 卡死的问题 [#38530](https://github.com/pingcap/tidb/issues/38530) @[mjonss](https://github.com/mjonss)
```suggestion
    - 修复了修改分区表的分区列导致 DDL 卡死的问题 [#38530](https://github.com/pingcap/tidb/issues/38530) @[mjonss](https://github.com/mjonss)
```

2022-12-15 03:27 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    - 修复了从 v4.0 升级到 v6.4 后 `ADMIN SHOW JOB` 操作崩溃的问题 [#38980](https://github.com/pingcap/tidb/issues/38980) @[tangenta](https://github.com/tangenta)
```suggestion
    - 修复了从 v4.0.16 升级到 v6.4.0 后 `ADMIN SHOW JOB` 操作崩溃的问题 [#38980](https://github.com/pingcap/tidb/issues/38980) @[tangenta](https://github.com/tangenta)
```

2022-12-15 03:27 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    - 修复了 `BEGIN; SELECT... FOR UPDATE;` 点查在 read engines 未配置 TiKV 时生成非预期执行计划的问题 [#39344](https://github.com/pingcap/tidb/issues/39344) @[Yisaer](https://github.com/Yisaer)
```suggestion
    - 修复了 `BEGIN; SELECT... FOR UPDATE;` 点查在读数据存储引擎 ( `tidb_isolation_read_engines`) 未配置 TiKV 时生成非预期执行计划的问题 [#39344](https://github.com/pingcap/tidb/issues/39344) @[Yisaer](https://github.com/Yisaer)
```

2022-12-15 03:28 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    - `cdc.min-ts-interval` 默认值从 `1s` 改为 `200ms` 以降低 CDC 延迟 [#12840](https://github.com/tikv/tikv/issues/12840) @[hicqu](https://github.com/hicqu)
@pingyu PTAL

2022-12-15 03:44 UTC, TomShawn commented on releases/release-6.5.0.md
> +    Cost Model Version 2 成为正式功能大幅提升了 TiDB 优化器的整体能力，并切实地向更加强大的 HTAP 数据库演进。
```suggestion
    Cost Model Version 2 成为正式功能大幅提升了 TiDB 优化器的整体能力，并使 TiDB 切实地向更加强大的 HTAP 数据库演进。
```

2022-12-15 03:57 UTC, qiancai commented on releases/release-6.5.0.md
> +- [添加索引加速](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入) 功能 GA，添加索引性能提升为原来的 10 倍
```suggestion
- [添加索引加速](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入) 功能 GA，添加索引的性能提升较 v6.1 提升了 10 倍
- 支持高性能、全局单调递增的 [`AUTO_INCREMENT` 列属性](/auto-increment.md#mysql-兼容模式)，兼容 MySQL
```

2022-12-15 03:57 UTC, qiancai commented on releases/release-6.5.0.md
> +- [TiDB 全局内存控制](/configure-memory-usage.md) GA
```suggestion
- [`tidb_server_memory_limit`](/system-variables.md#tidb_server_memory_limit-从-v640-版本开始引入) 可对全局内存控制的功能 GA
```

2022-12-15 03:57 UTC, qiancai commented on releases/release-6.5.0.md
> +- 支持 [Time to live (TTL)](/time-to-live.md)（实验特性）
```suggestion
- 支持行级别 [Time to live (TTL)](/time-to-live.md) 管理数据生命周期（实验特性）
```

2022-12-15 03:57 UTC, qiancai commented on releases/release-6.5.0.md
> +- [代价模型 V2](/cost-model.md#cost-model-version-2) GA
```suggestion
```

2022-12-15 03:57 UTC, qiancai commented on releases/release-6.5.0.md
> +- 进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能
```suggestion
- 增强[优化器代价模型](/cost-model.md#cost-model-version-2)并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能
```

2022-12-15 03:57 UTC, qiancai commented on releases/release-6.5.0.md
> +- 支持[保存 TiFlash 查询结果](/tiflash/tiflash-results-materialization.md)（实验特性）
```suggestion
```

2022-12-15 03:57 UTC, qiancai commented on releases/release-6.5.0.md
> +- [全局 Hint](/optimizer-hints.md#全局生效的-Hint) 干预视图内查询的计划生成
```suggestion
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +| TiKV | [`cdc.min-ts-interval`](/tikv-configuration-file.md#min-ts-interval) | 修改 | 默认值从 `1s` 修改为 `200ms` |
```suggestion
| TiKV | [`cdc.min-ts-interval`](/tikv-configuration-file.md#min-ts-interval) | 修改 | 默认值从 `1s` 修改为 `200ms` |
| TiKV | [`memory-use-ratio`](/tikv-configuration-file.md#memory-use-ratio-从-v650-版本开始引入) | 新增 | 用于 PITR 日志恢复功能，表示 PITR 恢复中可用内存与系统总内存的占比。 |
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 提升在恢复时的稳定性，允许 PD leader 切换的情况发生 [#36910](https://github.com/pingcap/tidb/issues/36910) @[MoCuishle28](https://github.com/MoCuishle28)
```suggestion
        - (dup) 修复恢复过程中由于 PD leader 切换导致恢复失败的问题 [#36910](https://github.com/pingcap/tidb/issues/36910) @[MoCuishle28](https://github.com/MoCuishle28)
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 日志备份的 tls 功能使用 openssl 协议，提升 tls 兼容性。[#13867](https://github.com/tikv/tikv/issues/13867) @[YuJuncen](https://github.com/YuJuncen)
```suggestion
        - 日志备份的 TLS 功能使用 OpenSSL 协议，提升 TLS 的兼容性 [#13867](https://github.com/tikv/tikv/issues/13867) @[YuJuncen](https://github.com/YuJuncen)
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 采用并发的方式对数据进行编码，极大提升了同步到 kafka 的吞吐能力 [#7532](https://github.com/pingcap/tiflow/issues/7532) [#7543](https://github.com/pingcap/tiflow/issues/7543) [#7540](https://github.com/pingcap/tiflow/i
```suggestion
        - (dup) 提升 Kafka 相关协议的编码性能  [#7540](https://github.com/pingcap/tiflow/issues/7540) [#7532](https://github.com/pingcap/tiflow/issues/7532) [#7543](https://github.com/pingcap/tiflow/issues/7543) @[3AceShowHand](https://github.com/3AceShowHand) @[sdojjy](https://github.com/sdojjy)
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 修复在大于 6.1 版本关闭 new_collation 设置，仍然恢复失败的问题 [#39150](https://github.com/pingcap/tidb/issues/39150) @[MoCuishle28](https://github.com/MoCuishle28)
```suggestion
        - (dup) 修复 BR 删除日志备份数据时，会删除不应被删除的数据的问题 [#38939](https://github.com/pingcap/tidb/issues/38939) @[Leavrth](https://github.com/Leavrth)
        - (dup) 修复数据库或数据表中使用旧的排序规则框架时，数据恢复失败的问题[#39150](https://github.com/pingcap/tidb/issues/39150) @[MoCuishle28](https://github.com/MoCuishle28)
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 修复在执行drop table 时用户快速暂停恢复同步任务导致可能的数据丢失问题 [#7682](https://github.com/pingcap/tiflow/issues/7682) @[asddongmen](https://github.com/asddongmen)
```suggestion
        - (dup) 修复在执行 DDL 后，暂停然后恢复 changefeed 会导致数据丢失的问题 [#7682](https://github.com/pingcap/tiflow/issues/7682) @[asddongmen](https://github.com/asddongmen)
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 修复下游网络出现故障导致cdc 卡住的问题 [#7706](https://github.com/pingcap/tiflow/issues/7706) @[hicqu](https://github.com/hicqu)
```suggestion
        - (dup) 修复下游网络发生异常时 sink 模块卡住的问题 [#7706](https://github.com/pingcap/tiflow/issues/7706) @[hicqu](https://github.com/hicqu)
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 修复 PD leader crash时 CDC 卡住的问题 [#7470](https://github.com/pingcap/tiflow/issues/7470) @[zeminzhou](https://github.com/zeminzhou)
```suggestion
        - 修复 PD leader crash 时 TiCDC 卡住的问题 [#7470](https://github.com/pingcap/tiflow/issues/7470) @[zeminzhou](https://github.com/zeminzhou)
```

2022-12-15 03:58 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 兼容上游开启 TiFlash 时版本兼容性问题 [#7744](https://github.com/pingcap/tiflow/issues/7744) @[overvenus](https://github.com/overvenus)
```suggestion
        - 修复存在高版本 TiFlash 时，TiCDC 会误报错的问题 [#7744](https://github.com/pingcap/tiflow/issues/7744) @[overvenus](https://github.com/overvenus)
```

2022-12-15 03:59 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 优化清理备份日志数据是 BR 的内存使用 [#38869](https://github.com/pingcap/tidb/issues/38869) @[Leavrth](https://github.com/Leavrth)
```suggestion
        - 优化清理备份日志数据时 BR 的内存使用 [#38869](https://github.com/pingcap/tidb/issues/38869) @[Leavrth](https://github.com/Leavrth)
```

2022-12-15 05:46 UTC, qiancai commented on releases/release-6.5.0.md
> +- [贡献者 GitHub ID](链接)
```suggestion
- [贡献者 GitHub ID](链接)
- [e1ijah1](https://github.com/e1ijah1)
- [guoxiangCN](https://github.com/guoxiangCN)（首次贡献者）
- [jiayang-zheng](https://github.com/jiayang-zheng)
- [jiyfhust](https://github.com/jiyfhust)
- [mikechengwei](https://github.com/mikechengwei)
- [pingandb](https://github.com/pingandb)
- [sashashura](https://github.com/sashashura)
- [sourcelliu](https://github.com/sourcelliu)
- [wxbty](https://github.com/wxbty)
```

2022-12-15 08:13 UTC, qiancai commented on releases/release-6.5.0.md
> +| [`validate_password.dictionary`](/system-variables.md#validate_passworddictionary-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，密码字典功能，设置的用户密码不允许包含字典中的单词。只有 [`validate_password.enable`](/system-variables.md#val
```suggestion
| [`validate_password.dictionary`](/system-variables.md#validate_passworddictionary-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，密码字典功能，设置的用户密码不允许包含字典中的单词。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启且 [validate_password.policy](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) 设置为 `2` (STRONG) 时，该变量才生效。默认值为空。 |
```

2022-12-15 08:13 UTC, qiancai commented on releases/release-6.5.0.md
> +| [`validate_password.check_user_name`](/system-variables.md#validate_passwordcheck_user_name-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，设置的用户密码不允许密码与当前会话账户的用户名部分相同。只有 [`validate_password.enable`](/system-vari
```suggestion
| [`validate_password.check_user_name`](/system-variables.md#validate_passwordcheck_user_name-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，设置的用户密码不允许密码与当前会话账户的用户名部分相同。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启时，该变量才生效。默认值为 `ON`。 |
```

2022-12-15 08:13 UTC, qiancai commented on releases/release-6.5.0.md
> +| [`validate_password.mixed_case_count`](/system-variables.md#validate_passwordmixed_case_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中大写字符和小写字符的最小数量。只有 [`validate_password.enable`](/system-variabl
```suggestion
| [`validate_password.length`](/system-variables.md#validate_passwordlength-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码最小长度。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启时，该变量才生效。默认值为 8。 |
| [`validate_password.mixed_case_count`](/system-variables.md#validate_passwordmixed_case_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中大写字符和小写字符的最小数量。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启且 [validate_password.policy](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) 大于或等于 `1` (MEDIUM) 时，该变量才生效。默认值为 1。 |
```

2022-12-15 08:13 UTC, qiancai commented on releases/release-6.5.0.md
> +| [`validate_password.special_char_count`](/system-variables.md#validate_passwordspecial_char_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中特殊字符的最小数量。只有 [`validate_password.enable`](/system-variable
```suggestion
| [`validate_password.number_count`](/system-variables.md#validate_passwordnumber_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中数字字符的最小数量。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启且 [validate_password.policy](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) 大于或等于 `1` (MEDIUM) 时，该变量才生效。默认值为 1。 |
| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]` 。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启时，该变量才生效。默认值为 1。 |
| [`validate_password.special_char_count`](/system-variables.md#validate_passwordspecial_char_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中特殊字符的最小数量。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启且 [validate_password.policy](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) 大于或等于 `1` (MEDIUM) 时，该变量才生效。默认值为 1。 |
```

2022-12-15 08:13 UTC, qiancai commented on releases/release-6.5.0.md
> +| TiDB | [`disconnect-on-expired-password`](/tidb-configuration-file.md#disconnect-on-expired-password`-从-v650-版本开始引入) | 新增 | 该配置用于控制 TiDB 服务端是否直接断开密码已过期用户的连接，默认值为 "true" ，表示 TiDB 服务端将直接断开密码已过期用户的连接
```suggestion
| TiDB | [`disconnect-on-expired-password`](/tidb-configuration-file.md#disconnect-on-expired-password`-从-v650-版本开始引入) | 新增 | 该配置用于控制 TiDB 服务端是否直接断开密码已过期用户的连接，默认值为 `true`，表示 TiDB 服务端将直接断开密码已过期用户的连接 |
```

2022-12-15 08:19 UTC, qiancai commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](链接)。
```suggestion
```

2022-12-15 08:19 UTC, qiancai commented on releases/release-6.5.0.md
> +
```suggestion
```

2022-12-15 08:44 UTC, qiancai commented on releases/release-6.5.0.md
> +即将于 v6.6.0 版本废弃 v4.0.7 版本引入的 Amending Transaction 机制，并使用[元数据锁](/metadata-lock.md) 替代。
```suggestion
v6.5.0 的下一个 v6.x 版本（即 v6.6.0） 将废弃 v4.0.7 版本引入的 [`AMEND TRANSACTION`](/system-variables.md#tidb_enable_amend_pessimistic_txn-从-v407-版本开始引入) 机制，并使用[元数据锁](/metadata-lock.md) 替代。
```

2022-12-15 09:13 UTC, TomShawn commented on releases/release-6.5.0.md
> +    在数据分析的场景中，通过无过滤条件的 `count(*)` 获取表的实际行数是一个常见操作。 TiFlash 在新版本中优化了 `count(*)` 的改写，自动选择带有“非空”属性的数据类型最短的列进行计数， 可以有效降低 TiFlash 上发生的 I/O 数量，进而提升获取表行数的执行效率。
```suggestion
* TiFlash 对获取表行数的操作进行优化 [#37165](https://github.com/pingcap/tidb/issues/37165) @[elsa0520](https://github.com/elsa0520)

    在数据分析的场景中，通过无过滤条件的 `COUNT(*)` 获取表的实际行数是一个常见操作。TiFlash 在 v6.5.0 中优化了 `COUNT(*)` 的改写，自动选择带有“非空”属性且最短的列进行计数， 这样可以有效降低 TiFlash 上发生的 I/O 数量，进而提升获取表行数的执行效率。
```

2022-12-15 09:36 UTC, hfxsd commented on releases/release-6.5.0.md
> +    在 TiDB 场景测试验证中， TiCDC 的性能得到了比较大提升。
```suggestion
    在 TiDB 场景测试验证中，TiCDC 的性能得到了比较大提升。
```

2022-12-15 09:36 UTC, hfxsd commented on releases/release-6.5.0.md
> +    单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s。即使在常规的 TiKV/TiCDC 滚动升级场景，同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC Redo log 和 Syncpoint 后，吞吐为 xx rows/s 时，容灾复制延迟可以保持在 x s。
这里两处 xx  记得替换成数据

2022-12-15 09:36 UTC, hfxsd commented on releases/release-6.5.0.md
> +    TiDB 快照备份功能支持断点续传。当 BR 遇到对可恢复的错误时会进行重试，但是超过固定重试次数之后会备份退出。断点续传功能允许对持续更长时间的可恢复故障进行重试恢复，比如几十分钟的的网络故障。
```suggestion
    TiDB 快照备份功能支持断点续传。当 BR 遇到对可恢复的错误时会进行重试，但是超过固定重试次数之后会备份退出。断点续传功能允许对持续更长时间的可恢复故障进行重试恢复，比如几十分钟的网络故障。
```

2022-12-15 09:36 UTC, hfxsd commented on releases/release-6.5.0.md
> +    TiKV-BR 是一个 TiKV 集群的备份和恢复工具。TiKV 可以独立于 TiDB，与 PD 构成 KV 数据库，此时的产品形态为 RawKV。TiKV-BR 工具支持对使用 RawKV 的产品进行备份和恢复，也支持将 TiKV 集群中的数据从 `API V1` 备份为 `API V2` 数据， 以实现 TiKV 集群 [`api-version`](/tikv-configurat
```suggestion
    TiKV-BR 是一个 TiKV 集群的备份和恢复工具。TiKV 可以独立于 TiDB，与 PD 构成 KV 数据库，此时的产品形态为 RawKV。TiKV-BR 工具支持对使用 RawKV 的产品进行备份和恢复，也支持将 TiKV 集群中的数据从 `API V1` 备份为 `API V2` 数据，以实现 TiKV 集群 [`api-version`](/tikv-configuration-file.md#api-version-从-v610-版本开始引入) 的升级。
```

2022-12-15 09:36 UTC, hfxsd commented on releases/release-6.5.0.md
> +        - 修复因非 s3 存储的不兼容请求导致备份 panic 的问题 [39545](https://github.com/pingcap/tidb/issues/39545) @[3pointer](https://github.com/3pointer)
这句话看不懂，建议改写
```suggestion
        - 修复因非 Amazon S3 存储的不兼容请求导致备份 panic 的问题 [39545](https://github.com/pingcap/tidb/issues/39545) @[3pointer](https://github.com/3pointer)
```

2022-12-15 09:54 UTC, benmaoer requested changes
change depreciated feature version

2022-12-15 09:54 UTC, benmaoer commented on releases/release-6.5.0.md
> +v6.5.0 的下一个 v6.x 版本（即 v6.6.0） 将废弃 v4.0.7 版本引入的 [`AMEND TRANSACTION`](/system-variables.md#tidb_enable_amend_pessimistic_txn-从-v407-版本开始引入) 机制，并使用[元数据锁](/metadata-lock.md) 替代。
```suggestion
v6.5.0 版本开始废弃 v4.0.7 版本引入的  [`AMEND TRANSACTION`](/system-variables.md#tidb_enable_amend_pessimistic_txn-从-v407-版本开始引入) 机制，并使用[元数据锁](/metadata-lock.md) 替代。
```

2022-12-15 10:01 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +    - 修复 TiFlash Open File OPS 过高的问题 [#6345](https://github.com/pingcap/tiflash/issues/6345) @[JaySon-Huang](https://github.com/JaySon-Huang)
Could we provide the full name of OPS?

2022-12-15 10:17 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 在开放 TiDB Dashboard 到外网时，不用担心 PD 中的特权端口的权限问题，降低集群的安全风险。
```suggestion
    - TiDB Dashboard 的计算将不会再对 PD 节点有压力，可以更好的保障集群运行。
    - 如果 PD 节点因异常不可访问，也还可以继续使用 TiDB Dashboard 进行集群诊断。
    - 在开放 TiDB Dashboard 到外网时，不用担心 PD 中的特权端口的权限问题，降低集群的安全风险。
```

2022-12-15 10:17 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +    单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s。即使在常规的 TiKV/TiCDC 滚动升级场景，同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC Redo log 和 Syncpoint 后，吞吐为 xx rows/s 时，容灾复制延迟可以保持在 x s。
测试仍在进行，QA 有数据后会提供。

2022-12-15 10:17 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 修复因非 s3 存储的不兼容请求导致备份 panic 的问题 [39545](https://github.com/pingcap/tidb/issues/39545) @[3pointer](https://github.com/3pointer)
Done

2022-12-15 10:33 UTC, songrijie commented on releases/release-6.5.0.md
> +    在数据分析的场景中，通过无过滤条件的 `count(*)` 获取表的实际行数是一个常见操作。 TiFlash 在新版本中优化了 `count(*)` 的改写，自动选择带有“非空”属性的数据类型最短的列进行计数， 可以有效降低 TiFlash 上发生的 I/O 数量，进而提升获取表行数的执行效率。
LGTM

2022-12-15 10:40 UTC, hfxsd commented on releases/release-6.5.0.md
> +    - 修复 TiFlash Open File OPS 过高的问题 [#6345](https://github.com/pingcap/tiflash/issues/6345) @[JaySon-Huang](https://github.com/JaySon-Huang)
```suggestion
    - 修复 TiFlash File Open OPS 过高的问题 [#6345](https://github.com/pingcap/tiflash/issues/6345) @[JaySon-Huang](https://github.com/JaySon-Huang)
```

2022-12-15 11:02 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 复阿里云和华为云跟 S3 存储不完全兼容导致的备份失败的问题 [39545](https://github.com/pingcap/tidb/issues/39545) @[3pointer](https://github.com/3pointer)
```suggestion
        - 修复阿里云和华为云与 S3 存储不完全兼容导致的备份失败问题 [39545](https://github.com/pingcap/tidb/issues/39545) @[3pointer](https://github.com/3pointer)
```

2022-12-15 11:04 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +        - 修复阿里云和华为云与 S3 存储不完全兼容导致的备份失败问题 [39545](https://github.com/pingcap/tidb/issues/39545) @[3pointer](https://github.com/3pointer)
```suggestion
        - 修复阿里云和华为云与 S3 存储不完全兼容导致的备份失败问题 [#39545](https://github.com/pingcap/tidb/issues/39545) @[3pointer](https://github.com/3pointer)
```

2022-12-16 01:39 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiCDC 支持[将实时变更数据保存到存储服务](ticdc/ticdc-sink-to-cloud-storage.md)(S3/Azure Blob Storage/NFS)。
```suggestion
- TiCDC 支持[将实时变更数据保存到存储服务](ticdc/ticdc-sink-to-cloud-storage.md)(例如，S3、Azure Blob Storage、NFS)。
```

2022-12-16 02:59 UTC, yiwen92 requested changes
• 默认开启[索引加速功能](https://github.com/pingcap/docs-cn/blob/master/system-variables.md#tidb_ddl_enable_fast_reorg-%E4%BB%8E-v630-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5)，添加索引的性能提升较 v6.1 提升了 10 倍。
• 支持通过 [tidb_server_memory_limit](https://github.com/pingcap/docs-cn/blob/master/system-variables.md#tidb_server_memory_limit-%E4%BB%8E-v640-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5) 控制 TiDB 全局内存。
• 支持高性能、全局单调递增的 AUTO_INCREMENT 列属性，兼容 MySQL。
• 支持 [FLASHBACK CLUSTER TO TIMESTAMP](https://github.com/pingcap/docs-cn/blob/master/sql-statements/sql-statement-flashback-to-timestamp.md)，兼容 TiCDC 和 PITR。
• 增强[优化器代价模型](https://github.com/pingcap/docs-cn/blob/master/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](https://github.com/pingcap/docs-cn/blob/master/glossary.md#index-merge) 功能。
• 支持下推 JSON_EXTRACT() 函数至 TiFlash。
• 支持[密码管理](https://github.com/pingcap/docs-cn/blob/master/password-management.md)策略，满足密码合规审计需求。
• TiDB Lightning 和 Dumpling 支持[导入](https://github.com/pingcap/docs-cn/blob/master/releases/tidb-lightning/tidb-lightning-data-source.md)和[导出](https://github.com/pingcap/docs-cn/blob/master/dumpling-overview.md#%E9%80%9A%E8%BF%87%E5%B9%B6%E5%8F%91%E6%8F%90%E9%AB%98-dumpling-%E7%9A%84%E5%AF%BC%E5%87%BA%E6%95%88%E7%8E%87)压缩格式文件。
• TiDB Data Migration (DM) 支持[增量数据校验](https://github.com/pingcap/docs-cn/blob/master/dm/dm-continuous-data-validation.md)。
• TiDB 快照备份支持断点续传，[PITR](https://github.com/pingcap/docs-cn/blob/master/br-pitr-guide.md#%E8%BF%9B%E8%A1%8C-pitr) 性能提升 x 倍，RPO 降低到 x min。
• TiCDC [同步数据到 Kafka](https://github.com/pingcap/docs-cn/blob/master/replicate-data-to-kafka.md) 吞吐提升 x 倍，复制延迟降低到 x 秒。
• 提供行级别 [Time to live (TTL)](https://github.com/pingcap/docs-cn/blob/master/time-to-live.md) 管理数据生命周期（实验特性）。
TiCDC 支持 S3/Azure Blob Storage/NFS 对象存储（实验特性）。

2022-12-16 03:14 UTC, qiancai commented on releases/release-6.5.0.md
> +- 支持高性能、全局单调递增的 [`AUTO_INCREMENT` 列属性](/auto-increment.md#mysql-兼容模式)，兼容 MySQL。
```suggestion
- 支持高性能、全局单调递增的 [`AUTO_INCREMENT` 列属性](/auto-increment.md#mysql-兼容模式)，兼容 MySQL。
- 支持 [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md)，兼容 TiCDC 和 PITR。
```

2022-12-16 03:14 UTC, qiancai commented on releases/release-6.5.0.md
> +- 支持[下推 `JSON_EXTRACT()` 函数](/tiflash/tiflash-supported-pushdown-calculations.md)至 TiFlash。
```suggestion
- 支持下推 `JSON_EXTRACT()` 函数至 TiFlash。
```

2022-12-16 03:14 UTC, qiancai commented on releases/release-6.5.0.md
> +- 支持[密码管理](/password-management.md)策略，满足密码合规审计需求。
```suggestion
- 支持[密码管理](/password-management.md)策略，满足密码合规审计需求。
- TiDB Lightning 和 Dumpling 支持[导入](tidb-lightning/tidb-lightning-data-source.md)和[导出](/dumpling-overview.md#通过并发提高-dumpling-的导出效率)压缩格式文件。
- TiDB Data Migration (DM) 支持[增量数据校验](/dm/dm-continuous-data-validation.md)。
```

2022-12-16 03:14 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiCDC [同步数据到 Kafka](/replicate-data-to-kafka.md) 吞吐提升 x 倍，复制延迟降低到 x 秒。
```suggestion
- TiDB 快照备份支持断点续传，[PITR](/br-pitr-guide.md#进行-pitr) 的恢复性能提升 x 倍，RPO 降低到 x min。
- TiCDC [同步数据到 Kafka](/replicate-data-to-kafka.md) 吞吐提升 x 倍，复制延迟降低到 x 秒。
- 提供行级别 [Time to live (TTL)](/time-to-live.md) 管理数据生命周期（实验特性）。
- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的 [对象存储](ticdc/ticdc-sink-to-cloud-storage.md)
```

2022-12-16 03:16 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的 [对象存储](ticdc/ticdc-sink-to-cloud-storage.md)
```suggestion
- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的 [对象存储](ticdc/ticdc-sink-to-cloud-storage.md)。
```

2022-12-16 03:22 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的 [对象存储](ticdc/ticdc-sink-to-cloud-storage.md)。
```suggestion
- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的[对象存储](ticdc/ticdc-sink-to-cloud-storage.md)。
```

2022-12-16 03:29 UTC, qiancai commented on releases/release-6.5.0.md
> +* TiCDC 支持输出变更数据至 storage sink [tiflow#6797](https://github.com/pingcap/tiflow/issues/6797) @[zhaoxinyu](https://github.com/zhaoxinyu) **tw@shichun-0415**
```suggestion
* TiCDC 支持输出变更数据至 storage sink（实验特性） [tiflow#6797](https://github.com/pingcap/tiflow/issues/6797) @[zhaoxinyu](https://github.com/zhaoxinyu) **tw@shichun-0415**
```

2022-12-16 03:30 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的 [对象存储](ticdc/ticdc-sink-to-cloud-storage.md)。
```suggestion
- TiCDC [同步数据到 Kafka](/replicate-data-to-kafka.md) 吞吐提升 x 倍，复制延迟降低到 x 秒。
- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的 [对象存储](ticdc/ticdc-sink-to-cloud-storage.md) （实验特性）。
- 提供行级别 [Time to live (TTL)](/time-to-live.md) 管理数据生命周期（实验特性）。
```

2022-12-16 03:46 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的 [对象存储](ticdc/ticdc-sink-to-cloud-storage.md)。
```suggestion
- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的[对象存储](ticdc/ticdc-sink-to-cloud-storage.md) （实验特性）。
```

2022-12-16 04:41 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +- 默认开启[索引加速功能](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入)，添加索引的性能提升较 v6.1 提升了 10 倍。
```suggestion
- 默认开启[添加索引加速功能](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入)，添加索引的性能提升为 v6.1.0 的 10 倍。
```

2022-12-16 04:43 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +- 支持高性能、全局单调递增的 [`AUTO_INCREMENT` 列属性](/auto-increment.md#mysql-兼容模式)，兼容 MySQL。
```suggestion
- 支持高性能、全局单调递增、兼容 MySQL 的 [`AUTO_INCREMENT` 列属性](/auto-increment.md#mysql-兼容模式)。
```

2022-12-16 04:43 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +- 支持 [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md)，兼容 TiCDC 和 PITR。
```suggestion
- 支持通过 [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 命令将集群快速回退到特定的时间点，兼容 TiCDC 和 PITR。
```

2022-12-16 04:47 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +- 增强[优化器代价模型](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能。
```suggestion
- 优化器引入更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对合取范式的支持。
```
@TomShawn PTAL

2022-12-16 04:48 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +- [索引加速功能](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入)默认开启，与 [PITR (Point-in-time recovery)](/br/br-pitr-guide.md) 功能不兼容。在使用索引加速功能时，需要确保后台没有启动 PITR 备份任务，否则可能会出现非预期结果，详情请参考[tidb_ddl
```suggestion
- [添加索引加速功能](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入)默认开启，与 [PITR (Point-in-time recovery)](/br/br-pitr-guide.md) 不兼容。在使用索引加速功能时，需要确保后台没有启动 PITR 备份任务，否则可能会出现非预期结果。详情请参考 [`tidb_ddl_enable_fast_reorg`](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入)。
```

2022-12-16 06:02 UTC, TomShawn commented on releases/release-6.5.0.md
> +- 默认开启[索引加速功能](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入)，添加索引的性能提升较 v6.1 提升了 10 倍。
“约 10 倍”？

2022-12-16 06:03 UTC, TomShawn commented on releases/release-6.5.0.md
> +- 增强[优化器代价模型](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能。
```suggestion
- 优化器进一步增强更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对合取范式的支持。
```

2022-12-16 06:08 UTC, hfxsd commented on releases/release-6.5.0.md
> +- TiDB Data Migration (DM) 支持[增量数据校验](/dm/dm-continuous-data-validation.md)。
```suggestion
- TiDB Data Migration (DM) 的[增量数据校验](/dm/dm-continuous-data-validation.md)特性 GA。
```

2022-12-19 02:24 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +- 优化器进一步增强更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对合取范式的支持。
```suggestion
- 优化器引入的更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2) GA，同时优化器增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对合取范式的支持。
```
@qiancai @TomShawn PTAL

2022-12-19 02:29 UTC, qiancai commented on releases/release-6.5.0.md
> +- 优化器进一步增强更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对合取范式的支持。
```suggestion
- 优化器引入的更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2) GA，同时优化器支持索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对合取范式的支持。
```

2022-12-19 03:04 UTC, qiancai commented on releases/release-6.5.0.md
> +- [添加索引加速](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入)特性 GA，添加索引的性能提升为 v6.1.0 的约 10 倍。
```suggestion
- [添加索引加速](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入)特性 GA，添加索引的性能约提升为 v6.1.0 的 10 倍。
```

2022-12-19 03:56 UTC, qiancai commented on releases/release-6.5.0.md
> +* 新增支持绑定历史执行计划（实验特性）[#39199](https://github.com/pingcap/tidb/issues/39199) @[fzzf678](https://github.com/fzzf678) **tw@qiancai**
```suggestion
* 支持绑定历史执行计划（实验特性）[#39199](https://github.com/pingcap/tidb/issues/39199) @[fzzf678](https://github.com/fzzf678) **tw@qiancai**
```

2022-12-19 03:56 UTC, qiancai commented on releases/release-6.5.0.md
> +    更多信息，参考 [TiDB Operator 部署独立的 TiDB Dashboard](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/get-started#部署独立的-tidb-dashboard)。
```suggestion
    更多信息，请参考 [TiDB Operator 部署独立的 TiDB Dashboard](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/get-started#部署独立的-tidb-dashboard)。
```

2022-12-19 03:56 UTC, qiancai commented on releases/release-6.5.0.md
> +* 新增支持下推以下[JSON 函数](/tiflash/tiflash-supported-pushdown-calculations.md) 至 TiFlash [#39458](https://github.com/pingcap/tidb/issues/39458) @[yibin87](https://github.com/yibin87) **tw@qiancai**
```suggestion
* 新增支持下推以下 JSON 函数至 TiFlash [#39458](https://github.com/pingcap/tidb/issues/39458) @[yibin87](https://github.com/yibin87) **tw@qiancai**
```

2022-12-19 03:56 UTC, qiancai commented on releases/release-6.5.0.md
> +* 新增支持下推以下 [字符串函数](/tiflash/tiflash-supported-pushdown-calculations.md) 至 TiFlash [#6115](https://github.com/pingcap/tiflash/issues/6115) @[xzhangxian1008](https://github.com/xzhangxian1008) **tw@qia
```suggestion
* 新增支持下推以下字符串函数至 TiFlash [#6115](https://github.com/pingcap/tiflash/issues/6115) @[xzhangxian1008](https://github.com/xzhangxian1008) **tw@qiancai**
```

2022-12-19 03:56 UTC, qiancai commented on releases/release-6.5.0.md
> +| TiDB | [`disconnect-on-expired-password`](/tidb-configuration-file.md#disconnect-on-expired-password`-从-v650-版本开始引入) | 新增 | 该配置用于控制 TiDB 服务端是否直接断开密码已过期用户的连接，默认值为 `true`，表示 TiDB 服务端将直接断开密码已过期用户的连接 |
```suggestion
| TiDB | [`disconnect-on-expired-password`](/tidb-configuration-file.md#disconnect-on-expired-password`-从-v650-版本开始引入) | 新增 | 该配置用于控制 TiDB 服务端是否直接断开密码已过期用户的连接，默认值为 `true`，表示 TiDB 服务端将直接断开密码已过期用户的连接。 |
```

2022-12-19 03:56 UTC, qiancai commented on releases/release-6.5.0.md
> +v6.5.0 版本开始废弃 v4.0.7 版本引入的 [`AMEND TRANSACTION`](/system-variables.md#tidb_enable_amend_pessimistic_txn-从-v407-版本开始引入) 机制，并使用[元数据锁](/metadata-lock.md)替代。
```suggestion
v6.5.0 开始废弃 v4.0.7 版本引入的 [`AMEND TRANSACTION`](/system-variables.md#tidb_enable_amend_pessimistic_txn-从-v407-版本开始引入) 机制，并使用[元数据锁](/metadata-lock.md)替代。
```

2022-12-19 03:59 UTC, TomShawn commented on releases/release-6.5.0.md
> +- 优化器进一步增强更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对合取范式的支持。
LGTM

2022-12-19 04:01 UTC, TomShawn commented on releases/release-6.5.0.md
> +* 索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能支持合取范式（`AND` 连接的表达式）[#39333](https://github.com/pingcap/tidb/issues/39333) @[guo-shaoge](https://github.com/guo-shaoge) @[time-and-fate](https://githu
```suggestion
* 索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能支持 `AND` 连接的表达式 [#39333](https://github.com/pingcap/tidb/issues/39333) @[guo-shaoge](https://github.com/guo-shaoge) @[time-and-fate](https://github.com/time-and-fate) @[hailanwhu](https://github.com/hailanwhu) **tw@TomShawn**
```

2022-12-19 04:02 UTC, TomShawn commented on releases/release-6.5.0.md
> +- 优化器进一步增强更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对合取范式的支持。
```suggestion
- 优化器进一步增强更精准的代价模型 [Cost Model Version 2](/cost-model.md#cost-model-version-2)，并进一步增强索引合并 [INDEX MERGE](/glossary.md#index-merge) 功能对 `AND` 连接的表达式的支持。
```

2022-12-19 06:38 UTC, Oreoxmt reviewed
@qiancai PTAL

2022-12-19 06:38 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* TiDB 添加索引的性能提升为原来的 10 倍 [#35983](https://github.com/pingcap/tidb/issues/35983) @[benjamin2037](https://github.com/benjamin2037) @[tangenta](https://github.com/tangenta) **tw@Oreoxmt**
```suggestion
* TiDB 添加索引的性能提升为原来的 10 倍 (GA) [#35983](https://github.com/pingcap/tidb/issues/35983) @[benjamin2037](https://github.com/benjamin2037) @[tangenta](https://github.com/tangenta) **tw@Oreoxmt**
```

2022-12-19 06:38 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* 提供轻量级元数据锁，提升 DDL 变更过程 DML 的成功率 [#37275](https://github.com/pingcap/tidb/issues/37275) @[wjhuang2016](https://github.com/wjhuang2016) **tw@Oreoxmt**
```suggestion
* 提供轻量级元数据锁，提升 DDL 变更过程 DML 的成功率 (GA) [#37275](https://github.com/pingcap/tidb/issues/37275) @[wjhuang2016](https://github.com/wjhuang2016) **tw@Oreoxmt**
```

2022-12-19 06:38 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* 支持通过 `FLASHBACK CLUSTER TO TIMESTAMP` 命令将集群快速回退到特定的时间点 [#37197](https://github.com/pingcap/tidb/issues/37197) [#13303](https://github.com/tikv/tikv/issues/13303) @[Defined2014](https://github.com/D
```suggestion
* 支持通过 `FLASHBACK CLUSTER TO TIMESTAMP` 命令将集群快速回退到特定的时间点 (GA) [#37197](https://github.com/pingcap/tidb/issues/37197) [#13303](https://github.com/tikv/tikv/issues/13303) @[Defined2014](https://github.com/Defined2014) @[bb7133](https://github.com/bb7133) @[JmPotato](https://github.com/JmPotato) @[Connor1996](https://github.com/Connor1996) @[HuSharp](https://github.com/HuSharp) @[CalvinNeo](https://github.com/CalvinNeo)  **tw@Oreoxmt**
```

2022-12-19 06:38 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* 优化器引入更精准的代价模型 Cost Model Version 2 [#35240](https://github.com/pingcap/tidb/issues/35240) @[qw4990](https://github.com/qw4990) **tw@Oreoxmt**
```suggestion
* 优化器引入更精准的代价模型 Cost Model Version 2 (GA) [#35240](https://github.com/pingcap/tidb/issues/35240) @[qw4990](https://github.com/qw4990) **tw@Oreoxmt**
```

2022-12-19 06:38 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* 支持高性能、全局单调递增的 `AUTO_INCREMENT` 列属性 [#38442](https://github.com/pingcap/tidb/issues/38442) @[tiancaiamao](https://github.com/tiancaiamao) **tw@Oreoxmt**
```suggestion
* 支持高性能、全局单调递增的 `AUTO_INCREMENT` 列属性 (GA) [#38442](https://github.com/pingcap/tidb/issues/38442) @[tiancaiamao](https://github.com/tiancaiamao) **tw@Oreoxmt**
```

2022-12-19 06:48 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* 支持 Time to live (TTL)（实验特性）[#39262](https://github.com/pingcap/tidb/issues/39262)  @[lcwangchao](https://github.com/lcwangchao) **tw@ran-huang**
```suggestion
* 支持 Time to live (TTL)（实验特性）[#39262](https://github.com/pingcap/tidb/issues/39262) @[lcwangchao](https://github.com/lcwangchao) **tw@ran-huang**
```

2022-12-19 06:48 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    从 v6.5.0 起， TiDB 支持下推 `INSERT INTO SELECT` 语句中的 `SELECT` 子句（分析查询）到 TiFlash，你可以将 TiFlash 的查询结果方便地保存到 `INSERT INTO` 指定的 TiDB 表中供后续分析使用，起到了结果缓存（即结果物化）的效果。例如：
```suggestion
    从 v6.5.0 起，TiDB 支持下推 `INSERT INTO SELECT` 语句中的 `SELECT` 子句（分析查询）到 TiFlash，你可以将 TiFlash 的查询结果方便地保存到 `INSERT INTO` 指定的 TiDB 表中供后续分析使用，起到了结果缓存（即结果物化）的效果。例如：
```

2022-12-19 06:48 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    [分区表](/partitioned-table.md)特性在 v6.1.0 正式 GA 后，TiDB 仍然在持续提升分区表相关的性能。在 v6.5.0 中， TiDB 支持将 `ORDER BY` 和 `LIMIT` 等排序操作下推至 TiKV 进行计算和过滤，降低网络 I/O 的开销，提升了使用分区表时 SQL 的性能。
```suggestion
    [分区表](/partitioned-table.md)特性在 v6.1.0 正式 GA 后，TiDB 仍然在持续提升分区表相关的性能。在 v6.5.0 中，TiDB 支持将 `ORDER BY` 和 `LIMIT` 等排序操作下推至 TiKV 进行计算和过滤，降低网络 I/O 的开销，提升了使用分区表时 SQL 的性能。
```

2022-12-19 06:48 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* TiKV-BR 工具 GA, 支持 RawKV 的备份和恢复 [#67](https://github.com/tikv/migration/issues/67) @[pingyu](https://github.com/pingyu) @[haojinming](https://github.com/haojinming) **tw@shichun-0415**
```suggestion
* TiKV-BR 工具 GA，支持 RawKV 的备份和恢复 [#67](https://github.com/tikv/migration/issues/67) @[pingyu](https://github.com/pingyu) @[haojinming](https://github.com/haojinming) **tw@shichun-0415**
```

2022-12-19 06:58 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* 支持通过 `INSERT INTO SELECT` 语句保存 TiFlash 查询结果（实验特性） [#37515](https://github.com/pingcap/tidb/issues/37515) @[gengliqi](https://github.com/gengliqi) **tw@qiancai**
```suggestion
* 支持通过 `INSERT INTO SELECT` 语句保存 TiFlash 查询结果（实验特性）[#37515](https://github.com/pingcap/tidb/issues/37515) @[gengliqi](https://github.com/gengliqi) **tw@qiancai**
```

2022-12-19 06:58 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](/tiflash/tiflash-results-materialization.md)。
```suggestion
  更多信息，请参考[用户文档](/tiflash/tiflash-results-materialization.md)。
```

2022-12-19 06:58 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    更多信息，请参考 [TiDB Operator 部署独立的 TiDB Dashboard](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/get-started#部署独立的-tidb-dashboard)。
```suggestion
  更多信息，请参考 [TiDB Operator 部署独立的 TiDB Dashboard](https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/get-started#部署独立的-tidb-dashboard)。
```

2022-12-19 06:58 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    JSON 格式为应用设计提供了灵活的建模方式，目前越来越多的应用采用 JSON 格式进行数据交换和数据存储。通过将 JSON 函数下推至 TiFlash，你可以提高 JSON 类型数据的分析效率，拓展 TiDB 实时分析的应用场景。
```suggestion
  JSON 格式为应用设计提供了灵活的建模方式，目前越来越多的应用采用 JSON 格式进行数据交换和数据存储。通过将 JSON 函数下推至 TiFlash，你可以提高 JSON 类型数据的分析效率，拓展 TiDB 实时分析的应用场景。
```

2022-12-20 03:19 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +    TiCDC 支持将 changed log 输出到 S3、Azure Blob Storage、NFS，以及兼容 S3 协议的存储服务中。Cloud storage 价格便宜，使用方便。对于不希望使用 Kafka 的用户，可以选择使用 storage sink。TiCDC 将 changed log 保存到文件，然后发送到存储系统中；消费程序定时从存储系统读取新产生的 changed l
```suggestion
    TiCDC 支持将 changed log 输出到 S3、Azure Blob Storage、NFS，以及兼容 S3 协议的存储服务中。Cloud storage 价格便宜，使用方便。对于不希望使用 Kafka 的用户，可以选择使用 storage sink。TiCDC 将 changed log 保存到文件，发送到存储系统中。用户自研的消费程序可以定时从存储系统读取新产生的 changed log 进行处理。
```

2022-12-20 03:35 UTC, dbsid commented on releases/release-6.5.0.md
> +
TiDB v6.5中的Performance Overview Grafana面板现在支持 TiFlash 和 CDC（Change Data Capture）。这意味着用户现在可以使用单个 Grafana 面板来分析他们的 TiDB 集群的所有组件。
请参照[新版性能调优手册](/performance-tuning-method.md)
    - 通过 TiFlash 面板，用户可以直观的了解 TiFlash 集群的请求类型、延迟分析和资源使用概览
    - 通过 CDC 面板，用户可以直观的了解 CDC 的集群健康状况、同步延迟、数据流和下游写入延迟等信息
    - SQL Execute Time Overview 新增 `tiflash_mpp` 类别；新增 KV Request Time By Source 信息，可以用来识别存储层的请求来源为正常的业务请求还是TiDB内部活动

2022-12-20 03:53 UTC, dbsid commented on releases/release-6.5.0.md
> +
TiDB v6.5.0 中的 Performance Overview Grafana 面板现在支持 TiFlash 和 CDC（Change Data Capture）。这意味着用户现在可以使用单个 Grafana 面板来分析他们的 TiDB 集群的所有组件。v6.5.0 中重新编排了 TiFlash 和 CDC 监控信息，大幅度提高 TiFlash 和 CDC 性能分析和故障诊断的效率。
请参照[新版性能调优手册](/performance-tuning-method.md)
    - 通过 TiFlash 面板，用户可以直观的了解 TiFlash 集群的请求类型、延迟分析和资源使用概览
    - 通过 CDC 面板，用户可以直观的了解 CDC 的集群健康状况、同步延迟、数据流和下游写入延迟等信息
    - SQL Execute Time Overview 新增 `tiflash_mpp` 类别；新增 KV Request Time By Source 信息，可以用来识别存储层的请求来源为正常的业务请求还是 TiDB 内部活动

2022-12-20 06:07 UTC, qiancai commented on releases/release-6.5.0.md
> +
```suggestion

+ Performance Overview 面板中新增  TiFlash 和 CDC (Change Data Capture) 面板

    TiDB 从 v6.1.0 起在 Grafana 中引入了 Performance Overview 面板，为 TiDB、TiKV、PD 提供了系统级别的总体性能诊断入口。在 v6.5.0 中，Performance Overview 面板中新增了 TiFlash 和 CDC 面板。通过此次新增，从 v6.5.0 起，使用单个 Performance Overview 面板即可分析 TiDB 集群中的所有组件的性能。

    TiFlash 和 CDC 面板重新编排了 TiFlash 和 CDC 相关的监控信息，可以帮助你大幅提高 TiFlash 和 CDC 性能分析和故障诊断的效率：
    
    - 通过 TiFlash 面板，你可以直观的了解 TiFlash 集群的请求类型、延迟分析和资源使用概览
    - 通过 CDC 面板，你可以直观的了解 CDC 的集群健康状况、同步延迟、数据流和下游写入延迟等信息
    
  更多信息，请参考[用户文档](performance-tuning-method.md/)。

```

2022-12-20 08:20 UTC, hfxsd commented on releases/release-6.5.0.md
> +    TiCDC 支持在线更新 TLS 证书。用户为了数据安全，会对系统使用的证书设置相应的过期策略，系统经过固定的时间后需要使用新的证书工作。TiCDC v6.5.0 支持在线更新 TLS 证书，在不影响同步的任务的前提下，TiCDC 会自动检测和更新新证书，无需用户手动操作，满足用户对证书更新的需求。
```suggestion
   * TiCDC 支持在线更新 TLS 证书 [tiflow#7908](https://github.com/pingcap/tiflow/issues/7908) @[CharlesCheung96](https://github.com/CharlesCheung96) **tw@shichun-0415**

    用户为了数据安全，会对系统使用的证书设置相应的过期策略，系统经过固定的时间后需要使用新的证书工作。TiCDC v6.5.0 支持在线更新 TLS 证书，在不影响同步的任务的前提下，TiCDC 会自动检测和更新证书，无需用户手动操作，满足用户对证书更新的需求。 
```

2022-12-20 08:35 UTC, qiancai commented on releases/release-6.5.0.md
> ++ Performance Overview 面板中新增 TiFlash 和 CDC (Change Data Capture) 面板
```suggestion
+ Performance Overview 面板中新增 TiFlash 和 CDC (Change Data Capture) 面板 [#39230](https://github.com/pingcap/tidb/issues/39230) @[dbsid](https://github.com/dbsid)
```

2022-12-21 01:16 UTC, qiancai commented on releases/release-6.5.0.md
> +|[`tidb_enable_amend_pessimistic_txn`](/system-variables.md#tidb_enable_amend_pessimistic_txn-从-v407-版本开始引入)| 废弃 | 从 v6.5.0 开始，该变量被废弃，TiDB 会默认使用[元数据锁](/metadata-lock.md)机制解决 `Information schema is ch
```suggestion
|[`tidb_enable_amend_pessimistic_txn`](/system-variables.md#tidb_enable_amend_pessimistic_txn-从-v407-版本开始引入)| 废弃 | 从 v6.5.0 开始，该变量被废弃，TiDB 会默认使用[元数据锁](/metadata-lock.md)机制解决 `Information schema is changed` 报错的问题。|
| [`tidb_enable_outer_join_reorder`](/system-variables.md#tidb_enable_outer_join_reorder-从-v610-版本开始引入) | 修改 | 该变量默认值从 `OFF` 修改为 `ON`，表示默认启用 Outer Join 的 [Join Reorder 算法](/join-reorder.md)。|
```

2022-12-21 04:00 UTC, qiancai commented on releases/release-6.5.0.md
> +    - 对于 `BIT` 和 `CHAR` 类型的列，使 `INFORMATION_SCHEMA.COLUMNS` 的显示结果与 MySQL 一致 [#25472](https://github.com/pingcap/tidb/issues/25472) @[hawkingrei](https://github.com/hawkingrei)
```suggestion
    - 对于 `BIT` 和 `CHAR` 类型的列，使 `INFORMATION_SCHEMA.COLUMNS` 的显示结果与 MySQL 一致 [#25472](https://github.com/pingcap/tidb/issues/25472) @[hawkingrei](https://github.com/hawkingrei)
    - 优化 TiDB 在 TiFlash MPP 模式下对 TiFlash 节点的探活机制 [#39932](https://github.com/pingcap/tidb/pull/39932) @[hackersean](https://github.com/hackersean)
```

2022-12-21 08:07 UTC, qiancai commented on releases/release-6.5.0.md
> ++ Performance Overview 面板中新增 TiFlash 和 CDC (Change Data Capture) 面板 [#39230](https://github.com/pingcap/tidb/issues/39230) @[dbsid](https://github.com/dbsid) **tw@qiancai**
```suggestion
* Performance Overview 面板中新增 TiFlash 和 CDC (Change Data Capture) 面板 [#39230](https://github.com/pingcap/tidb/issues/39230) @[dbsid](https://github.com/dbsid) **tw@qiancai**
```

2022-12-21 08:39 UTC, ran-huang commented on releases/release-6.5.0.md
> +    - 通过 [CDC 面板](/grafana-performance-overview-dashboard.md#cdc)，你可以直观地了解 TiCDC 的集群的健康状况、同步延迟、数据流和下游写入延迟等信息。
```suggestion
    - 通过 [CDC 面板](/grafana-performance-overview-dashboard.md#cdc)，你可以直观地了解 TiCDC 集群的健康状况、同步延迟、数据流和下游写入延迟等信息。
```

2022-12-22 05:47 UTC, qiancai commented on releases/release-6.5.0.md
> +| [`tidb_enable_outer_join_reorder`](/system-variables.md#tidb_enable_outer_join_reorder-从-v610-版本开始引入) | 修改 | 该变量默认值从 `OFF` 修改为 `ON`，表示默认启用 Outer Join 的 [Join Reorder 算法](/join-reorder.md)。|
```suggestion
| [`tidb_enable_outer_join_reorder`](/system-variables.md#tidb_enable_outer_join_reorder-从-v610-版本开始引入) | 修改 | 经进一步的测试后，该变量默认值从 `OFF` 修改为 `ON`，表示默认启用 Outer Join 的 [Join Reorder 算法](/join-reorder.md)。|
```

2022-12-22 06:04 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`tidb_cost_model_version`](/system-variables.md#tidb_cost_model_version-从-v620-版本开始引入) | 修改 | 该变量默认值从 `1` 修改为 `2`，表示默认使用 Cost Model Version 2 进行索引选择和算子选择。 |
```suggestion
| [`tidb_cost_model_version`](/system-variables.md#tidb_cost_model_version-从-v620-版本开始引入) | 修改 | 经进一步的测试后，该变量默认值从 `1` 修改为 `2`，表示默认使用 Cost Model Version 2 进行索引选择和算子选择。 |
```

2022-12-22 06:04 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`tidb_enable_metadata_lock`](/system-variables.md#tidb_enable_metadata_lock-从-v630-版本开始引入) | 修改 | 该变量默认值从 `OFF` 修改为 `ON`，表示默认开启元数据锁。 |
```suggestion
| [`tidb_enable_metadata_lock`](/system-variables.md#tidb_enable_metadata_lock-从-v630-版本开始引入) | 修改 | 经进一步的测试后，该变量默认值从 `OFF` 修改为 `ON`，表示默认开启元数据锁。 |
```

2022-12-22 06:04 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`tidb_ddl_enable_fast_reorg`](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入) | 修改 | 该变量默认值从 `OFF` 修改为 `ON`，表示默认开启创建索引加速功能。 |
```suggestion
| [`tidb_ddl_enable_fast_reorg`](/system-variables.md#tidb_ddl_enable_fast_reorg-从-v630-版本开始引入) | 修改 | 经进一步的测试后，该变量默认值从 `OFF` 修改为 `ON`，表示默认开启创建索引加速功能。 |
```

2022-12-22 06:06 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| TiKV | [`cdc.min-ts-interval`](/tikv-configuration-file.md#min-ts-interval) | 修改 | 默认值从 `1s` 修改为 `200ms`。 |
```suggestion
| TiKV | [`cdc.min-ts-interval`](/tikv-configuration-file.md#min-ts-interval) | 修改 | 为降低 CDC 延迟，该配置的默认值从 `1s` 修改为 `200ms`。 |
```
@hicqu PTAL

2022-12-22 06:14 UTC, qiancai commented on releases/release-6.5.0.md
> +| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 从 v6.5.0 起，当该变量的值为 `closest-adaptive` 时，如果一个读请求的预估返回结果大于或等于 [`tidb_adaptive_closest_read_threshold`](/system-variab
```suggestion
| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 从 v6.5.0 起，为了优化各个 TiDB 节点的负载均衡，当该变量的值为 `closest-adaptive` 时，如果一个读请求的预估返回结果大于或等于 [`tidb_adaptive_closest_read_threshold`](/system-variables.md#tidb_adaptive_closest_read_threshold-从-v630-版本开始引入)，在每个可用区中 `closest-adaptive` 配置实际生效的 TiDB 节点数总是与包含 TiDB 节点最少的可用区中的 TiDB 节点数相同。对于生效的节点，TiDB 会优先选择分布在同一可用区的副本执行读取操作，其他多出的 TiDB 节点将自动切换为读取 leader 副本。 |
```

2022-12-22 06:44 UTC, XuHuaiyu commented on releases/release-6.5.0.md
> +| [`tidb_mem_quota_query`](/system-variables.md#tidb_mem_quota_query) | 修改 | 在 v6.5.0 之前的版本中，该变量用来设置单条查询的内存使用限制。在 v6.5.0 及之后的版本中，该变量用来设置单个会话整体的内存使用限制。 |
```suggestion
| [`tidb_mem_quota_query`](/system-variables.md#tidb_mem_quota_query) | 修改 | 在 v6.5.0 之前的版本中，该变量用来设置单条查询的内存使用限制。在 v6.5.0 及之后的版本中，为了对 DML 语句的内存进行更准确地控制，该变量用来设置单个会话整体的内存使用限制。 |
```

2022-12-22 07:22 UTC, TomShawn commented on releases/release-6.5.0.md
> +| [`tidb_server_memory_limit`](/system-variables.md#tidb_server_memory_limit-从-v640-版本开始引入) |  修改 | 该变量默认值由 `0` 修改为 `80%`，表示默认将 TiDB 实例的内存限制设为总内存的 80%。|
```suggestion
| [`tidb_server_memory_limit`](/system-variables.md#tidb_server_memory_limit-从-v640-版本开始引入) |  修改 | 该变量默认值由 `0` 修改为 `80%`，因为 TiDB 全局内存控制特性 GA。该默认值修改默认开启 TiDB 实例的内存限制，并将默认的内存限制设为总内存的 80%。|
```

2022-12-22 08:08 UTC, qiancai commented on releases/release-6.5.0.md
> +   * TiCDC 支持在线更新 TLS 证书 [tiflow#7908](https://github.com/pingcap/tiflow/issues/7908) @[CharlesCheung96](https://github.com/CharlesCheung96) **tw@shichun-0415**
```suggestion
* TiCDC 支持在线更新 TLS 证书 [tiflow#7908](https://github.com/pingcap/tiflow/issues/7908) @[CharlesCheung96](https://github.com/CharlesCheung96) **tw@shichun-0415**
```

2022-12-22 08:56 UTC, D3Hunter approved these changes

2022-12-23 01:19 UTC, bb7133 commented on releases/release-6.5.0.md
> +- [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 特性 GA，可将集群快速回退到特定的时间点，兼容 TiCDC 和 PITR。
```suggestion
- [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 特性 GA，可将集群快速回退到特定的时间点。
```
我感觉「兼容 TiCDC 和 PiTR」不用特意说吧，总有点此地无银三百两的意思。

2022-12-23 01:49 UTC, fzzf678 approved these changes

2022-12-23 02:14 UTC, qiancai commented on releases/release-6.5.0.md
> +- [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 特性 GA，可将集群快速回退到特定的时间点，兼容 TiCDC 和 PITR。
@benmaoer@yiwen92， PTAL

2022-12-23 02:37 UTC, benmaoer requested changes

2022-12-23 02:37 UTC, benmaoer commented on releases/release-6.5.0.md
> +- [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 特性 GA，可将集群快速回退到特定的时间点，兼容 TiCDC 和 PITR。
上一个版本的 Flashback Cluster 是明确说明不兼容 TiCDC 和 PiTR 的，咱们这个版本不说明，客户可能仍然保持不兼容的说法

2022-12-23 02:37 UTC, benmaoer commented on releases/release-6.5.0.md
> +- [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 特性 GA，可将集群快速回退到特定的时间点，兼容 TiCDC 和 PITR。
```suggestion
- [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 特性新增对 TiCDC 和 PiTR 的兼容性支持，该特性已 GA。
```

2022-12-23 06:18 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +- [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 特性 GA，可将集群快速回退到特定的时间点，兼容 TiCDC 和 PITR。
> @Oreoxmt PTAL

LGTM

2022-12-23 06:20 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    TiDB v6.4.0 引入了 [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 语句作为实验特性，支持在 Garbage Collection (GC) life time 内快速回退整个集群到指定的时间点。该功能在 v6.5.0 正式 GA，适用于快速
```suggestion
    TiDB v6.4.0 引入了 [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 语句作为实验特性，支持在 Garbage Collection (GC) life time 内快速回退整个集群到指定的时间点。该功能在 v6.5.0 正式 GA，适用于快速撤消 DML 误操作、支持集群分钟级别的快速回退、支持在时间线上多次回退以确定特定数据更改发生的时间，并新增对 TiCDC 和 PITR 的兼容性支持。
```
@qiancai @benmaoer

2022-12-23 09:01 UTC, TomShawn commented on releases/release-6.5.0.md
> +| [`password_reuse_interval`](/system-variables.md#password_reuse_interval-从-v650-版本开始引入) | 新增 | 基于经过时间限制的密码重用策略，不允许用户重复使用最近设置天数内使用过的密码。默认值为 `0`，表示禁用基于密码更改次数的密码重用策略。 |
```suggestion
| [`password_reuse_interval`](/system-variables.md#password_reuse_interval-从-v650-版本开始引入) | 新增 | 基于经过时间限制的密码重用策略，不允许用户重复使用最近设置天数内使用过的密码。默认值为 `0`，表示禁用基于密码更改次数的密码重用策略。 |
| [`tidb_auto_build_stats_concurrency`](/system-variables.md#tidb_auto_build_stats_concurrency-从-v650-版本开始引入) | 新增 | 这个变量用来设置执行统计信息自动更新的并发度，默认值为 `1`。 |
```

2022-12-23 09:03 UTC, TomShawn commented on releases/release-6.5.0.md
> +| [`tidb_source_id`](/system-variables.md#tidb_source_id-从-v650-版本开始引入) | 新增 | 设置在[双向复制](/ticdc/ticdc-bidirectional-replication.md)系统内不同集群的 ID。|
```suggestion
| [`tidb_source_id`](/system-variables.md#tidb_source_id-从-v650-版本开始引入) | 新增 | 设置在[双向复制](/ticdc/ticdc-bidirectional-replication.md)系统内不同集群的 ID。|
| [`tidb_sysproc_scan_concurrency`](/system-variables.md#tidb_sysproc_scan_concurrency-从-v650-版本开始引入) | 新增 | 这个变量用来设置 TiDB 执行内部 SQL 语句（例如统计信息自动更新）时 scan 操作的并发度，默认值为 `1`。 |
```

2022-12-26 11:14 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的[对象存储](ticdc/ticdc-sink-to-cloud-storage.md)（实验特性）。
```suggestion
- TiCDC 支持 Amazon S3、Azure Blob Storage、NFS 的[对象存储](/ticdc/ticdc-sink-to-cloud-storage.md)（实验特性）。
```

2022-12-26 11:32 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiDB 快照备份支持断点续传，[PITR](/br-pitr-guide.md#进行-pitr) 的恢复性能提升 50%，正常场景下 RPO 降低到 5 min。
```suggestion
- TiDB 快照备份支持断点续传，[PITR](/br-pitr-guide.md#进行-pitr) 的恢复性能提升了 50%，正常场景下 RPO 降低到 5 min。
```

2022-12-26 11:32 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiCDC [同步数据到 Kafka](/replicate-data-to-kafka.md) 吞吐提升 x 倍，复制延迟降低到 x 秒。
```suggestion
- TiCDC [同步数据到 Kafka](/replicate-data-to-kafka.md) 吞吐提升了 x 倍，复制延迟降低到 x 秒。
```

2022-12-27 01:49 UTC, qiancai commented on releases/release-6.5.0.md
> +* TiCDC 支持在多个 TiDB 集群之间进行双向复制 @[asddongmen](https://github.com/asddongmen) **tw@ran-huang**
```suggestion
* TiCDC 支持在多个 TiDB 集群之间进行双向复制 [#38587](https://github.com/pingcap/tidb/issues/38587) @[xiongjiwei](https://github.com/xiongjiwei) @[asddongmen](https://github.com/asddongmen) **tw@ran-huang**
```

2022-12-27 02:05 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +- TiDB 快照备份支持断点续传，[PITR](/br-pitr-guide.md#进行-pitr) 的恢复性能提升了 50%，正常场景下 RPO 降低到 5 min。
```suggestion
- TiDB 快照备份支持断点续传，此外 [PITR](/br-pitr-guide.md#进行-pitr) 的恢复性能提升了 50%，正常场景下 RPO 降低到 5 min。
```

2022-12-27 02:07 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +    Storage sink 支持格式为 canal-json 和 csv 的 changed log，此外 changed log 从 TiCDC 同步到存储的延迟可以达到 xx。更多信息，请参考[用户文档](/ticdc/ticdc-sink-to-cloud-storage.md)。
```suggestion
    Storage sink 支持格式为 canal-json 和 csv 的 changed log。更多信息，请参考[用户文档](/ticdc/ticdc-sink-to-cloud-storage.md)。
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`default_password_lifetime`](/system-variables.md#default_password_lifetime-从-v650-版本开始引入) | 新增 | 用于设置全局自动密码过期策略，要求用户定期修改密码。默认值为 `0` ，表示禁用全局自动密码过期策略。 |
```suggestion
| [`default_password_lifetime`](/system-variables.md#default_password_lifetime-从-v650-版本开始引入) | 新增 | 用于设置全局自动密码过期策略，要求用户定期修改密码。默认值为 `0`，表示禁用全局自动密码过期策略。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`validate_password.length`](/system-variables.md#validate_passwordlength-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码最小长度。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从
```suggestion
| [`validate_password.length`](/system-variables.md#validate_passwordlength-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码最小长度。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启时，该变量才生效。默认值为 `8`。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`validate_password.mixed_case_count`](/system-variables.md#validate_passwordmixed_case_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中大写字符和小写字符的最小数量。只有 [`validate_password.enable`](/system-variabl
```suggestion
| [`validate_password.mixed_case_count`](/system-variables.md#validate_passwordmixed_case_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中大写字符和小写字符的最小数量。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启且 [validate_password.policy](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) 大于或等于 `1` (MEDIUM) 时，该变量才生效。默认值为 `1`。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`validate_password.number_count`](/system-variables.md#validate_passwordnumber_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中数字字符的最小数量。只有 [`validate_password.enable`](/system-variables.md#validat
```suggestion
| [`validate_password.number_count`](/system-variables.md#validate_passwordnumber_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中数字字符的最小数量。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启且 [validate_password.policy](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) 大于或等于 `1` (MEDIUM) 时，该变量才生效。默认值为 `1`。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]` 。只有 [`validate_password.enable`](/system-variables.md#validate_passwo
```suggestion
| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]`。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启时，该变量才生效。默认值为 `1`。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`validate_password.special_char_count`](/system-variables.md#validate_passwordspecial_char_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中特殊字符的最小数量。只有 [`validate_password.enable`](/system-variable
```suggestion
| [`validate_password.special_char_count`](/system-variables.md#validate_passwordspecial_char_count-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查项，限定了用户密码中特殊字符的最小数量。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启且 [validate_password.policy](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) 大于或等于 `1` (MEDIUM) 时，该变量才生效。默认值为 `1`。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]` 。只有 [`validate_password.enable`](/system-variables.md#validate_passwo
```suggestion
| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]`。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启时，该变量才生效。默认值为 `1`。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]` 。只有 [`validate_password.enable`](/system-variables.md#validate_passwo
```suggestion
| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]`。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启时，该变量才生效。默认值为 `1`。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]` 。只有 [`validate_password.enable`](/system-variables.md#validate_passwo
```suggestion
| [`validate_password.policy`](/system-variables.md#validate_passwordpolicy-从-v650-版本开始引入) | 新增 | 密码复杂度策略检查的强度，强度等级分为 `[0, 1, 2]`。只有 [`validate_password.enable`](/system-variables.md#validate_passwordenable-从-v650-版本开始引入) 开启时，该变量才生效。默认值为 `1`。 |
```

2022-12-27 07:59 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +| TiCDC | [`sink.csv.include-commit-ts`](/ticdc/ticdc-changefeed-config.md#ticdc-changefeed-配置文件说明) | 新增| 是否在 CSV 行中包含 commit-ts。默认值为 false。 |
```suggestion
| TiCDC | [`sink.csv.include-commit-ts`](/ticdc/ticdc-changefeed-config.md#ticdc-changefeed-配置文件说明) | 新增| 是否在 CSV 行中包含 commit-ts。默认值为 `false`。 |
```

2022-12-27 08:03 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +* TiCDC 支持输出变更数据至 storage sink（实验特性） [tiflow#6797](https://github.com/pingcap/tiflow/issues/6797) @[zhaoxinyu](https://github.com/zhaoxinyu) **tw@shichun-0415**
```suggestion
* TiCDC 支持输出变更数据至 storage sink（实验特性）[#6797](https://github.com/pingcap/tiflow/issues/6797) @[zhaoxinyu](https://github.com/zhaoxinyu) **tw@shichun-0415**
```

2022-12-27 08:03 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +    - 优化心跳处理过程，减少不必要的开销 [#5648](https://github.com/tikv/pd/issues/5648)@[rleungx](https://github.com/rleungx)
```suggestion
    - 优化心跳处理过程，减少不必要的开销 [#5648](https://github.com/tikv/pd/issues/5648) @[rleungx](https://github.com/rleungx)
```

2022-12-27 10:53 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiDB Lightning 和 Dumpling 支持[导入](tidb-lightning/tidb-lightning-data-source.md)和[导出](/dumpling-overview.md#通过并发提高-dumpling-的导出效率)压缩格式文件。
```suggestion
- TiDB Lightning 和 Dumpling 支持[导入](/tidb-lightning/tidb-lightning-data-source.md)和[导出](/dumpling-overview.md#通过并发提高-dumpling-的导出效率)压缩格式文件。
```

2022-12-27 10:55 UTC, qiancai commented on releases/release-6.5.0.md
> +  更多信息，请参考[用户文档](/performance-tuning-method.md/)。
```suggestion
  更多信息，请参考[用户文档](/performance-tuning-method.md)。
```

2022-12-27 10:55 UTC, qiancai commented on releases/release-6.5.0.md
> +  更多信息，请参考[用户文档](/performance-tuning-method.md/)。
```suggestion
  更多信息，请参考[用户文档](/performance-tuning-method.md)。
```

2022-12-27 10:55 UTC, qiancai commented on releases/release-6.5.0.md
> +    关于索引合并功能的更多信息，请参阅 [v5.4.0 Release Notes](/release-5.4.0#性能)，以及优化器相关的[用户文档](/explain-index-merge.md)
```suggestion
    关于索引合并功能的更多信息，请参阅 [v5.4.0 Release Notes](/release-5.4.0.md#性能)，以及优化器相关的[用户文档](/explain-index-merge.md)
```

2022-12-27 10:55 UTC, qiancai commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](sql-statements/sql-statement-explain-analyze.md)。
```suggestion
    更多信息，请参考[用户文档](/sql-statements/sql-statement-explain-analyze.md)。
```

2022-12-27 10:58 UTC, qiancai commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](/tidb-lightning-physical-import-mode-usage.md#磁盘资源配额-从-v6.2.0-版本开始引入)。
```suggestion
    更多信息，请参考[用户文档](/tidb-lightning/tidb-lightning-physical-import-mode-usage.md#磁盘资源配额-从-v620-版本开始引入)。
```

2022-12-27 10:59 UTC, qiancai commented on releases/release-6.5.0.md
> +- TiDB 快照备份支持断点续传，此外 [PITR](/br-pitr-guide.md#进行-pitr) 的恢复性能提升了 50%，一般场景下 RPO 降低到 5 min。
```suggestion
- TiDB 快照备份支持断点续传，此外 [PITR](/br/br-pitr-guide.md#进行-pitr) 的恢复性能提升了 50%，一般场景下 RPO 降低到 5 min。
```

2022-12-27 11:15 UTC, qiancai commented on releases/release-6.5.0.md
> +  更多信息，请参考[用户文档](/performance-tuning-method.md)。
```suggestion
  更多信息，请参考[用户文档](/performance-tuning-methods.md)。
```

2022-12-27 11:15 UTC, qiancai commented on releases/release-6.5.0.md
> +    关于索引合并功能的更多信息，请参阅 [v5.4.0 Release Notes](/release-5.4.0.md#性能)，以及优化器相关的[用户文档](/explain-index-merge.md)
```suggestion
    关于索引合并功能的更多信息，请参阅 [v5.4.0 Release Notes](/releases/release-5.4.0.md#性能)，以及优化器相关的[用户文档](/explain-index-merge.md)
```

2022-12-27 11:16 UTC, qiancai commented on releases/release-6.5.0.md
> +  更多信息，请参考[用户文档](/performance-tuning-method.md)。
```suggestion
  更多信息，请参考[用户文档](/performance-tuning-methods.md)。
```

2022-12-27 11:17 UTC, qiancai commented on releases/release-6.5.0.md
> +  更多信息，请参考[用户文档](/performance-tuning-method.md)。
```suggestion
  更多信息，请参考[用户文档](/performance-tuning-methods.md)。
```

2022-12-27 11:17 UTC, qiancai commented on releases/release-6.5.0.md
> +    关于索引合并功能的更多信息，请参阅 [v5.4.0 Release Notes](/release-5.4.0.md#性能)，以及优化器相关的[用户文档](/explain-index-merge.md)
```suggestion
    关于索引合并功能的更多信息，请参阅 [v5.4.0 Release Notes](/releases/release-5.4.0.md#性能)，以及优化器相关的[用户文档](/explain-index-merge.md)
```

2022-12-28 02:51 UTC, Frank945946 approved these changes

2022-12-28 03:11 UTC, hfxsd approved these changes

2022-12-28 03:49 UTC, shichun-0415 commented on releases/release-6.5.0.md
> +| TiDB | [`disconnect-on-expired-password`](/tidb-configuration-file.md#disconnect-on-expired-password`-从-v650-版本开始引入) | 新增 | 该配置用于控制 TiDB 服务端是否直接断开密码已过期用户的连接，默认值为 `true`，表示 TiDB 服务端将直接断开密码已过期用户的连接。
```suggestion
| TiDB | [`disconnect-on-expired-password`](/tidb-configuration-file.md#disconnect-on-expired-password-从-v650-版本开始引入) | 新增 | 该配置用于控制 TiDB 服务端是否直接断开密码已过期用户的连接，默认值为 `true`，表示 TiDB 服务端将直接断开密码已过期用户的连接。 |
```

2022-12-28 04:36 UTC, Oreoxmt approved these changes
LGTM

2022-12-28 05:36 UTC, chrysan commented on releases/release-6.5.0.md
> +| [`tidb_server_memory_limit`](/system-variables.md#tidb_server_memory_limit-从-v640-版本开始引入) |  修改 | 该变量默认值由 `0` 修改为 `80%`，因为 TiDB 全局内存控制特性 GA，该调整默认开启 TiDB 实例的内存限制，并将默认的内存限制设为总内存的 80%。|
| [`tidb_enable_gc_aware_memory_track`](/system-variables#tidb_enable_gc_aware_memory_track) |  修改 | 该变量默认值由 `ON` 修改为 `OFF`，由于 gc_aware_memory_track 在测试中发现不准确、导致 analyze 内存追踪过大的情况，因此先关闭。并且在 go1.19 下，该开关追踪的内存对整体的影响变小。|

2022-12-28 05:53 UTC, hfxsd commented on releases/release-6.5.0.md
> +    TiCDC 支持将 changed log 输出到 S3、Azure Blob Storage、NFS，以及兼容 S3 协议的存储服务中。Cloud storage 价格便宜，使用方便。对于不希望使用 Kafka 的用户，可以选择使用 storage sink。使用该功能，TiCDC 会将 changed log 保存到文件，发送到存储系统中。用户自研的消费程序定时从存储系统读取新产生的
```suggestion
    TiCDC 支持将 changed log 输出到 Amazon S3、Azure Blob Storage、NFS，以及兼容 Amazon S3 协议的存储服务中。Cloud storage 价格便宜，使用方便。对于不希望使用 Kafka 的用户，可以选择使用 storage sink。使用该功能，TiCDC 会将 changed log 保存到文件，发送到存储系统中。用户自研的消费程序定时从存储系统读取新产生的 changed log 进行数据处理。
```

2022-12-28 06:04 UTC, TomShawn commented on releases/release-6.5.0.md
> +| [`tidb_cost_model_version`](/system-variables.md#tidb_cost_model_version-从-v620-版本开始引入) | 修改 | 经进一步的测试后，该变量默认值从 `1` 修改为 `2`，表示默认使用 Cost Model Version 2 进行索引选择和算子选择。 |
```suggestion
| [`tidb_cost_model_version`](/system-variables.md#tidb_cost_model_version-从-v620-版本开始引入) | 修改 | 经进一步的测试后，该变量默认值从 `1` 修改为 `2`，表示默认使用 Cost Model Version 2 进行索引选择和算子选择。 |
| [`tidb_enable_gc_aware_memory_track`](/system-variables#tidb_enable_gc_aware_memory_track) |  修改 | 该变量默认值由 `ON` 修改为 `OFF`。由于在测试中发现 GC-Aware memory track 不准确，导致 Analyze 追踪到的内存过大的情况，因此先关闭内存追踪。在 Golang 1.19 下，GC-Aware memory track 追踪的内存对整体内存的影响变小。|
```

2022-12-28 06:09 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +    TiCDC 支持在多个 TiDB 集群之间进行双向复制。如果业务上需要 TiDB 多活，尤其是异地多活的场景下，可以使用该功能作为 TiDB 多活的解决方案。只要为每个 TiDB 集群到其他 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现多个 TiDB 集群之间的数据相互复制。
```suggestion
    TiCDC 支持在多个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为每个 TiDB 集群到其他 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现多个 TiDB 集群之间的数据相互复制。
```

2022-12-28 06:10 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +    为确保数据安全，用户会对系统使用的证书设置相应的过期策略。经过固定的时间后需要使用新的证书工作。TiCDC v6.5.0 支持在线更新 TLS 证书，在不影响同步的任务的前提下，TiCDC 会自动检测和更新证书，无需用户手动操作，满足用户对证书更新的需求。
```suggestion
    为确保系统数据安全，用户会对系统使用的证书设置相应的过期策略，经过固定的时间后会将系统使用的证书更换成新证书。TiCDC v6.5.0 支持在线更新 TLS 证书，在不影响同步的任务的前提下，TiCDC 会自动检测和更新证书，无需用户手动操作，满足用户对证书更新的需求。
```

2022-12-28 06:10 UTC, hfxsd commented on releases/release-6.5.0.md
> +    单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s。即使在常规的 TiKV/TiCDC 滚动升级场景，同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC Redo log 和 Syncpoint 后，吞吐从 4000 行每秒提升到 35000 行每秒，容灾复制延迟可以保持在 2 s。
```suggestion
    单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s。即使在常规的 TiKV/TiCDC 滚动升级场景，同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC Redo log 和 Syncpoint 后，吞吐从 4000 行每秒提升到 35000 行每秒，容灾复制延迟可以保持在 2s。
```

2022-12-28 06:13 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +  PITR 恢复的日志恢复阶段，单台 TiKV 的恢复速度可以达到 9 MiB/s，提升了 50%。恢复速度可扩展，有效地降低容灾场景的 RTO 指标；容灾场景的 RPO 优化到 5 分钟，在常规的集群运维，如滚动升级，单 TiKV 故障等场景下，可以达到 RPO = 5 min 的目标。
```suggestion
  PITR 恢复的日志恢复阶段，单台 TiKV 的恢复速度可以达到 9 MiB/s，提升了 50%，并且恢复速度可扩展，有效地降低容灾场景的 RTO 指标；容灾场景的 RPO 优化到 5 分钟，在常规的集群运维，如滚动升级，单 TiKV 故障等场景下，可以达到 RPO = 5 min 的目标。
```

2022-12-28 06:13 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +    TiDB 快照备份功能支持断点续传。当 BR 遇到对可恢复的错误时会进行重试，但是超过固定重试次数之后会备份退出。断点续传功能允许对持续更长时间的可恢复故障进行重试恢复，比如几十分钟的网络故障。
```suggestion
    TiDB 快照备份功能支持断点续传。当 BR 遇到可恢复的错误时会进行重试，但是超过固定重试次数之后会备份退出。断点续传功能允许对持续更长时间的可恢复故障进行重试恢复，比如几十分钟的网络故障。
```

2022-12-28 06:21 UTC, hfxsd commented on releases/release-6.5.0.md
> +| [`password_reuse_interval`](/system-variables.md#password_reuse_interval-从-v650-版本开始引入) | 新增 | 基于经过时间限制的密码重用策略，不允许用户重复使用最近设置天数内使用过的密码。默认值为 `0`，表示禁用基于密码更改次数的密码重用策略。 |
```suggestion
| [`password_reuse_interval`](/system-variables.md#password_reuse_interval-从-v650-版本开始引入) | 新增 | 基于经过时间限制的密码重用策略，不允许用户重复使用最近设置天数内使用过的密码。默认值为 `0`，表示禁用基于密码更改时间内的密码重用策略。 |
```

2022-12-28 07:34 UTC, joey-yez approved these changes
LGTM

2022-12-28 07:57 UTC, qiancai commented on releases/release-6.5.0.md
> +    TiCDC 支持在多个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为每个 TiDB 集群到其他 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现多个 TiDB 集群之间的数据相互复制。
```suggestion
* TiCDC 支持在两个 TiDB 集群之间进行双向复制 [#38587](https://github.com/pingcap/tidb/issues/38587) @[xiongjiwei](https://github.com/xiongjiwei) @[asddongmen](https://github.com/asddongmen)

    TiCDC 支持在两个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为每个 TiDB 集群到其他 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现两个 TiDB 集群之间的数据相互复制。
```

2022-12-28 07:58 UTC, easonn7 commented
LGTM

2022-12-28 08:04 UTC, qiancai commented on releases/release-6.5.0.md
> +    TiCDC 支持在两个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为 TiDB 集群到另一个 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现两个 TiDB 集群之间的数据相互复制。
```suggestion
    TiCDC 支持在两个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为一个 TiDB 集群到另一个 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现两个 TiDB 集群之间的数据相互复制。
```

2022-12-28 08:26 UTC, Oreoxmt approved these changes
Rest LGTM

2022-12-28 08:26 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +* TiDB 添加索引的性能提升为原来的 10 倍 (GA) [#35983](https://github.com/pingcap/tidb/issues/35983) @[benjamin2037](https://github.com/benjamin2037) @[tangenta](https://github.com/tangenta)
```suggestion
* TiDB 添加索引的性能约提升为原来的 10 倍 (GA) [#35983](https://github.com/pingcap/tidb/issues/35983) @[benjamin2037](https://github.com/benjamin2037) @[tangenta](https://github.com/tangenta)
```

2022-12-28 08:26 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    TiDB v6.4.0 引入了 [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 语句作为实验特性，支持在 Garbage Collection (GC) life time 内快速回退整个集群到指定的时间点。该功能在 v6.5.0 正式 GA，适用于快速
```suggestion
    TiDB v6.4.0 引入了 [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 语句作为实验特性，支持在 Garbage Collection (GC) life time 内快速回退整个集群到指定的时间点。该功能在 v6.5.0 新增对 TiCDC 和 PITR 的兼容性支持并正式 GA，适用于快速撤消 DML 误操作、支持集群分钟级别的快速回退、支持在时间线上多次回退以确定特定数据更改发生的时间。
```

2022-12-28 11:16 UTC, yiwen92 approved these changes

2022-12-28 11:24 UTC, qiancai commented on releases/release-6.5.0.md
> +    在 v6.5.0 中，TiDB 扩展了执行计划的打印格式。通过 `EXPLAIN FORMAT=tidb_json <SQL语句>` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
```suggestion
    在 v6.5.0 中，TiDB 扩展了执行计划的打印格式。通过在 `EXPLAIN` 语句中指定 `FORMAT = "tidb_json"` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
```

2022-12-28 11:24 UTC, qiancai commented on releases/release-6.5.0.md
> +    在 v6.5.0 中，TiDB 扩展了执行计划的打印格式。通过 `EXPLAIN FORMAT=tidb_json <SQL语句>` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
```suggestion
    在 v6.5.0 中，TiDB 扩展了执行计划的打印格式。通过在 `EXPLAIN` 语句中指定 `FORMAT = "tidb_json"` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
```

2022-12-28 11:24 UTC, benmaoer requested changes
change metadata lock release note, after the cluster is upgraded, the switch is turned on by default

2022-12-28 11:24 UTC, benmaoer commented on releases/release-6.5.0.md
> +    TiDB v6.3.0 引入了[元数据锁](/metadata-lock.md)作为实验特性，通过协调表元数据变更过程中 DML 语句和 DDL 语句的优先级，让执行中的 DDL 语句等待持有旧版本元数据的 DML 语句提交，尽可能避免 DML 语句的 `Information schema is changed` 错误。该功能在 v6.5.0 正式 GA 并默认打开，适用于各类 DDL
```suggestion
    TiDB v6.3.0 引入了[元数据锁](/metadata-lock.md)作为实验特性，通过协调表元数据变更过程中 DML 语句和 DDL 语句的优先级，让执行中的 DDL 语句等待持有旧版本元数据的 DML 语句提交，尽可能避免 DML 语句的 `Information schema is changed` 错误。该功能在 v6.5.0 正式 GA 并默认打开，适用于各类 DDL 变更场景。当集群从 v6.5.0 之前的版本升级到 v6.5.0 及之后的版本时，TiDB 默认自动开启该功能。如果需要关闭该功能，你可以将系统变量 [tidb_enable_metadata_lock](system-variables.md#tidb_enable_metadata_lock-从-v630-版本开始引入) 设置为 `OFF`
```

2022-12-28 11:25 UTC, qiancai commented on releases/release-6.5.0.md
> +    在 v6.5.0 中，TiDB 扩展了执行计划的打印格式。通过 `EXPLAIN FORMAT=tidb_json <SQL语句>` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
fix the following error. @songrijie PTAL
![image](https://user-images.githubusercontent.com/79440533/209804920-9e7a1aec-a2b1-4c5c-ab06-8d5e5ce4c6c7.png)

2022-12-28 11:28 UTC, qiancai commented on releases/release-6.5.0.md
> +    TiDB v6.3.0 引入了[元数据锁](/metadata-lock.md)作为实验特性，通过协调表元数据变更过程中 DML 语句和 DDL 语句的优先级，让执行中的 DDL 语句等待持有旧版本元数据的 DML 语句提交，尽可能避免 DML 语句的 `Information schema is changed` 错误。该功能在 v6.5.0 正式 GA 并默认打开，适用于各类 DDL
@Oreoxmt PTAL. Thanks.

2022-12-28 11:31 UTC, Oreoxmt commented on releases/release-6.5.0.md
> +    TiDB v6.3.0 引入了[元数据锁](/metadata-lock.md)作为实验特性，通过协调表元数据变更过程中 DML 语句和 DDL 语句的优先级，让执行中的 DDL 语句等待持有旧版本元数据的 DML 语句提交，尽可能避免 DML 语句的 `Information schema is changed` 错误。该功能在 v6.5.0 正式 GA 并默认打开，适用于各类 DDL
LGTM

2022-12-28 11:47 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +    TiCDC 支持在两个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为一个 TiDB 集群到另一个 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现两个 TiDB 集群之间的数据相互复制。
```suggestion
    TiCDC 支持在两个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为 TiDB 集群到另一个 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现两个 TiDB 集群之间的数据相互复制。
```

2022-12-28 11:48 UTC, IANTHEREAL commented on releases/release-6.5.0.md
> +    TiCDC 支持在两个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为一个 TiDB 集群到另一个 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现两个 TiDB 集群之间的数据相互复制。
```suggestion
    TiCDC 支持在两个 TiDB 集群之间进行双向复制。如果业务上需要构建异地多活的 TiDB 集群架构，可以使用该功能作为 TiDB 多活的解决方案。只要为 TiDB 集群到另一个 TiDB 集群的 TiCDC 同步任务配置 `bdr-mode = true` 参数，就可以实现两个 TiDB 集群之间的数据相互复制。
```

2022-12-28 11:48 UTC, IANTHEREAL commented
LGTM

2022-12-28 12:53 UTC, songrijie commented on releases/release-6.5.0.md
> +    在 v6.5.0 中，TiDB 扩展了执行计划的打印格式。通过 `EXPLAIN FORMAT=tidb_json <SQL语句>` 能够将 SQL 的执行计划以 JSON 格式输出。借助这个能力，SQL 调试工具和诊断工具能够更方便准确地解读执行计划，进而提升 SQL 诊断调优的易用性。
LGTM

2022-12-28 12:58 UTC, songrijie approved these changes
LGTM

2022-12-28 14:42 UTC, qiancai commented on releases/release-6.5.0.md
> +| [`tidb_server_memory_limit`](/system-variables.md#tidb_server_memory_limit-从-v640-版本开始引入) |  修改 | 该变量默认值由 `0` 修改为 `80%`，因为 TiDB 全局内存控制特性 GA，该调整默认开启 TiDB 实例的内存限制，并将默认的内存限制设为总内存的 80%。|
added in https://github.com/pingcap/docs-cn/pull/12100/commits/fe3bbd6ddaf0e34071b0d7088ef3555953a16138

2022-12-28 14:43 UTC, qiancai commented on releases/release-6.5.0.md
> +| [`tidb_enable_gc_aware_memory_track`](/system-variables#tidb_enable_gc_aware_memory_track) |  修改 | 该变量默认值由 `ON` 修改为 `OFF`。由于在测试中发现 GC-Aware memory track 不准确，导致 Analyze 追踪到的内存过大的情况，因此先关闭内存追踪。在 Golan
```suggestion
| [`tidb_enable_gc_aware_memory_track`](/system-variables.md#tidb_enable_gc_aware_memory_track) |  修改 | 该变量默认值由 `ON` 修改为 `OFF`。由于在测试中发现 GC-Aware memory track 不准确，导致 Analyze 追踪到的内存过大的情况，因此先关闭内存追踪。在 Golang 1.19 下，GC-Aware memory track 追踪的内存对整体内存的影响变小。|
```

2022-12-28 14:57 UTC, qiancai commented on releases/release-6.5.0.md
> +    TiDB v6.3.0 引入了[元数据锁](/metadata-lock.md)作为实验特性，通过协调表元数据变更过程中 DML 语句和 DDL 语句的优先级，让执行中的 DDL 语句等待持有旧版本元数据的 DML 语句提交，尽可能避免 DML 语句的 `Information schema is changed` 错误。该功能在 v6.5.0 正式 GA 并默认打开，适用于各类 DDL
```suggestion
    TiDB v6.3.0 引入了[元数据锁](/metadata-lock.md)作为实验特性，通过协调表元数据变更过程中 DML 语句和 DDL 语句的优先级，让执行中的 DDL 语句等待持有旧版本元数据的 DML 语句提交，尽可能避免 DML 语句的 `Information schema is changed` 错误。该功能在 v6.5.0 正式 GA 并默认打开，适用于各类 DDL 变更场景。当集群从 v6.5.0 之前的版本升级到 v6.5.0 及之后的版本时，TiDB 默认自动开启该功能。如果需要关闭该功能，你可以将系统变量 [`tidb_enable_metadata_lock`](/system-variables.md#tidb_enable_metadata_lock-从-v630-版本开始引入) 设置为 `OFF`。
```

2022-12-28 15:07 UTC, qiancai commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](/optimizer-hints.md#全局生效的-Hint)。
```suggestion
    更多信息，请参考[用户文档](/optimizer-hints.md#全局生效的-hint)。
```

2022-12-28 15:59 UTC, qiancai commented on releases/release-6.5.0.md
> +    更多信息，请参考[用户文档](/tiflash/tiflash-results-materialization.md)。
```suggestion
  更多信息，请参考[用户文档](/tiflash/tiflash-results-materialization.md)。
```

2022-12-29 01:49 UTC, hfxsd commented on releases/release-6.5.0.md
> +    单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s。即使在常规的 TiKV/TiCDC 滚动升级场景，同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC Redo log 和 Syncpoint 后，吞吐从 4000 行每秒提升到 35000 行每秒，容灾复制延迟可以保持在 2s。
```suggestion
    单台 TiCDC 节点能处理的最大行变更吞吐可以达到 30K rows/s，同步延迟降低到 10s。即使在常规的 TiKV/TiCDC 滚动升级场景，同步延迟也小于 30s；在容灾场景测试中，打开 TiCDC redo log 和 Syncpoint 后，吞吐从 4000 行每秒提升到 35000 行每秒，容灾复制延迟可以保持在 2s。
```

2022-12-29 02:02 UTC, benmaoer approved these changes
LGTM

2022-12-29 02:02 UTC, TomShawn approved these changes
LGTM

2022-12-29 02:37 UTC, ran-huang commented on releases/release-6.5.0.md
> +* TiCDC 支持两个 TiDB 集群之间进行双向复制 [#38587](https://github.com/pingcap/tidb/issues/38587) @[xiongjiwei](https://github.com/xiongjiwei) @[asddongmen](https://github.com/asddongmen)
```suggestion
* TiCDC 支持在两个 TiDB 集群之间进行双向复制 [#38587](https://github.com/pingcap/tidb/issues/38587) @[xiongjiwei](https://github.com/xiongjiwei) @[asddongmen](https://github.com/asddongmen)
```

2022-12-29 05:41 UTC, qiancai commented
/merge

2022-12-29 05:42 UTC, merged