The add translation
pingcap/docs-cn pull request #12138
Opened 2022-11-28 10:30 UTC by qiancai

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [ ] master (the latest development version)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.4 (TiDB 6.4 versions)
- [ ] v6.3 (TiDB 6.3 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-11-28 11:11 UTC, qiancai commented on partitioned-table.md
> +- 使用`ALTER TABLE <表名> REORGANIZE PARTITION <分区列表> INTO (<新的分区说明>)`语句对分区进行合并、拆分、或者其他修改。
```suggestion
- 使用 `ALTER TABLE <表名> REORGANIZE PARTITION <分区列表> INTO (<新的分区说明>)`语句对分区进行合并、拆分、或者其他修改。
```

2022-11-28 11:12 UTC, qiancai commented on partitioned-table.md
> +本小节将以如下 SQL 语句创建的分区表为例，介绍如何进行 Range 分区和 List 分区管理。
```suggestion
本小节将以如下 SQL 语句创建的分区表为例，介绍如何管理 Range 分区和 List 分区。
```

2022-11-28 11:13 UTC, qiancai commented on partitioned-table.md
> +对于 Range 分区，`ADD PARTITION` 只能在分区列表的最后添加新的分区。与分区列表中已有的分区相比，你需要将新分区的 `VALUES LESS THAN` 定义为更大的值。否则，执行该语句时将会报错。
```suggestion
对于 Range 分区表，`ADD PARTITION` 只能在分区列表的最后添加新的分区。与分区列表中已有的分区相比，你需要将新分区的 `VALUES LESS THAN` 定义为更大的值。否则，执行该语句时将会报错。
```

2022-11-28 11:14 UTC, qiancai commented on partitioned-table.md
> +修改分区定义：
```suggestion
修改分区表定义：
```

2022-11-28 11:15 UTC, qiancai commented on partitioned-table.md
> +- 对于 Range 分区表，你只能重组表中相邻的分区：
```suggestion
- 对于 Range 分区表，你只能对表中相邻的分区进行重组：
```

2022-11-28 11:17 UTC, qiancai commented on partitioned-table.md
> +- 对于 List 分区表，当修改分区定义中的数据集合时，必须保证新的数据集合能覆盖到该分区中现有的所有值，否则 TiDB 将返回报错。
```suggestion
- 对于 List 分区表，如需修改分区定义中的数据集合，必须保证新的数据集合能覆盖到该分区中现有的所有值，否则 TiDB 将返回报错。
```

2022-11-28 11:17 UTC, qiancai commented on partitioned-table.md
> +- 对于 Range 分区表，当修改 Range 定义中的最大值时，必须保证 `VALUES LESS THAN` 中新定义的值大于现有分区中的所有值。否则，TiDB 将返回报错，提示现有的行值对应不到分区。
```suggestion
- 对于 Range 分区表，如需修改 Range 定义中的最大值，必须保证 `VALUES LESS THAN` 中新定义的值大于现有分区中的所有值。否则，TiDB 将返回报错，提示现有的行值对应不到分区。
```

2022-11-28 11:38 UTC, moyun requested changes

2022-11-28 11:38 UTC, moyun commented on mysql-compatibility.md
> +* 分区表还支持 `ADD`、`DROP`、`TRUNCATE`、`REORGANIZE` 操作。其他分区操作会被忽略。TiDB 不支持以下分区表语法：
> ... 操作。其他分区操作会被忽略。

here seems just need a comma ","

2022-11-28 11:38 UTC, moyun commented on mysql-compatibility.md
>    更多详情，请参考[分区表文档](/partitioned-table.md)。
> ","

，

2022-11-28 11:38 UTC, moyun commented on partitioned-table.md
> +- 对于 Range 分区表，如需修改 Range 定义中的最大值，必须保证 `VALUES LESS THAN` 中新定义的值大于现有分区中的所有值。否则，TiDB 将返回报错，提示现有的行值对应不到分区。
> 否则，TiDB 将返回报错
two options:
1. 否则，TiDB 将报错
2. 否则，TiDB 将返回错误信息

2022-11-28 11:38 UTC, moyun commented on partitioned-table.md
> +- 对于 Range 分区表，如需修改 Range 定义中的最大值，必须保证 `VALUES LESS THAN` 中新定义的值大于现有分区中的所有值。否则，TiDB 将返回报错，提示现有的行值对应不到分区。
“返回报错” 是一病句

2023-01-28 05:52 UTC, qiancai commented on mysql-compatibility.md
> +* 分区表还支持 `ADD`、`DROP`、`TRUNCATE`、`REORGANIZE` 操作。其他分区操作会被忽略。TiDB 不支持以下分区表语法：
```suggestion
* 分区表还支持 `ADD`、`DROP`、`TRUNCATE`、`REORGANIZE` 操作，其他分区操作会被忽略。TiDB 不支持以下分区表语法：
```

2023-01-28 05:52 UTC, qiancai commented on partitioned-table.md
> +- 对于 Range 分区表，如需修改 Range 定义中的最大值，必须保证 `VALUES LESS THAN` 中新定义的值大于现有分区中的所有值。否则，TiDB 将返回报错，提示现有的行值对应不到分区。
```suggestion
- 对于 Range 分区表，如需修改 Range 定义中的最大值，必须保证 `VALUES LESS THAN` 中新定义的值大于现有分区中的所有值。否则，TiDB 将报错，提示现有的行值对应不到分区。
```

2023-01-28 05:52 UTC, qiancai commented on partitioned-table.md
> +- 对于 List 分区表，如需修改分区定义中的数据集合，必须保证新的数据集合能覆盖到该分区中现有的所有值，否则 TiDB 将返回报错。
```suggestion
- 对于 List 分区表，如需修改分区定义中的数据集合，必须保证新的数据集合能覆盖到该分区中现有的所有值，否则 TiDB 将报错。
```

2023-01-28 05:53 UTC, qiancai commented on mysql-compatibility.md
>    更多详情，请参考[分区表文档](/partitioned-table.md)。
This comma in Line 122 is correct.

2023-01-28 05:57 UTC, qiancai commented on partitioned-table.md
> +- 使用 `ALTER TABLE <表名> TRUNCATE PARTITION <分区列表>` 语句清空分区里的数据。`TRUNCATE PARTITION`的逻辑与 [`TRUNCATE TABLE`](/sql-statements/sql-statement-truncate.md) 相似，但它的操作对象为分区。
```suggestion
- 使用 `ALTER TABLE <表名> TRUNCATE PARTITION <分区列表>` 语句清空分区里的数据。`TRUNCATE PARTITION` 的逻辑与 [`TRUNCATE TABLE`](/sql-statements/sql-statement-truncate.md) 相似，但它的操作对象为分区。
```

2023-01-31 09:23 UTC, hfxsd approved these changes
Rest LGTM

2023-01-31 09:23 UTC, hfxsd commented on partitioned-table.md
> +### 添加分区
可以把这一小节放到 删除分区 小节之前。逻辑上比较合理。

2023-01-31 09:52 UTC, hfxsd commented on partitioned-table.md
> +### Range 分区和 List 分区管理
```suggestion
### 管理 Range 分区和 List 分区
```

2023-02-01 10:52 UTC, qiancai commented on partitioned-table.md
> +### 添加分区
看了下，这个例子中这三个之间有顺序关系，不能直接调整，
最前面的例子 L775 行建了 PARTITION p1990 VALUES LESS THAN (2000)); 分区，如果这个例子之后直接放添加分区，和 L789 行的 PARTITION `p1990to2010` 冲突，需要先通过删除分区小节删除 PARTITION p1990; 分区，才能添加 PARTITION `p1990to2010`

2023-03-22 08:19 UTC, qiancai commented on partitioned-table.md
>  ### Hash 分区管理
```suggestion
### 管理 Hash 分区
```

2023-03-22 08:19 UTC, qiancai commented on partitioned-table.md
> +### 管理 Range 分区和 List 分区
```suggestion
### 管理 Range 分区、Range COLUMNS 分区、List 分区、List COLUMNS 分区
```

2023-03-22 08:19 UTC, qiancai commented on partitioned-table.md
> +对于 `LIST` 和 `RANGE` 分区表，你可以进行以下分区管理操作：
```suggestion
对于 `LIST`、`LIST COLUMNS`、`RANGE`、`RANGE COLUMNS` 分区表，你可以进行以下分区管理操作：
```

2023-03-23 02:15 UTC, bb7133 approved these changes
LGTM

2023-03-27 06:40 UTC, qiancai commented
/merge

2023-03-27 06:42 UTC, qiancai commented
/remove-status LGT1
/status LGT2

2023-03-27 06:42 UTC, qiancai commented
/merge

2023-03-27 06:42 UTC, merged