releases: add 6.6.0 release notes
pingcap/docs-cn pull request #12652
Opened 2023-01-12 06:43 UTC by TomShawn

### What is changed, added or deleted? (Required)
releases: add 6.6.0 release notes

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v6.6 (TiDB 6.6 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.4 (TiDB 6.4 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2023-01-17 03:19 UTC, TomShawn commented on releases/release-6.6.0.md
> +* 功能标题 [#issue号](链接) @[贡献者 GitHub ID](链接)
From @CbcWestwolf 

* 可通过命令行参数或者配置项在 TiDB 集群初次启动时指定执行的初始化 SQL 脚本 [#35625](https://github.com/pingcap/tidb/pull/35625) @[morgo](https://github.com/morgo)

    命令行参数 `--initialize-sql-file` 用于指定 TiDB 集群初次启动时执行的 SQL 脚本，可用于修改系统变量的值，或者创建用户、分配权限等。

    更多信息，请参考[配置项 `initialize-sql-file`](/tidb-configuration-file.md#initialize-sql-file-从-v660-版本开始引入)。

2023-01-18 13:32 UTC, tiancaiamao commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/tidb-resource-control.md)。
tidb-resource-control.md 没有添加进来？

2023-01-19 03:28 UTC, BornChanger commented on releases/release-6.6.0.md
> +    在 v6.6 中， 启用资源管控技术需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-%E4%BB%8E-v660-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5) 及 TiK
叫“用量”好还是 “配额”好?

2023-01-19 04:00 UTC, Frank945946 commented on releases/release-6.6.0.md
> +
* Data Migration(DM) 集成了 Lightning 的 Physical Import Mode ，全量迁移性能最高提升  10 倍  @[
lance6716](https://github.com/lance6716)

    功能描述 ：Data Migration (DM)的全量迁移能力，集成了 Lightning 的 Physical Import Mode ，使得 DM 做全量数据迁移时的性能最高可提升 10 倍，大大缩短了大数据量场景下的迁移时间。原先客户数据量较多时，客户得单独配置 Lightning 的 Physical Import Mode 的任务来做快速的全量数据迁移，之后再用 DM 来做增量数据迁移，配置复杂。现在集成该能力后，用户迁移大数据量的场景，无需再配置 Lightning 的任务，在一个 DM 任务里就可以搞定了。

    更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12296)。

2023-01-19 04:09 UTC, Frank945946 commented on releases/release-6.6.0.md
> +
+  Sync-diff-inspector
        - 新增一个参数，当下游数据库的表在上游不存在时，可配置该参数跳过对上下游数据库表数量不一致场景的校验，而不是任务中断退出。@[lichunzhu](https://github.com/lichunzhu)@[liumengya94](https://github.com/liumengya94)

2023-01-19 07:39 UTC, songrijie commented on releases/release-6.6.0.md
> +    在 v6.6 中， 启用资源管控技术需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-%E4%BB%8E-v660-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5) 及 TiK
我是这么想的，“配额”可以有多种方式，比如按百分比也是配额。 根据”用量“是其中一个“配额”方式。

2023-01-19 14:11 UTC, MyonKeminta commented on releases/release-6.6.0.md
> +    如果业务场景存在单点悲观锁冲突频繁的情况，原有的随机唤醒机制会造成事务响应时间的不确定性，长尾延迟高，甚至获取超时。 在 v6.6.0 中，通过设置系统变量 [`tidb_pessimistic_txn_aggressive_locking`](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始
> 原有的随机唤醒机制

原有的唤醒机制本身并不是设计为随机唤醒。原先有多个事务在等一个锁时，唤醒也会优先唤醒 start ts 最小的，但是无法保证被唤醒的事务是下一个成功上锁的事务，因而这里有一定的随机性，使得唤醒顺序不可控

2023-01-20 01:40 UTC, easonn7 commented on releases/release-6.6.0.md
> +
* 支持 MySQL 语法兼容的外键约束 （实验特性）[#18209](https://github.com/pingcap/tidb/issues/18209) @[crazycs520](https://github.com/crazycs520)

    TiDB 在 v6.6.0 引入了 MySQL 语法兼容的外键约束特性，支持表内，表间的数据关联和约束校验能力，支持集联操作。该特性有助于保持数据一致性，提升数据质量，也方便客户进行数据建模。

    更多信息，请参考[用户文档](/sql-statements/sql-statement-foreign-key.md)。

2023-01-20 02:25 UTC, Frank945946 commented on releases/release-6.6.0.md
> +
* 同步到下游 Kafka 的 Changefeed 可将上游单表的同步任务下发到多个 TiCDC Nodes 执行，实现单表同步性能的水平扩展 [#7720](https://github.com/pingcap/tiflow/issues/7720) @[overvenus](https://github.com/overvenus)

    功能描述：下游为 Kafka 的 Changefeed 可将上游单表的复制任务调度到多个  TiCDC Nodes 执行，实现单张表同步性能的水平扩展。在这个功能发布之前，上游单表写入数据量较大时，无法水平扩展单表的复制能力，导致同步延迟增加。该功能发布后，就可以通过水平扩展，解决单表同步性能的问题。

    更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12693)。

2023-01-20 05:35 UTC, songrijie commented on releases/release-6.6.0.md
> +    如果业务场景存在单点悲观锁冲突频繁的情况，原有的随机唤醒机制会造成事务响应时间的不确定性，长尾延迟高，甚至获取超时。 在 v6.6.0 中，通过设置系统变量 [`tidb_pessimistic_txn_aggressive_locking`](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始
ok， 我稍微修改准确些

2023-01-28 02:22 UTC, songrijie commented on releases/release-6.6.0.md
> +    如果业务场景存在单点悲观锁冲突频繁的情况，原有的随机唤醒机制会造成事务响应时间的不确定性，长尾延迟高，甚至获取超时。 在 v6.6.0 中，通过设置系统变量 [`tidb_pessimistic_txn_aggressive_locking`](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始
https://github.com/pingcap/docs-cn/pull/12652/commits/a95e1ee1ba9e9e9d051dab270464963aa66739f0

2023-01-29 01:20 UTC, haojinming approved these changes
LGTM

2023-01-29 02:32 UTC, hfxsd commented on releases/release-6.6.0.md
> +    资源管控技术的引入对 TiDB 具有里程碑的意义， 它能够将一个分布式数据库集群中划分成多个逻辑单元， 即使个别单元对资源过度使用，也不会完全挤占其他单元所需的资源。 利用这个技术， 用户可以将数个来自不同系统的中小型应用合入一个 TiDB 集群中， 个别应用的负载提升，不会影响其他业务的正常运行；而在系统负载较低的时候，繁忙的应用即使超过限额，也仍旧可以被分配到需要的系统资源，达到资源
```suggestion
    TiDB 集群支持创建资源组，将不用的数据库用户映射到对应的资源组中，根据实际需要设置每个资源组的配额。当集群资源紧张时，来自同一个资源组的会话所使用的全部资源将被限制在配额内，避免其中一个资源组过度消耗从而抑制其他资源组中的会话正常运行。系统内置视图会对资源的实际使用情况进行反馈和展示，协助用户更合理地配置资源。 

    资源管控技术的引入对 TiDB 具有里程碑的意义，它能够将一个分布式数据库集群中划分成多个逻辑单元，即使个别单元对资源过度使用，也不会完全挤占其他单元所需的资源。利用这个技术，你可以将数个来自不同系统的中小型应用合入一个 TiDB 集群中，个别应用的负载提升，不会影响其他业务的正常运行；而在系统负载较低的时候，繁忙的应用即使超过限额，也仍旧可以被分配到所需的系统资源，达到资源的最大化利用。 同样的，你可以选择将所有测试环境合入一个集群，或者将消耗较大的批量任务编入一个单独的资源组，在保证重要应用获得必要资源的同时，提升硬件利用率，降低运行成本。另外，合理利用资源管控技术可以减少集群数量，降低运维难度及管理成本。
```

2023-01-29 03:16 UTC, TomShawn commented on releases/release-6.6.0.md
> +
committed in PR

2023-01-29 03:16 UTC, TomShawn commented on releases/release-6.6.0.md
> +* 功能标题 [#issue号](链接) @[贡献者 GitHub ID](链接)
committed in PR

2023-01-29 03:16 UTC, TomShawn commented on releases/release-6.6.0.md
> +
committed in PR

2023-01-29 03:16 UTC, TomShawn commented on releases/release-6.6.0.md
> +
committed in PR

2023-01-29 03:16 UTC, TomShawn commented on releases/release-6.6.0.md
> +
committed in PR

2023-01-29 08:10 UTC, lilyjazz commented on releases/release-6.6.0.md
> +
```suggestion

* 快速绑定执行计划 [#781](https://github.com/pingcap/tidb-dashboard/issues/781) @[YiniXu9506](https://github.com/YiniXu9506)

    TiDB 的一键计划绑定功能：允许用户在 TiDB 仪表盘 UI 中一分钟内绑定特定 SQL 与特定计划。

    通过提供友好的界面简化在 TiDB 上绑定计划的过程，减少计划绑定过程的复杂性提高用户体验，提高计划绑定过程的效率。
    
    更多信息，请参考[用户文档](/dashboard/dashboard-statement-details.md)。
   
```

2023-01-29 08:38 UTC, lilyjazz commented on releases/release-6.6.0.md
> +    向慢查询日志中增加一个新的字段 `Warning` ，以 JSON 格式记录该慢查询语句在执行过程中产生的警告，用来协助查询性能问题的诊断。
```suggestion
    向慢查询日志中增加一个新的字段 `Warning` ，以 JSON 格式记录该慢查询语句在执行过程中产生的警告，用来协助查询性能问题的诊断。 
    
    用户也可以在 TiDB Dashboard 中的慢查询页面中查看。
```

2023-01-29 13:12 UTC, TomShawn commented on releases/release-6.6.0.md
> + *TiFlash 支持 TLS certificate hot reload（https://internal.pingcap.net/jira/browse/FD-906）
@ywqzzy

2023-01-30 03:31 UTC, TomShawn commented on releases/release-6.6.0.md
> + *TiFlash 支持 TLS certificate hot reload（https://internal.pingcap.net/jira/browse/FD-906）
@lulukelu Please delete the internal link and avoid using it in GitHub. Thanks~

2023-01-30 03:54 UTC, TomShawn commented on releases/release-6.6.0.md
> + *TiFlash 支持 TLS certificate hot reload
```suggestion
 *TiFlash 支持 TLS certificate hot reload @[ywqzzy](https://github.com/ywqzzy)
```

2023-01-30 04:03 UTC, xzhangxian1008 approved these changes

2023-01-30 04:03 UTC, xzhangxian1008 commented on releases/release-6.6.0.md
> +* 新增支持下推以下字符串函数至 TiFlash [#6115](https://github.com/pingcap/tiflash/issues/6115) @[xzhangxian1008](https://github.com/xzhangxian1008)
lgtm

2023-01-30 04:07 UTC, ywqzzy commented on releases/release-6.6.0.md
> +    Tiflash TLS 证书自动轮换是指客户创建了TiDB Cluster，当TiFlash的TLS证书过期后，重新签发一个新TLS证书给Tiflash时，可以不用重启TiDB Cluster，自动加载新Tiflash TLS证书。这样可以保证TiDB Cluster内部组件之间TLS过期轮换不影响TiDB Cluster的正常使用，既保障了TiDB集群高可用性，也保证TLS证书更新使用
```suggestion
    TiFlash TLS 证书自动轮换指在开启组件间加密传输的 TiDB Cluster 上，当 TiFlash 的 TLS 证书过期，重新签发一个新 TLS 证书给 TiFlash 时，可以不用重启 TiDB Cluster，自动加载新 TiFlash TLS 证书。TiDB Cluster 内部组件之间 TLS 过期轮换不影响 TiDB Cluster 的正常使用，保障了 TiDB 集群高可用性。
```

2023-01-30 04:09 UTC, hehechen commented on releases/release-6.6.0.md
> +    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，TiDB 可以读取指定的时间点或时间范围内的历史数据。Stale Read 允许引擎直接读取本地副本数据，降低读取延迟，提升查询性能。但是，只有 TiKV 引擎支持 Stale Read 功能，TiFlash 引擎并不支持 Stale Read 功能，即使查询的表包含 TiFlash 副本，TiDB 也只能使用 Ti
不止支持`AS OF TIMESTAMP`，tidb_read_staleness 之类的也支持

2023-01-30 04:10 UTC, overvenus commented on releases/release-6.6.0.md
> +    功能描述：下游为 Kafka 的 Changefeed 可将上游单表的复制任务调度到多个  TiCDC Nodes 执行，实现单张表同步性能的水平扩展。在这个功能发布之前，上游单表写入数据量较大时，无法水平扩展单表的复制能力，导致同步延迟增加。该功能发布后，就可以通过水平扩展，解决单表同步性能的问题。
```suggestion
    功能描述：下游为 Kafka 的 Changefeed 可将上游单表的复制任务调度到多个 TiCDC Nodes 执行，实现单张表同步性能的水平扩展。在这个功能发布之前，上游单表写入数据量较大时，无法水平扩展单表的复制能力，导致同步延迟增加。该功能发布后，就可以通过水平扩展，解决单表同步性能的问题。
```

2023-01-30 04:13 UTC, zeminzhou approved these changes
LGTM

2023-01-30 04:43 UTC, MyonKeminta approved these changes

2023-01-30 05:59 UTC, lance6716 approved these changes

2023-01-30 06:11 UTC, fzzf678 commented on releases/release-6.6.0.md
> +* 带有子查询和 `LIMIT` 子句的 SQL 可进入计划缓存 [#40219](https://github.com/pingcap/tidb/issues/40219) @[fzzf678](https://github.com/fzzf678)
```suggestion
* 带有 `LIMIT` 子句的 SQL 可进入计划缓存 [#40219](https://github.com/pingcap/tidb/issues/40219) @[fzzf678](https://github.com/fzzf678)
```

2023-01-30 06:11 UTC, fzzf678 commented on releases/release-6.6.0.md
> +    * 带有子查询的 SQL 可进入执行计划缓存，如 `select * from t where a > (select ...)`。
```suggestion
```

2023-01-30 09:40 UTC, SunRunAway commented on releases/release-6.6.0.md
> +
* 使用临时 Witness 副本来加速副本恢复 [#12876](https://github.com/tikv/tikv/issues/12876) [@Connor1996](https://github.com/Connor1996) [@ethercflow](https://github.com/ethercflow)

    Witness 功能可用于快速恢复 failover，以提高系统可用性。例如在 3 缺 1 的情况下，虽然满足多数派要求，但是系统很脆弱，而完整恢复一个新成员的时间通常很长（需要先拷贝 snapshot 然后 apply 最新的日志），特别是 Region snapshot 比较大的情况。而且拷贝副本的过程可能会对不健康的副本造成更多的压力。因此，先添加一个 Witness 可以快速下掉不健康的节点，保证恢复数据的过程中日志的安全性，后续再由 PD 的 rule checker 将 Witness 副本变为普通的 Voter。

    更多信息，请参考[用户文档](/use-witness-to-speed-up-failover.md)。

2023-01-30 09:40 UTC, SunRunAway commented on releases/release-6.6.0.md
> +
```suggestion

* 使用 Witness 节约成本  [#12876](https://github.com/tikv/tikv/issues/12876) [@Connor1996](https://github.com/Connor1996) [@ethercflow](https://github.com/ethercflow)

    在云环境中，当 TiKV 使用如 AWS EBS 或 GCP 的 Persistent Disk 作为单节点存储时，它们提供的持久性相比物理磁盘更高。此时，TiKV 使用 3 个 Raft 副本虽然可行，但并不必要。为了降低成本，TiKV 引入了 Witness 功能，即 2 Replicas With 1 Log Only 机制。其中 1 Log Only 副本仅存储 Raft 日志但不进行数据 apply，依然可以通过 Raft 协议保证数据一致性。与标准的 3 副本架构相比，Witness 可以节省存储资源及 CPU 使用率。
    
    更多信息，请参考[用户文档](/use-witness-to-save-costs.md)。


```

2023-01-30 10:27 UTC, songrijie commented on releases/release-6.6.0.md
> +* 带有子查询和 `LIMIT` 子句的 SQL 可进入计划缓存 [#40219](https://github.com/pingcap/tidb/issues/40219) @[fzzf678](https://github.com/fzzf678)
https://github.com/pingcap/docs-cn/pull/12652/commits/23af2ead0cd396035b39f76848ab85aebf4da81c

2023-01-30 12:26 UTC, fzzf678 approved these changes

2023-01-30 15:33 UTC, BornChanger commented on releases/release-6.6.0.md
> +    在 v6.6 中， 启用资源管控技术需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-%E4%BB%8E-v660-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5) 及 TiK
lgtm

2023-01-30 16:44 UTC, benmaoer requested changes
add new release notes

2023-01-30 16:44 UTC, benmaoer commented on releases/release-6.6.0.md
> +
```
*  支持通过`FLASHBACK CLUSTER TO TIMESTAMP` 命令闪回 DDL 操作 [#14088](https://github.com/tikv/tikv/pull/14088) @[Defined2014](https://github.com/Defined2014) @[JmPotato](https://github.com/JmPotato)

    [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 语句支持在 Garbage Collection (GC) life time 内快速回退整个集群到指定的时间点，该功能在 TiDB v6.6.0 版本新增支持撤销 DDL 操作，适用于快速撤消集群的 DML 或 DDL 误操作、支持集群分钟级别的快速回退、支持在时间线上多次回退以确定特定数据更改发生的时间。

    更多信息，请参考[用户文档](/sql-statements/sql-statement-flashback-to-timestamp.md)。

* 支持 DDL 分布式并行执行框架（实验性特性） [#issue](链接)  @[zimulala](https://github.com/zimulala)

    在过去的版本中，整个 TiDB 集群中仅允许一个 TiDB 实例作为 DDL Owner 有权处理 Schema 变更任务，为了进一步提升 DDL 的并发性，TiDB v6.6.0 版本引入了 DDL 分布式并行执行框架，支持集群中所有的 TiDB 实例都作为 Owner 并发执行同一个 Schema 变更子任务，加速 DDL 的执行。

    更多信息，请参考[用户文档](链接)。

```

2023-01-30 16:44 UTC, benmaoer commented on releases/release-6.6.0.md
> +
```suggestion
* 支持 DDL 动态资源管控（实验性特性） [#issue](链接)  @[hawkingrei](https://github.com/hawkingrei)

    TiDB v6.6.0 版本引入了 DDL 动态资源管控， 通过自动控制 DDL 的 CPU 和内存使用量，尽量降低 DDL 变更任务对线上业务的影响。
    
    更多信息，请参考[用户文档](链接)。
```

2023-01-31 06:17 UTC, TomShawn commented on releases/release-6.6.0.md
> +
```suggestion

*  支持通过`FLASHBACK CLUSTER TO TIMESTAMP` 命令闪回 DDL 操作 [#14088](https://github.com/tikv/tikv/pull/14088) @[Defined2014](https://github.com/Defined2014) @[JmPotato](https://github.com/JmPotato)

    [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 语句支持在 Garbage Collection (GC) life time 内快速回退整个集群到指定的时间点，该功能在 TiDB v6.6.0 版本新增支持撤销 DDL 操作，适用于快速撤消集群的 DML 或 DDL 误操作、支持集群分钟级别的快速回退、支持在时间线上多次回退以确定特定数据更改发生的时间。

    更多信息，请参考[用户文档](/sql-statements/sql-statement-flashback-to-timestamp.md)。

* 支持 DDL 分布式并行执行框架（实验性特性） [#issue](链接)  @[zimulala](https://github.com/zimulala)

    在过去的版本中，整个 TiDB 集群中仅允许一个 TiDB 实例作为 DDL Owner 有权处理 Schema 变更任务，为了进一步提升 DDL 的并发性，TiDB v6.6.0 版本引入了 DDL 分布式并行执行框架，支持集群中所有的 TiDB 实例都作为 Owner 并发执行同一个 Schema 变更子任务，加速 DDL 的执行。

    更多信息，请参考[用户文档](链接)。

```

2023-01-31 06:18 UTC, TomShawn commented on releases/release-6.6.0.md
> +
already added in PR

2023-01-31 07:18 UTC, joey-yez commented on releases/release-6.6.0.md
> +    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，TiDB 可以读取指定的时间点或时间范围内的历史数据。Stale Read 允许引擎直接读取本地副本数据，降低读取延迟，提升查询性能。但是，只有 TiKV 引擎支持 Stale Read 功能，TiFlash 引擎并不支持 Stale Read 功能，即使查询的表包含 TiFlash 副本，TiDB 也只能使用 Ti
```suggestion
    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，TiDB 可以读取指定的时间点或时间范围内的历史数据。Stale Read 允许引擎直接读取本地副本数据，降低读取延迟，提升查询性能。但是，只有 TiKV 引擎支持 Stale Read 功能，TiFlash 引擎并不支持 Stale Read 功能，即使查询的表包含 TiFlash 副本，TiDB 也只能使用 TiKV 副本进行指定时间点或时间范围内的历史数据查询。在 v6.6.0 中，TiFlash 引擎实现了对 Stale Read 功能的支持。使用语法 `AS OF TIMESTAMP` 或系统变量 `tidb_read_staleness` 等方式进行指定时间点或时间范围内的历史数据查询时，如果查询的表包含 TiFlash 副本，优化器可以选择 TiFlash 引擎读取指定的时间点或时间范围内的历史数据。
```

2023-01-31 07:52 UTC, you06 commented on releases/release-6.6.0.md
> +    当 TiDB 向 TiKV 发送数据请求时， 会根据数据所在的 Region 将请求编入不同的子任务，每个子任务只处理单个 Region 的请求。 当访问的数据离散度很高时， 即使数据量不大，也会生成众多的子任务，进而产生大量 RPC 请求，消耗额外的时间。 在 v6.6.0 中，TiDB 支持将发送到相同 TiKV 实例的数据请求部分合并，减少子任务的数量和 RPC 请求的开销。 在数
```suggestion
    当 TiDB 向 TiKV 发送数据请求时， 会根据数据所在的 Region 将请求编入不同的子任务，每个子任务只处理单个 Region 的请求。 当访问的数据离散度很高时， 即使数据量不大，也会生成众多的子任务，进而产生大量 RPC 请求，消耗额外的时间。 在 v6.6.0 中，TiDB 支持将发送到相同 TiKV 实例的数据请求部分合并，减少子任务的数量和 RPC 请求的开销。 在数据离散度高且 gRPC 线程池资源紧张的情况下，批量化请求能够将性能提升 50% 以上。 
```

2023-01-31 07:52 UTC, you06 commented on releases/release-6.6.0.md
> +    此特性默认关闭， 通过系统变量 [`tidb_store_batch_size`](/system-variables.md#tidb_store_batch_size) 设置批量请求的大小即可开启。
```suggestion
    此特性默认打开， 通过系统变量 [`tidb_store_batch_size`](/system-variables.md#tidb_store_batch_size) 设置批量请求的大小。
```

2023-01-31 08:01 UTC, TomShawn commented on releases/release-6.6.0.md
> +     更多信息，请参考[用户文档](/placement-rules-in-sql.md#生存偏好)
@nolouch PTAL

2023-01-31 08:06 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/use-witness-to-save-costs.md)。
@Connor1996 @ethercflow PTAL

2023-01-31 08:06 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/use-witness-to-speed-up-failover.md)。
@Connor1996 @ethercflow PTAL

2023-01-31 08:07 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/use-witness-to-save-costs.md)。
@Connor1996 @ethercflow PTAL

2023-01-31 08:07 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/partitioned-table.md#重组分区)
@mjonss PTAL

2023-01-31 08:08 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](链接)。
@hawkingrei PTAL

2023-01-31 08:09 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/sql-statements/sql-statement-flashback-to-timestamp.md)。
@Defined2014 PTAL

2023-01-31 08:09 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](链接)。
@zimulala PTAL

2023-01-31 08:14 UTC, hehechen approved these changes

2023-01-31 08:15 UTC, hehechen commented on releases/release-6.6.0.md
> +    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，TiDB 可以读取指定的时间点或时间范围内的历史数据。Stale Read 允许引擎直接读取本地副本数据，降低读取延迟，提升查询性能。但是，只有 TiKV 引擎支持 Stale Read 功能，TiFlash 引擎并不支持 Stale Read 功能，即使查询的表包含 TiFlash 副本，TiDB 也只能使用 Ti
LGTM

2023-01-31 08:20 UTC, ywqzzy approved these changes
LGTM

2023-01-31 08:23 UTC, Defined2014 approved these changes

2023-01-31 08:24 UTC, you06 approved these changes

2023-01-31 08:42 UTC, xiongjiwei commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/choose-index.md#使用多值索引)。
```suggestion
    更多信息，请参考[用户文档](/sql-statements/sql-statement-create-index.md#多值索引)。
```

2023-01-31 08:45 UTC, xiongjiwei approved these changes

2023-01-31 08:54 UTC, mornyx commented on releases/release-6.6.0.md
> +
```suggestion

* Statements Summary 持久化（实验特性） [#40812](https://github.com/pingcap/tidb/issues/40812) @[mornyx](https://github.com/mornyx) 

    Statements Summary 过去只在内存中维护，一旦 TiDB 发生重启数据便会全部丢失。开启持久化配置后历史数据将会定期被写入磁盘，相关系统表的查询数据源也将由内存变为磁盘，TiDB 发生重启后历史数据将依然保持存在。

    更多信息，请参考[用户文档](/statement-summary-tables.md#持久化-statements-summary)。
```

2023-01-31 09:28 UTC, Frank945946 commented on releases/release-6.6.0.md
> +
- 修复了一个在部分场景下 TiDB 重启导致 Lightning timeout 卡主的 bug。[33714](https://github.com/pingcap/tidb/issues/33714) @[lichunzhu](https://github.com/lichunzhu)

2023-01-31 09:29 UTC, TomShawn commented on releases/release-6.6.0.md
> +
@lilyjazz PTAL

2023-01-31 09:31 UTC, Frank945946 commented on releases/release-6.6.0.md
> +    + TiDB Data Migration (DM)
- 优化了 DM 的告警规则和内容。
之前 DM_XXX_process_exits_with_error 类告警是遇到错误就报警，有些告警实际是由于 db conn 长时间 idle 导致，重连后即可恢复，为了降低这类 false alerm，现在细分为可自动恢复错误和不可恢复错误
对不可自动恢复错误，维持旧的行为，立即 alert
对可自动回复错误，只有在 2m 内发生超过 3 次时才报警
 [7376](https://github.com/pingcap/tiflow/issues/7376) @[D3Hunter](https://github.com/D3Hunter)

2023-01-31 09:33 UTC, YiniXu9506 commented on releases/release-6.6.0.md
> +    通过提供友好的界面简化在 TiDB 上绑定计划的过程，减少计划绑定过程的复杂性提高用户体验，提高计划绑定过程的效率。
```suggestion
    通过提供友好的界面简化在 TiDB 上绑定计划的过程，减少计划绑定过程的复杂性，提高计划绑定过程的效率和用户体验。
```

2023-01-31 09:36 UTC, TomShawn commented on releases/release-6.6.0.md
> +        - 新增一个参数，当下游数据库的表在上游不存在时，可配置该参数跳过对上下游数据库表数量不一致场景的校验，而不是任务中断退出。 @[lichunzhu](https://github.com/lichunzhu) @[liumengya94](https://github.com/liumengya9)
```suggestion
        - 新增一个参数，当下游数据库的表在上游不存在时，可配置该参数跳过对上下游数据库表数量不一致场景的校验，而不是任务中断退出。 @[lichunzhu](https://github.com/lichunzhu) @[liumengya94](https://github.com/liumengya9) **tw@shichun-0415**
```

2023-01-31 09:38 UTC, mornyx commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/statement-summary-tables.md#持久化-statements-summary)。
```suggestion
    更多信息，请参考[用户文档](/statement-summary-tables.md#持久化-statements-summary)。

```

2023-01-31 09:48 UTC, YiniXu9506 approved these changes

2023-01-31 14:04 UTC, time-and-fate commented on releases/release-6.6.0.md
> +    向慢查询日志中增加一个新的字段 `Warning` ，以 JSON 格式记录该慢查询语句在执行过程中产生的警告，用来协助查询性能问题的诊断。
```suggestion
    向慢查询日志中增加一个新的字段 `Warnings` ，以 JSON 格式记录该慢查询语句在执行过程中产生的警告，用来协助查询性能问题的诊断。
```

2023-02-01 02:14 UTC, LykxSassinator commented on releases/release-6.6.0.md
> +| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 新增选项 learner ， 指定 TiDB 从只读节点中读取数据的 learner 副本。  |
| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 从 6.6.0 起新增选项  `prefer-leader`， 以提高 TiDB 集群整体的**读**可用性。该选项被启用时，TiDB 会优先选择 Leader 副本进行读取操作；当 Leader 副本不可用时，会自动将**读操作**转发给 Follower 副本。|

2023-02-01 03:43 UTC, qw4990 approved these changes

2023-02-01 05:33 UTC, zimulala commented on releases/release-6.6.0.md
> +    在过去的版本中，整个 TiDB 集群中仅允许一个 TiDB 实例作为 DDL Owner 有权处理 Schema 变更任务，为了进一步提升 DDL 的并发性，TiDB v6.6.0 版本引入了 DDL 分布式并行执行框架，支持集群中所有的 TiDB 实例都作为 Owner 并发执行同一个 Schema 变更子任务，加速 DDL 的执行。
```suggestion
    在过去的版本中，整个 TiDB 集群中仅允许一个 TiDB 实例作为 DDL Owner 有权处理 Schema 变更任务，为了进一步提升 DDL 的并发性，TiDB v6.6.0 版本引入了 DDL 分布式并行执行框架，支持集群中所有的 TiDB 实例可以并发执行同一个任务的 `StateWriteReorganization` 阶段，加速 DDL 的执行。目前只支持 `Add Index` 操作。
```

2023-02-01 05:54 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +|          |          |          |          |
```suggestion
| TiKV | `storage.block-cache.shared` | 修改 | 从 v6.6.0 起，该配置项永远开启且无法关闭。 |
| TiKV | `storage.block-cache.block-cache-size` | 修改 | 从 v6.6.0 起，该配置项仅用于计算 `storage.block-cache.capacity` 的默认值。 |
```

@BusyJay PTAL

2023-02-01 07:44 UTC, lichunzhu commented on releases/release-6.6.0.md
> +- 修复了一个在部分场景下 TiDB 重启导致 Lightning timeout 卡主的 bug。[33714](https://github.com/pingcap/tidb/issues/33714) @[lichunzhu](https://github.com/lichunzhu) **tw@shichun-0415**
```suggestion
        - 修复在部分场景下 TiDB/TiKV 重启导致 Lightning 重试耗费更长时间的问题。[33714](https://github.com/pingcap/tidb/issues/33714) @[lichunzhu](https://github.com/lichunzhu) **tw@shichun-0415**
```

2023-02-01 07:44 UTC, lichunzhu commented on releases/release-6.6.0.md
> +        - 新增一个参数，当下游数据库的表在上游不存在时，可配置该参数跳过对上下游数据库表数量不一致场景的校验，而不是任务中断退出。 @[lichunzhu](https://github.com/lichunzhu) @[liumengya94](https://github.com/liumengya9) **tw@shichun-0415**
```suggestion
        - 新增 `skip-non-existing-table` 参数，当对比的上下游存在上游或下游表全部缺失的情况时，可配置该参数跳过对上下游表数据不一致的校验并输出到结果集与日志中，而不是任务中断退出。 @[lichunzhu](https://github.com/lichunzhu) @[liumengya94](https://github.com/liumengya9) **tw@shichun-0415**
```

2023-02-01 07:50 UTC, lichunzhu approved these changes
LGTM

2023-02-01 07:55 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](链接)。
```suggestion
```

2023-02-01 09:01 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| TiKV | `storage.block-cache.shared` | 修改 | 从 v6.6.0 起，该配置项永远开启且无法关闭。 |
```suggestion
| TiKV | `storage.block-cache.shared` | 删除 | 从 v6.6.0 起，该配置项永远开启且无法关闭。 |
```

2023-02-01 09:04 UTC, ran-huang commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12296)。
```suggestion
* TiDB Data Migration(DM) 集成了 TiDB Lightning 的 Physical Import Mode，全量迁移性能提升最高达到 10 倍  @[lance6716](https://github.com/lance6716) **tw@ran-huang**

    在 v6.6.0 版本中，DM 的全量迁移能力集成了 TiDB Lightning 的 Physical Import Mode，使得 DM 全量数据迁移的性能最高可提升 10 倍，大大缩短了大数据量场景下的迁移时间。在 v6.6.0 以前，数据量较多的场景下，需要单独配置 TiDB Lightning 的 Physical Import Mode 任务来进行快速的全量数据迁移，再用 DM 来进行增量数据迁移，配置较为复杂。从 v6.6.0 起，用户迁移大数据量的场景，无需再配置 TiDB Lightning 的任务，使用一个 DM 任务即可完成。

    更多信息，请参考[用户文档](/dm/dm-precheck.md#physical-import-检查项)。
```

2023-02-01 09:39 UTC, zimulala commented on releases/release-6.6.0.md
> +| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 新增选项 learner ， 指定 TiDB 从只读节点中读取数据的 learner 副本。  |
新增：
| `tidb_ddl_distribute_reorg` | 新增 | 用于控制是否开启分布式执行 DDL reorg 阶段，从而加速执行此阶段。|

2023-02-02 03:29 UTC, qiancai commented on releases/release-6.6.0.md
> +    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，TiDB 可以读取指定的时间点或时间范围内的历史数据。Stale Read 允许引擎直接读取本地副本数据，降低读取延迟，提升查询性能。但是，只有 TiKV 引擎支持 Stale Read 功能，TiFlash 引擎并不支持 Stale Read 功能，即使查询的表包含 TiFlash 副本，TiDB 也只能使用 Ti
```suggestion
    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，支持读取指定时间点或时间范围内的历史数据。Stale Read 允许直接读取 TiKV 本地副本数据，可以降低读取延迟，提升查询性能。在 v6.6.0 之前的版本中， TiFlash 并不支持 Stale Read 功能，即使 Stale Read 查询的表包含 TiFlash 副本，TiDB 也只能使用 TiKV 副本进行查询。在 v6.6.0 中，TiFlash 实现了对 Stale Read 功能的支持。当使用 `AS OF TIMESTAMP` 语法或 `tidb_read_staleness` 系统变量等方式查询指定时间点或时间范围内的历史数据时，如果查询的表包含 TiFlash 副本，优化器可以选择 TiFlash 副本读取对应的数据，从而进一步提高查询性能。
```

2023-02-02 03:34 UTC, qiancai commented on releases/release-6.6.0.md
> +* TiFlash 引擎支持独立的 MVCC 位图过滤器 [#6296](https://github.com/pingcap/tiflash/issues/6296) @[JinheLin](https://github.com/JinheLin) **tw@qiancai**
```suggestion
* TiFlash 支持独立的 MVCC 位图过滤器 [#6296](https://github.com/pingcap/tiflash/issues/6296) @[JinheLin](https://github.com/JinheLin) **tw@qiancai**
```

2023-02-02 03:34 UTC, qiancai commented on releases/release-6.6.0.md
> +    TiFlash 引擎的数据扫描流程包含 MVCC 过滤和扫描列数据等操作。由于 MVCC 过滤和其他数据扫描操作具有较高的耦合性，导致无法对数据扫描流程进行优化改进。在 v6.6.0 中，TiFlash 将整体数据扫描流程中的 MVCC 过滤操作进行解耦，提供独立的 MVCC 位图过滤器，为后续优化数据扫描流程提供基础。
```suggestion
    TiFlash 的数据扫描流程包含 MVCC 过滤和扫描列数据等操作。由于 MVCC 过滤和其他数据扫描操作具有较高的耦合性，导致无法对数据扫描流程进行优化改进。在 v6.6.0 中，TiFlash 将整体数据扫描流程中的 MVCC 过滤操作进行解耦，提供独立的 MVCC 位图过滤器，为后续优化数据扫描流程提供基础。
```

2023-02-02 03:34 UTC, qiancai commented on releases/release-6.6.0.md
> +    TiFlash 引擎的数据扫描流程包含 MVCC 过滤和扫描列数据等操作。由于 MVCC 过滤和其他数据扫描操作具有较高的耦合性，导致无法对数据扫描流程进行优化改进。在 v6.6.0 中，TiFlash 将整体数据扫描流程中的 MVCC 过滤操作进行解耦，提供独立的 MVCC 位图过滤器，为后续优化数据扫描流程提供基础。
@joey-yez这一条是否可以归到“提升改进”里呢

2023-02-02 03:34 UTC, nolouch commented on releases/release-6.6.0.md
> +     更多信息，请参考[用户文档](/placement-rules-in-sql.md#生存偏好)
lgtm for this part

2023-02-02 03:37 UTC, qiancai commented on releases/release-6.6.0.md
> +    * `regexp_replace`
```suggestion
* 新增支持下推字符串函数 `regexp_replace` 至 TiFlash [#6115](https://github.com/pingcap/tiflash/issues/6115) @[xzhangxian1008](https://github.com/xzhangxian1008) **tw@qiancai**
```

2023-02-02 03:43 UTC, zimulala approved these changes

2023-02-02 03:53 UTC, Connor1996 approved these changes
LGTM

2023-02-02 04:00 UTC, hawkingrei commented on releases/release-6.6.0.md
> +* 支持 DDL 动态资源管控（实验性特性） [#issue](链接)  @[hawkingrei](https://github.com/hawkingrei) **tw@ran-huang**
DDL 动态资源管控，只在分布式 ddl 启动后，才会启动。

2023-02-02 05:41 UTC, qiancai commented on releases/release-6.6.0.md
> +    TiDB 支持 `ALTER TABLE…REORGANIZE PARTITION` 语法。此语法用于对表的部分分区、全部分区重新组织分区结构，并且不丢失数据。
@SunRunAway PTAL. Thanks.

2023-02-02 05:47 UTC, qiancai commented on releases/release-6.6.0.md
> +     更多信息，请参考[用户文档](/placement-rules-in-sql.md#生存偏好)
Thanks for the review.

2023-02-02 05:51 UTC, qiancai commented on releases/release-6.6.0.md
> +    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，TiDB 可以读取指定的时间点或时间范围内的历史数据。Stale Read 允许引擎直接读取本地副本数据，降低读取延迟，提升查询性能。但是，只有 TiKV 引擎支持 Stale Read 功能，TiFlash 引擎并不支持 Stale Read 功能，即使查询的表包含 TiFlash 副本，TiDB 也只能使用 Ti
@joey-yez PATL. Thanks.

2023-02-02 05:57 UTC, joey-yez commented on releases/release-6.6.0.md
> +    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，TiDB 可以读取指定的时间点或时间范围内的历史数据。Stale Read 允许引擎直接读取本地副本数据，降低读取延迟，提升查询性能。但是，只有 TiKV 引擎支持 Stale Read 功能，TiFlash 引擎并不支持 Stale Read 功能，即使查询的表包含 TiFlash 副本，TiDB 也只能使用 Ti
LGTM

2023-02-02 06:08 UTC, qiancai commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 将 TiFlash 整体数据扫描流程中的 MVCC 过滤操作进行解耦，提供独立的 MVCC 位图过滤器，为后续优化数据扫描流程提供基础。 [#6296](https://github.com/pingcap/tiflash/issues/6296) @[JinheLin]
```

2023-02-02 06:13 UTC, TomShawn commented on releases/release-6.6.0.md
> +| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 新增选项 learner ， 指定 TiDB 从只读节点中读取数据的 learner 副本。  |
已经添加进 PR

2023-02-02 11:30 UTC, qiancai commented on releases/release-6.6.0.md
> +    更多信息，请参考：https://docs.pingcap.com/tidb/stable/enable-tls-between-components
```suggestion
    更多信息，请[用户文档](/enable-tls-between-components.md)。
```

2023-02-03 03:02 UTC, qiancai commented on releases/release-6.6.0.md
> +    TiFlash 引擎的数据扫描流程包含 MVCC 过滤和扫描列数据等操作。由于 MVCC 过滤和其他数据扫描操作具有较高的耦合性，导致无法对数据扫描流程进行优化改进。在 v6.6.0 中，TiFlash 将整体数据扫描流程中的 MVCC 过滤操作进行解耦，提供独立的 MVCC 位图过滤器，为后续优化数据扫描流程提供基础。
```suggestion
```

2023-02-03 03:02 UTC, qiancai commented on releases/release-6.6.0.md
> +    TiFlash 引擎的数据扫描流程包含 MVCC 过滤和扫描列数据等操作。由于 MVCC 过滤和其他数据扫描操作具有较高的耦合性，导致无法对数据扫描流程进行优化改进。在 v6.6.0 中，TiFlash 将整体数据扫描流程中的 MVCC 过滤操作进行解耦，提供独立的 MVCC 位图过滤器，为后续优化数据扫描流程提供基础。
移动该 release notes 到改进提升 https://github.com/pingcap/docs-cn/pull/12652/files#r1094077505

2023-02-03 03:05 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 提供独立的 MVCC 位图过滤器，解耦 TiFlash 整体数据扫描流程中的 MVCC 过滤操作，为后续优化数据扫描流程提供基础 [#6296](https://github.com/pingcap/tiflash/issues/6296) @[JinheLin]
```suggestion
    - 提供独立的 MVCC 位图过滤器，解耦 TiFlash 整体数据扫描流程中的 MVCC 过滤操作，为后续优化数据扫描流程提供基础 [#6296](https://github.com/pingcap/tiflash/issues/6296) @[JinheLin] **tw@qiancai**
```

2023-02-03 03:22 UTC, TomShawn commented on releases/release-6.6.0.md
> +
```suggestion

* TiFlash 引擎支持带压缩的数据交换 [#6620](https://github.com/pingcap/tiflash/issues/6620) @[solotzg](https://github.com/solotzg)

为了协同多节点进行计算，TiFlash 引擎需要在不同节点中进行数据交换。当需要交换的数据量非常大时，数据交换性能可能影响整体计算效率。在 v6.6 版本中，TiFlash 引擎引入压缩机制，在必要时对需要交换的数据进行压缩，然后进行交换，从而提升数据交换效率。

```

2023-02-03 03:24 UTC, TomShawn commented on releases/release-6.6.0.md
> +* TiFlash 引擎支持带压缩的数据交换 [#6620](https://github.com/pingcap/tiflash/issues/6620) @[solotzg](https://github.com/solotzg)
```suggestion
* TiFlash 引擎支持带压缩的数据交换 [#6620](https://github.com/pingcap/tiflash/issues/6620) @[solotzg](https://github.com/solotzg) **tw@TomShawn**
```

2023-02-03 03:47 UTC, easonn7 commented
LGTM

2023-02-03 07:44 UTC, solotzg approved these changes

2023-02-03 07:47 UTC, yiwen92 commented on releases/release-6.6.0.md
> +- 提供独立的 MVCC 位图过滤器，解耦 TiFlash 整体数据扫描流程中的 MVCC 过滤操作，为后续优化数据扫描流程提供基础。
```suggestion

```

2023-02-03 08:10 UTC, TomShawn commented on releases/release-6.6.0.md
> +- 引入 MySQL 兼容的多值索引，增强 JSON 类型，提升 TiDB 对 MySQL 8.0 的兼容性（实验特性）。
@yiwen92 PTAL

2023-02-03 08:16 UTC, qiancai commented on releases/release-6.6.0.md
> +        - 对于单区域部署的 TiDB 集群，你可以控制当指定数据库或表在某个可用区产生故障时，也能在另一个可用区提供服务。
```suggestion

    - 对于跨区域部署的 TiDB 集群，你可以控制当指定数据库或表在某个区域产生故障时，也能在另一个区域提供服务。
    - 对于单区域部署的 TiDB 集群，你可以控制当指定数据库或表在某个可用区产生故障时，也能在另一个可用区提供服务。
```

2023-02-03 09:43 UTC, qiancai commented on releases/release-6.6.0.md
> +    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，支持读取指定时间点或时间范围内的历史数据。Stale Read 允许直接读取 TiKV 本地副本数据，可以降低读取延迟，提升查询性能。在 v6.6.0 之前的版本中， TiFlash 并不支持 Stale Read 功能，即使 Stale Read 查询的表包含 TiFlash 副本，TiDB 也只能使用 TiKV
```suggestion
    在 v5.1.1 中，TiDB 正式发布了 Stale Read 功能，支持读取指定时间点或时间范围内的历史数据。Stale Read 允许直接读取 TiKV 本地副本数据，可以降低读取延迟，提升查询性能。在 v6.6.0 之前的版本中， TiFlash 并不支持 Stale Read 功能，即使 Stale Read 查询的表包含 TiFlash 副本，TiDB 也只能使用 TiKV 副本进行查询。在 v6.6.0 中，TiFlash 实现了对 Stale Read 功能的支持。当使用 `AS OF TIMESTAMP` 语法或 `tidb_read_staleness` 系统变量等方式查询历史数据时，如果查询的表包含 TiFlash 副本，优化器可以选择 TiFlash 副本读取对应的数据，从而进一步提高查询性能。
```

2023-02-03 10:57 UTC, qiancai commented on releases/release-6.6.0.md
> +* [Placement Rules in SQL](https://docs.pingcap.com/zh/tidb/dev/placement-rules-in-sql) 支持指定 `SURVIVAL_PREFERENCE` [#38605](https://github.com/pingcap/tidb/issues/38605) @nolouch[https://github.com/n
```suggestion
* [Placement Rules in SQL](/placement-rules-in-sql.md) 支持指定 `SURVIVAL_PREFERENCE` [#38605](https://github.com/pingcap/tidb/issues/38605) @nolouch[https://github.com/nolouch] **tw@qiancai**
```

2023-02-03 10:58 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/statement-summary-tables.md#持久化-statements-summary)。
```suggestion
* 持久化 statements summary（实验特性） [#40812](https://github.com/pingcap/tidb/issues/40812) @[mornyx](https://github.com/mornyx) **tw@shichun-0415**

    v6.6.0 之前版本，statements summary 数据在内存中维护，一旦 TiDB 发生重启，数据便会全部丢失。开启 statements summary 持久化特性后，历史数据将会定期被写入磁盘，相关系统表的查询数据源也将由内存变为磁盘。TiDB 重启后，历史数据将依然保持存在。

    更多信息，请参考[用户文档](/statement-summary-tables.md#持久化-statements-summary)。
```

2023-02-03 10:58 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/dynamic-config.md)。
```suggestion
* 支持动态修改参数 `store-io-pool-size` [#13964](https://github.com/tikv/tikv/issues/13964) @[LykxSassinator](https://github.com/LykxSassinator) **tw@shichun-0415**

    TiKV 中的 [`raftstore.store-io-pool-size`](/tikv-configuration-file.md#store-io-pool-size-从-v530-版本开始引入)用于设定处理 Raft I/O 任务的线程池中线程的数量，需要在 TiKV 性能调优时进行修改调整。在 v6.6.0 版本之前，这个参数无法动态修改。v6.6.0 支持动态修改该参数，提高了 TiKV 性能调优的灵活性。

    更多信息，请参考[用户文档](/dynamic-config.md)。
```

2023-02-03 10:58 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    更多信息，请参考[配置项 `initialize-sql-file`](/tidb-configuration-file.md#initialize-sql-file-从-v660-版本开始引入)。
```suggestion
* 支持指定集群初次启动时的初始化 SQL 脚本 [#35624](https://github.com/pingcap/tidb/issues/35624) @[morgo](https://github.com/morgo) **tw@shichun-0415**

    TiDB 集群初次启动时，可通过命令行参数 `--initialize-sql-file` 指定执行的 SQL 脚本。该功能可用于修改系统变量的值，或者创建用户、分配权限等。

    更多信息，请参考[配置项 `initialize-sql-file`](/tidb-configuration-file.md#initialize-sql-file-从-v660-版本开始引入)。
```

2023-02-03 10:58 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +        - 修复在部分场景下 TiDB/TiKV 重启导致 Lightning 重试耗费更长时间的问题。[33714](https://github.com/pingcap/tidb/issues/33714) @[lichunzhu](https://github.com/lichunzhu) **tw@shichun-0415**
```suggestion
```

2023-02-03 10:58 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +        - 新增 `skip-non-existing-table` 参数，当对比的上下游存在上游或下游表全部缺失的情况时，可配置该参数跳过对上下游表数据不一致的校验并输出到结果集与日志中，而不是任务中断退出。 @[lichunzhu](https://github.com/lichunzhu) @[liumengya94](https://github.com/liumengya9)
```suggestion
        - 新增一个参数 `skip-non-existing-table`，当下游数据库的表在上游不存在时，可配置该参数跳过对上下游数据库表数量不一致场景的校验，而不是任务中断退出 [#692](https://github.com/pingcap/tidb-tools/issues/692) @[lichunzhu](https://github.com/lichunzhu) @[liumengya94](https://github.com/liumengya9) **tw@shichun-0415**
```

2023-02-03 10:58 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
        - 修复了部分场景下 TiDB 重启导致 TiDB Lightning timeout 卡住的问题 [#33714](https://github.com/pingcap/tidb/issues/33714) @[lichunzhu](https://github.com/lichunzhu) **tw@shichun-0415**
        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```

2023-02-03 12:11 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +        - 新增一个参数 `skip-non-existing-table`，当下游数据库的表在上游不存在时，可配置该参数跳过对上下游数据库表数量不一致场景的校验，而不是任务中断退出 [#692](https://github.com/pingcap/tidb-tools/issues/692) @[lichunzhu](https://github.com/lichunzhu) @[l
```suggestion
        - 新增一个参数 `skip-non-existing-table`，当下游数据库的表在上游不存在时，可配置该参数跳过对上下游数据库表数量不一致场景的校验 [#692](https://github.com/pingcap/tidb-tools/issues/692) @[lichunzhu](https://github.com/lichunzhu) @[liumengya94](https://github.com/liumengya9) **tw@shichun-0415**
```

2023-02-06 01:12 UTC, hfxsd commented on releases/release-6.6.0.md
> +    在 v6.6 中， 启用资源管控技术需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-%E4%BB%8E-v660-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5) 及 TiK
```suggestion
    在 v6.6 中， 启用资源管控技术需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-从-v660-版本开始引入) 及 TiKV 的配置项 [`resource_control.enabled`](/tikv-configuration-file.md#tidb_enable_resource_control)。 当前支持的限额方式是基于"[用量](/tidb-resource-control.md#什么是-request-unit-ru)" (即 Request Unit 或 RU )，RU 是 TiDB 对 CPU、IO 等系统资源的统一抽象单位。
```

2023-02-06 01:16 UTC, hfxsd commented on releases/release-6.6.0.md
> +    资源管控技术的引入对 TiDB 具有里程碑的意义，它能够将一个分布式数据库集群中划分成多个逻辑单元，即使个别单元对资源过度使用，也不会完全挤占其他单元所需的资源。利用这个技术，你可以将数个来自不同系统的中小型应用合入一个 TiDB 集群中，个别应用的负载提升，不会影响其他业务的正常运行；而在系统负载较低的时候，繁忙的应用即使超过限额，也仍旧可以被分配到所需的系统资源，达到资源的最大化利用
```suggestion
资源管控特性的引入对 TiDB 具有里程碑的意义。它能够将一个分布式数据库集群划分成多个逻辑单元，即使个别单元对资源过度使用，也不会挤占其他单元所需的资源。利用该特性：

- 你可以将多个来自不同系统的中小型应用合入一个 TiDB 集群中，个别应用的负载提升，不会影响其他业务的正常运行。而在系统负载较低的时候，繁忙的应用即使超过设定的读写配额，也仍然可以被分配到所需的系统资源，达到资源的最大化利用。
- 你可以选择将所有测试环境合入一个集群，或者将消耗较大的批量任务编入一个单独的资源组，在保证重要应用获得必要资源的同时，提升硬件利用率，降低运行成本。

此外，合理利用资源管控特性可以减少集群数量，降低运维难度及管理成本。
```

2023-02-06 01:18 UTC, hfxsd commented on releases/release-6.6.0.md
> +- 你可以选择将所有测试环境合入一个集群，或者将消耗较大的批量任务编入一个单独的资源组，在保证重要应用获得必要资源的同时，提升硬件利用率，降低运行成本。
```suggestion
    - 你可以将多个来自不同系统的中小型应用合入一个 TiDB 集群中，个别应用的负载提升，不会影响其他业务的正常运行。而在系统负载较低的时候，繁忙的应用即使超过设定的读写配额，也仍然可以被分配到所需的系统资源，达到资源的最大化利用。
    - 你可以选择将所有测试环境合入一个集群，或者将消耗较大的批量任务编入一个单独的资源组，在保证重要应用获得必要资源的同时，提升硬件利用率，降低运行成本。
```

2023-02-06 01:19 UTC, hfxsd commented on releases/release-6.6.0.md
> +此外，合理利用资源管控特性可以减少集群数量，降低运维难度及管理成本。
```suggestion
    资源管控特性的引入对 TiDB 具有里程碑的意义。它能够将一个分布式数据库集群划分成多个逻辑单元，即使个别单元对资源过度使用，也不会挤占其他单元所需的资源。利用该特性：

    - 你可以将多个来自不同系统的中小型应用合入一个 TiDB 集群中，个别应用的负载提升，不会影响其他业务的正常运行。而在系统负载较低的时候，繁忙的应用即使超过设定的读写配额，也仍然可以被分配到所需的系统资源，达到资源的最大化利用。
    - 你可以选择将所有测试环境合入一个集群，或者将消耗较大的批量任务编入一个单独的资源组，在保证重要应用获得必要资源的同时，提升硬件利用率，降低运行成本。

    此外，合理利用资源管控特性可以减少集群数量，降低运维难度及管理成本。
```

2023-02-06 01:45 UTC, hfxsd commented on releases/release-6.6.0.md
> +    TiDB 集群支持创建资源组，将不用的数据库用户映射到对应的资源组中，根据实际需要设置每个资源组的配额。当集群资源紧张时，来自同一个资源组的会话所使用的全部资源将被限制在配额内，避免其中一个资源组过度消耗从而抑制其他资源组中的会话正常运行。系统内置视图会对资源的实际使用情况进行反馈和展示，协助用户更合理地配置资源。
这里的 “不用的数据库用户”好像写错了？

2023-02-06 01:58 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/sql-statements/sql-statement-create-index.md#多值索引)。
```suggestion
* 支持 MySQL 兼容的多值索引 (Multi-Valued Index)（实验特性）[#39592](https://github.com/pingcap/tidb/issues/39592) @[xiongjiwei](https://github.com/xiongjiwei) @[qw4990](https://github.com/qw4990) **tw@TomShawn**

    TiDB 在 v6.6.0 引入了 MySQL 兼容的多值索引 (Multi-Valued Index)。过滤 JSON 列类型中某个数组的值是常见的操作， 但普通索引对这类操作起不到加速作用。在数组上创建多值索引能够大幅提升过滤的性能。如果 JSON 类型中的某个数组上存在多值索引，那么带有 `MEMBER OF()`、`JSON_CONTAINS()`、`JSON_OVERLAPS()` 这几个函数的检索条件可以利用多值索引进行过滤，减少大量的 I/O 消耗，从而提升运行速度。

    多值索引的引入， 进一步增强了 JSON 类型， 同时也提升了 TiDB 对 MySQL 8.0 的兼容性。

    更多信息，请参考[用户文档](/sql-statements/sql-statement-create-index.md#多值索引)。
```

2023-02-06 01:59 UTC, hfxsd commented on releases/release-6.6.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
        优化了 DM 的告警规则和内容。[7376](https://github.com/pingcap/tiflow/issues/7376) @[D3Hunter](https://github.com/D3Hunter) **tw@hfxsd**

        之前 "DM_XXX_process_exits_with_error" 类告警是遇到错误就报警，有些告警实际是由于数据库链接 长时间 idle 导致，重连后即可恢复。为了减少这类报警，将告警分为可自动恢复错误和不可恢复错误。

        - 对于可自动回复错误，只有在 2 分钟内发生超过 3 次时才报警。
        - 对于不可自动恢复错误，维持原有行为，立即报警。
```

2023-02-06 02:14 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/sql-plan-management.md#根据历史执行计划创建绑定)。
```suggestion
* 绑定历史执行计划 GA [#39199](https://github.com/pingcap/tidb/issues/39199) @[fzzf678](https://github.com/fzzf678) **tw@TomShawn**

    在 v6.5.0 中，TiDB 扩展了 [`CREATE [GLOBAL | SESSION] BINDING`](/sql-statements/sql-statement-create-binding.md) 语句中的绑定对象，支持根据历史执行计划创建绑定。在 v6.6.0 中该功能 GA， 执行计划的选择不仅限于当前 TiDB 节点，任意 TiDB 节点产生的历史执行计划都可以被选为 [SQL Binding](/sql-statements/sql-statement-create-binding.md)) 的目标，进一步提升了功能的易用性。

    更多信息，请参考[用户文档](/sql-plan-management.md#根据历史执行计划创建绑定)。
```

2023-02-06 02:25 UTC, ran-huang commented on releases/release-6.6.0.md
> +    TiDB v6.6.0 版本引入了 DDL 动态资源管控， 通过自动控制 DDL 的 CPU 和内存使用量，尽量降低 DDL 变更任务对线上业务的影响。
```suggestion
    TiDB v6.6.0 版本引入了 DDL 动态资源管控， 通过自动控制 DDL 的 CPU 和内存使用量，尽量降低 DDL 变更任务对线上业务的影响。该功能仅在开启 [DDL 分布式并行执行框架](/system-variables.md#tidb_ddl_distribute_reorg-从-v660-版本开始引入)后生效。
```

2023-02-06 02:25 UTC, ran-huang commented on releases/release-6.6.0.md
> +    TiDB v6.6.0 版本引入了 DDL 动态资源管控， 通过自动控制 DDL 的 CPU 和内存使用量，尽量降低 DDL 变更任务对线上业务的影响。
@hawkingrei how about this?

2023-02-06 02:30 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/sql-prepared-plan-cache.md#prepared-plan-cache-诊断)。
```suggestion
* 为执行计划缓存增加告警 @[qw4990](https://github.com/qw4990) **tw@TomShawn**

    当执行计划无法被缓存时，TiDB 会通过告警的方式提示该计划无法被缓存的原因，降低诊断的难度。例如：

    ```sql
    mysql> PREPARE st FROM 'SELECT * FROM t WHERE a<?';
    Query OK, 0 rows affected (0.00 sec)

    mysql> SET @a='1';
    Query OK, 0 rows affected (0.00 sec)

    mysql> EXECUTE st USING @a;
    Empty set, 1 warning (0.01 sec)

    mysql> SHOW WARNINGS;
    +---------+------+----------------------------------------------+
    | Level   | Code | Message                                      |
    +---------+------+----------------------------------------------+
    | Warning | 1105 | skip plan-cache: '1' may be converted to INT |
    +---------+------+----------------------------------------------+
    ```

    在以上例子中，优化器进行了非 INT 类型到 INT 类型的转换，产生的执行计划可能随着参数变化而存在风险，因此 TiDB 不缓存该计划。

    更多信息，请参考[用户文档](/sql-prepared-plan-cache.md#prepared-plan-cache-诊断)。
```

2023-02-06 02:40 UTC, TomShawn commented on releases/release-6.6.0.md
> +    此特性默认打开， 通过系统变量 [`tidb_store_batch_size`](/system-variables.md#tidb_store_batch_size) 设置批量请求的大小。
```suggestion
* 批量聚合数据请求 [#39361](https://github.com/pingcap/tidb/issues/39361) @[cfzjywxk](https://github.com/cfzjywxk) @[you06](https://github.com/you06) **tw@TomShawn**

    TiDB 向 TiKV 发送数据请求时，会根据数据所在的 Region 将请求编入不同的子任务，每个子任务只处理单个 Region 的请求。当访问的数据离散度很高时，即使数据量不大，也会生成众多的子任务，进而产生大量 RPC 请求，消耗额外的时间。在 v6.6.0 中，TiDB 支持将发送到相同 TiKV 实例的数据请求部分合并，减少子任务的数量和 RPC 请求的开销。在数据离散度高且 gRPC 线程池资源紧张的情况下，批量化请求能够将性能提升 50% 以上。

    此特性默认打开，可通过系统变量 [`tidb_store_batch_size`](/system-variables.md#tidb_store_batch_size) 设置批量请求的大小。
```

2023-02-06 02:49 UTC, ran-huang commented on releases/release-6.6.0.md
> +    在执行计划问题的排查过程中，`PLAN REPLAYER` 能够协助保存现场，提升诊断的效率。 但在个别场景中，一些执行计划的生成无法任意重现，给诊断工作增加了难度。针对这类问题，`PLAN REPLAYER` 扩展了自动捕获的能力。 通过 `PLAN REPLAYER CAPTURE` 命令字，用户可提前注册目标 SQL，也可以同时指定目标执行计划， 当 TiDB 检测到执行的 SQL
```suggestion
    在执行计划问题的排查过程中，`PLAN REPLAYER` 能够协助保存现场，提升诊断的效率。 但在个别场景中，一些执行计划的生成无法任意重现，给诊断工作增加了难度。针对这类问题，在 TiDB v6.6.0 中，`PLAN REPLAYER` 扩展了自动捕获的能力。 通过 `PLAN REPLAYER CAPTURE` 命令字，用户可提前注册目标 SQL，也可以同时指定目标执行计划。当 TiDB 检测到执行的 SQL 和执行计划与注册目标匹配时，会自动生成并打包 `PLAN REPLAYER` 的信息，提升执行计划不稳定时的诊断效率。
```

2023-02-06 02:59 UTC, ran-huang commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12296)。
```suggestion
* TiDB Data Migration(DM) 集成了 TiDB Lightning 的 Physical Import Mode，全量迁移性能提升最高达到 10 倍  @[lance6716](https://github.com/lance6716) **tw@ran-huang**

    在 v6.6.0 版本中，DM 的全量迁移能力集成了 TiDB Lightning 的 Physical Import Mode，使得 DM 全量数据迁移的性能最高可提升 10 倍，大大缩短了大数据量场景下的迁移时间。在 v6.6.0 以前，数据量较多的场景下，需要单独配置 TiDB Lightning 的 Physical Import Mode 任务来进行快速的全量数据迁移，再用 DM 来进行增量数据迁移，配置较为复杂。从 v6.6.0 起，用户迁移大数据量的场景，无需再配置 TiDB Lightning 的任务，使用一个 DM 任务即可完成。

    更多信息，请参考[用户文档](/dm/dm-precheck.md#physical-import-检查项)。
```

2023-02-06 03:02 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](链接)。
```suggestion
* 支持兼容 MySQL 语法的外键约束（实验特性）[#18209](https://github.com/pingcap/tidb/issues/18209) @[crazycs520](https://github.com/crazycs520) **tw@Oreoxmt**

    更多信息，请参考 v6.6.0 Release Notes 中 [SQL 部分](#sql)以及[用户文档](/sql-statements/sql-statement-foreign-key.md)。
```

2023-02-06 03:06 UTC, TomShawn commented on releases/release-6.6.0.md
> +    优化器 Hint 的持续引入，为用户提供了更多的干预手段，有助于 SQL 性能问题的解决，并提升了整体性能的稳定性。
```suggestion
* 新增若干优化器 Hint [#39964](https://github.com/pingcap/tidb/issues/39964) @[Reminiscent](https://github.com/Reminiscent) **tw@TomShawn**

    TiDB 在 v6.6.0 中增加了若干优化器 Hint，用来控制 `LIMIT` 操作的执行计划选择：

    - [`ORDER_INDEX()`](/optimizer-hints.md#keep_ordert1_name-idx1_name--idx2_name-)：提示优化器使用指定的索引，读取数据时保持索引的顺序，生成类似 `Limit + IndexScan(keep order: true)` 的计划。
    - [`NO_ORDER_INDEX()`](/optimizer-hints.md#no_keep_ordert1_name-idx1_name--idx2_name-)：提示优化器使用指定的索引，读取数据时不保持顺序，生成类似 `TopN + IndexScan(keep order: false)` 的计划。

    持续引入优化器 Hint 为用户提供了更多的干预手段，有助于解决 SQL 性能问题，并提升了整体性能的稳定性。
```

2023-02-06 03:19 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始引入)。
```suggestion
* 支持悲观锁队列的稳定唤醒模型 [#13298](https://github.com/tikv/tikv/issues/13298) @[MyonKeminta](https://github.com/MyonKeminta) **tw@TomShawn**

    如果业务场景存在单点悲观锁冲突频繁的情况，原有的唤醒机制无法保证事务获取锁的时间，造成长尾延迟高，甚至获取锁超时。自 v6.6.0 起，用户可通过设置系统变量 [`tidb_pessimistic_txn_aggressive_locking`](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始引入) 为 `ON` 开启悲观锁的稳定唤醒模型。在该唤醒模型下，队列的唤醒顺序可被严格控制，避免无效唤醒造成的资源浪费。在锁冲突严重的场景中，能够减少长尾延时，降低 P99 响应时间。

    更多信息，请参考[用户文档](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始引入)。
```

2023-02-06 03:27 UTC, TomShawn commented on releases/release-6.6.0.md
> +    为了协同多节点进行计算，TiFlash 引擎需要在不同节点中进行数据交换。当需要交换的数据量非常大时，数据交换性能可能影响整体计算效率。在 v6.6 版本中，TiFlash 引擎引入压缩机制，在必要时对需要交换的数据进行压缩，然后进行交换，从而提升数据交换效率。
```suggestion
* TiFlash 引擎支持带压缩的数据交换 [#6620](https://github.com/pingcap/tiflash/issues/6620) @[solotzg](https://github.com/solotzg) **tw@TomShawn**

    为了协同多节点进行计算，TiFlash 引擎需要在不同节点中进行数据交换。当需要交换的数据量非常大时，数据交换的性能可能影响整体计算效率。在 v6.6.0 版本中，TiFlash 引擎引入压缩机制，在必要时对需要交换的数据进行压缩，然后进行交换，从而提升数据交换效率。
    
    更多信息，参见[用户文档](/explain-mpp.md#启用-mpp-数据压缩的执行计划)。
```

2023-02-06 03:54 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +* 支持兼容 MySQL 语法的外键约束（实验特性）[#18209](https://github.com/pingcap/tidb/issues/18209) @[crazycs520](https://github.com/crazycs520) **tw@Oreoxmt**
```suggestion
* 支持兼容 MySQL 语法的外键约束 [#18209](https://github.com/pingcap/tidb/issues/18209) @[crazycs520](https://github.com/crazycs520) **tw@Oreoxmt**
```

2023-02-06 03:54 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +* 支持兼容 MySQL 语法的外键约束（实验特性）[#18209](https://github.com/pingcap/tidb/issues/18209) @[crazycs520](https://github.com/crazycs520) **tw@Oreoxmt**
```suggestion
* 支持兼容 MySQL 语法的外键约束 [#18209](https://github.com/pingcap/tidb/issues/18209) @[crazycs520](https://github.com/crazycs520) **tw@Oreoxmt**
```

2023-02-06 03:56 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| [`tidb_enable_foreign_key`](/system-variables.md#tidb_enable_foreign_key-从-v630-版本开始引入) | 修改 | 用于控制是否开启外键功能。默认值由 `OFF` 修改为 `ON`，表示默认开启外键功能。|
@crazycs520 PTAL

2023-02-06 04:22 UTC, crazycs520 commented on releases/release-6.6.0.md
> +| [`tidb_enable_foreign_key`](/system-variables.md#tidb_enable_foreign_key-从-v630-版本开始引入) | 修改 | 用于控制是否开启外键功能。默认值由 `OFF` 修改为 `ON`，表示默认开启外键功能。|
LGTM

2023-02-06 05:18 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| TiCDC   |   新增       |  `scheduler.region-per-span`        |    **tw@Oreoxmt**      |
```suggestion
| TiCDC | [`scheduler.region-per-span`](/ticdc/ticdc-changefeed-config.md#ticdc-changefeed-配置文件说明) | 新增 | 将表按 Region 个数划分成多个同步范围，这些范围可由多个 TiCDC 节点同步。 |
```

2023-02-06 05:18 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 新增选项 learner ， 指定 TiDB 从只读节点中读取数据的 learner 副本。  |
```suggestion
| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 新增选项 `learner`，指定 TiDB 从只读节点中读取数据的 learner 副本。  |
```

2023-02-06 05:18 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +|  .... |  新增  |  https://github.com/pingcap/docs-cn/pull/12819/files **tw@Oreoxmt**  |
```suggestion
| TiSpark | [`spark.tispark.replica_read`](/tispark-overview.md#tispark-配置) | 新增 | 控制读取副本的类型，可选值为 `leader`、`follower`、`learner`。 |
| TiSpark | [`spark.tispark.replica_read.label`](/tispark-overview.md#tispark-配置) | 新增 | 设置目标 TiKV 节点的标签。 |
```

2023-02-06 06:05 UTC, TomShawn commented on releases/release-6.6.0.md
> +* 支持 MySQL 兼容的多值索引 (Multi-Valued Index)（实验特性）[#39592](https://github.com/pingcap/tidb/issues/39592) @[xiongjiwei](https://github.com/xiongjiwei) @[qw4990](https://github.com/qw4990) **tw@TomShawn**
```suggestion

* 支持 MySQL 兼容的多值索引 (Multi-Valued Index)（实验特性）[#39592](https://github.com/pingcap/tidb/issues/39592) @[xiongjiwei](https://github.com/xiongjiwei) @[qw4990](https://github.com/qw4990) **tw@TomShawn**
```

2023-02-06 06:29 UTC, TomShawn commented on releases/release-6.6.0.md
> +| [`tidb_store_batch_size`](/system-variables.md#tidb_store_batch_size) | 修改 | 此变量可用于生产环境。 设置 `IndexLookUp` 算子回表时多个 Coprocessor Task 的 batch 大小。`0` 代表不使用 batch。当 `IndexLookUp` 算子的回表 Task 数量特别多，出现极长的慢
```suggestion
| [`tidb_store_batch_size`](/system-variables.md#tidb_store_batch_size) | 修改 | 该变量设置 `IndexLookUp` 算子回表时多个 Coprocessor Task 的 batch 大小。`0` 代表不使用 batch。自 v6.6.0 起，默认值由 `0` 调整为 `4`，即每批请求包含 4 个 Coprocessor Task。 |
```

2023-02-06 06:31 UTC, TomShawn commented on releases/release-6.6.0.md
> +| TiKV | `storage.block-cache.block-cache-size` | 修改 | 从 v6.6.0 起，该配置项仅用于计算 `storage.block-cache.capacity` 的默认值。 |
```suggestion
| TiKV | `storage.block-cache.shared` | 删除 | 从 v6.6.0 起删除该配置项，默认开启 block cache 且无法关闭，详情参见 [#12936](https://github.com/tikv/tikv/issues/12936)。 |
| TiKV | `storage.block-cache.block-cache-size` | 修改 | 从 v6.6.0 起，该配置项仅用于计算 `storage.block-cache.capacity` 的默认值。详情参见 [#12936](https://github.com/tikv/tikv/issues/12936)。 |
```

2023-02-06 06:42 UTC, YangKeao commented on releases/release-6.6.0.md
> +| [`tidb_enable_concurrent_ddl`](/system-variables.md#tidb_enable_concurrent_ddl-从-v620-版本开始引入) | 删除 | 这个变量用于控制是否让 TiDB 使用并发 DDL 语句。自 v6.6.0 前，该变量被删除。 |
> 自 v6.6.0 前，该变量被删除。
应该是 "自 v6.6.0 起"？

删除的原因是：在 v6.6.0 版本为每个 Table 提供了属性 TTL_JOB_INTERVAL 用于配置 TTL 运行的间隔，允许用户为每个 Table 设置不同的运行间隔，比单独系统变量更加灵活。所以移除了系统变量 `tidb_enable_concurrent_ddl` @TomShawn

2023-02-06 06:48 UTC, TomShawn commented on releases/release-6.6.0.md
> +| [`tidb_enable_concurrent_ddl`](/system-variables.md#tidb_enable_concurrent_ddl-从-v620-版本开始引入) | 删除 | 这个变量用于控制是否让 TiDB 使用并发 DDL 语句。自 v6.6.0 前，该变量被删除。 |
```suggestion
| [`tidb_enable_concurrent_ddl`](/system-variables.md#tidb_enable_concurrent_ddl-从-v620-版本开始引入) | 删除 | 这个变量用于控制是否让 TiDB 使用并发 DDL 语句。自 v6.6.0 起，该变量被删除。 |
```

2023-02-06 06:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +| [`tidb_ttl_job_run_interval`](/system-variables.md#tidb_ttl_job_run_interval-从-v650-版本开始引入) | 删除 | 这个变量用于控制 TTL 后台清理任务的调度周期。比如，如果当前值设置成了 `1h0m0s`，则代表每张设置了 TTL 属性的表会每小时清理一次过期数据。自 v6.6.0 起删除该变量，因为 **
```suggestion
| [`tidb_ttl_job_run_interval`](/system-variables.md#tidb_ttl_job_run_interval-从-v650-版本开始引入) | 删除 | 这个变量用于控制 TTL 后台清理任务的调度周期。自 v6.6.0 起删除该变量，因为自 v6.6.0 起 TiDB 为每张表提供了属性 `TTL_JOB_INTERVAL` 用于配置 TTL 运行的间隔，允许用户为每张表设置不同的运行间隔，比系统变量更加灵活。 |
```

2023-02-06 08:05 UTC, tabokie commented on releases/release-6.6.0.md
> +| TiKV  |  `enable-statistics`  |  删除   |  该配置项指定是否开启 RocksDB 的统计信息收集功能。从 v6.6.0 起，删除该配置项。。更多细节，参见 [tikv/tikv#13942](https://github.com/tikv/tikv/pull/13942)。  |
```suggestion
| TiKV  |  `enable-statistics`  |  删除   |  该配置项指定是否开启 RocksDB 的统计信息收集功能。从 v6.6.0 起，删除该配置项。所有集群默认开启统计信息收集，以便于故障排查。更多细节，参见 [tikv/tikv#13942](https://github.com/tikv/tikv/pull/13942)。  |
```

2023-02-06 08:46 UTC, hfxsd commented on releases/release-6.6.0.md
> +    - 对于单区域部署的 TiDB 集群，你可以控制当指定数据库或表在某个可用区产生故障时，也能在另一个可用区提供服务。
```suggestion
    - 对于跨区域部署的 TiDB 集群，你可以控制当指定数据库或表在某个区域产生故障时，能在另一个区域继续提供服务。
    - 对于单区域部署的 TiDB 集群，你可以控制当指定数据库或表在某个可用区产生故障时，能在另一个可用区继续提供服务。
```

2023-02-06 08:46 UTC, hfxsd commented on releases/release-6.6.0.md
> +    TiFlash TLS 证书自动轮换指在开启组件间加密传输的 TiDB 集群上，当 TiFlash 的 TLS 证书过期需要重新签发一个新 TLS 证书给 TiFlash 时，支持自动加载新的 TiFlash TLS 证书，无需重启 TiDB 集群。TiDB 集群内部组件之间 TLS 过期轮换不影响 TiDB 集群的正常使用，保障了 TiDB 集群的高可用。
```suggestion
    TiDB v6.6.0 引入了 TiFlash TLS 证书自动轮换功能。在开启组件间加密传输的 TiDB 集群上，当 TiFlash 的 TLS 证书过期需要重新签发时，支持自动加载新的 TiFlash TLS 证书，无需重启 TiDB 集群。而且，TiDB 集群内部组件之间 TLS 过期轮换不影响 TiDB 集群的正常使用，保障了 TiDB 集群的高可用。
```

2023-02-06 08:46 UTC, hfxsd commented on releases/release-6.6.0.md
> +    在 v6.6.0 中，TiFlash 实现了对 Stale Read 功能的支持。当使用 `AS OF TIMESTAMP` 语法或 `tidb_read_staleness` 系统变量等方式查询历史数据时，如果查询的表包含 TiFlash 副本，优化器可以选择 TiFlash 副本读取对应的数据，从而进一步提高查询性能。
`AS OF TIMESTAMP` 语法或 `tidb_read_staleness` 系统变量 可以加上链接。
```suggestion
    Stale Read 功能是从 TiDB v5.1.1 开始正式引入的，支持读取指定时间点或时间范围内的历史数据。Stale Read 允许直接读取 TiKV 本地副本数据，可以降低读取延迟，提升查询性能。在 v6.6.0 之前的版本中，TiFlash 并不支持 Stale Read 功能，即使 Stale Read 查询的表包含 TiFlash 副本，TiDB 也只能使用 TiKV 副本进行查询。

    在 v6.6.0 中，TiFlash 开始 Stale Read 功能。当使用 `AS OF TIMESTAMP` 语法或 `tidb_read_staleness` 系统变量等方式查询历史数据时，如果查询的表包含 TiFlash 副本，优化器可以选择 TiFlash 副本读取对应的数据，从而进一步提高查询性能。
```

2023-02-06 10:05 UTC, songrijie commented on releases/release-6.6.0.md
> +    TiDB 集群支持创建资源组，将不用的数据库用户映射到对应的资源组中，根据实际需要设置每个资源组的配额。当集群资源紧张时，来自同一个资源组的会话所使用的全部资源将被限制在配额内，避免其中一个资源组过度消耗从而抑制其他资源组中的会话正常运行。系统内置视图会对资源的实际使用情况进行反馈和展示，协助用户更合理地配置资源。
Please refer to update: https://github.com/pingcap/docs-cn/pull/12652/commits/c39d118a64f900c79ee9355ed8391285a590241f

2023-02-07 02:15 UTC, TomShawn commented on releases/release-6.6.0.md
> +| TiKV  |  `enable-statistics`  |  删除   |  该配置项指定是否开启 RocksDB 的统计信息收集功能。从 v6.6.0 起，删除该配置项。详情参见 [tikv/tikv#13942](https://github.com/tikv/tikv/pull/13942)。  |
```suggestion
| TiKV  |  `enable-statistics`  |  删除   |  该配置项指定是否开启 RocksDB 的统计信息收集功能。从 v6.6.0 起，删除该配置项。所有集群默认开启统计信息收集，以便于故障排查。详情参见 [tikv/tikv#13942](https://github.com/tikv/tikv/pull/13942)。  |
```

2023-02-07 02:40 UTC, wjhuang2016 commented on releases/release-6.6.0.md
> +| [`tidb_enable_concurrent_ddl`](/system-variables.md#tidb_enable_concurrent_ddl-从-v620-版本开始引入) | 删除 | 这个变量用于控制是否让 TiDB 使用并发 DDL 语句。自 v6.6.0 起，该变量被删除。 |
不再支持关闭（DDL 旧框架）的情况。

2023-02-07 02:42 UTC, TomShawn commented on releases/release-6.6.0.md
> +    [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 语句支持在 Garbage Collection (GC) life time 内快速回退整个集群到指定的时间点。在 TiDB v6.6.0 版本中，该功能新增了支持撤销 DDL 操作，适用于快速撤消集群的
```suggestion
    [`FLASHBACK CLUSTER TO TIMESTAMP`](/sql-statements/sql-statement-flashback-to-timestamp.md) 语句支持在 Garbage Collection (GC) life time 内快速回退整个集群到指定的时间点。在 TiDB v6.6.0 版本中，该功能新支持撤销 DDL 操作，适用于快速撤消集群的 DML 或 DDL 误操作、支持分钟级别的快速回退集群、支持在时间线上多次回退以确定特定数据更改发生的时间。
```

2023-02-07 02:42 UTC, TomShawn commented on releases/release-6.6.0.md
> +    在过去的版本中，整个 TiDB 集群中仅允许一个 TiDB 实例作为 DDL Owner 有权处理 Schema 变更任务。为了进一步提升 DDL 的并发性，TiDB v6.6.0 版本引入了 DDL 分布式并行执行框架，支持集群中所有的 TiDB 实例可以并发执行同一个任务的 `StateWriteReorganization` 阶段，加速 DDL 的执行。该功能由系统变量 [`tid
```suggestion
    在过去的版本中，整个 TiDB 集群中仅允许一个 TiDB 实例作为 DDL Owner 处理 Schema 变更任务。为了进一步提升 DDL 的并发性，TiDB v6.6.0 版本引入了 DDL 分布式并行执行框架，支持集群中所有的 TiDB 实例并发执行同一个任务的 `StateWriteReorganization` 阶段，加速 DDL 的执行。该功能由系统变量 [`tidb_ddl_distribute_reorg`](/system-variables.md#tidb_ddl_distribute_reorg-从-v660-版本开始引入) 控制是否开启，目前只支持 `Add Index` 操作。
```

2023-02-07 02:42 UTC, TomShawn commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/system-variables.md#tidb_ddl_distribute_reorg-从-v660-版本开始引入)。
经和 FO 确认，这个 feature 在 v6.6 中不需要文档。
```suggestion
```

2023-02-07 02:42 UTC, TomShawn commented on releases/release-6.6.0.md
> +    TiDB v6.6.0 中引入了执行计划快速绑定功能，允许用户在 TiDB Dashboard 中一分钟内完成 SQL 与特定计划的绑定。
```suggestion
    TiDB v6.6.0 中引入了执行计划快速绑定功能，允许用户在 TiDB Dashboard 中快速完成 SQL 语句与特定计划的绑定。
```

2023-02-07 02:42 UTC, TomShawn commented on releases/release-6.6.0.md
> +    通过提供友好的界面，简化了在 TiDB 上绑定计划的过程，减少计划绑定过程的复杂性，提高计划绑定过程的效率和用户体验。
```suggestion
    通过提供友好的界面，简化了在 TiDB Dashboard 上绑定 SQL 执行计划的过程，提高绑定过程的效率和用户体验。
```

2023-02-07 02:42 UTC, TomShawn commented on releases/release-6.6.0.md
> +    启用这个功能需要设置系统变量 [`tidb_enable_plan_replayer_capture`](/system-variables.md#tidb_enable_plan_replayer_capture) 为 `ON`。
```suggestion
    在执行计划问题的排查过程中，`PLAN REPLAYER` 能够协助保存现场，提升诊断的效率。但在个别场景中，一些执行计划的生成无法任意重现，给诊断工作增加了难度。针对这类场景，在 TiDB v6.6.0 中，`PLAN REPLAYER` 扩展了自动捕获的能力。通过 `PLAN REPLAYER CAPTURE` 命令，用户可提前注册目标 SQL 语句，也可以同时指定目标执行计划。当 TiDB 检测到执行的 SQL 语句和执行计划与注册目标匹配时，会自动生成并打包 `PLAN REPLAYER` 的信息，提升执行计划不稳定时的诊断效率。

    要启用该功能，需要将系统变量 [`tidb_enable_plan_replayer_capture`](/system-variables.md#tidb_enable_plan_replayer_capture) 的值设为 `ON`。
```

2023-02-07 02:42 UTC, TomShawn commented on releases/release-6.6.0.md
> +* TiDB Data Migration(DM) 集成了 TiDB Lightning 的 Physical Import Mode，全量迁移性能提升最高达到 10 倍  @[lance6716](https://github.com/lance6716) **tw@ran-huang**
```suggestion
* TiDB Data Migration(DM) 集成了 TiDB Lightning 的 Physical Import Mode，全量迁移性能提升最高达到 10 倍 @[lance6716](https://github.com/lance6716) **tw@ran-huang**
```

2023-02-07 02:44 UTC, xiongjiwei commented on releases/release-6.6.0.md
> +    TiDB 在 v6.6.0 引入了 MySQL 兼容的多值索引 (Multi-Valued Index)。过滤 JSON 列类型中某个数组的值是常见的操作，但普通索引对这类操作起不到加速作用。在数组上创建多值索引能够大幅提升过滤的性能。如果 JSON 类型中的某个数组上存在多值索引，那么可以利用多值索引过滤带有 `MEMBER OF()`、`JSON_CONTAINS()`、`JSON_
LGTM

2023-02-07 06:03 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    更多信息，请参考[配置项 `initialize-sql-file`](/tidb-configuration-file.md#initialize-sql-file-从-v660-版本开始引入)。
```suggestion
    更多信息，请参考[用户文档](/tidb-configuration-file.md#initialize-sql-file-从-v660-版本开始引入)。
```

2023-02-07 06:03 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    TiDB 集群初次启动时，可通过命令行参数 `--initialize-sql-file` 指定执行的 SQL 脚本。该功能可用于修改系统变量的值，或者创建用户、分配权限等。
```suggestion
    TiDB 集群初次启动时，可通过命令行参数 `--initialize-sql-file` 指定执行的 SQL 脚本。该功能可用于修改系统变量的值、创建用户或分配权限等。
```

2023-02-07 07:10 UTC, ran-huang commented on releases/release-6.6.0.md
> +| DM   | 新增    |    https://github.com/pingcap/docs-cn/pull/12296       |    **tw@ran-huang**      |
```suggestion
| DM | 修改 | [`import-mode`](/dm/task-configuration-file-full.md)  | 该配置项的可选值由 `"sql"` 和 `"loader"` 变更为 `"logical"` 和 `"physical"`。默认值为 `"logical"`，即使用 TiDB Lightning 的 logical import mode 进行导入。 |
| DM | 删除 | `on-duplicate` | 该配置项控制全量导入阶段针对冲突数据的解决方式。自 v6.6.0 起，引入新的配置项 `on-duplicate-logical` 和 `on-duplicate-physical`，取代 `on-duplicate`。 |
| DM | 新增 | [`on-duplicate-logical`](/dm/task-configuration-file-full.md) | 该配置项控制 logical import 针对冲突数据的解决方式。默认值为 `"replace"`，表示用最新数据替代已有数据。 |
| DM | 新增 | [`on-duplicate-physical`](/dm/task-configuration-file-full.md) | 该配置项控制 physical import 针对冲突数据的解决方式。默认值为 `"none"`，表示遇到冲突数据时不进行处理。该模式性能最佳，但下游数据库会遇到数据索引不一致的问题。  |
| DM | 新增 | [`sorting-dir-physical`](/dm/task-configuration-file-full.md) | 该配置项控制 physical import 用作本地排序的目录位置，该选项的默认值与 `dir` 配置项一致。 |
| DM | 新增 | [`disk-quota-physical`](/dm/task-configuration-file-full.md) | 该配置项设置了磁盘的空间限制，对应 TiDB Lightning 的 [`disk-quota` 配置](/tidb-lightning/tidb-lightning-physical-import-mode-usage#磁盘资源配额-从-v620-版本开始引入)。|
| DM | 新增 | [`checksum-physical`](/dm/task-configuration-file-full.md) | 该配置项控制 physical import 在导入完成一张表后，对每一个表执行 `ADMIN CHECKSUM TABLE <table>` 进行数据校验。默认值为 `"required"`。表示导入完成后进行数据校验，如果校验失败会让任务暂停，需要用户手动处理。|
```

2023-02-07 08:11 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +* TiKV-CDC 工具 GA，支持订阅 RawKV 的数据变更 [#48](https://github.com/tikv/migration/issues/48) @[zeminzhou](https://github.com/zeminzhou) @[haojinming](https://github.com/haojinming) @[pingyu](https://github.c
This contributor [zeminzhou](https://github.com/zeminzhou) is missing in Chinese.

2023-02-07 08:22 UTC, qiancai commented on releases/release-6.6.0.md
> +    `SURVIVAL_PREFERENCES` 为数据提供了生存偏好设置，从而提高数据的容灾生存能力。通过指定 `SURVIVAL_PREFERENCE`，你可以：
```suggestion
    `SURVIVAL_PREFERENCES` 为数据提供了生存偏好设置，从而提高数据的容灾生存能力。通过指定 `SURVIVAL_PREFERENCE`，你可以控制：
```

2023-02-07 09:25 UTC, qiancai commented on releases/release-6.6.0.md
> +    在 v6.6.0 中，TiFlash 开始支持 Stale Read 功能。当使用 `AS OF TIMESTAMP` 语法或 `tidb_read_staleness` 系统变量等方式查询历史数据时，如果查询的表包含 TiFlash 副本，优化器可以选择 TiFlash 副本读取对应的数据，从而进一步提高查询性能。
```suggestion
    在 v6.6.0 中，TiFlash 开始支持 Stale Read 功能。当使用 [`AS OF TIMESTAMP`](/as-of-timestamp.md) 语法或 [`tidb_read_staleness`](/tidb-read-staleness.md) 系统变量等方式查询历史数据时，如果查询的表包含 TiFlash 副本，优化器可以选择 TiFlash 副本读取对应的数据，从而进一步提高查询性能。
```

2023-02-07 10:28 UTC, BornChanger commented on releases/release-6.6.0.md
> +| TiKV | [`resource_control.enabled`](/tikv-configuration-file.md#tidb_enable_resource_control-%E4%BB%8E-v660-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5) | 新增 | 是否支持按照资源组配额调度。 默认 `false`
change resource_control to resource-control

2023-02-07 10:30 UTC, BornChanger commented on releases/release-6.6.0.md
> +    在 v6.6 中， 启用资源管控技术需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-%E4%BB%8E-v660-%E7%89%88%E6%9C%AC%E5%BC%80%E5%A7%8B%E5%BC%95%E5%85%A5) 及 TiK
change resource_control to resource-control

2023-02-07 11:26 UTC, TomShawn commented on releases/release-6.6.0.md
> +| [`tidb_enable_concurrent_ddl`](/system-variables.md#tidb_enable_concurrent_ddl-从-v620-版本开始引入) | 删除 | 这个变量用于控制是否让 TiDB 使用并发 DDL 语句。自 v6.6.0 起，该变量被删除。 |
```suggestion
| [`tidb_enable_concurrent_ddl`](/system-variables.md#tidb_enable_concurrent_ddl-从-v620-版本开始引入) | 删除 | 这个变量用于控制是否让 TiDB 使用并发 DDL 语句。自 v6.6.0 起，该变量被删除，表示不再使用非并发的 DDL 语句。 |
```

2023-02-08 01:19 UTC, hfxsd commented on releases/release-6.6.0.md
> +| TiKV | [`resource-control.enabled`](/tikv-configuration-file.md#resource-control-从-v660-版本开始引入) | 新增 | 控制是否支持对用户前台的读写请求按照对应的资源组配额做优先级调度。默认为 `false`，即关闭按照资源组配额调度。 |
```suggestion
| TiKV | [`resource-control.enabled`](/tikv-configuration-file.md#resource-control) | 新增 | 控制是否支持对用户前台的读写请求按照对应的资源组配额做优先级调度。默认为 `false`，即关闭按照资源组配额调度。 |
```

2023-02-08 01:33 UTC, qiancai commented on releases/release-6.6.0.md
> +| [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-从-v660-版本开始引入) | 新增  | 该变量是资源管控特性的开关。该变量设置为 `ON` 后，集群支持应用按照资源组做资源隔离。 |
```suggestion
| [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-从-v660-版本开始引入) | 新增  | 该变量是[资源管控特性](/tidb-resource-control.md)的开关。默认值为 `OFF`。该变量设置为 `ON` 后，集群支持应用按照资源组做资源隔离。 |
```

2023-02-08 01:33 UTC, qiancai commented on releases/release-6.6.0.md
> +    在 v6.6.0 中，启用资源管控特性需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-从-v660-版本开始引入) 及 TiKV 的配置项 [`resource_control.enabled`](/tikv-configuration
```suggestion
    在 v6.6.0 中，启用资源管控特性需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-从-v660-版本开始引入) 及 TiKV 的配置项 [`resource_control.enabled`](/tikv-configuration-file.md#resource-control)。当前支持的限额方式基于 "[用量](/tidb-resource-control.md#什么是-request-unit-ru)"（Request Unit，即 RU），RU 是 TiDB 对 CPU、IO 等系统资源的统一抽象单位。
```

2023-02-08 02:54 UTC, TomShawn commented on releases/release-6.6.0.md
> +
已加入 PR

2023-02-08 02:57 UTC, okJiang commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本之前 TiDB Lightning 仅支持通过 AWS IAM 角色的密钥访问 S3 的数据，无法结合会话令牌访问 S3 的数据。自 v6.6.0 起，TiDB Lightning 支持通过 AWS IAM 角色的密钥以及会话令牌来访问 S3 数据，以提高安全性。
```suggestion
* TiDB Lightning 支持通过 AWS IAM 角色的密钥以及会话令牌来访问 S3 数据 @[okJiang](https://github.com/okJiang)

    在 v6.6.0 版本之前 TiDB Lightning 仅支持通过 AWS IAM 用户的密钥访问 S3 的数据，无法使用临时会话令牌访问 S3 的数据。自 v6.6.0 起，TiDB Lightning 支持通过 AWS IAM 角色的密钥以及会话令牌来访问 S3 数据，以提高安全性。
```

2023-02-08 02:58 UTC, okJiang commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本之前 TiDB Lightning 仅支持通过 AWS IAM 角色的密钥访问 S3 的数据，无法结合会话令牌访问 S3 的数据。自 v6.6.0 起，TiDB Lightning 支持通过 AWS IAM 角色的密钥以及会话令牌来访问 S3 数据，以提高安全性。
用户和角色在 IAM 中是两个概念

2023-02-08 03:03 UTC, gozssky commented on releases/release-6.6.0.md
> +
是发送 KV Pairs 时启用压缩，不是直接压缩 KV Pairs。

2023-02-08 03:40 UTC, Frank945946 commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本之前 TiDB Lightning 仅支持通过 AWS IAM 角色的密钥访问 S3 的数据，无法结合会话令牌访问 S3 的数据。自 v6.6.0 起，TiDB Lightning 支持通过 AWS IAM 角色的密钥以及会话令牌来访问 S3 数据，以提高安全性。
好的，了解了。

2023-02-08 03:59 UTC, Frank945946 commented on releases/release-6.6.0.md
> +
ok，那就改成如下描述：
TiDB Lightning 向 TiKV 传输 KV Pairs 时支持启用压缩传输，减少数据在网络传输中的体积，降低网络带宽开销 @[gozssky](https://github.com/gozssky)

    自 v6.6.0 版本起，TiDB Lightning 节点本地编码排序后的 KV Paris 传输到 TiKV 时支持开启压缩传输，降低网络带宽要求，减少传输的流量开销。而原先的版本不支持，在数据量较大的情况下，对网络带宽要求相对较高，且会产生较高的流量费，通过该 Feature ，用户在传输 Kv Pairs 到 TiKV 时，可以设置基于 Gzip 算法进行压缩传输，降低传输的流量费用。

2023-02-08 04:36 UTC, gozssky commented on releases/release-6.6.0.md
> +
LGTM.

2023-02-08 06:15 UTC, TomShawn commented on releases/release-6.6.0.md
> +    自 v6.6.0 版本起，TiDB Lightning 支持将 TiDB Lightning 节点本地编码排序后的 KV Paris 压缩后再发送到 TiKV，降低网络带宽要求，减少传输的流量。而原先的版本不支持，在数据量较大的情况下，对网络带宽要求相对较高，且会产生较高的流量费，通过该 Feature ，用户可以设置将这些 Kv Pairs 压缩为 Gzip 后再发送到 TiKV，降低
```suggestion
* TiDB Lightning 向 TiKV 传输键值对时支持启用压缩传输，减少数据在网络传输中的体积，降低网络带宽开销 @[gozssky](https://github.com/gozssky)

    自 v6.6.0 版本起，TiDB Lightning 节点将在本地编码排序后的键值对传输到 TiKV 时，支持开启压缩传输，降低网络带宽要求，减少传输的流量开销。而此前的版本不支持压缩传输，在数据量较大的情况下，对网络带宽要求相对较高，且会产生较高的流量费。自 v6.6.0 起，TiDB Lightning 在传输键值对到 TiKV 时，用户可以设置基于 Gzip 算法进行压缩传输，降低传输的流量费用。
```

2023-02-08 06:21 UTC, gozssky approved these changes

2023-02-08 06:24 UTC, okJiang approved these changes

2023-02-08 09:17 UTC, Leavrth commented on releases/release-6.6.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
        - 支持在恢复日志备份文件前分裂和分散 Region [#37207](https://github.com/pingcap/tidb/issues/37207) @[Leavrth](https://github.com/Leavrth)
```

2023-02-08 10:06 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    TiDB v6.6.0 移除了执行计划缓存的限制，带有变量的 `LIMIT` 子句可以进入执行计划缓存，如 `Limit ?` 或者 `Limit 10, ?`。这使得更多的 SQL 能够从计划缓存中获益，提升执行效率。
```suggestion
    TiDB v6.6.0 移除了执行计划缓存的限制，带有变量的 `LIMIT` 子句可以进入执行计划缓存，如 `LIMIT ?` 或者 `LIMIT 10, ?`。这使得更多的 SQL 能够从计划缓存中获益，提升执行效率。
```

2023-02-08 10:07 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    TiDB v6.6.0 移除了执行计划缓存的限制，带有变量的 `LIMIT` 子句可以进入执行计划缓存，如 `Limit ?` 或者 `Limit 10, ?`。这使得更多的 SQL 能够从计划缓存中获益，提升执行效率。
@shichun-0415 PTAL

2023-02-08 11:18 UTC, TomShawn commented on releases/release-6.6.0.md
> +* TiDB Data Migration(DM) 集成了 TiDB Lightning 的 Physical Import Mode，全量迁移性能提升最高达到 10 倍 @[lance6716](https://github.com/lance6716) **tw@ran-huang**
```suggestion
* TiDB Data Migration(DM) 集成了 TiDB Lightning 的 Physical Import Mode，全量迁移性能提升最高达到 10 倍（实验特性）@[lance6716](https://github.com/lance6716) **tw@ran-huang**
```

2023-02-08 11:18 UTC, TomShawn commented on releases/release-6.6.0.md
> +- TiDB Data Migration (DM) 集成 TiDB Lightning 的 Physical Import 模式，提升 DM 全量数据迁移时的性能，大幅缩短大数据量场景下的迁移时间。
```suggestion
- TiDB Data Migration (DM) 集成 TiDB Lightning 的 Physical Import 模式，提升 DM 全量数据迁移时的性能，大幅缩短大数据量场景下的迁移时间（实验特性）。
```

2023-02-08 12:01 UTC, Frank945946 commented on releases/release-6.6.0.md
> +    自 v6.6.0 起，TiDB Lightning 支持将 TiDB Lightning 节点本地编码排序后的键值对压缩后再发送到 TiKV，降低网络带宽要求，减少传输的流量。之前版本不支持该功能，在数据量较大的情况下，对网络带宽要求相对较高，且会产生较高的流量费。通过使用该功能，用户可以设置将这些键值对压缩为 Gzip 后再发送到 TiKV，降低传输的流量。
@qiancai “节点本地编码排序后的键值对压缩为 Gzip 后再发送到 TiKV”，这里不对，需要改成“节点本地编码排序后的键值对在网络传输时进行压缩并发送到 tivk ”这里是支持传输过程中基于 gzip 算法进行压缩传输，而不是压缩好的文件再传输。

2023-02-08 12:18 UTC, Frank945946 commented on releases/release-6.6.0.md
> +
* TiDB TiDB Lightning 新增配置文件参数 "header-schema-match"，用于处理源文件里的列名和目标表的列名不匹配的异常。 @[dsdashun](https://github.com/dsdashun) 

    在 v6.6.0 版本中，TiDB TiDB Lightning 新增配置文件参数 "header-schema-match"，默认取值为 true，表示源 csv 文件第一行有表的列名信息，且和目标表列名保持一致；取值为 false，表示不一致，在历史版本里这个场景会导致导入报错，在 v6.6.0 版本中，将该参数设置为 false 后，在源文件的列顺序和目标表列顺序是一致的前提下，是可以忽略该报错，并继续导入数据。
    更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12963)。

2023-02-08 13:58 UTC, hfxsd commented on releases/release-6.6.0.md
> +    在 v6.6.0 中，启用资源管控特性需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-从-v660-版本开始引入) 及 TiKV 的配置项 [`resource_control.enabled`](/tikv-configuration
```suggestion
    在 v6.6.0 中，启用资源管控特性需要同时打开 TiDB 的全局变量 [`tidb_enable_resource_control`](/system-variables.md#tidb_enable_resource_control-从-v660-版本开始引入) 及 TiKV 的配置项 [`resource-control.enabled`](/tikv-configuration-file.md#resource-control)。当前支持的限额方式基于 "[用量](/tidb-resource-control.md#什么是-request-unit-ru)"（Request Unit，即 RU），RU 是 TiDB 对 CPU、IO 等系统资源的统一抽象单位。
```

2023-02-08 14:09 UTC, hfxsd commented on releases/release-6.6.0.md
> +    Witness 功能可用于快速恢复 (failover)，以提高系统的可用性和数据持久性。例如在 3 缺 1 的情况下，虽然满足多数派要求，但是系统很脆弱，而完整恢复一个新成员的时间通常很长（需要先拷贝 snapshot 然后 apply 最新的日志），特别是 Region snapshot 比较大时，恢复的时间会更长。而且，拷贝副本的过程可能会对不健康的 Group member 造成
优化了下内容。“又一个节点“有一个节点”吗？或者改成 “又有其他节点”
```suggestion
    Witness 功能可用于快速恢复 (failover)，以提高系统的可用性和数据持久性。例如在 3 缺 1 的情况下，存在以下问题：
    
    - 虽然满足多数派要求，但是系统很脆弱。
    - 完整恢复一个新成员耗时长，需要先拷贝 snapshot 然后 apply 最新的日志。
    - 在 Region snapshot 比较大时，恢复时间会更长。
    - 拷贝副本的过程可能会对不健康的 Group member 造成更多的压力。
    
    为解决这些问题，可以先添加一个 Witness 快速移除不健康的节点，降低在恢复新成员过程中（此时 Learner 无法参与选举和提交），又有其他节点出故障导致 Raft Group 不可用的风险，从而保证恢复数据过程中日志的安全性。
```

2023-02-08 14:13 UTC, hfxsd commented on releases/release-6.6.0.md
> +* TiDB Data Migration(DM) 集成了 TiDB Lightning 的 Physical Import Mode，全量迁移性能提升最高达到 10 倍（实验特性）@[lance6716](https://github.com/lance6716) **tw@ran-huang**
```suggestion
* TiDB Data Migration (DM) 集成了 TiDB Lightning 的 Physical Import Mode，全量迁移性能提升最高达到 10 倍（实验特性）@[lance6716](https://github.com/lance6716) **tw@ran-huang**
```

2023-02-08 14:17 UTC, hfxsd commented on releases/release-6.6.0.md
> +    在 v6.6.0 之前，TiDB Lightning 仅支持通过 AWS IAM **用户的密钥**访问 S3 的数据，无法使用临时会话令牌访问 S3 的数据。自 v6.6.0 起，TiDB Lightning 支持通过 AWS IAM **角色的密钥 + 会话令牌**来访问 S3 数据，以提高安全性。
```suggestion
    在 v6.6.0 之前，TiDB Lightning 仅支持通过 AWS IAM **用户密钥**访问 S3 的数据，无法使用临时会话令牌。自 v6.6.0 起，TiDB Lightning 支持通过 AWS IAM **角色密钥 + 会话令牌**的方式来访问 S3 数据，以提高安全性。
```

2023-02-08 14:18 UTC, hfxsd commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12947)。
链接待更新

2023-02-09 02:54 UTC, TomShawn commented on releases/release-6.6.0.md
> +
```suggestion

* 支持兼容 MySQL 语法的多值索引 [#39592](https://github.com/pingcap/tidb/issues/39592) @[xiongjiwei](https://github.com/xiongjiwei) @[qw4990](https://github.com/qw4990) **tw@TomShawn**

    更多信息，请参考 v6.6.0 Release Notes 中 [SQL 部分](#sql)以及用户文档](/sql-statements/sql-statement-create-index.md#多值索引)。

```

2023-02-09 03:00 UTC, hnes commented on releases/release-6.6.0.md
> +| PD  | [`pd-server.server-memory-limit`](/pd-configuration-file.md#server-memory-limit-从-v660-版本开始引入) | 新增 | PD 实例的内存限制。默认值为 `0.8`，即限制 PD 实例的内存占总内存的 80%。 |
```suggestion
| PD  | [`pd-server.server-memory-limit`](/pd-configuration-file.md#server-memory-limit-从-v660-版本开始引入) | 新增 | PD 实例的内存限制。默认关闭。 |
```

2023-02-09 03:00 UTC, hnes commented on releases/release-6.6.0.md
> +| PD  | [`pd-server.enable-gogc-tuner`](/pd-configuration-file.md#enable-gogc-tuner-从-v660-版本开始引入) | 新增 | 控制是否开启 GOGC Tuner。默认开启。 |
```suggestion
| PD  | [`pd-server.enable-gogc-tuner`](/pd-configuration-file.md#enable-gogc-tuner-从-v660-版本开始引入) | 新增 | 控制是否开启 GOGC Tuner。默认关闭。 |
```

2023-02-09 03:58 UTC, qiancai commented on releases/release-6.6.0.md
> +    自 v6.6.0 起，TiDB Lightning 支持将 TiDB Lightning 节点本地编码排序后的键值对压缩后再发送到 TiKV，降低网络带宽要求，减少传输的流量。之前版本不支持该功能，在数据量较大的情况下，对网络带宽要求相对较高，且会产生较高的流量费。通过使用该功能，用户可以设置将这些键值对压缩为 Gzip 后再发送到 TiKV，降低传输的流量。
哦哦，看到这里原文里写的 “将 TiDB Lightning 节点本地编码排序后的键值对压缩后再发送到 TiKV”，我就误解了

2023-02-09 04:02 UTC, qiancai commented on releases/release-6.6.0.md
> +    自 v6.6.0 起，TiDB Lightning 支持将 TiDB Lightning 节点本地编码排序后的键值对压缩后再发送到 TiKV，降低网络带宽要求，减少传输的流量。之前版本不支持该功能，在数据量较大的情况下，对网络带宽要求相对较高，且会产生较高的流量费。通过使用该功能，用户可以设置将这些键值对压缩为 Gzip 后再发送到 TiKV，降低传输的流量。
修改了，PTAL

2023-02-09 04:31 UTC, Frank945946 commented on releases/release-6.6.0.md
> +    自 v6.6.0 起，TiDB Lightning 支持将 TiDB Lightning 节点本地编码排序后的键值对压缩后再发送到 TiKV，降低网络带宽要求，减少传输的流量。之前版本不支持该功能，在数据量较大的情况下，对网络带宽要求相对较高，且会产生较高的流量费。通过使用该功能，用户可以设置将这些键值对压缩为 Gzip 后再发送到 TiKV，降低传输的流量。
LGTM

2023-02-09 05:56 UTC, Frank945946 approved these changes

2023-02-09 06:03 UTC, TomShawn commented on releases/release-6.6.0.md
> +
```suggestion
```

2023-02-09 06:04 UTC, TomShawn commented on releases/release-6.6.0.md
> +    - 增加 GC Tuner 功能以缓解 GC 压力 [#5827](https://github.com/tikv/pd/issues/5827) @[hnes](https://github.com/hnes)
```suggestion
    - 增加全局内存阈值管理功能以缓解 OOM 问题（实验特性）[#5827](https://github.com/tikv/pd/issues/5827) @[hnes](https://github.com/hnes)
    - 增加 GC Tuner 功能以缓解 GC 压力（实验特性）[#5827](https://github.com/tikv/pd/issues/5827) @[hnes](https://github.com/hnes)
```

2023-02-09 08:54 UTC, xuyifangreeneyes commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复了收集统计信息任务因为 incorrect datetime value 而失败的问题 [#39336](https://github.com/pingcap/tidb/issues/39336) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
    - 修复了 stats meta 没有创建的问题 [#38189](https://github.com/pingcap/tidb/issues/38189) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
```

2023-02-09 09:54 UTC, hfxsd commented on releases/release-6.6.0.md
> +
```suggestion

* TiDB Lightning 新增配置文件参数 "header-schema-match"，用于处理源文件里的列名和目标表的列名不匹配的异常。 @[dsdashun](https://github.com/dsdashun)

    在 v6.6.0 版本中，TiDB Lightning 新增配置文件参数 "header-schema-match"，默认取值为 `true`，表示源 CSV 文件第一行有表的列名信息，且和目标表列名保持一致；取值为 `false` 则表示不一致，在历史版本里这个场景会导致导入报错，在 v6.6.0 版本中，将该参数设置为 `false` 后，在源文件的列顺序和目标表列顺序一致的前提下，可以忽略该报错，继续导入数据。

    更多信息，请参考 [TiDB Lightning 任务配置](tidb-lightning/tidb-lightning-configuration.md#tidb-lightning-任务配置)。

```

2023-02-09 09:56 UTC, hfxsd commented on releases/release-6.6.0.md
> +* TiDB Lightning 新增配置文件参数 "header-schema-match"，用于处理源文件里的列名和目标表的列名不匹配的异常。 @[dsdashun](https://github.com/dsdashun)
```suggestion
* TiDB Lightning 新增配置文件参数 "header-schema-match" 用于解决源文件里的列名和目标表的列名不匹配的问题 @[dsdashun](https://github.com/dsdashun)
```

2023-02-09 09:57 UTC, qiancai commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12947)。
```suggestion
    更多信息，请参考[用户文档](/tidb-lightning/tidb-lightning-data-source.md#从-amazon-s3-导入数据)。
```

2023-02-09 10:20 UTC, hfxsd commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本中，TiDB Lightning 新增配置文件参数 "header-schema-match"，默认取值为 `true`，表示源 CSV 文件第一行有表的列名信息，且和目标表列名保持一致；取值为 `false` 则表示不一致，在历史版本里这个场景会导致导入报错，在 v6.6.0 版本中，将该参数设置为 `false` 后，在源文件的列顺序和目标表列顺序一致的前提下，
"在源文件的列顺序和目标表列顺序一致的前提下" 这句话是不是可以删掉啊？能确认下吗？@dsdashun @frank945946

2023-02-09 10:41 UTC, qiancai commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](https://github.com/pingcap/docs-cn/pull/12948)。
```suggestion
    更多信息，请参考[用户文档](/tidb-lightning/tidb-lightning-configuration.md#tidb-lightning-任务配置)。
```

2023-02-09 11:09 UTC, dsdashun commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本中，TiDB Lightning 新增配置文件参数 "header-schema-match"，默认取值为 `true`，表示源 CSV 文件第一行有表的列名信息，且和目标表列名保持一致；取值为 `false` 则表示不一致，在历史版本里这个场景会导致导入报错，在 v6.6.0 版本中，将该参数设置为 `false` 后，在源文件的列顺序和目标表列顺序一致的前提下，
这里的意思是，如果设置为 false 之后，忽略列名不能匹配的错误，继续进行导入。这时，按照目标表列的顺序来导入 CSV 的每一列数据。这种场景下，如果 CSV 的列顺序和目标表的顺序是一致的，那么肯定没有问题。如果不一致的话，可能导入任务不会报错，但是导入的数据由于列类型不匹配，最终导入的数据会出现偏差。

2023-02-09 11:10 UTC, dsdashun commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本中，TiDB Lightning 新增配置文件参数 "header-schema-match"，默认取值为 `true`，表示源 CSV 文件第一行有表的列名信息，且和目标表列名保持一致；取值为 `false` 则表示不一致，在历史版本里这个场景会导致导入报错，在 v6.6.0 版本中，将该参数设置为 `false` 后，在源文件的列顺序和目标表列顺序一致的前提下，
这种情况下，就和导入一个不带表头的 CSV 文件，但是 CSV 文件列的顺序和目标表是不一致的，有同样的问题

2023-02-09 11:35 UTC, TomShawn commented on releases/release-6.6.0.md
> +- 引入 MySQL 兼容的多值索引，增强 JSON 类型，提升 TiDB 对 MySQL 8.0 的兼容性（实验特性）。
sss

2023-02-09 11:36 UTC, TomShawn commented on releases/release-6.6.0.md
> +- 引入 MySQL 兼容的多值索引，增强 JSON 类型，提升 TiDB 对 MySQL 8.0 的兼容性（实验特性）。
```suggestion
- 引入 MySQL 兼容的多值索引，增强 JSON 类型，提升 TiDB 对 MySQL 8.0 的兼容性（实验特性）。  
```

2023-02-09 11:36 UTC, yiwen92 reviewed
Highlight update

2023-02-10 01:24 UTC, hfxsd commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本中，TiDB Lightning 新增配置文件参数 "header-schema-match"，默认取值为 `true`，表示源 CSV 文件第一行有表的列名信息，且和目标表列名保持一致；取值为 `false` 则表示不一致，在历史版本里这个场景会导致导入报错，在 v6.6.0 版本中，将该参数设置为 `false` 后，在源文件的列顺序和目标表列顺序一致的前提下，
```suggestion
    在 v6.6.0 版本中，TiDB Lightning 新增配置文件参数 "header-schema-match"，默认取值为 `true`，表示源 CSV 文件第一行有表的列名信息，且和目标表列名保持一致。如果 CSV 表头中的字段名和目标表的列名不匹配（例如，一些 CSV 表头中的字段名在目标表中可能找不到对应的同名列）但列的顺序是一致的，此时可以将该配置设置为 false，TiDB Lightning 将忽略该报错，继续导入数据。
```

2023-02-10 01:25 UTC, hfxsd commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本中，TiDB Lightning 新增配置文件参数 "header-schema-match"，默认取值为 `true`，表示源 CSV 文件第一行有表的列名信息，且和目标表列名保持一致；取值为 `false` 则表示不一致，在历史版本里这个场景会导致导入报错，在 v6.6.0 版本中，将该参数设置为 `false` 后，在源文件的列顺序和目标表列顺序一致的前提下，
改成下面这样呢，麻烦再看下 @dsdashun

2023-02-10 02:53 UTC, flowbehappy commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复查询 TiFlash 相关的系统表可能会卡住的 [#6745](https://github.com/pingcap/tiflash/pull/6745) @[lidezhu](https://github.com/lidezhu)
```

2023-02-10 02:58 UTC, flowbehappy commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 减少 TiFlash 在没有查询的情况下的内存使用，最高减少 30% [#6589](https://github.com/pingcap/tiflash/pull/6589) @[hongyunyan](https://github.com/hongyunyan)
```

2023-02-10 02:59 UTC, flowbehappy commented on releases/release-6.6.0.md
> +    - 修复查询 TiFlash 相关的系统表可能会卡住的 [#6745](https://github.com/pingcap/tiflash/pull/6745) @[lidezhu](https://github.com/lidezhu)
```suggestion
    - 修复查询 TiFlash 相关的系统表可能会卡住的问题 [#6745](https://github.com/pingcap/tiflash/pull/6745) @[lidezhu](https://github.com/lidezhu)
```

2023-02-10 03:42 UTC, BornChanger commented on releases/release-6.6.0.md
> +- 支持基于资源组的资源管控，将不用的数据库用户映射到对应的资源组中，根据实际需要设置每个资源组的配额（实验特性）。
```suggestion
- 支持基于资源组的资源管控，将不同的数据库用户映射到对应的资源组中，根据实际需要设置每个资源组的配额（实验特性）。
```

2023-02-10 03:48 UTC, TomShawn commented on releases/release-6.6.0.md
> +| [`tidb_enable_foreign_key`](/system-variables.md#tidb_enable_foreign_key-从-v630-版本开始引入) | 修改 | 用于控制是否开启外键功能。默认值由 `OFF` 修改为 `ON`，表示默认开启外键功能。|
```suggestion
| [`tidb_enable_foreign_key`](/system-variables.md#tidb_enable_foreign_key-从-v630-版本开始引入) | 修改 | 用于控制是否开启外键功能。默认值由 `OFF` 修改为 `ON`，表示默认开启外键功能。|
| `tidb_enable_general_plan_cache`  |  修改  |   这个变量用来控制是否开启 General Plan Cache。自 v6.6.0 起，该变量更名为 [`tidb_enable_non_prepared_plan_cache`](/system-variables.md#tidb_enable_non_prepared_plan_cache)。 |
|  `tidb_general_plan_cache_size`  |  修改   |   这个变量用来控制 General Plan Cache 最多能够缓存的计划数量。自 v6.6.0 起，该变量更名为 [`tidb_non_prepared_plan_cache_size`](/system-variables.md#tidb_non_prepared_plan_cache_size)。 |

2023-02-10 05:59 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| TiKV  |  `enable-statistics`  |  删除   |  该配置项指定是否开启 RocksDB 的统计信息收集功能。从 v6.6.0 起，删除该配置项。所有集群默认开启统计信息收集，以便于故障排查。详情参见 [tikv/tikv#13942](https://github.com/tikv/tikv/pull/13942)。  |
```suggestion
| TiKV  |  `enable-statistics`  |  删除   |  该配置项指定是否开启 RocksDB 的统计信息收集功能。从 v6.6.0 起，删除该配置项。所有集群默认开启统计信息收集，以便于故障排查。详情参见 [#13942](https://github.com/tikv/tikv/pull/13942)。  |
```

2023-02-10 05:59 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| DM | 新增 | [`checksum-physical`](/dm/task-configuration-file-full.md) | 该配置项控制 physical import 在导入完成一张表后，对每一个表执行 `ADMIN CHECKSUM TABLE <table>` 进行数据校验。默认值为 `"required"`。表示导入完成后进行数据校验，如果校验失败会让任务暂停，需要
```suggestion
| DM | `on-duplicate` | 删除 | 该配置项控制全量导入阶段针对冲突数据的解决方式。自 v6.6.0 起，引入新的配置项 `on-duplicate-logical` 和 `on-duplicate-physical`，取代 `on-duplicate`。 |
| DM | [`import-mode`](/dm/task-configuration-file-full.md) | 修改 | 该配置项的可选值由 `"sql"` 和 `"loader"` 变更为 `"logical"` 和 `"physical"`。默认值为 `"logical"`，即使用 TiDB Lightning 的 logical import mode 进行导入。 |
| DM | [`checksum-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 physical import 在导入完成一张表后，对每一个表执行 `ADMIN CHECKSUM TABLE <table>` 进行数据校验。默认值为 `"required"`。表示导入完成后进行数据校验，如果校验失败会让任务暂停，需要用户手动处理。|
| DM | [`disk-quota-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项设置了磁盘的空间限制，对应 TiDB Lightning 的 [`disk-quota` 配置](/tidb-lightning/tidb-lightning-physical-import-mode-usage#磁盘资源配额-从-v620-版本开始引入)。|
| DM | [`on-duplicate-logical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 logical import 针对冲突数据的解决方式。默认值为 `"replace"`，表示用最新数据替代已有数据。 |
| DM | [`on-duplicate-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 physical import 针对冲突数据的解决方式。默认值为 `"none"`，表示遇到冲突数据时不进行处理。该模式性能最佳，但下游数据库会遇到数据索引不一致的问题。  |
| DM | [`sorting-dir-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 physical import 用作本地排序的目录位置，该选项的默认值与 `dir` 配置项一致。 |
```

2023-02-10 07:22 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +- 支持动态修改参数 `store-io-pool-size`，增加了 TiKV 性能调优的灵活性。
```suggestion
- 支持动态修改参数 [`store-io-pool-size`](/tikv-configuration-file.md#store-io-pool-size-从-v530-版本开始引入)，增加了 TiKV 性能调优的灵活性。
```

2023-02-10 07:22 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| PD  | [`pd-server.gc-tuner-threshold`](/pd-configuration-file.md#gc-tuner-threshold-从-v660-版本开始引入) | 新增 | GOGC Tuner 自动调节的最大内存阈值比例。默认值为 `0.6`。 |
```suggestion
| PD  | [`pd-server.enable-gogc-tuner`](/pd-configuration-file.md#enable-gogc-tuner-从-v660-版本开始引入) | 新增 | 控制是否开启 GOGC Tuner。默认关闭。 |
| PD  | [`pd-server.gc-tuner-threshold`](/pd-configuration-file.md#gc-tuner-threshold-从-v660-版本开始引入) | 新增 | GOGC Tuner 自动调节的最大内存阈值比例。默认值为 `0.6`。 |
| PD  | [`pd-server.server-memory-limit`](/pd-configuration-file.md#server-memory-limit-从-v660-版本开始引入) | 新增 | PD 实例的内存限制比例。`0` 表示不设内存限制。 |
| PD  |  [`pd-server.server-memory-limit-gc-trigger`](/pd-configuration-file.md#server-memory-limit-gc-trigger-从-v660-版本开始引入) | 新增 | PD 尝试触发 GC 的阈值比例。默认值为 `0.7`。 |
```

2023-02-10 07:22 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| TiDB | [`tidb_stmt_summary_file_max_backups`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_backups-从-v660-版本开始引入) | 新增 | 当开启了 statements summary 持久化时，该配置用于限制持久化数据文件最大数量，`0` 表示不限制，默认值为 `0`
```suggestion
| TiDB | [`tidb_stmt_summary_file_max_backups`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_backups-从-v660-版本开始引入) | 新增 | 当开启了 statements summary 持久化时，该配置用于限制持久化数据文件最大数量，`0` 表示不限制，默认值为 `0`。 |
| TiDB | [`tidb_stmt_summary_file_max_days`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_days-从-v660-版本开始引入) | 新增 | 当开启了 statements summary 持久化时，该配置用于指定持久化数据文件所保留的最大天数，默认为 3 天。 |
| TiDB | [`tidb_stmt_summary_file_max_size`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_size-从-v660-版本开始引入) | 新增 | 当开启了 statements summary 持久化时，该配置用于限制持久化数据单个文件的大小 (MiB)，默认值为 `64`。 |
| TiDB | [`tidb_stmt_summary_filename`](/tidb-configuration-file.md#tidb_stmt_summary_filename-从-v660-版本开始引入) | 新增 | 当开启了 statements summary 持久化时，该配置用于指定持久化数据所写入的文件名称，默认为 `tidb-statements.log`。 |
```

2023-02-10 07:22 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 新增选项 `learner`，指定 TiDB 从只读节点中读取数据的 learner 副本。  |
```suggestion
| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 新增选项 `learner`，指定 TiDB 从只读节点中读取数据的 learner 副本。 |
| [`tidb_replica_read`](/system-variables.md#tidb_replica_read-从-v40-版本开始引入) | 修改 | 新增选项 `prefer-leader`，以提高 TiDB 集群整体的读可用性。该选项被启用时，TiDB 会优先选择 Leader 副本进行读取操作；当 Leader 副本的处理性能显著下降时，TiDB 会自动将读操作转发给 Follower 副本。|
```

2023-02-10 10:07 UTC, lcwangchao commented on releases/release-6.6.0.md
> +
```suggestion
    - 改进了 TTL 后台清理任务的调度机制。允许将单个表的清理任务拆分成若干子任务并调度到多个 TiDB 节点同时运行。 [#40361](https://github.com/pingcap/tidb/issues/40361) @[YangKeao](https://github.com/YangKeao)
    - 优化了在设置了非默认的 delimiter 后运行 multi-statement 返回结果的列名的显示 [#39662](https://github.com/pingcap/tidb/issues/39662) @[mjonss](https://github.com/mjonss)
    - 优化了生成警告信息时的执行效率 [#39702](https://github.com/pingcap/tidb/issues/39702) @[tiancaiamao](https://github.com/tiancaiamao)
    - 为 ADD INDEX 支持分布式数据回填 (实验特性) [#37119](https://github.com/pingcap/tidb/issues/37119) @[zimulala](https://github.com/zimulala)
    - 允许使用 CURDATE() 作为列的默认值 [#38356](https://github.com/pingcap/tidb/issues/38356) @[CbcWestwolf](https://github.com/CbcWestwolf)
```

2023-02-10 10:07 UTC, lcwangchao commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 优化了删除分区表所依赖的列时的错误提示 [#38739](https://github.com/pingcap/tidb/issues/38739) @[jiyfhust](https://github.com/jiyfhust)
    - 修复了 DDL 回填数据时频繁发生的事务写冲突问题 [#24427](https://github.com/pingcap/tidb/issues/24427) @[mjonss](https://github.com/mjonss)
    - 增加了 FLASHBACK CLUSTER 在检查 `min-resolved-ts` 失败后的重试机制 [#39836](https://github.com/pingcap/tidb/issues/39836) @[Defined2014](https://github.com/Defined2014)
    - 修复了部分情况下空表不能使用 ingest 模式添加索引的问题 [#39641](https://github.com/pingcap/tidb/issues/39641) @[tangenta](https://github.com/tangenta)
    - 修复了同一个事务中不同 SQL 的慢日志 `wait_ts` 相同的问题 [#39713](https://github.com/pingcap/tidb/issues/39713) @[TonsnakeLin](https://github.com/TonsnakeLin)
    - 修复了添加列的过程中删除行记录报 "Assertion Failed" 错误的问题 [#39570](https://github.com/pingcap/tidb/issues/39570) @[wjhuang2016](https://github.com/wjhuang2016)
    - 修复了修改列类型时报 "not a DDL owner" 错误的问题 [#39643](https://github.com/pingcap/tidb/issues/39643) @[zimulala](https://github.com/zimulala)
    - 修复了 AUTO_INCREMENT 列自动分配值耗尽后插入一行不报错的问题 [#38950](https://github.com/pingcap/tidb/issues/38950) @[Dousir9](https://github.com/Dousir9)
    - 修复了创建表达式索引时报 "Unknown column" 错误的问题 [#39784](https://github.com/pingcap/tidb/issues/39784) @[Defined2014](https://github.com/Defined2014)
    - 修复了生成列表达式包含表名时，重命名表后无法插入数据的问题 [#39826](https://github.com/pingcap/tidb/issues/39826) @[Defined2014](https://github.com/Defined2014)
    - 修复了列在 write-only 状态下 INSERT IGNORE 语句无法正确填充默认值的问题 [#40192](https://github.com/pingcap/tidb/issues/40192) @[YangKeao](https://github.com/YangKeao)
    - 修复了资源管控模块关闭时未能释放资源的问题 [#40546](https://github.com/pingcap/tidb/issues/40546) @[zimulala](https://github.com/zimulala)
    - 不支持在分区表上执行 MODIFY COLUMN [#39915](https://github.com/pingcap/tidb/issues/39915) @[wjhuang2016](https://github.com/wjhuang2016)
    - 禁止重命名分区表所依赖的列 [#40150](https://github.com/pingcap/tidb/issues/40150) @[mjonss](https://github.com/mjonss)
    - 修复了 TTL 任务不能及时触发统计信息更新的问题 [#40109](https://github.com/pingcap/tidb/issues/40109) @[YangKeao](https://github.com/YangKeao)
    - 修复了 TiDB 构造 key 范围时对 null 值处理不当导致读到预期外数据的行为 [#40158](https://github.com/pingcap/tidb/issues/40158) @[tiancaiamao](https://github.com/tiancaiamao)
    - 修复了 MODIFY COLUMN 同时修改列默认值导致写入非法值的问题 [#40164](https://github.com/pingcap/tidb/issues/40164) @[wjhuang2016](https://github.com/wjhuang2016)
    - 修复了表 region 比较多时因 region 缓存失效导致加索引效率低下的问题 [#38436](https://github.com/pingcap/tidb/issues/38436) @[tangenta](https://github.com/tangenta)
    - 修复了分配自增 ID 时的数据竞争问题 [#40584](https://github.com/pingcap/tidb/issues/40584) @[Dousir9](https://github.com/Dousir9)
    - 修复了 JSON 的 not 表达式实现与 MySQL 实现不兼容的问题 [#40683](https://github.com/pingcap/tidb/issues/40683) @[YangKeao](https://github.com/YangKeao)
    - 修复了并发视图时可能会造成 DDL 操作卡住的问题 [#40352](https://github.com/pingcap/tidb/issues/40352) @[zeminzhou](https://github.com/zeminzhou)
    - 修复了并发对分区表执行 Modify Column 的 DDL 操作时有可能会造成数据不一致的问题 [#40620](https://github.com/pingcap/tidb/issues/40620) @[mjonss](https://github.com/mjonss)
    - 修复了使用 `caching_sha2_password` 方式进行认证时如果不指定的密码会报错 "Malformed packet" 的问题 [#40831](https://github.com/pingcap/tidb/issues/40831) @[dveeden](https://github.com/dveeden)
    - 修复了在执行 TTL 任务时，如果表的主键包含 `ENUM` 类型的列任务会失败的问题 [#40456](https://github.com/pingcap/tidb/issues/40456) @[lcwangchao](https://github.com/lcwangchao)
    - 修复了某些被 MDL 阻塞的 DDL 操作无法在 `mysql.tidb_mdl_view` 中查询到的问题 [#40838](https://github.com/pingcap/tidb/issues/40838) @[YangKeao](https://github.com/YangKeao)
    - 修复了 DDL 在 ingest 过程中可能会发生数据竞争的问题 [#40970](https://github.com/pingcap/tidb/issues/40970) @[tangenta](https://github.com/tangenta)
    - 修复了在改变时区后 TTL 任务可能会错误删除某些数据的问题 [41043](https://github.com/pingcap/tidb/issues/41043) @[lcwangchao](https://github.com/lcwangchao)
    - 修复了 `JSON_OBJECT` 在某些情况下会报错的问题 [#39997](https://github.com/pingcap/tidb/pull/39997) @[YangKeao](https://github.com/YangKeao)
    - 修复了 TiDB 在初始化时有可能死锁的问题 [#40408](https://github.com/pingcap/tidb/issues/40408) @[Defined2014](https://github.com/Defined2014)
    - 修复了内存重用导致的在某些情况下系统变量的值会被错误修改的问题 [#40979](https://github.com/pingcap/tidb/issues/40979) @[lcwangchao](https://github.com/lcwangchao)
    - 修复了 ingest 模式下创建唯一索引可能会导致数据和索引不一致的问题 [#40464](https://github.com/pingcap/tidb/issues/40464) @[tangenta](https://github.com/tangenta)
    - 修复了并发 truncate 同一张表时部分 truncate 操作无法被 MDL 阻塞的问题 [#40484](https://github.com/pingcap/tidb/issues/40484) @[wjhuang2016](https://github.com/wjhuang2016)
    - 修复了 `SHOW PRIVILEGES` 命令显示的权限列表不完整的问题 [#40591](https://github.com/pingcap/tidb/issues/40591) @[CbcWestwolf](https://github.com/CbcWestwolf)
    - 修复了在 ADD UNIQUE INDEX 时有可能会 PANIC 的问题 [#40592](https://github.com/pingcap/tidb/issues/40592) @[tangenta](https://github.com/tangenta)
    - 修复了 ADMIN RECOVER 操作可能会造成索引数据损坏的问题 [#40430](https://github.com/pingcap/tidb/issues/40430) @[xiongjiwei](https://github.com/xiongjiwei)
    - 修复了表达式索引中含有 CAST 时对表进行查询可能出错的问题 [#40129](https://github.com/pingcap/tidb/pull/40129) @[xiongjiwei](https://github.com/xiongjiwei)
    - 修复了某些情况下唯一索引仍然可能产生重复数据的问题 [#40217](https://github.com/pingcap/tidb/issues/40217) @[tangenta](https://github.com/tangenta)
    - 修复了使用 Prepare/Execute 查询某些虚拟表时无法将表 ID 下推导致在大量 Region 的情况下 PD OOM 的问题 [#39605](https://github.com/pingcap/tidb/issues/39605) @[djshow832](https://github.com/djshow832)
    - 修复了添加索引时可能导致数据竞争的问题 [#40879](https://github.com/pingcap/tidb/issues/40879) @[tangenta](https://github.com/tangenta)
```

2023-02-11 06:16 UTC, tonyxuqqi commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复cast const Enum 到其他类型时的错误 [#14156](https://github.com/tikv/tikv/issues/14156) @[wshwsh12] (https://github.com/wshwsh12)
    - 优化一些参数的默认值，当partitioned-raft-kv开启时block-cache调整为0.3可用内存(原来是0.45), region-split-size调整为10GB。当沿用raft-kv时且enable-region-bucket为true时，region-split-size默认调整为1GB [#12842](https://github.com/tikv/tikv/issues/12842) @[tonyxuqqi] (https://github.com/tonyxuqqi)
    - 减少resolve-ts带来的网络流量 [#14098] (https://github.com/tikv/tikv/issues/14092) @[overvenus] (https://github.com/overvenus)
    - 支持在Raftstore异步写入中的优先级调度[#13730] (https://github.com/tikv/tikv/issues/13730) @[Connor1996] (https://github.com/Connor1996)
    - 支持TiKV在小于1 core的CPU下启动 [#13586] [#13752] [#14017]  (https://github.com/tikv/tikv/issues/13586) @[andreid-db] (https://github.com/andreid-db)
    - 修改rocksdb.defaultcf.block-size以及rocksdb.writecf.block-size的默认参数为16KB [#14052] (https://github.com/tikv/tikv/issues/14052) @[tonyxuqqi] (https://github.com/tonyxuqqi)
    - copr: 修复old collation时Like中的 _ pattern的行为[#13785] (https://github.com/tikv/tikv/pull/13785) @[Yangkeao]  (https://github.com/Yangkeao)
    - txn: 在重复的acqurie_pessimsitic_lock请求时的做限制性检查。修复并发的DML时当TiDB和TiKV有网络故障时潜在的数据不一致。 [#14038] (https://github.com/tikv/tikv/issues/14038) @[myonkeminta] (https://github.com/myonkeminta)
    - raftstore: 优化slow score探测的新机制，加入新的`evict-slow-trend-scheduler`。[#14131] (https://github.com/tikv/tikv/issues/14131) @[innerr] (https://github.com/innerr)
    - rocksdb的block cache强制为共享的。不支持按照CF单独设置Block cache [#12936] (https://github.com/tikv/tikv/issues/12936) @[busyjay] (https://github.com/busyjay)
```

2023-02-11 06:17 UTC, tonyxuqqi commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
       - 修复cast const Enum 到其他类型时的错误 [#14156](https://github.com/tikv/tikv/issues/14156) @[wshwsh12] (https://github.com/wshwsh12)
    - 减少resolve-ts带来的网络流量 [#14098] (https://github.com/tikv/tikv/issues/14092) @[overvenus] (https://github.com/overvenus)
    - 支持TiKV在小于1 core的CPU下启动 [#13586] [#13752] [#14017]  (https://github.com/tikv/tikv/issues/13586) @[andreid-db] (https://github.com/andreid-db)
    - copr: 修复old collation时Like中的 _ pattern的行为[#13785] (https://github.com/tikv/tikv/pull/13785) @[Yangkeao]  (https://github.com/Yangkeao)
    - txn: 在重复的acqurie_pessimsitic_lock请求时的做限制性检查。修复并发的DML时当TiDB和TiKV有网络故障时潜在的数据不一致。 [#14038] (https://github.com/tikv/tikv/issues/14038) @[myonkeminta] (https://github.com/myonkeminta)
```

2023-02-13 02:17 UTC, qiancai commented on releases/release-6.6.0.md
> +| TiCDC | [`scheduler.region-per-span`](/ticdc/ticdc-changefeed-config.md#ticdc-changefeed-配置文件说明) | 新增 | 该配置项用于将表按 Region 个数划分成多个同步范围，这些范围可由多个 TiCDC 节点同步，默认值为 `50000`。 |
```suggestion
| TiCDC | [`scheduler.region-per-span`](/ticdc/ticdc-changefeed-config.md#ticdc-changefeed-配置文件说明) | 新增 | 该配置项用于将表按 Region 个数划分成多个同步范围，这些范围可由多个 TiCDC 节点同步，默认值为 `50000`。 |
| TiDB Lightning | [`compress-kv-pairs`](/tidb-lightning/tidb-lightning-configuration.md#tidb-lightning-任务配置) | 新增 | 该配置项控制 Physical Import Mode 向 TiKV 发送 KV 时是否启用压缩，默认值为空，代表不启用压缩。 |
```

2023-02-13 02:57 UTC, XuHuaiyu commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
- 修复了 IndexMerge 算子在触发内存限制行为时可能导致 tidb-server 崩溃的问题[#41036](https://github.com/pingcap/tidb/pull/41036) @[guo-shaoge](https://github.com/guo-shaoge)
- 修复了在分区表上执行查询 `select * from t limit 1` 时，执行速度慢的问题[#40741](https://github.com/pingcap/tidb/pull/40741)@[solotzg](https://github.com/solotzg)

2023-02-13 03:00 UTC, sticnarf commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复了过期的 region cache 可能残留导致的内存泄漏和性能下降问题 [#40461](https://github.com/pingcap/tidb/issues/40461) @[sticnarf](https://github.com/sticnarf)
```

2023-02-13 03:02 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +| DM | [`sorting-dir-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 physical import 用作本地排序的目录位置，该选项的默认值与 `dir` 配置项一致。 |
@ran-huang PTAL. Keep the name consistent with:

https://github.com/pingcap/docs-cn/blob/4488a29d65c3c9ad619c38fe0379fbe244194ed7/releases/release-6.6.0.md?plain=1#L228-L230

2023-02-13 03:36 UTC, XuHuaiyu commented on releases/release-6.6.0.md
> +
```suggestion
- 修复半连接在计算笛卡尔积时，使用内存过量的问题 [#issue](链接) @[贡献者 GitHub ID](链接)
```

2023-02-13 04:04 UTC, chrysan commented on releases/release-6.6.0.md
> +
- 增加了 partial order prop push down 对 LIST 类型的分区表的支持 [#40273](https://github.com/pingcap/tidb/issues/40273) @[winoros](https://github.com/winoros)
    - 增加了 hint 和 binding 冲突时的 warning 信息 [#40910](https://github.com/pingcap/tidb/issues/40910) @[Reminiscent](https://github.com/Reminiscent)

2023-02-13 04:05 UTC, chrysan commented on releases/release-6.6.0.md
> +
```suggestion
    - 增加了 partial order prop push down 对 LIST 类型的分区表的支持 [#40273](https://github.com/pingcap/tidb/issues/40273) @[winoros](https://github.com/winoros)
    - 增加了 hint 和 binding 冲突时的 warning 信息 [#40910](https://github.com/pingcap/tidb/issues/40910) @[Reminiscent](https://github.com/Reminiscent)
```

2023-02-13 04:25 UTC, chrysan commented on releases/release-6.6.0.md
> +
```suggestion
    - 修复了非法的 datetime 值导致 analyze 失败的问题 [#39336](https://github.com/pingcap/tidb/issues/39336) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
    - 修复了由 virtual column 引发的 can't find proper physical plan 问题 [#41014](https://github.com/pingcap/tidb/issues/41014) @[AilinKid](https://github.com/AilinKid)
   - 修复了当动态裁剪模式下的分区表有 global binding 时，TiDB 重启失败的问题 [#40368](https://github.com/pingcap/tidb/issues/40368) @[Yisaer](https://github.com/Yisaer)
   - 修复了 auto analyze 导致 graceful shutdown 耗时的问题 [#40038](https://github.com/pingcap/tidb/issues/40038) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
```

2023-02-13 05:31 UTC, 3pointer commented on releases/release-6.6.0.md
> +    在生产环境中，可能有部分只读操作定期消耗大量资源，对整个集群的性能产生影响，比如备份和大规模数据读取分析等。TiDB v6.6.0 支持配置只读存储节点，用来执行重度资源消耗的只读任务，避免对线上业务的影响。目前支持 TiDB、TiSpark 和 BR 读取只读节点上的数据。你可以按照[操作步骤](/readonly-nodes.md#操作步骤)配置只读存储节点，并通过 TiDB 系统变
```suggestion
    在生产环境中，可能有部分只读操作定期消耗大量资源，对整个集群的性能产生影响，比如备份和大规模数据读取分析等。TiDB v6.6.0 支持配置只读存储节点，用来执行重度资源消耗的只读任务，避免对线上业务的影响。目前支持 TiDB、TiSpark 和 BR 读取只读节点上的数据。你可以按照[操作步骤](/readonly-nodes.md#操作步骤)配置只读存储节点，并通过 TiDB 系统变量 `tidb_replica_read`、TiSpark 配置项 `spark.tispark.replica_read` 或 br 命令行参数 `--replica-read-label` 指定数据读取位置，以保证集群性能稳定。
```
cc @v01dstar

2023-02-13 05:44 UTC, Leavrth commented on releases/release-6.6.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
        - 修复了恢复数据到正在运行日志备份的集群，导致日志备份文件无法恢复的问题 [#40797](https://github.com/pingcap/tidb/issues/40797) @[Leavrth](https://github.com/Leavrth)
        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```

2023-02-13 05:46 UTC, flowbehappy approved these changes

2023-02-13 06:07 UTC, qw4990 commented on releases/release-6.6.0.md
> +
```suggestion
    - 优化了 Plan Cache 策略避免在一些场景使用 Plan Cache 时产生不优的计划 [#40312](https://github.com/pingcap/tidb/pull/40312), [#40218](https://github.com/pingcap/tidb/pull/40218), [#40280](https://github.com/pingcap/tidb/pull/40280), [#41136](https://github.com/pingcap/tidb/pull/41136), [#40686](https://github.com/pingcap/tidb/pull/40686) @[qw4990](https://github.com/qw4990)
```

2023-02-13 06:08 UTC, qw4990 commented on releases/release-6.6.0.md
> +
@TomShawn 这样几个合成一个麻烦文档老师看看 OK 吗

2023-02-13 06:35 UTC, nolouch commented on releases/release-6.6.0.md
> +    - 增加 GC Tuner 功能以缓解 GC 压力（实验特性）[#5827](https://github.com/tikv/pd/issues/5827) @[hnes](https://github.com/hnes)
```suggestion
    - 增加 GC Tuner 功能以缓解 GC 压力（实验特性）[#5827](https://github.com/tikv/pd/issues/5827) @[hnes](https://github.com/hnes)
    - 增加 `balance-witness-scheduler` 调度器用于调度 witness [#5763](https://github.com/tikv/pd/pull/5763) @[ethercflow](https://github.com/ethercflow)
    - 增加 `evict-slow-trend-scheduler` 调度器用于异常节点检测和调度 [#5808](https://github.com/tikv/pd/pull/5808) @[innerr](https://github.com/innerr)
```

2023-02-13 06:41 UTC, nolouch commented on releases/release-6.6.0.md
> +    - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
    - 修复 region scatter 任务会生产多余非预期副本的问题 [#5920](https://github.com/tikv/pd/pull/5920) @[HundunDM](https://github.com/HunDunDM)
    - 修复 online-unsafe-recovery 在 auto-detect 模式下卡住并超时的问题 [#5754](https://github.com/tikv/pd/pull/5754) @[Connor1996](https://github.com/Connor1996)
    - 修复 replace down peer 在特定条件下执行变慢的问题 [#5789](https://github.com/tikv/pd/pull/5789)@[HundunDM](https://github.com/HunDunDM)
    - 修复调用 ReportMinResolvedTS 过高的情况下造成 PD OOM 的问题  [#5965](https://github.com/tikv/pd/issues/5965) @[HundunDM](https://github.com/HunDunDM)
```

2023-02-13 07:17 UTC, nongfushanquan commented on releases/release-6.6.0.md
> +
* 支持 batch update dml 语句，提升 TiCDC 同步批量 update DML 的性能。 [#8084](https://github.com/pingcap/tiflow/issues/8084)

2023-02-13 07:34 UTC, nongfushanquan commented on releases/release-6.6.0.md
> +    + TiCDC
* 支持 batch update dml 语句，提升 TiCDC 同步批量 update DML 的性能。 [#8084](https://github.com/pingcap/tiflow/issues/8084)
* 将 pull-based sink 设置为默认模式，提升 TiCDC 日常吞吐、开启 Redo log 场景下的性能。 [#5928](https://github.com/pingcap/tiflow/issues/5928)

2023-02-13 07:51 UTC, nongfushanquan commented on releases/release-6.6.0.md
> +
* 修复 changefeed 里面某些参数不能通过 configure 文件更新的问题。 [#7935](https://github.com/pingcap/tiflow/issues/7935)
* 修复 redo log 存储路径没做权限预检查的问题。 [#6335](https://github.com/pingcap/tiflow/issues/6335) 
* 修复 redo log 容忍S3存储故障过短的问题。 [#8089](https://github.com/pingcap/tiflow/issues/8089) 
* 修复 changefeed 在 tikv、CDC 节点扩缩容特殊场景下卡住的问题。 [#8197](https://github.com/pingcap/tiflow/issues/8197) 
* 修复 在6.5 中引入tikv 节点之间流量过大的问题。 [#14092](https://github.com/tikv/tikv/issues/14092) 
* 优化 pull-based sink 打开时在 CPU 利用率、内存控制、吞吐等方面若干性能问题。[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.com/pingcap/tiflow/issues/8001) [#5928](https://github.com/pingcap/tiflow/issues/5928)

2023-02-13 08:31 UTC, TomShawn commented on releases/release-6.6.0.md
> +> **注意**
```suggestion
> **注意：**
```

2023-02-13 08:31 UTC, TomShawn commented on releases/release-6.6.0.md
> +* [GORM] 已添加 TiDB 集成测试。目前 TiDB 已成为 GORM 默认支持的数据库。
```suggestion
* GORM 已添加 TiDB 集成测试。目前 TiDB 已成为 GORM 默认支持的数据库。
```

2023-02-13 10:15 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 提供独立的 MVCC 位图过滤器，解耦 TiFlash 整体数据扫描流程中的 MVCC 过滤操作，为后续优化数据扫描流程提供基础 [#6296](https://github.com/pingcap/tiflash/issues/6296) @[JinheLin] **tw@qiancai**
```suggestion
    - 提供独立的 MVCC 位图过滤器，解耦 TiFlash 整体数据扫描流程中的 MVCC 过滤操作，为后续优化数据扫描流程提供基础 [#6296](https://github.com/pingcap/tiflash/issues/6296) @[JinheLin](https://github.com/JinheLin) **tw@qiancai**
```

2023-02-13 13:42 UTC, chrysan commented on releases/release-6.6.0.md
> +| [`tidb_enable_plan_replayer_capture`](/system-variables.md#tidb_enable_plan_replayer_capture) | 新增 | 这个变量用来控制是否开启 [`PLAN REPLAYER CAPTURE`](/sql-plan-replayer.md#使用-plan-replayer-capture-抓取目标计划)。默认
```suggestion
| [`tidb_enable_plan_replayer_capture`](/system-variables.md#tidb_enable_plan_replayer_capture) | 新增 | 这个变量用来控制是否开启 [`PLAN REPLAYER CAPTURE`](/sql-plan-replayer.md#使用-plan-replayer-capture-抓取目标计划)。默认值 `OFF`，代表默认关闭 `PLAN REPLAYER CAPTURE`。 |
| [`tidb_enable_historical_stats`](/system-variables.md#tidb_enable_historical_stats) | 修改 | 这个变量用来控制是否开启历史统计信息。默认值由 `OFF` 修改为 `ON`，表示默认开启历史统计信息。 |
| [`tidb_enable_historical_stats_for_capture`](/system-variables.md#tidb_enable_historical_stats_for_capture) | 新增 | 这个变量用来控制 PLAN REPLAYER CAPTURE 抓取的内容是否默认带历史统计信息 。默认值 `OFF` ，表示默认不带历史统计信息。 |
| [`tidb_historical_stats_duration`](/system-variables.md#tidb_historical_stats_duration) | 新增 | 这个变量用来控制 历史统计信息在存储中的保留时间 。默认值 7 天。 |
```

2023-02-13 22:53 UTC, v01dstar commented on releases/release-6.6.0.md
> +    在生产环境中，可能有部分只读操作定期消耗大量资源，对整个集群的性能产生影响，比如备份和大规模数据读取分析等。TiDB v6.6.0 支持配置只读存储节点，用来执行重度资源消耗的只读任务，避免对线上业务的影响。目前支持 TiDB、TiSpark 和 BR 读取只读节点上的数据。你可以按照[操作步骤](/readonly-nodes.md#操作步骤)配置只读存储节点，并通过 TiDB 系统变
👍

2023-02-14 02:28 UTC, zhangyangyu commented on releases/release-6.6.0.md
> +    - [GORM MySQL driver](https://github.com/go-gorm/mysql) 在 `v1.4.6` 中修复连接 TiDB 时，在 `AutoMigrate` 期间无法更改 `Unique` 字段的非 `Unique` 属性的问题 [#105](https://github.com/go-gorm/mysql/pull/104) @[Icemap](htt
```suggestion
    - [GORM MySQL driver](https://github.com/go-gorm/mysql) 在 `v1.4.6` 中修复连接 TiDB 时，在 `AutoMigrate` 期间无法更改 `Unique` 字段的非 `Unique` 属性的问题 [#105](https://github.com/go-gorm/mysql/pull/105) @[Icemap](https://github.com/Icemap)
```

2023-02-14 03:04 UTC, qw4990 commented on releases/release-6.6.0.md
> +| TiDB  | [`tidb_stmt_summary_enable_persistent`](/tidb-configuration-file.md#tidb_stmt_summary_enable_persistent-从-v660-版本开始引入)  |  新增  |  用于控制是否开启 statements summary 持久化。默认值为 `false`，即不开启该功能。  |
```suggestion
| TiDB  | [`tidb_index_join_double_read_penalty_cost_rate `](/tidb-configuration-file.md#tidb_index_join_double_read_penalty_cost_rate-从-v660-版本开始引入)  |  新增  |  用于控制是否给 index join 增加一些惩罚性代价。默认值为 `0`，即不开启该功能。  |
| TiDB  | [`tidb_stmt_summary_enable_persistent`](/tidb-configuration-file.md#tidb_stmt_summary_enable_persistent-从-v660-版本开始引入)  |  新增  |  用于控制是否开启 statements summary 持久化。默认值为 `false`，即不开启该功能。  |
```

2023-02-14 03:21 UTC, zhangyangyu approved these changes

2023-02-14 03:52 UTC, D3Hunter commented on releases/release-6.6.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
        - physical 导入模式支持 keyspace [#40531](https://github.com/pingcap/tidb/issues/40531) @[iosmanthus]
        - 支持通过 lightning.max-error 设置最大冲突个数 [#40743](https://github.com/pingcap/tidb/issues/40743) @[dsdashun]
        - 支持带有 BOM header 的数据文件 [#40744](https://github.com/pingcap/tidb/issues/40744) @[dsdashun]
        - 优化遇到 tikv 限流错误时处理逻辑，改为尝试其他不繁忙的 region [#40205](https://github.com/pingcap/tidb/issues/40205) @[lance6716]
        - 导入时关闭对表外键的检查 [#40027](https://github.com/pingcap/tidb/issues/40027) @[gozssky]

```

2023-02-14 03:52 UTC, D3Hunter commented on releases/release-6.6.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion
        - 修复并行导入时，当除最后一个外的 lightning 实例都遇到本地重复时，lightning 可能会跳过冲突处理的问题 [#40923](https://github.com/pingcap/tidb/issues/40923) @[lichunzhu]
        - 修复 precheck 无法准确检测目标集群是否存在运行中的 CDC 的问题 [#41040](https://github.com/pingcap/tidb/issues/41040) @[lance6716]
        - 修复 lightning 在 split-region 阶段 panic 问题（next key） [#40934](https://github.com/pingcap/tidb/issues/40934) @[lance6716]
        - 修复踢重逻辑可能导致 checksum 不一致的问题 [#40657](https://github.com/pingcap/tidb/issues/40657) @[gozssky]
        - 修复当数据文件中存在未闭合的 delimiter 可能导致 OOM 的问题 [#40400](https://github.com/pingcap/tidb/issues/40400) @[buchuitoudegou]
        - 修复报错中的文件 offset 超过文件大小的问题 [#40034](https://github.com/pingcap/tidb/issues/40034) @[buchuitoudegou]
        - 修复新版 PDClient 可能导致并行导入失败的问题 [#40493](https://github.com/pingcap/tidb/issues/40493) @[AmoebaProtozoa]
        - 修复检测目标表是否为空的检查项无法检测到之前导入的脏数据的问题 [#39477](https://github.com/pingcap/tidb/issues/39477) @[dsdashun]

```

2023-02-14 03:52 UTC, D3Hunter commented on releases/release-6.6.0.md
> +
```suggestion

    + Dumpling
        - 支持导出外键相关设置 [#39913](https://github.com/pingcap/tidb/issues/39913) @[lichunzhu]
```

2023-02-14 04:07 UTC, D3Hunter commented on releases/release-6.6.0.md
> +
```suggestion
        - 优化 relay 性能[#4287](https://github.com/pingcap/tiflow/issues/4287) @[GMHDBJD]
```

2023-02-14 04:07 UTC, D3Hunter commented on releases/release-6.6.0.md
> +        - note [#issue](链接) @[贡献者 GitHub ID](链接)
```suggestion

        - 修复 binlog-schema delete 失败的问题[#7373](https://github.com/pingcap/tiflow/issues/7373) @[liumengya94]
        - 修复最后一个 binlog 为被 skip 的 ddl 会导致 checkpoint 不推进的问题[#8175](https://github.com/pingcap/tiflow/issues/8175) @[D3Hunter]
        - 修复在同时有 update 和 non-update 类型的 expression filter 时所有的 update 类型的行变更都被跳过的问题[#7831](https://github.com/pingcap/tiflow/issues/7831) @[lance6716]
        - 修复当某个表只有 `update-old-value-expr` 或 `update-new-value-expr` 被设置时，不生效或 panic 的问题[#7774](https://github.com/pingcap/tiflow/issues/7774) @[lance6716]
```

2023-02-14 07:00 UTC, hfxsd commented on releases/release-6.6.0.md
> +        - 对于不可自动恢复的错误，维持原有行为，立即报警。
```suggestion
            之前 "DM_XXX_process_exits_with_error" 类告警是遇到相关错误就报警，但有些告警是由于数据库连接长时间 idle 导致的，重连后即可恢复。为了减少这类报警，DM 将错误分为了可自动恢复错误和不可自动恢复错误：

            - 对于可自动恢复的错误，只有在 2 分钟内发生超过 3 次时才报警。
            - 对于不可自动恢复的错误，维持原有行为，立即报警。
```

2023-02-14 09:01 UTC, joccau commented on releases/release-6.6.0.md
> +
```suggestion
- 修复了 PITR 功能不支持 CA-bundle 认证的问题 #38775 @YuJuncen
- 修复了恢复时重复的临时表导致的 Panic 问题 #40797 @joccau
- 修复了 PITR 不支持 PD 集群配置变更的问题 #14165 @YuJuncen
- 修复了 PD 与 tidb-server 的连接故障导致 PITR 备份进度不推进的问题 #41082 @YuJuncen
- 修复了 PD 与 TiKV 的连接故障导致 TiKV 不能监听 PITR 任务的问题 #14159 @YuJuncen
- 修复了当 TiDB 集群不存在 PITR 备份任务时，resolve lock 频率过高的问题 #40759 @joccau
- 修复了 PITR 备份任务被删除时存在备份信息残留导致新任务出现数据不一致的问题 #40403 @joccau
```

2023-02-14 09:16 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    多值索引的引入， 进一步增强了 TiDB 对 JSON 类型的支持， 同时也提升了 TiDB 对 MySQL 8.0 的兼容性。
```suggestion
    多值索引的引入， 进一步增强了 TiDB 对 JSON 类型的支持，同时也提升了 TiDB 对 MySQL 8.0 的兼容性。
```

2023-02-14 09:16 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    TiDB v6.6.0 版本引入了 DDL 动态资源管控， 通过自动控制 DDL 的 CPU 使用量，尽量降低 DDL 变更任务对线上业务的影响。该功能仅在开启 [DDL 分布式并行执行框架](/system-variables.md#tidb_ddl_distribute_reorg-从-v660-版本开始引入)后生效。
```suggestion
    TiDB v6.6.0 版本引入了 DDL 动态资源管控，通过自动控制 DDL 的 CPU 使用量，尽量降低 DDL 变更任务对线上业务的影响。该功能仅在开启 [DDL 分布式并行执行框架](/system-variables.md#tidb_ddl_distribute_reorg-从-v660-版本开始引入)后生效。
```

2023-02-14 09:16 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +* 支持 DDL 动态资源管控（实验特性） [#38025](https://github.com/pingcap/tidb/issues/38025)  @[hawkingrei](https://github.com/hawkingrei) **tw@ran-huang**
```suggestion
* 支持 DDL 动态资源管控（实验特性）[#38025](https://github.com/pingcap/tidb/issues/38025)  @[hawkingrei](https://github.com/hawkingrei) **tw@ran-huang**
```

2023-02-14 09:16 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +* 支持 DDL 分布式并行执行框架（实验特性） [#37125](https://github.com/pingcap/tidb/issues/37125) @[zimulala](https://github.com/zimulala) **tw@ran-huang**
```suggestion
* 支持 DDL 分布式并行执行框架（实验特性）[#37125](https://github.com/pingcap/tidb/issues/37125) @[zimulala](https://github.com/zimulala) **tw@ran-huang**
```

2023-02-14 09:16 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +* [Placement Rules in SQL](/placement-rules-in-sql.md) 支持指定 `SURVIVAL_PREFERENCE` [#38605](https://github.com/pingcap/tidb/issues/38605) @nolouch[https://github.com/nolouch] **tw@qiancai**
```suggestion
* [Placement Rules in SQL](/placement-rules-in-sql.md) 支持指定 `SURVIVAL_PREFERENCE` [#38605](https://github.com/pingcap/tidb/issues/38605) @[nolouch](https://github.com/nolouch) **tw@qiancai**
```

2023-02-14 09:16 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    更多信息，请参考 v6.6.0 Release Notes 中 [SQL 部分](#sql)以及用户文档](/sql-statements/sql-statement-create-index.md#多值索引)。
```suggestion
    更多信息，请参考 v6.6.0 Release Notes 中 [SQL 部分](#sql)以及[用户文档](/sql-statements/sql-statement-create-index.md#多值索引)。
```

2023-02-14 09:53 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +* TiCDC 支持在 Kafka 同步任务上开启单表的横向扩展功能，将单表的同步任务下发到多个 TiCDC 节点上执行 [#7720](https://github.com/pingcap/tiflow/issues/7720) @[overvenus](https://github.com/overvenus) **tw@Oreoxmt**
```suggestion
* TiCDC 支持在 Kafka 同步任务上开启单表的横向扩展功能，将单表的同步任务下发到多个 TiCDC 节点上执行（实验特性）[#7720](https://github.com/pingcap/tiflow/issues/7720) @[overvenus](https://github.com/overvenus) **tw@Oreoxmt**
```

2023-02-14 11:12 UTC, hfxsd commented on releases/release-6.6.0.md
> +            - 对于不可自动恢复的错误，维持原有行为，立即报警。
```suggestion
        - 优化了 DM 的告警规则和内容 [#7376](https://github.com/pingcap/tiflow/issues/7376) @[D3Hunter](https://github.com/D3Hunter) **tw@hfxsd**

            之前 "DM_XXX_process_exits_with_error" 类告警是遇到相关错误即报警，但有些告警是由于数据库连接长时间 idle 导致的，重连后即可恢复。为了减少此类报警，DM 将错误分为了可自动恢复错误和不可自动恢复错误：

            - 对于可自动恢复的错误，只有在 2 分钟内发生超过 3 次时才报警。
            - 对于不可自动恢复的错误，维持原有行为，立即报警。
```

2023-02-14 11:12 UTC, hfxsd commented on releases/release-6.6.0.md
> +        - 优化 relay 性能[#4287](https://github.com/pingcap/tiflow/issues/4287) @[GMHDBJD]
```suggestion
        - 优化 relay 性能 [#4287](https://github.com/pingcap/tiflow/issues/4287) @[GMHDBJD](https://github.com/GMHDBJD)
```

2023-02-14 11:12 UTC, hfxsd commented on releases/release-6.6.0.md
> +        - 导入时关闭对表外键的检查 [#40027](https://github.com/pingcap/tidb/issues/40027) @[gozssky]
```suggestion
        - Physical Import Mode 支持 Keyspace [#40531](https://github.com/pingcap/tidb/issues/40531) @[iosmanthus](https://github.com/iosmanthus)
        - 支持通过 `lightning.max-error` 设置最大冲突个数 [#40743](https://github.com/pingcap/tidb/issues/40743) @[dsdashun](https://github.com/dsdashun)
        - 支持导入带有 BOM header 的 CSV 数据文件 [#40744](https://github.com/pingcap/tidb/issues/40744) @[dsdashun](https://github.com/dsdashun)
        - 优化遇到 TiKV 限流错误时的处理逻辑，改为尝试其他空闲的 region [#40205](https://github.com/pingcap/tidb/issues/40205) @[lance6716](https://github.com/lance6716)
        - 导入时关闭对表外键的检查 [#40027](https://github.com/pingcap/tidb/issues/40027) @[gozssky](https://github.com/gozssky)
```

2023-02-14 11:12 UTC, hfxsd commented on releases/release-6.6.0.md
> +        - 支持导出外键相关设置 [#39913](https://github.com/pingcap/tidb/issues/39913) @[lichunzhu]
```suggestion
        - 支持导出外键相关设置 [#39913](https://github.com/pingcap/tidb/issues/39913) @[lichunzhu](https://github.com/lichunzhu)
```

2023-02-14 11:12 UTC, hfxsd commented on releases/release-6.6.0.md
> +
```suggestion
    + Backup & Restore (BR) @hfxsd 
        <!-- 9 -->
        - 修复恢复日志备份时热点 Region 导致恢复失败的问题 [#37207](https://github.com/pingcap/tidb/issues/37207) @[Leavrth](https://github.com/Leavrth)
        - 修复恢复数据到正在运行日志备份的集群，导致日志备份文件无法恢复的问题 [#40797](https://github.com/pingcap/tidb/issues/40797) @[Leavrth](https://github.com/Leavrth)
        - 修复 PITR 功能不支持 CA-bundle 认证的问题 [#38775](https://github.com/pingcap/tidb/issues/38775) @[YuJuncen](https://github.com/YuJuncen)
        - 修复恢复时重复的临时表导致的 Panic 问题 [#40797](https://github.com/pingcap/tidb/issues/40797) @[joccau](https://github.com/joccau)
        - 修复 PITR 不支持 PD 集群配置变更的问题 [#14165](https://github.com/tikv/tikv/issues/14165) @[YuJuncen](https://github.com/YuJuncen)
        - 修复 PD 与 tidb-server 的连接故障导致 PITR 备份进度不推进的问题 [#41082](https://github.com/pingcap/tidb/issues/41082) @[YuJuncen](https://github.com/YuJuncen)
        - 修复 PD 与 TiKV 的连接故障导致 TiKV 不能监听 PITR 任务的问题 [#14159](https://github.com/tikv/tikv/issues/14159) @[YuJuncen](https://github.com/YuJuncen)
        - 修复当 TiDB 集群不存在 PITR 备份任务时，`resolve lock` 频率过高的问题 [#40759](https://github.com/pingcap/tidb/issues/40759) @[joccau](https://github.com/joccau)
        - 修复了 PITR 备份任务被删除时，存在备份信息残留导致新任务出现数据不一致的问题 [#40403](https://github.com/pingcap/tidb/issues/40403) @[joccau](https://github.com/joccau)

```

2023-02-14 11:42 UTC, TomShawn commented on releases/release-6.6.0.md
> +> 除了 v6.6.0 及之后发布的 DMR 和 LTS 版本默认关闭遥测外，2022 年 2 月 20 日后，为 TiDB LTS 版本发布的补丁版本也默认关闭遥测功能，默认不再收集使用情况信息分享给 PingCAP。具体的版本可参考 [TiDB 版本发布时间线](/releases/release-timeline.md)。
```suggestion
- 在 v6.6.0 及之后发布的里程碑版本 (DMR) 和长期支持版本 (LTS) 中，TiDB 和 TiDB Dashboard 默认关闭遥测功能，即默认不再收集使用情况信息。如果升级前使用默认的遥测配置，则升级后遥测功能处于关闭状态。
- 从 v1.11.3 起，新部署的 TiUP 默认关闭遥测功能，即默认不再收集使用情况信息。如果从 v1.11.3 之前的 TiUP 版本升级至 v1.11.3 或更高 TiUP 版本，遥测保持升级前的开启或关闭状态。

> **注意：**
>
> 除了 v6.6.0 及之后发布的 DMR 和 LTS 版本默认关闭遥测外，2023 年 2 月 20 日后，为 TiDB LTS 版本发布的补丁版本也默认关闭遥测功能，默认不再收集使用情况信息分享给 PingCAP。具体的版本可参考 [TiDB 版本发布时间线](/releases/release-timeline.md)。
```

2023-02-14 14:28 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +| TiDB  |  [`enable-telemetry`](/tidb-configuration-file.md#enable-telemetry-从-v402-版本开始引入)  |   自 v6.6.0 起，该配置项默认值由 `true` 改为 `false`，表示默认关闭 TiDB 的遥测功能。  |
```suggestion
| TiDB  |  [`enable-telemetry`](/tidb-configuration-file.md#enable-telemetry-从-v402-版本开始引入)  |  修改 |  自 v6.6.0 起，该配置项默认值由 `true` 改为 `false`，表示默认关闭 TiDB 的遥测功能。  |
```

2023-02-14 14:28 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +| TiDB | [`tidb_stmt_summary_file_max_backups`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_backups-从-v660-版本开始引入) | 新增 | 当开启了 statements summary 持久化时，该配置用于限制持久化数据文件最大数量，`0` 表示不限制，默认值为 `0`
```suggestion
| TiDB | [`tidb_stmt_summary_file_max_backups`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_backups-从-v660-版本开始引入) | 新增 | 当开启了 statements summary 持久化时，该配置用于限制持久化数据文件最大数量，默认值为 `0`，表示不限制。 |
```

2023-02-15 01:06 UTC, hfxsd commented on releases/release-6.6.0.md
> +| TiDB Lightning | [`compress-kv-pairs`](/tidb-lightning/tidb-lightning-configuration.md#tidb-lightning-任务配置) | 新增 | 该配置项控制 Physical Import Mode 向 TiKV 发送 KV 时是否启用压缩，默认值为空，代表不启用压缩。 |
```suggestion
| TiDB Lightning | [`compress-kv-pairs`](/tidb-lightning/tidb-lightning-configuration.md#tidb-lightning-任务配置) | 新增 | 该配置项控制 Physical Import Mode 向 TiKV 发送 KV 时是否启用压缩，默认值为空，表示不启用压缩。 |
```

2023-02-15 01:08 UTC, hfxsd commented on releases/release-6.6.0.md
> +| DM | [`checksum-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 physical import 在导入完成一张表后，对每一个表执行 `ADMIN CHECKSUM TABLE <table>` 进行数据校验。默认值为 `"required"`。表示导入完成后进行数据校验，如果校验失败会让任务暂停，需要
```suggestion
| DM | [`checksum-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 Physical Import 在导入完成一张表后，对每一个表执行 `ADMIN CHECKSUM TABLE <table>` 进行数据校验。默认值为 `"required"`，表示导入完成后进行数据校验，如果校验失败会暂停任务，需要你手动处理。|
```

2023-02-15 01:09 UTC, hfxsd commented on releases/release-6.6.0.md
> +| DM | [`on-duplicate-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 Physical Import 针对冲突数据的解决方式。默认值为 `"none"`，表示遇到冲突数据时不进行处理。该模式性能最佳，但下游数据库会遇到数据索引不一致的问题。  |
```suggestion
| DM | [`on-duplicate-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 Physical Import 针对冲突数据的解决方式。默认值为 `"none"`，表示遇到冲突数据时不进行处理。该模式性能最佳，但下游数据库会出现数据索引不一致的问题。  |
```

2023-02-15 01:10 UTC, hfxsd commented on releases/release-6.6.0.md
> +| DM | [`sorting-dir-physical`](/dm/task-configuration-file-full.md) | 新增 | 该配置项控制 Physical Import 用作本地排序的目录位置，该选项的默认值与 `dir` 配置项一致。 |
加个 dir 的链接？

2023-02-15 02:37 UTC, hfxsd commented on releases/release-6.6.0.md
> +        - 支持 Batch UPDATE DML 语句，提升 TiCDC 同步 Batch UPDATE DML 的性能 [#8084](https://github.com/pingcap/tiflow/issues/8084)
```suggestion
        - 支持 Batch UPDATE DML 语句，提升 TiCDC 的同步性能 [#8084](https://github.com/pingcap/tiflow/issues/8084)
```

2023-02-15 03:30 UTC, TomShawn commented on releases/release-6.6.0.md
> +- 自 2023 年 2 月 20 日起，新发布的 TiDB 和 TiDB Dashboard 版本（含 v6.6.0），默认关闭遥测功能，即默认不再收集使用情况信息分享给 PingCAP。如果升级前使用默认的遥测配置，则升级后遥测功能处于关闭状态。具体的版本可参考 [TiDB 版本发布时间线](/releases/release-timeline.md)。
```suggestion
- 自 2023 年 2 月 20 日起，新发布的 TiDB 和 TiDB Dashboard 版本（含 v6.6.0），默认关闭遥测功能，即默认不再收集使用情况信息分享给 PingCAP。如果升级至这些版本前使用默认的遥测配置，则升级后遥测功能处于关闭状态。具体的版本可参考 [TiDB 版本发布时间线](/releases/release-timeline.md)。
```

2023-02-15 03:38 UTC, hfxsd commented on releases/release-6.6.0.md
> +        - 优化 relay 性能 [#4287](https://github.com/pingcap/tiflow/issues/4287) @[GMHDBJD](https://github.com/GMHDBJD)
```suggestion
        - 新增 async/batch relay writer 以优化 relay 性能 [#4287](https://github.com/pingcap/tiflow/issues/4287) @[GMHDBJD](https://github.com/GMHDBJD)
```

2023-02-15 06:21 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 优化 pull-based sink 打开时在 CPU 利用率、内存控制、吞吐等方面若干性能问题。[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.com/pin
```suggestion
        - 修复 redo log 存储路径没做权限预检查的问题 [#6335](https://github.com/pingcap/tiflow/issues/6335)
        - 修复 redo log 容忍 S3 存储故障的时间过短的问题 [#8089](https://github.com/pingcap/tiflow/issues/8089)
        - 修复 changefeed 在 TiKV、TiCDC 节点扩缩容特殊场景下卡住的问题 [#8197](https://github.com/pingcap/tiflow/issues/8197)
        - 修复TiKV 节点之间流量过大的问题 [#14092](https://github.com/tikv/tikv/issues/14092)
        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题。[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.com/pingcap/tiflow/issues/8001) [#5928](https://github.com/pingcap/tiflow/issues/5928)
```

2023-02-15 06:35 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 修复 changefeed 在 TiKV、TiCDC 节点扩缩容特殊场景下卡住的问题 [#8197](https://github.com/pingcap/tiflow/issues/8197)
@nongfushanquan 1) The link is a pull request, not an issue. Please confirm which issue this node is related to.
2) The note seems unrelated to the pull request.

2023-02-15 06:43 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 修复 redo log 容忍 S3 存储故障的时间过短的问题 [#8089](https://github.com/pingcap/tiflow/issues/8089)
```suggestion
        - 修复 redo log 存储路径没做权限预检查的问题 [#6335](https://github.com/pingcap/tiflow/issues/6335) @[CharlesCheung96](https://github.com/CharlesCheung96)
        - 修复 redo log 容忍 S3 存储故障的时间过短的问题 [#8089](https://github.com/pingcap/tiflow/issues/8089) @[CharlesCheung96](https://github.com/CharlesCheung96)
```

2023-02-15 06:46 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题。[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.
```suggestion
        - 修复 TiKV 节点之间流量过大的问题 [#14092](https://github.com/tikv/tikv/issues/14092) @[overvenus](https://github.com/overvenus)
        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题。[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.com/pingcap/tiflow/issues/8001) [#5928](https://github.com/pingcap/tiflow/issues/5928) @[hicqu](https://github.com/hicqu) @[hi-rustin](https://github.com/hi-rustin)
```

2023-02-15 06:54 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 修复最后一个 binlog 为被 skip 的 ddl 会导致 checkpoint 不推进的问题[#8175](https://github.com/pingcap/tiflow/issues/8175) @[D3Hunter]
```suggestion
        - 修复 `binlog-schema delete` 命令执行失败的问题 [#7373](https://github.com/pingcap/tiflow/issues/7373) @[liumengya94]
        - 修复当最后一个 binlog 是被 skip 的 DDL 时，checkpoint 不推进的问题 [#8175](https://github.com/pingcap/tiflow/issues/8175) @[D3Hunter]
```

2023-02-15 07:01 UTC, hfxsd commented on releases/release-6.6.0.md
> +---
```suggestion
summary: 了解 TiDB 6.6.0 版本的新功能、兼容性变更、改进提升，以及错误修复。
---
```

2023-02-15 08:09 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 修复新版 PDClient 可能导致并行导入失败的问题 [#40493](https://github.com/pingcap/tidb/issues/40493) @[AmoebaProtozoa]
```suggestion
        - 修复在并行导入时，当除最后一个 TiDB Lightning 实例外的其他实例都遇到本地重复记录时，TiDB Lightning 可能会错误地跳过冲突处理的问题 [#40923](https://github.com/pingcap/tidb/issues/40923) @[lichunzhu]
        - 修复 precheck 无法准确检测目标集群是否存在运行中的 TiCDC 的问题 [#41040](https://github.com/pingcap/tidb/issues/41040) @[lance6716]
        - 修复 TiDB Lightning 在 split-region 阶段发生 panic 的问题 [#40934](https://github.com/pingcap/tidb/issues/40934) @[lance6716]
        - 修复冲突处理逻辑 (`duplicate-resolution`) 可能导致 checksum 不一致的问题 [#40657](https://github.com/pingcap/tidb/issues/40657) @[gozssky]
        - 修复当数据文件中存在未闭合的 delimiter 时可能 OOM 的问题 [#40400](https://github.com/pingcap/tidb/issues/40400) @[buchuitoudegou]
        - 修复报错中的文件 offset 超过文件大小的问题 [#40034](https://github.com/pingcap/tidb/issues/40034) @[buchuitoudegou]
        - 修复新版 PDClient 可能导致并行导入失败的问题 [#40493](https://github.com/pingcap/tidb/issues/40493) @[AmoebaProtozoa]
```

2023-02-15 09:24 UTC, hfxsd commented on releases/release-6.6.0.md
> +    + Backup & Restore (BR) @hfxsd
```suggestion
    + Backup & Restore (BR)
```

2023-02-15 09:54 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复了并发视图时可能会造成 DDL 操作卡住的问题 [#40352](https://github.com/pingcap/tidb/issues/40352) @[zeminzhou](https://github.com/zeminzhou)
```suggestion
    - 修复了 JSON 的 not 表达式实现与 MySQL 实现不兼容的问题 [#40683](https://github.com/pingcap/tidb/issues/40683) @[YangKeao](https://github.com/YangKeao)
    - 修复了并发视图模式可能会造成 DDL 操作卡住的问题 [#40352](https://github.com/pingcap/tidb/issues/40352) @[zeminzhou](https://github.com/zeminzhou)
```

2023-02-15 09:54 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复了使用 `caching_sha2_password` 方式进行认证时如果不指定的密码会报错 "Malformed packet" 的问题 [#40831](https://github.com/pingcap/tidb/issues/40831) @[dveeden](https://github.com/dveeden)
```suggestion
    - 修复了使用 `caching_sha2_password` 方式进行认证但不指定密码导致的 "Malformed packet" 问题 [#40831](https://github.com/pingcap/tidb/issues/40831) @[dveeden](https://github.com/dveeden)
```

2023-02-15 09:54 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复了并发 truncate 同一张表时部分 truncate 操作无法被 MDL 阻塞的问题 [#40484](https://github.com/pingcap/tidb/issues/40484) @[wjhuang2016](https://github.com/wjhuang2016)
```suggestion
    - 修复了 `JSON_OBJECT` 在某些情况下会报错的问题 [#39806](https://github.com/pingcap/tidb/issues/39806) @[YangKeao](https://github.com/YangKeao)
    - 修复了 TiDB 在初始化时有可能死锁的问题 [#40408](https://github.com/pingcap/tidb/issues/40408) @[Defined2014](https://github.com/Defined2014)
    - 修复了内存重用导致的在某些情况下系统变量的值会被错误修改的问题 [#40979](https://github.com/pingcap/tidb/issues/40979) @[lcwangchao](https://github.com/lcwangchao)
    - 修复了 ingest 模式下创建唯一索引可能会导致数据和索引不一致的问题 [#40464](https://github.com/pingcap/tidb/issues/40464) @[tangenta](https://github.com/tangenta)
    - 修复了并发 truncate 同一张表时，部分 truncate 操作无法被 MDL 阻塞的问题 [#40484](https://github.com/pingcap/tidb/issues/40484) @[wjhuang2016](https://github.com/wjhuang2016)
```

2023-02-15 09:54 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复了表达式索引中含有 CAST 时对表进行查询可能出错的问题 [#40129](https://github.com/pingcap/tidb/pull/40129) @[xiongjiwei](https://github.com/xiongjiwei)
```suggestion
    - 修复了表达式索引中含有 `CAST` 时对表进行查询可能出错的问题 [#40130](https://github.com/pingcap/tidb/issues/40130) @[xiongjiwei](https://github.com/xiongjiwei)
```

2023-02-15 09:55 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复了使用 Prepare/Execute 查询某些虚拟表时无法将表 ID 下推导致在大量 Region 的情况下 PD OOM 的问题 [#39605](https://github.com/pingcap/tidb/issues/39605) @[djshow832](https://github.com/djshow832)
```suggestion
    - 修复了使用 `Prepare` 或 `Execute` 查询某些虚拟表时无法将表 ID 下推导致在大量 Region 的情况下 PD OOM 的问题 [#39605](https://github.com/pingcap/tidb/issues/39605) @[djshow832](https://github.com/djshow832)
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +### 生态系统
```suggestion
### TiDB 工具
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +### 生态系统
生态一般是指 TiDB 以外的集成工具，例如 Kafka。2021 年末的时候，文档站一级目录里也用的是生态工具，后来为了避免歧义更名为 TiDB 工具了

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复了非法的 datetime 值导致 analyze 失败的问题 [#39336](https://github.com/pingcap/tidb/issues/39336) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
这个和 sql-infra 错误下的第一条重复了，issue 号和含义都是一样的，可以删除哇？

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复了由 virtual column 引发的 can't find proper physical plan 问题 [#41014](https://github.com/pingcap/tidb/issues/41014) @[AilinKid](https://github.com/AilinKid)
```suggestion
    - 修复了由虚拟列引发的 `can't find proper physical plan` 问题 [#41014](https://github.com/pingcap/tidb/issues/41014) @[AilinKid](https://github.com/AilinKid)
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复了 IndexMerge 算子在触发内存限制行为时可能导致 tidb-server 崩溃的问题[#41036](https://github.com/pingcap/tidb/pull/41036) @[guo-shaoge](https://github.com/guo-shaoge)
```suggestion
    - 修复了 IndexMerge 算子在触发内存限制行为时可能导致 TiDB server 崩溃的问题[#41036](https://github.com/pingcap/tidb/pull/41036) @[guo-shaoge](https://github.com/guo-shaoge)
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复了在分区表上执行查询 `select * from t limit 1` 时，执行速度慢的问题[#40741](https://github.com/pingcap/tidb/pull/40741)@[solotzg](https://github.com/solotzg)
```suggestion
    - 修复了在分区表上执行查询 `select * from t limit 1` 时，执行速度慢的问题 [#40741](https://github.com/pingcap/tidb/pull/40741) @[solotzg](https://github.com/solotzg)
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复了过期的 region cache 可能残留导致的内存泄漏和性能下降问题 [#40461](https://github.com/pingcap/tidb/issues/40461) @[sticnarf](https://github.com/sticnarf)
```suggestion
    - 修复了过期的 region 缓存可能残留导致的内存泄漏和性能下降问题 [#40461](https://github.com/pingcap/tidb/issues/40461) @[sticnarf](https://github.com/sticnarf)
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复cast const Enum 到其他类型时的错误 [#14156](https://github.com/tikv/tikv/issues/14156) @[wshwsh12](https://github.com/wshwsh12)
```suggestion
    - 修复 cast const Enum 到其他类型时的错误 [#14156](https://github.com/tikv/tikv/issues/14156) @[wshwsh12](https://github.com/wshwsh12)
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 减少resolve-ts带来的网络流量 [#14098](https://github.com/tikv/tikv/issues/14092) @[overvenus] (https://github.com/overvenus)
```suggestion
    - 减少 resolve-ts 带来的网络流量 [#14098](https://github.com/tikv/tikv/issues/14092) @[overvenus] (https://github.com/overvenus)
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 支持TiKV在小于1 core的CPU下启动 [#13586] [#13752] [#14017](https://github.com/tikv/tikv/issues/13586) @[andreid-db](https://github.com/andreid-db)
```suggestion
    - 支持 TiKV 在小于 1 core 的 CPU 下启动 [#13586] [#13752] [#14017](https://github.com/tikv/tikv/issues/13586) @[andreid-db](https://github.com/andreid-db)
```

2023-02-15 10:47 UTC, qiancai commented on releases/release-6.6.0.md
> +    - copr: 修复old collation时Like中的 _ pattern的行为 [#13785](https://github.com/tikv/tikv/pull/13785) @[Yangkeao](https://github.com/Yangkeao)
```suggestion
    - 修复 old collation 时 Like 中的 _ pattern的行为 [#13785](https://github.com/tikv/tikv/pull/13785) @[Yangkeao](https://github.com/Yangkeao)
```

2023-02-15 11:11 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复了并发视图模式可能会造成 DDL 操作卡住的问题 [#40352](https://github.com/pingcap/tidb/issues/40352) @[zeminzhou](https://github.com/zeminzhou)
```suggestion
    - 修复了并发视图模式可能会造成 DDL 操作卡住的问题 [#40352](https://github.com/pingcap/tidb/issues/40352) @[zeminzhou](https://github.com/zeminzhou)
    - 修复了并发对分区表执行 Modify Column 的 DDL 操作时有可能会造成数据不一致的问题 [#40620](https://github.com/pingcap/tidb/issues/40620) @[mjonss](https://github.com/mjonss) @[mjonss](https://github.com/mjonss)
```

2023-02-15 11:11 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复了使用 `Prepare` 或 `Execute` 查询某些虚拟表时无法将表 ID 下推导致在大量 Region 的情况下 PD OOM 的问题 [#39605](https://github.com/pingcap/tidb/issues/39605) @[djshow832](https://github.com/djshow832)
```suggestion
    - 修复了使用 `Prepare` 或 `Execute` 查询某些虚拟表时无法将表 ID 下推，导致在大量 Region 的情况下 PD OOM 的问题 [#39605](https://github.com/pingcap/tidb/issues/39605) @[djshow832](https://github.com/djshow832)
```

2023-02-15 11:37 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复 region scatter 任务会生产多余非预期副本的问题 [#5920](https://github.com/tikv/pd/pull/5920) @[HundunDM](https://github.com/HunDunDM)
```suggestion
    - 修复 Region Scatter 任务会生成非预期的多余副本的问题 [#5909](https://github.com/tikv/pd/issues/5909) @[HundunDM](https://github.com/HunDunDM)
```

2023-02-15 11:37 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复 online-unsafe-recovery 在 auto-detect 模式下卡住并超时的问题 [#5754](https://github.com/tikv/pd/pull/5754) @[Connor1996](https://github.com/Connor1996)
```suggestion
    - 修复 Online Unsafe Recovery 功能在 `auto-detect` 模式下卡住并超时的问题 [#5753](https://github.com/tikv/pd/issues/5753) @[Connor1996](https://github.com/Connor1996)
```

2023-02-15 14:50 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复 replace down peer 在特定条件下执行变慢的问题 [#5789](https://github.com/tikv/pd/pull/5789)@[HundunDM](https://github.com/HunDunDM)
```suggestion
    - 修复 `replace-down-peer` 在特定条件下执行变慢的问题 [#5788](https://github.com/tikv/pd/issues/5788) @[HundunDM](https://github.com/HunDunDM)
```

2023-02-15 14:50 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复调用 ReportMinResolvedTS 过高的情况下造成 PD OOM 的问题  [#5965](https://github.com/tikv/pd/issues/5965) @[HundunDM](https://github.com/HunDunDM)
```suggestion
    - 修复调用 `ReportMinResolvedTS` 过高的情况下造成 PD OOM 的问题  [#5965](https://github.com/tikv/pd/issues/5965) @[HundunDM](https://github.com/HunDunDM)
```

2023-02-16 01:44 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    - 修复了 TiDB 构造 key 范围时对 null 值处理不当，导致读取到预期外数据的行为 [#40158](https://github.com/pingcap/tidb/issues/40158) @[tiancaiamao](https://github.com/tiancaiamao)
```suggestion
    - 修复了 TiDB 构造 key 范围时对 `NULL` 值处理不当，导致读取到预期外数据的行为 [#40158](https://github.com/pingcap/tidb/issues/40158) @[tiancaiamao](https://github.com/tiancaiamao)
```

2023-02-16 02:24 UTC, xuyifangreeneyes commented on releases/release-6.6.0.md
> +    - 修复了非法的 datetime 值导致 analyze 失败的问题 [#39336](https://github.com/pingcap/tidb/issues/39336) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
可以删除

2023-02-16 02:52 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +| [`tidb_pessimistic_txn_aggressive_locking`](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始引入) | 新增 | 是否对悲观锁启用加强的悲观锁唤醒模型。默认值为 `OFF`，表示默认不对悲观锁启用加强的悲观锁唤醒模型。 |
```suggestion
| [`tidb_pessimistic_txn_aggressive_locking`](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始引入) | 新增 | 是否对悲观锁启用加强的悲观锁唤醒模型。默认值为 `OFF`，表示默认不对悲观锁启用加强的悲观锁唤醒模型。 |
| [`tidb_stmt_summary_enable_persistent`](/system-variables.md#tidb_stmt_summary_enable_persistent-从-v660-版本开始引入) | 新增 | 只读变量。表示是否开启 [statement summary tables 持久化](/statement-summary-tables.md#持久化-statements-summary)。该变量的值与配置文件中 [`tidb_stmt_summary_enable_persistent`](/tidb-configuration-file.md#tidb_stmt_summary_enable_persistent-从-v660-版本开始引入) 的取值相同。 |
| [`tidb_stmt_summary_filename`](/system-variables.md#tidb_stmt_summary_filename-从-v660-版本开始引入) | 新增 | 只读变量。表示当开启 [statement summary tables 持久化](/statement-summary-tables.md#持久化-statements-summary)后持久化数据所写入的文件。该变量的值与配置文件中 [`tidb_stmt_summary_filename`](/tidb-configuration-file.md#tidb_stmt_summary_filename-从-v660-版本开始引入) 的取值相同。 | 
| [`tidb_stmt_summary_file_max_backups`](/system-variables.md#tidb_stmt_summary_file_max_backups-从-v660-版本开始引入) | 新增 | 只读变量。表示当开启 [statement summary tables 持久化](/statement-summary-tables.md#持久化-statements-summary)后持久化数据文件的最大数量限制。该变量的值与配置文件中 [`tidb_stmt_summary_file_max_backups`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_backups-从-v660-版本开始引入) 的取值相同。 |
| [`tidb_stmt_summary_file_max_days`](/system-variables.md#tidb_stmt_summary_file_max_days-从-v660-版本开始引入) | 新增 | 只读变量。表示当开启 [statement summary tables 持久化](/statement-summary-tables.md#持久化-statements-summary)后持久化数据文件所保留的最大天数。该变量的值与配置文件中 [`tidb_stmt_summary_file_max_days`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_days-从-v660-版本开始引入) 的取值相同。 |
| [`tidb_stmt_summary_file_max_size`](/system-variables.md#tidb_stmt_summary_file_max_size-从-v660-版本开始引入) | 新增 | 只读变量。表示当开启 [statement summary tables 持久化](/statement-summary-tables.md#持久化-statements-summary)后持久化数据单个文件的大小限制。该变量的值与配置文件中 [`tidb_stmt_summary_file_max_size`](/tidb-configuration-file.md#tidb_stmt_summary_file_max_size-从-v660-版本开始引入) 的取值相同。 |

```

2023-02-16 03:45 UTC, nongfushanquan commented on releases/release-6.6.0.md
> +        - 修复 changefeed 在 TiKV、TiCDC 节点扩缩容特殊场景下卡住的问题 [#8197](https://github.com/pingcap/tiflow/issues/8197)
- 修复 changefeed 在 TiKV、TiCDC 节点扩缩容特殊场景下卡住的问题 [#8174](https://github.com/pingcap/tiflow/issues/8174)

2023-02-16 03:50 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 修复 changefeed 在 TiKV、TiCDC 节点扩缩容特殊场景下卡住的问题 [#8197](https://github.com/pingcap/tiflow/issues/8197)
```suggestion
        - 修复 changefeed 在 TiKV、TiCDC 节点扩缩容等特殊场景下卡住的问题 [#8174](https://github.com/pingcap/tiflow/issues/8174)
```

2023-02-16 03:51 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 修复 changefeed 在 TiKV、TiCDC 节点扩缩容等特殊场景下卡住的问题 [#8174](https://github.com/pingcap/tiflow/issues/8174)
```suggestion
        - 修复 changefeed 在 TiKV、TiCDC 节点扩缩容等特殊场景下卡住的问题 [#8174](https://github.com/pingcap/tiflow/issues/8174) @[hicqu](https://github.com/hicqu)
```

2023-02-16 07:00 UTC, TomShawn commented on releases/release-6.6.0.md
> +### 运维操作
```suggestion
### 数据库管理
```

2023-02-16 08:13 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复了 TiDB 构造 key 范围时对 `NULL` 值处理不当，导致读取到预期外数据的行为 [#40158](https://github.com/pingcap/tidb/issues/40158) @[tiancaiamao](https://github.com/tiancaiamao)
```suggestion
    - 修复了 TiDB 构造 key 范围时对 `NULL` 值处理不当，导致读取非预期数据的问题 [#40158](https://github.com/pingcap/tidb/issues/40158) @[tiancaiamao](https://github.com/tiancaiamao)
```

2023-02-16 10:11 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复了非法的 datetime 值导致 analyze 失败的问题 [#39336](https://github.com/pingcap/tidb/issues/39336) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
```suggestion
```

2023-02-16 10:11 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复 TiKV 在 CPU 核数小于 1 时无法启动的问题  [#13586] [#13752] [#14017](https://github.com/tikv/tikv/issues/13586) @[andreid-db](https://github.com/andreid-db)
```suggestion
    - 修复 TiKV 在 CPU 核数小于 1 时无法启动的问题  [#13586](https://github.com/tikv/tikv/issues/13586) [#13752](https://github.com/tikv/tikv/issues/13752) [#14017](https://github.com/tikv/tikv/issues/14017) @[andreid-db](https://github.com/andreid-db)
```

2023-02-16 10:11 UTC, qiancai commented on releases/release-6.6.0.md
> +    - copr: 修复old collation时Like中的 _ pattern的行为 [#13785](https://github.com/tikv/tikv/pull/13785) @[Yangkeao](https://github.com/Yangkeao)
```suggestion
```

2023-02-16 10:14 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 定期清理过期的 Region 缓存，避免内存泄漏和性能下降问题 [#40461](https://github.com/pingcap/tidb/issues/40461) @[sticnarf](https://github.com/sticnarf)
```suggestion

```

2023-02-16 10:14 UTC, qiancai commented on releases/release-6.6.0.md
> +
```suggestion
- 定期清理过期的 Region 缓存，避免内存泄漏和性能下降问题 [#40461](https://github.com/pingcap/tidb/issues/40461) @[sticnarf](https://github.com/sticnarf)


```

2023-02-16 10:15 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 定期清理过期的 Region 缓存，避免内存泄漏和性能下降问题 [#40461](https://github.com/pingcap/tidb/issues/40461) @[sticnarf](https://github.com/sticnarf)
移到了提升改进

2023-02-16 10:16 UTC, qiancai commented on releases/release-6.6.0.md
> +- 定期清理过期的 Region 缓存，避免内存泄漏和性能下降问题 [#40461](https://github.com/pingcap/tidb/issues/40461) @[sticnarf](https://github.com/sticnarf)
```suggestion
    - 定期清理过期的 Region 缓存，避免内存泄漏和性能下降问题 [#40461](https://github.com/pingcap/tidb/issues/40461) @[sticnarf](https://github.com/sticnarf)
```

2023-02-16 11:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +        - 修复 `binlog-schema delete` 命令执行失败的问题 [#7373](https://github.com/pingcap/tiflow/issues/7373) @[liumengya94]
```suggestion
        - 修复 `binlog-schema delete` 命令执行失败的问题 [#7373](https://github.com/pingcap/tiflow/issues/7373) @[liumengya94](https://github.com/liumengya94)
```

2023-02-16 11:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +        - 修复当最后一个 binlog 是被 skip 的 DDL 时，checkpoint 不推进的问题 [#8175](https://github.com/pingcap/tiflow/issues/8175) @[D3Hunter]
```suggestion
        - 修复当最后一个 binlog 是被 skip 的 DDL 时，checkpoint 不推进的问题 [#8175](https://github.com/pingcap/tiflow/issues/8175) @[D3Hunter](https://github.com/D3Hunter)
```

2023-02-16 11:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +        (dup: release-6.1.4.md > Bug 修复> Tools> TiDB Data Migration (DM))- 修复当某个表上仅指定 `update-old-value-expr` 或 `update-new-value-expr` 时，过滤规则不生效或 DM 发生 panic 的问题 [#7774](https://github.com/pingcap/t
```suggestion
        (dup: release-6.1.4.md > Bug 修复> Tools> TiDB Data Migration (DM))- 修复当在某个表上同时指定 `UPDATE` 和非 `UPDATE` 类型的表达式过滤规则 `expression-filter` 时，所有 `UPDATE` 操作被跳过的问题 [#7831](https://github.com/pingcap/tiflow/issues/7831) @[lance6716](https://github.com/lance6716)
        (dup: release-6.1.4.md > Bug 修复> Tools> TiDB Data Migration (DM))- 修复当某个表上仅指定 `update-old-value-expr` 或 `update-new-value-expr` 时，过滤规则不生效或 DM 发生 panic 的问题 [#7774](https://github.com/pingcap/tiflow/issues/7774) @[lance6716](https://github.com/lance6716)
```

2023-02-16 11:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +        - 修复在并行导入时，当除最后一个 TiDB Lightning 实例外的其他实例都遇到本地重复记录时，TiDB Lightning 可能会错误地跳过冲突处理的问题 [#40923](https://github.com/pingcap/tidb/issues/40923) @[lichunzhu]
```suggestion
        - 修复在并行导入时，当除最后一个 TiDB Lightning 实例外的其他实例都遇到本地重复记录时，TiDB Lightning 可能会错误地跳过冲突处理的问题 [#40923](https://github.com/pingcap/tidb/issues/40923) @[lichunzhu](https://github.com/lichunzhu)
```

2023-02-16 11:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +        - 修复 precheck 无法准确检测目标集群是否存在运行中的 TiCDC 的问题 [#41040](https://github.com/pingcap/tidb/issues/41040) @[lance6716]
```suggestion
        - 修复 precheck 无法准确检测目标集群是否存在运行中的 TiCDC 的问题 [#41040](https://github.com/pingcap/tidb/issues/41040) @[lance6716](https://github.com/lance6716)
```

2023-02-16 11:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +        - 修复 TiDB Lightning 在 split-region 阶段发生 panic 的问题 [#40934](https://github.com/pingcap/tidb/issues/40934) @[lance6716]
```suggestion
        - 修复 TiDB Lightning 在 split-region 阶段发生 panic 的问题 [#40934](https://github.com/pingcap/tidb/issues/40934) @[lance6716](https://github.com/lance6716)
```

2023-02-16 11:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +        - 修复新版 PDClient 可能导致并行导入失败的问题 [#40493](https://github.com/pingcap/tidb/issues/40493) @[AmoebaProtozoa]
```suggestion
        - 修复冲突处理逻辑 (`duplicate-resolution`) 可能导致 checksum 不一致的问题 [#40657](https://github.com/pingcap/tidb/issues/40657) @[gozssky](https://github.com/gozssky)
        - 修复当数据文件中存在未闭合的 delimiter 时可能 OOM 的问题 [#40400](https://github.com/pingcap/tidb/issues/40400) @[buchuitoudegou](https://github.com/buchuitoudegou)
        - 修复报错中的文件 offset 超过文件大小的问题 [#40034](https://github.com/pingcap/tidb/issues/40034) @[buchuitoudegou](https://github.com/buchuitoudegou)
        - 修复新版 PD Client 可能导致并行导入失败的问题 [#40493](https://github.com/pingcap/tidb/issues/40493) @[AmoebaProtozoa](https://github.com/AmoebaProtozoa)
```

2023-02-16 15:47 UTC, qiancai commented on releases/release-6.6.0.md
> +        - 支持 Batch UPDATE DML 语句，提升 TiCDC 的同步性能 [#8084](https://github.com/pingcap/tiflow/issues/8084)
1. 缺少 contributor 信息，不确实是否是 https://github.com/pingcap/tiflow/pull/8069 的作者
2.  https://github.com/pingcap/tiflow/issues/8084 这条 issue 的标签是 type/bug，是否属于缺陷修复

2023-02-16 15:47 UTC, qiancai commented on releases/release-6.6.0.md
> +        - 支持通过 `lightning.max-error` 设置最大冲突个数 [#40743](https://github.com/pingcap/tidb/issues/40743) @[dsdashun](https://github.com/dsdashun)
是否需要在用户文档中添加 `lightning.max-error` 支持设置最大冲突个数的说明

2023-02-16 15:47 UTC, qiancai commented on releases/release-6.6.0.md
> +        - 修复恢复时重复的临时表导致的 Panic 问题 [#40797](https://github.com/pingcap/tidb/issues/40797) @[joccau](https://github.com/joccau)
```suggestion
        - 修复恢复时重复的临时表导致的 panic 问题 [#40797](https://github.com/pingcap/tidb/issues/40797) @[joccau](https://github.com/joccau)
```

2023-02-16 15:47 UTC, qiancai commented on releases/release-6.6.0.md
> +        - 修复 PD 与 tidb-server 的连接故障导致 PITR 备份进度不推进的问题 [#41082](https://github.com/pingcap/tidb/issues/41082) @[YuJuncen](https://github.com/YuJuncen)
```suggestion
        - 修复 PD 与 TiDB server 的连接故障导致 PITR 备份进度不推进的问题 [#41082](https://github.com/pingcap/tidb/issues/41082) @[YuJuncen](https://github.com/YuJuncen)
```

2023-02-17 01:24 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复 TiKV 在 CPU 核数小于 1 时无法启动的问题  [#13586](https://github.com/tikv/tikv/issues/13586) [#13752](https://github.com/tikv/tikv/issues/13752) [#14017](https://github.com/tikv/tikv/issues/14017) @[andr
```suggestion
```

2023-02-17 01:25 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复 TiKV 在 CPU 核数小于 1 时无法启动的问题  [#13586](https://github.com/tikv/tikv/issues/13586) [#13752](https://github.com/tikv/tikv/issues/13752) [#14017](https://github.com/tikv/tikv/issues/14017) @[andr
remove this note because the same one is already provided in "Improvements"

2023-02-17 01:34 UTC, hfxsd commented on releases/release-6.6.0.md
> +        - 支持 Batch UPDATE DML 语句，提升 TiCDC 的同步性能 [#8084](https://github.com/pingcap/tiflow/issues/8084)
```suggestion
        - 支持 Batch UPDATE DML 语句，提升 TiCDC 的同步性能 [#8084](https://github.com/pingcap/tiflow/issues/8084) @[amyangfei](https://github.com/amyangfei)
```

2023-02-17 02:27 UTC, amyangfei commented on releases/release-6.6.0.md
> +        - 支持 Batch UPDATE DML 语句，提升 TiCDC 的同步性能 [#8084](https://github.com/pingcap/tiflow/issues/8084)
It belongs to performance improvement

2023-02-17 02:29 UTC, ran-huang commented on releases/release-6.6.0.md
> +        - 支持通过 `lightning.max-error` 设置最大冲突个数 [#40743](https://github.com/pingcap/tidb/issues/40743) @[dsdashun](https://github.com/dsdashun)
from author: 要不先不加，因为这个只是一个临时的方案。后续会进一步改进接口

2023-02-17 03:06 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    TiDB v6.6.0 引入了兼容 MySQL 语法的外键约束功能，支持在表内、表间关联数据并进行约束校验，并且支持级联操作。该特性有助于保持数据一致性，提升数据质量，并且方便数据建模。
```suggestion
    TiDB v6.6.0 引入了兼容 MySQL 语法的外键约束功能，支持在表内、表间关联数据并进行约束校验，并且支持级联操作。该特性有助于将 MySQL 上的应用迁移到 TiDB、保持数据一致性、提升数据质量并且方便数据建模。
```

2023-02-17 03:06 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +* 支持配置只读存储节点来执行资源消耗型任务 [#issue号](链接) @[v01dstar](https://github.com/v01dstar) **tw@Oreoxmt**
```suggestion
* 支持配置只读存储节点来执行资源消耗型任务 @[v01dstar](https://github.com/v01dstar) **tw@Oreoxmt**
```

2023-02-17 03:17 UTC, ran-huang commented on releases/release-6.6.0.md
> +    - 为优化器提示和执行计划绑定的冲突新增报错信息 [#40910](https://github.com/pingcap/tidb/issues/40910) @[Reminiscent](https://github.com/Reminiscent)
optimizer hints 在文档里使用英文表述的时候较多
```suggestion
    - 为 Optimizer Hints 和执行计划绑定的冲突新增报错信息 [#40910](https://github.com/pingcap/tidb/issues/40910) @[Reminiscent](https://github.com/Reminiscent)
```

2023-02-17 03:18 UTC, qqqdan commented
telemetry LGTM

2023-02-17 03:20 UTC, yiwen92 requested changes
Update chinese highlight

2023-02-17 04:39 UTC, yiwen92 requested changes
chinese structure reorg

2023-02-17 04:46 UTC, TomShawn commented
/rebase

2023-02-17 05:53 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复 Resolved TS 导致网络流量升高的问题 [#14098](https://github.com/tikv/tikv/issues/14092) @[overvenus](https://github.com/overvenus)
```suggestion
    - 修复 Resolved TS 导致网络流量升高的问题 [#14098](https://github.com/tikv/tikv/issues/14092) @[overvenus(https://github.com/overvenus)
```

2023-02-17 06:01 UTC, Yisaer approved these changes

2023-02-17 06:01 UTC, Yisaer commented on system-variables.md
> +- 这个变量用来控制 `PLAN REPLAYER CAPTURE` 抓取的内容是否默认带历史统计信息。默认值为 `OFF`，表示默认不带历史统计信息。
lgtm

2023-02-17 06:01 UTC, Yisaer commented on system-variables.md
> +- 这个变量用来控制是否开启 [`PLAN REPLAYER CAPTURE` 功能](/sql-plan-replayer.md#使用-plan-replayer-capture-抓取目标计划)。默认值 `ON` 代表开启 `PLAN REPLAYER CAPTURE` 功能。
lgtm

2023-02-17 06:03 UTC, hfxsd commented on releases/release-6.6.0.md
> +    - 修复调用 `ReportMinResolvedTS` 过于频繁的情况下造成 PD OOM 的问题  [#5965](https://github.com/tikv/pd/issues/5965) @[HundunDM](https://github.com/HunDunDM)
```suggestion
    - 修复调用 `ReportMinResolvedTS` 过于频繁导致 PD OOM 的问题 [#5965](https://github.com/tikv/pd/issues/5965) @[HundunDM](https://github.com/HunDunDM)
```

2023-02-17 06:03 UTC, hfxsd commented on releases/release-6.6.0.md
> +    - 修复了对 DECIMAL 数据类型进行除法运算时结果不舍入的问题 [#6393](https://github.com/pingcap/tiflash/issues/6393) @[LittleFall](https://github.com/LittleFall)
```suggestion
    - 修复对 DECIMAL 数据类型进行除法运算时结果不舍入的问题 [#6393](https://github.com/pingcap/tiflash/issues/6393) @[LittleFall](https://github.com/LittleFall)
```

2023-02-17 06:07 UTC, hfxsd commented on releases/release-6.6.0.md
> +    - 修复 TiDB 中事务在执行悲观 DML 失败后，再执行其他 DML 时，如果 TiDB 和 TiKV 之间存在网络故障，可能会造成数据不一致的问题 [#14038](https://github.com/tikv/tikv/issues/14038) @[MyonKeminta](https://github.com/MyonKeminta) @[myonkeminta](http
```suggestion
    - 修复 TiDB 中事务在执行悲观 DML 失败后，再执行其他 DML 时，如果 TiDB 和 TiKV 之间存在网络故障，可能会造成数据不一致的问题 [#14038](https://github.com/tikv/tikv/issues/14038) @[MyonKeminta](https://github.com/MyonKeminta)
```

2023-02-17 06:12 UTC, hfxsd commented on releases/release-6.6.0.md
> +    - 修复了 auto analyze 导致 graceful shutdown 耗时长的问题 [#40038](https://github.com/pingcap/tidb/issues/40038) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
```suggestion
    - 修复了 `auto analyze` 导致 graceful shutdown 耗时长的问题 [#40038](https://github.com/pingcap/tidb/issues/40038) @[xuyifangreeneyes](https://github.com/xuyifangreeneyes)
```

2023-02-17 06:14 UTC, hfxsd commented on releases/release-6.6.0.md
> +    - 修复 Resolved TS 导致网络流量升高的问题 [#14098](https://github.com/tikv/tikv/issues/14092) @[overvenus](https://github.com/overvenus)
这个 issue 号不一致 14098  14092

2023-02-17 08:35 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    在执行计划问题的排查过程中，`PLAN REPLAYER` 能够协助保存现场，提升诊断的效率。但在个别场景中，一些执行计划的生成无法任意重现，给诊断工作增加了难度。针对这类场景，在 TiDB v6.6.0 中，`PLAN REPLAYER` 扩展了自动捕获的能力。通过 `PLAN REPLAYER CAPTURE` 命令，用户可提前注册目标 SQL 语句，也可以同时指定目标执行计划。当
```suggestion
    在执行计划问题的排查过程中，`PLAN REPLAYER` 能够协助保存现场，提升诊断的效率。但在个别场景中，一些执行计划的生成无法任意重现，给诊断工作增加了难度。针对这类场景，在 TiDB v6.6.0 中，`PLAN REPLAYER` 扩展了自动捕获的能力。通过 `PLAN REPLAYER CAPTURE` 命令，你可提前注册目标 SQL 语句，也可以同时指定目标执行计划。当 TiDB 检测到执行的 SQL 语句或执行计划与注册目标匹配时，会自动生成并打包 `PLAN REPLAYER` 的信息，提升执行计划不稳定时的诊断效率。
```

2023-02-17 08:35 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    如果业务场景存在单点悲观锁冲突频繁的情况，原有的唤醒机制无法保证事务获取锁的时间，造成长尾延迟高，甚至获取锁超时。自 v6.6.0 起，用户可通过设置系统变量 [`tidb_pessimistic_txn_aggressive_locking`](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开
```suggestion
    如果业务场景存在单点悲观锁冲突频繁的情况，原有的唤醒机制无法保证事务获取锁的时间，造成长尾延迟高，甚至获取锁超时。自 v6.6.0 起，你可以通过设置系统变量 [`tidb_pessimistic_txn_aggressive_locking`](/system-variables.md#tidb_pessimistic_txn_aggressive_locking-从-v660-版本开始引入) 为 `ON` 开启悲观锁的稳定唤醒模型。在该唤醒模型下，队列的唤醒顺序可被严格控制，避免无效唤醒造成的资源浪费。在锁冲突严重的场景中，能够减少长尾延时，降低 P99 响应时间。
```

2023-02-17 08:35 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    在 v6.6.0 版本中，DM 的全量迁移能力集成了 TiDB Lightning 的 Physical Import Mode，使得 DM 全量数据迁移的性能最高可提升 10 倍，大大缩短了大数据量场景下的迁移时间。在 v6.6.0 以前，数据量较多的场景下，需要单独配置 TiDB Lightning 的 Physical Import Mode 任务来进行快速的全量数据迁移，再用 D
```suggestion
    在 v6.6.0 版本中，DM 的全量迁移能力集成了 TiDB Lightning 的 Physical Import Mode，使得 DM 全量数据迁移的性能最高可提升 10 倍，大大缩短了大数据量场景下的迁移时间。在 v6.6.0 以前，数据量较多的场景下，需要单独配置 TiDB Lightning 的 Physical Import Mode 任务来进行快速的全量数据迁移，再用 DM 来进行增量数据迁移，配置较为复杂。从 v6.6.0 起，在迁移大数据量的场景，无需再配置 TiDB Lightning 的任务，使用一个 DM 任务即可完成。
```

2023-02-17 08:35 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    TiDB v6.6.0 中引入了执行计划快速绑定功能，允许用户在 TiDB Dashboard 中快速完成 SQL 语句与特定计划的绑定。
```suggestion
    TiDB v6.6.0 中引入了执行计划快速绑定功能，你可以在 TiDB Dashboard 中快速完成 SQL 语句与特定计划的绑定。
```

2023-02-17 08:35 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    更多信息，参见[用户文档](/explain-mpp.md#启用-mpp-数据压缩的执行计划)。
```suggestion
    更多信息，请参考[用户文档](/explain-mpp.md#启用-mpp-数据压缩的执行计划)。
```

2023-02-17 08:35 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    更多信息，请参考[GORM 用户文档](https://gorm.io/docs/index.html)。
```suggestion
    更多信息，请参考 [GORM 用户文档](https://gorm.io/docs/index.html)。
```

2023-02-17 08:35 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    更多信息，请参考 v6.6.0 Release Notes 中 [SQL 部分](#sql)以及[用户文档](/sql-statements/sql-statement-create-index.md#多值索引)。
```suggestion
    更多信息，请参考本文 [SQL 部分](#sql)以及[用户文档](/sql-statements/sql-statement-create-index.md#多值索引)。
```

2023-02-17 08:35 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    - 修复 Resolved TS 导致网络流量升高的问题 [#14098](https://github.com/tikv/tikv/issues/14092) @[overvenus](https://github.com/overvenus)
```suggestion
    - 修复 Resolved TS 导致网络流量升高的问题 [#14092](https://github.com/tikv/tikv/issues/14092) @[overvenus](https://github.com/overvenus)
```

2023-02-17 08:41 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复 Resolved TS 导致网络流量升高的问题 [#14098](https://github.com/tikv/tikv/issues/14092) @[overvenus](https://github.com/overvenus)
```suggestion
    - 修复 Resolved TS 导致网络流量升高的问题 [#14092](https://github.com/tikv/tikv/issues/14092) @[overvenus](https://github.com/overvenus)
```

2023-02-17 09:14 UTC, songrijie approved these changes
LGTM

2023-02-17 09:20 UTC, joey-yez approved these changes

2023-02-17 10:03 UTC, TomShawn commented on releases/release-6.6.0.md
> +| [`tidb_enable_plan_replayer_capture`](/system-variables.md#tidb_enable_plan_replayer_capture) | 新增 | 这个变量用来控制是否开启 [`PLAN REPLAYER CAPTURE`](/sql-plan-replayer.md#使用-plan-replayer-capture-抓取目标计划)。默认
已添加

2023-02-17 10:07 UTC, benmaoer commented on releases/release-6.6.0.md
> +  </tr>
```suggestion
  </tr>
  <tr>
      <td>TiKV 支持下一代 Partitioned-Raft-KV 存储引擎</td>
      <td>TiKV 引入下一代存储引擎 Partitioned-Raft-KV，通过每个 Region 独享 RocksDB 实例轻松把集群的存储能力从 TB 级扩展到 PB 级，并提供更稳定的写入延迟和更强大的扩容能力 </td>
  </tr>
```

2023-02-17 10:11 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/explain-mpp.md##mpp-version-和-exchange-数据压缩)。
```suggestion
    更多信息，请参考[用户文档](/explain-mpp.md#mpp-version-和-exchange-数据压缩)。
```

2023-02-17 10:51 UTC, benmaoer commented on releases/release-6.6.0.md
> +
```suggestion
* 支持下一代 Partitioned-Raft-KV 存储引擎（实验特性）[#11515](https://github.com/tikv/tikv/issues/11515) [#12842](https://github.com/tikv/tikv/issues/12842) @[busyjay](https://github.com/busyjay) @[tonyxuqqi](https://github.com/tonyxuqqi) @[tabokie](https://github.com/tabokie) @[bufferflies](https://github.com/bufferflies) @[5kbpers](https://github.com/5kbpers) @[SpadeA-Tang](https://github.com/SpadeA-Tang) @[nolouch](https://github.com/nolouch)

        TiDB v6.6.0 之前，TiKV 基于 Raft 的存储引擎使用一个单一的 RocksDB 实例存储该 TiKV 实例所有 Region 的数据。为了更平稳的支持更大的集群，从 TiDB v6.6.0 开始，我们引入了一个全新的 TiKV 存储引擎，该引擎使用多个 RocksDB 实例来存储 TiKV 的 Region 数据，每个 Region 的数据都独立存储在单独的 RocksDB 实例中。新引擎能够更好的控制 RocksDB 实例的文件数和层级，并实现了 Region 间数据操作的物理隔离，避免互相影响，支持平稳管理更多的数据。可以理解为 TiKV 通过分区管理多个 RocksDB 实例，这也是该特性分区 Raft KV 名字的由来。该功能目前是实验特性，不推荐在生产环境中使用。该功能的主要优势在于更好的写入性能，更快的扩缩容，相同硬件下可以支持更大的数据，也能支持更大的集群规模。
        
```

2023-02-17 11:00 UTC, benmaoer requested changes
add partitioned_kv_raft highlight

2023-02-17 11:45 UTC, TomShawn commented on releases/release-6.6.0.md
> +  </tr>
already added to PR

2023-02-17 11:52 UTC, TomShawn commented on releases/release-6.6.0.md
> +
already added to PR

2023-02-17 12:14 UTC, yiwen92 approved these changes
LGTM

2023-02-17 12:36 UTC, yiwen92 reviewed
highlight adjustment

2023-02-17 12:50 UTC, TomShawn commented on releases/release-6.6.0.md
> +    [GORM 文档](https://github.com/go-gorm/gorm.io) 提及 TiDB 作为默认数据库 [#638](https://github.com/go-gorm/gorm.io/pull/638) @[Icemap](https://github.com/Icemap)
```suggestion
    - [GORM MySQL driver](https://github.com/go-gorm/mysql) 在 `v1.4.6` 中，新增 TiDB `AUTO_RANDOM` 特性适配 [#104](https://github.com/go-gorm/mysql/pull/104) @[Icemap](https://github.com/Icemap)。
    - [GORM MySQL driver](https://github.com/go-gorm/mysql) 在 `v1.4.6` 中，修复了连接 TiDB 时，在 `AutoMigrate` 期间无法更改 `Unique` 字段的非 `Unique` 属性的问题 [#105](https://github.com/go-gorm/mysql/pull/105) @[Icemap](https://github.com/Icemap)
    - [GORM 文档](https://github.com/go-gorm/gorm.io) 提及 TiDB 作为默认数据库 [#638](https://github.com/go-gorm/gorm.io/pull/638) @[Icemap](https://github.com/Icemap)
```

2023-02-17 13:14 UTC, Frank945946 approved these changes

2023-02-19 12:45 UTC, TomShawn commented on releases/release-6.6.0.md
> +| TiKV  | [`rocksdb.defaultcf.block-size`](/tikv-configuration-file.md#block-size) 和 [`rocksdb.writecf.block-size`](/tikv-configuration-file.md#block-size)  |  修改  |   默认值由 `64K` 调整为 `16K`。  |
```suggestion
| TiKV  | [`rocksdb.defaultcf.block-size`](/tikv-configuration-file.md#block-size) 和 [`rocksdb.writecf.block-size`](/tikv-configuration-file.md#block-size)  |  修改  |   默认值由 `64K` 调整为 `32K`。  |
```

2023-02-20 01:40 UTC, benmaoer approved these changes
LGTM

2023-02-20 01:44 UTC, easonn7 commented
LGTM

2023-02-20 01:48 UTC, qiancai commented on releases/release-6.6.0.md
> +    更多信息，请参考[用户文档](/placement-rules-in-sql.md#生存偏好)。
```suggestion
  更多信息，请参考[用户文档](/placement-rules-in-sql.md#生存偏好)。
```

2023-02-20 01:48 UTC, qiancai commented on releases/release-6.6.0.md
> +    持续引入优化器 Hint 为用户提供了更多的干预手段，有助于解决 SQL 性能问题，并提升了整体性能的稳定性。
```suggestion
  持续引入优化器 Hint 为用户提供了更多的干预手段，有助于解决 SQL 性能问题，并提升了整体性能的稳定性。
```

2023-02-20 01:48 UTC, qiancai commented on releases/release-6.6.0.md
> +    该功能默认关闭，你可以通过将 TiDB Lightning 配置项 `compress-kv-pairs` 设置为 "gzip" 或者 "gz" 开启此功能。
```suggestion
    该功能默认关闭，你可以通过将 TiDB Lightning 配置项 `compress-kv-pairs` 设置为 `"gzip"` 或者 `"gz"` 开启此功能。
```

2023-02-20 02:17 UTC, joccau commented on releases/release-6.6.0.md
> +- v6.6.0 及以上的 BR 版本不支持恢复数据到 v6.5.0 及以下版本的集群。
```suggestion
- v6.6.0 及以上的 BR 版本不支持恢复数据到 v6.1.0 及以下版本的集群。
```

2023-02-20 03:20 UTC, TomShawn commented on releases/release-6.6.0.md
> +* 支持兼容 MySQL 语法的多值索引 [#39592](https://github.com/pingcap/tidb/issues/39592) @[xiongjiwei](https://github.com/xiongjiwei) @[qw4990](https://github.com/qw4990)
```suggestion
* 支持兼容 MySQL 语法的多值索引（实验特性）[#39592](https://github.com/pingcap/tidb/issues/39592) @[xiongjiwei](https://github.com/xiongjiwei) @[qw4990](https://github.com/qw4990)
```

2023-02-20 03:20 UTC, TomShawn commented on releases/release-6.6.0.md
> +- 自 2023 年 2 月 20 日起，新发布的 TiDB 和 TiDB Dashboard 版本（含 v6.6.0），默认关闭遥测功能，即默认不再收集使用情况信息分享给 PingCAP。如果升级至这些版本前使用默认的遥测配置，则升级后遥测功能处于关闭状态。具体的版本可参考 [TiDB 版本发布时间线](/releases/release-timeline.md)。
```suggestion
- 自 2023 年 2 月 20 日起，新发布的 TiDB 和 TiDB Dashboard 版本（含 v6.6.0），默认关闭[遥测功能](/telemetry.md)，即默认不再收集使用情况信息分享给 PingCAP。如果升级至这些版本前使用默认的遥测配置，则升级后遥测功能处于关闭状态。具体的版本可参考 [TiDB 版本发布时间线](/releases/release-timeline.md)。
```

2023-02-20 03:21 UTC, TomShawn commented on releases/release-6.6.0.md
> +| TiKV | `storage.block-cache.block-cache-size` | 修改 | 从 v6.6.0 起，该配置项仅用于计算 `storage.block-cache.capacity` 的默认值。详情参见 [#12936](https://github.com/tikv/tikv/issues/12936)。 |
```suggestion
| TiKV | [`rocksdb.defaultcf.block-cache-size`](/tikv-configuration-file.md#block-cache-size), [`rocksdb.writecf.block-cache-size`](/tikv-configuration-file.md#block-cache-size), [`rocksdb.lockcf.block-cache-size`](/tikv-configuration-file.md#block-cache-size) | 修改 | 从 v6.6.0 起，该配置项仅用于计算 `storage.block-cache.capacity` 的默认值。详情参见 [#12936](https://github.com/tikv/tikv/issues/12936)。 |
```

2023-02-20 03:59 UTC, hfxsd approved these changes

2023-02-20 04:53 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    更多信息，请参考 v6.6.0 Release Notes 中 [SQL 部分](#sql-功能)以及[用户文档](/foreign-key.md)。
```suggestion
    更多信息，请参考本文的 [SQL 部分](#sql-功能)以及[用户文档](/foreign-key.md)。
```

2023-02-20 04:53 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    - 在 partitioned-raft-kv 模式下优化了一些参数的默认值：TiKV 配置项 `storage.block-cache.capacity` 的默认值由 45% 调整为 30%，`region-split-size` 的默认值由 `96MiB` 调整为 `10GiB`。当沿用 raft-kv 模式且 `enable-region-bucket` 为 `true` 时，`r
```suggestion
    - 在 partitioned-raft-kv 模式下优化了一些参数的默认值：TiKV 配置项 `storage.block-cache.capacity` 的默认值由 45% 调整为 30%，`region-split-size` 的默认值由 `96MiB` 调整为 `10GiB`。当沿用 raft-kv 模式且 `enable-region-bucket` 为 `true` 时，`region-split-size` 默认调整为 `1GiB` [#12842](https://github.com/tikv/tikv/issues/12842) @[tonyxuqqi](https://github.com/tonyxuqqi)
```

2023-02-20 04:53 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    - [GORM 文档](https://github.com/go-gorm/gorm.io) 提及 TiDB 作为默认数据库 [#638](https://github.com/go-gorm/gorm.io/pull/638) @[Icemap](https://github.com/Icemap)
```suggestion
    - [GORM 文档](https://github.com/go-gorm/gorm.io)提及 TiDB 作为默认数据库 [#638](https://github.com/go-gorm/gorm.io/pull/638) @[Icemap](https://github.com/Icemap)
```

2023-02-20 05:31 UTC, ran-huang commented on releases/release-6.6.0.md
> +    - [GORM 文档](https://github.com/go-gorm/gorm.io)提及 TiDB 作为默认数据库 [#638](https://github.com/go-gorm/gorm.io/pull/638) @[Icemap](https://github.com/Icemap)
```suggestion
    - [GORM MySQL driver](https://github.com/go-gorm/mysql) 在 `v1.4.6` 中，新增 TiDB `AUTO_RANDOM` 特性适配 [#104](https://github.com/go-gorm/mysql/pull/104)
    - [GORM MySQL driver](https://github.com/go-gorm/mysql) 在 `v1.4.6` 中，修复了连接 TiDB 时，在 `AutoMigrate` 期间无法更改 `Unique` 字段的非 `Unique` 属性的问题 [#105](https://github.com/go-gorm/mysql/pull/105)
    - [GORM 文档](https://github.com/go-gorm/gorm.io)提及 TiDB 作为默认数据库 [#638](https://github.com/go-gorm/gorm.io/pull/638)
```

2023-02-20 05:38 UTC, qiancai commented on releases/release-6.6.0.md
> +      <td>TiKV 引入下一代存储引擎 Partitioned-Raft-KV，通过每个数据 Region 独享 RocksDB 实例，轻松把集群的存储能力从 TB 级扩展到 PB 级，并提供更稳定的写入延迟和更强大的扩容能力。</td>
```suggestion
      <td>TiKV 引入下一代存储引擎 Partitioned-Raft-KV，通过每个数据 Region 独享 RocksDB 实例，可将集群的存储能力从 TB 级扩展到 PB 级，并提供更稳定的写入延迟和更强大的扩容能力。</td>
```

2023-02-20 05:38 UTC, qiancai commented on releases/release-6.6.0.md
> +    <td>引入资源管控框架，当前支持将资源配额映射到用户定义的资源组，在集群资源发生争用时，对资源组内用户的资源使用进行限制。</td>
```suggestion
    <td>引入资源管控框架，支持将资源配额映射到用户定义的资源组，在集群资源发生争用时，对资源组内用户的资源使用进行限制。</td>
```

2023-02-20 05:38 UTC, qiancai commented on releases/release-6.6.0.md
> +    - 修复了在改变时区后 TTL 任务可能会错误删除某些数据的问题 [41043](https://github.com/pingcap/tidb/issues/41043) @[lcwangchao](https://github.com/lcwangchao)
```suggestion
    - 修复了在改变时区后 TTL 任务可能会错误删除某些数据的问题 [#41043](https://github.com/pingcap/tidb/issues/41043) @[lcwangchao](https://github.com/lcwangchao)
```

2023-02-20 05:45 UTC, ran-huang approved these changes

2023-02-20 06:17 UTC, qiancai approved these changes

2023-02-20 06:25 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    <td>TiFlash 支持 <a href="https://docs.pingcap.com/zh/tidb/v6.6/stale-read" target="_blank">Stale Read</a> 和 <a href="https://docs.pingcap.com/zh/tidb/v6.6/explain-mpp#mpp-version-和-exchange-数据压缩"
```suggestion
    <td>TiFlash 支持 <a href="https://docs.pingcap.com/zh/tidb/v6.6/stale-read" target="_blank">Stale Read</a> 和<a href="https://docs.pingcap.com/zh/tidb/v6.6/explain-mpp#mpp-version-和-exchange-数据压缩" target="_blank">压缩数据交换</a></td>
```

2023-02-20 06:25 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +- TiCDC 支持在 Kafka 同步任务上开启单表的横向扩展功能，将单表的同步任务下发到多个 TiCDC 节点上执行 (实验特性) [#7720](https://github.com/pingcap/tiflow/issues/7720) @[overvenus](https://github.com/overvenus)
```suggestion
- TiCDC 支持在 Kafka 同步任务上开启单表的横向扩展功能，将单表的同步任务下发到多个 TiCDC 节点上执行（实验特性）[#7720](https://github.com/pingcap/tiflow/issues/7720) @[overvenus](https://github.com/overvenus)
```

2023-02-20 06:25 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +- TiCDC 支持在 Kafka 同步任务上开启单表的横向扩展功能，将单表的同步任务下发到多个 TiCDC 节点上执行 (实验特性) [#7720](https://github.com/pingcap/tiflow/issues/7720) @[overvenus](https://github.com/overvenus)
```suggestion
- TiCDC 支持在 Kafka 同步任务上开启单表的横向扩展功能，将单表的同步任务下发到多个 TiCDC 节点上执行（实验特性）[#7720](https://github.com/pingcap/tiflow/issues/7720) @[overvenus](https://github.com/overvenus)
```

2023-02-20 06:25 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +    更多信息，请[用户文档](/enable-tls-between-components.md)。
```suggestion
    更多信息，请参考[用户文档](/enable-tls-between-components.md)。
```

2023-02-20 06:33 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题。[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.
```suggestion
        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.com/pingcap/tiflow/issues/8001) [#5928](https://github.com/pingcap/tiflow/issues/5928) @[hicqu](https://github.com/hicqu) @[hi-rustin](https://github.com/hi-rustin)
```

2023-02-20 06:33 UTC, shichun-0415 commented on releases/release-6.6.0.md
> +        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题。[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.
```suggestion
        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.com/pingcap/tiflow/issues/8001) [#5928](https://github.com/pingcap/tiflow/issues/5928) @[hicqu](https://github.com/hicqu) @[hi-rustin](https://github.com/hi-rustin)
```

2023-02-20 06:59 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题[#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.c
```suggestion
        - 优化 pull-based sink 打开时 TiCDC 在 CPU 利用率、内存控制、吞吐等方面若干性能问题 [#8142](https://github.com/pingcap/tiflow/issues/8142) [#8157](https://github.com/pingcap/tiflow/issues/8157) [#8001](https://github.com/pingcap/tiflow/issues/8001) [#5928](https://github.com/pingcap/tiflow/issues/5928) @[hicqu](https://github.com/hicqu) @[hi-rustin](https://github.com/hi-rustin)
```

2023-02-20 06:59 UTC, Oreoxmt commented on releases/release-6.6.0.md
> +    - 新增 `balance-witness-scheduler` 调度器用于调度 witness [#5763](https://github.com/tikv/pd/pull/5763) @[ethercflow](https://github.com/ethercflow)
witness 功能在 6.6 没有引入，是否需要删除这一条 note？
@TomShawn @nathan-edgar

2023-02-20 07:01 UTC, Oreoxmt approved these changes
Rest LGTM

2023-02-20 08:16 UTC, shichun-0415 approved these changes
LGTM

2023-02-20 08:21 UTC, TomShawn commented on releases/release-6.6.0.md
> +    - 新增 `balance-witness-scheduler` 调度器用于调度 witness [#5763](https://github.com/tikv/pd/pull/5763) @[ethercflow](https://github.com/ethercflow)
```suggestion
```

2023-02-20 10:33 UTC, TomShawn commented
/merge

2023-02-20 10:35 UTC, merged