Hello World Apps - Java
pingcap/docs-cn pull request #14579
Opened 2023-07-19 09:42 UTC by Icemap

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [ ] master (the latest development version)
- [ ] v7.3 (TiDB 7.3 versions)
- [ ] v7.2 (TiDB 7.2 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v7.0 (TiDB 7.0 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2023-07-20 10:17 UTC, Icemap commented
/cc @Oreoxmt @Mini256

2023-07-21 04:31 UTC, Mini256 commented on develop/dev-guide-hello-world-java-hibernate.md
> +![hello-world-java-hibernate-dep-refresh](/media/develop/hello-world-java-hibernate-dep-refresh.jpg)
似乎并不是所有人右上角都会有刷新按钮，另外提示不太明显

2023-07-21 04:31 UTC, Mini256 commented on develop/dev-guide-hello-world-java-hibernate.md
> +> - `'`: `&apos;`
建议使用 `<details>` `<summary>` 标签替代, 提示放在配置文件后面。

放在配置代码前面，读者顺序阅读下来就会疑惑“哪里写了 `&amp;`”，结果发现是在后面

https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2

2023-07-21 04:31 UTC, Mini256 commented on develop/dev-guide-hello-world-java-hibernate.md
> +## 使用 Intellij IDEA 创建空白 Maven 程序
```suggestion
## 使用 IntelliJ IDEA 创建空白 Maven 程序
```

如果用户不使用 Intellij IDEA 的话呢

2023-07-21 05:01 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +![hello-world-java-maven-quickstart-create-project](/media/develop/hello-world-java-maven-quickstart-create-project.jpg)
Is there any reason?

2023-07-21 05:01 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +![hello-world-java-hibernate-dep-refresh](/media/develop/hello-world-java-hibernate-dep-refresh.jpg)
没有刷新按钮的应该是配置了自动刷新。提示不明显的部分，我要么加个箭头？这是个好想法吗？

2023-07-21 05:03 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +> - `'`: `&apos;`
Cool. Nice catch.

2023-07-21 05:09 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +## 使用 Intellij IDEA 创建空白 Maven 程序
Intellij IDEA 在 Java 中基本上是通用 IDE 了。再者，使用 Eclipse 和 VS Code 的 Java 程序员也并不需要 Hello World 教程。应为 Hello World Apps 是新手向的文档，Eclipse 至少使用 Java 有些年头，而使用编辑器加插件开发 Java 的程序员，我假定他们的经验会更加丰富。

2023-07-24 02:58 UTC, Mini256 commented on develop/dev-guide-hello-world-java-hibernate.md
> +![hello-world-java-maven-quickstart-create-project](/media/develop/hello-world-java-maven-quickstart-create-project.jpg)
图片会被拉伸

2023-07-24 03:00 UTC, Mini256 commented on develop/dev-guide-hello-world-java-hibernate.md
> +## 使用 Intellij IDEA 创建空白 Maven 程序
OK, 不过名称还是改一下 大小写

2023-07-24 03:02 UTC, Mini256 commented on develop/dev-guide-hello-world-java-mybatis.md
> +<summary>是否好奇配置中的 <code>&amp;</code> 是什么？</summary>
好像还是会被转义：

<img width="285" alt="image" src="https://github.com/pingcap/docs-cn/assets/5086433/f2dd7e88-2445-4a4e-b19f-c2be93bdccbb">

2023-07-24 04:08 UTC, Mini256 requested changes

2023-07-24 04:08 UTC, Mini256 commented on develop/dev-guide-hello-world-java-spring-boot-jpa.md
> +添加 `HelloWorldController.java`：
指出在那个包下

2023-07-24 04:08 UTC, Mini256 commented on develop/dev-guide-hello-world-java-spring-boot-jpa.md
> +![hello-world-java-spring-boot-jpa-result](/media/develop/hello-world-java-spring-boot-jpa-result.jpg)
同上，添加宽度限制，避免图片拉伸

2023-07-24 04:08 UTC, Mini256 commented on develop/dev-guide-hello-world-java-spring-boot-mybatis.md
> +添加 `HelloWorldController.java`：
在哪个包下添加，下同

2023-07-24 09:52 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +---
已更改四个文档内的标题和metadata。

2023-07-24 09:56 UTC, Mini256 commented on develop/dev-guide-hello-world-java-mybatis.md
> +```
结构上如果把源代码链接放到最前面，在最后在提示可以跳转到示例程序的文档查看如何进行 CRUD 和事务操作会不会要好一些。前文的部分也包括 @Oreoxmt 提到的“前提条件”。

在跳转到代码仓库的目录下可以添加一个 README.md, 附带 “Open on GitPod” 的入口。

参考：https://planetscale.com/docs/tutorials/connect-go-app

<img width="1034" alt="image" src="https://github.com/pingcap/docs-cn/assets/5086433/be1556e4-264a-46f1-b9cf-7c1fa0e1aebf">

2023-07-24 09:57 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +3. 打印展示。
Done

2023-07-24 10:04 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +</SimpleTab>
Done

2023-07-24 10:13 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +
Done

2023-07-24 10:17 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +## 获取你的 TiDB 参数信息
Done

2023-07-24 10:18 UTC, Icemap commented on develop/dev-guide-hello-world-java-spring-boot-mybatis.md
> +添加 `HelloWorldController.java`：
1. 有图示
2. 全限定名并非必要的出现在所有地方。

2023-07-24 10:20 UTC, Icemap commented on develop/dev-guide-hello-world-java-spring-boot-jpa.md
> +> **注意：**
确实是想使用 **注意：** 的。

2023-07-24 10:21 UTC, Icemap commented on develop/dev-guide-hello-world-java-spring-boot-jpa.md
> +- Type: 包管理器，此处使用 `Maven`
Done

2023-07-24 10:22 UTC, Icemap commented on develop/dev-guide-hello-world-java-spring-boot-jpa.md
> +3. HTTP 接口调用，并在返回值中展示。
是得到了 SQL 接口的返回值，并非 HTTP 接口的，已更改。

2023-07-24 10:27 UTC, Icemap commented on develop/dev-guide-hello-world-java-hibernate.md
> +![hello-world-java-maven-quickstart-create-project](/media/develop/hello-world-java-maven-quickstart-create-project.jpg)
当前整个文档站都没有这样的操作哦。

2023-07-24 10:52 UTC, Icemap commented on develop/dev-guide-hello-world-java-mybatis.md
> +在 `src/main/resources` 下创建 `mybatis-config.xml` 配置文件，内容如下，请使用在[获取你的 TiDB 参数信息](#获取你的-tidb-参数信息)一节中得到的 `host`, `port`, `user`, `password` 参数填充以下配置，在配置文件中，将使用形如 `${host}` 的占位符进行配置文件编写：
Done

2023-07-24 10:55 UTC, Icemap commented on develop/dev-guide-hello-world-java-mybatis.md
> +```
不能仅考虑用户顺序读文档，有可能是需要跳转的（而且非常有可能）。在看完整个文档之后才有 CRUD 的跳转并非一个好的实践。并且，这个文档基于 JetBrains IDE 编写，“Open on GitPod” / “Open with Codespace” 基于 VSCode，是否在 Golang / Python 等示例中更加适合？

2023-07-24 10:55 UTC, Icemap commented on develop/dev-guide-hello-world-java-spring-boot-jpa.md
> +2. 请使用在[获取你的 TiDB 参数信息](#获取你的-tidb-参数信息)一节中得到的 `host`, `port`, `user`, `password` 参数填充 `application.yaml` 配置，在配置文件中，将使用形如 `${host}` 的占位符进行配置文件编写：
Done

2023-07-25 02:26 UTC, Mini256 commented on develop/dev-guide-hello-world-java-mybatis.md
> +```
> 这个文档基于 JetBrains IDE 编写，“Open on GitPod” / “Open with Codespace” 基于 VSCode

看了一下 GitdPod 和 Codespace 对 JetBrains IDE 的支持，好像还是要在本地启动 IDE。https://www.gitpod.io/docs/references/ides-and-editors/intellij

> 在看完整个文档之后才有 CRUD 的跳转并非一个好的实践。

一般都会有 More resources / More reading 之类的小节

> 不能仅考虑用户顺序读文档，有可能是需要跳转的（而且非常有可能）。

那可能需要想想为啥读者刚点进来就要立刻跳转到其他章节，是不是因为标题引起了他的误解，认为 Hello World 的程序可能包含 CRUD 的示例。

2023-07-25 02:34 UTC, Mini256 commented on develop/dev-guide-hello-world-java-spring-boot-mybatis.md
> +添加 `HelloWorldController.java`：
> 1. 有图示

但是图示是在后面，在没有看见后面部分之前，读到这里我是不知道应该往哪里去创建这个 java 源文件的。

2023-07-26 00:36 UTC, Icemap commented on develop/dev-guide-hello-world-java-mybatis.md
> +```
OK. 那结论是：

1. 暂时不更改 GitPod/Codespace 部分
2. 将 Note 改为 Reading More 之类尾部章节

2023-07-26 01:44 UTC, Icemap commented
@Mini256 为本 PR 提供了 Example 的 README docs，PTAL： https://github.com/pingcap-inc/tidb-example-java/pull/9

2023-07-26 01:58 UTC, Icemap commented on develop/dev-guide-hello-world-java-mybatis.md
> +```
Done

2023-07-26 02:33 UTC, Icemap commented on develop/dev-guide-hello-world-java-spring-boot-mybatis.md
> +添加 `HelloWorldController.java`：
Done

2023-07-28 09:40 UTC, closed without merging