br: add description for --granularity
pingcap/docs-cn pull request #15944
Opened 2023-12-29 06:15 UTC by 3pointer

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [ ] master (the latest development version)
- [x] v7.6 (TiDB 7.6 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.4 (TiDB 7.4 versions)
- [ ] v7.3 (TiDB 7.3 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2023-12-29 06:59 UTC, BornChanger commented on br/br-snapshot-guide.md
> +- 在 TiDB v7.6 之后的版本中，通过指定 --concurrency 参数，可以控制单 TiKV 节点下载任务并发数，默认 128，适当调大该值可以让所有 TiKV 充分执行下载任务，直到打满下载带宽。
是否要用一个新参数?

2023-12-29 08:01 UTC, 3pointer commented on br/br-snapshot-guide.md
> +- 在 TiDB v7.6 之后的版本中，通过指定 --concurrency 参数，可以控制单 TiKV 节点下载任务并发数，默认 128，适当调大该值可以让所有 TiKV 充分执行下载任务，直到打满下载带宽。
cc @benmaoer

2024-01-04 09:12 UTC, benmaoer commented on br/br-snapshot-guide.md
> +
```suggestion

    ```sql
br restore full \
    --pd "${PDIP}:2379" \
    --storage "s3://${Bucket}/${Folder}" \
    --s3.region "${region}" \
    --granularity "coarse-grained" \
    --tikv-max-restore-concurrency 128 \
    --send-credentials-to-tikv=true \
    --log-file restorefull.log
    ```
 
```

2024-01-04 09:18 UTC, benmaoer commented on br/br-snapshot-guide.md
> +- 在 TiDB v7.6 之后的版本中，通过指定 --concurrency 参数，可以控制单 TiKV 节点下载任务并发数，默认 128，适当调大该值可以让所有 TiKV 充分执行下载任务，直到打满下载带宽。
```suggestion
- 在 v7.6.0 之后的版本中，BR 提供了一个实验性特性，允许通过指定新增的命令行参数 `--granularity=coarse-grained` 启用粗细粒度结合的 Region 打散算法和新增的命令行参数 `--tikv-max-restore-concurrency` 设置单 TiKV 节点的下载任务并发度，充分利用每个 TiKV 节点的所有资源实现了并行快速恢复。在实际案例中，大规模 Region 场景下，集群快照恢复速度最高提升约 10 倍。
```

2024-01-04 09:18 UTC, benmaoer requested changes
add new example for br restoration acceleration

2024-01-05 03:35 UTC, Oreoxmt commented on br/br-snapshot-guide.md
> +在 v7.6 版本之后，BR 支持了粗粒度打散 Region 的方式来进行恢复，以避免在 Region 过多的场景中，打散 Region 成为瓶颈的问题，通过指定 --granularity="coarse-grained" 的方式即可开启。
```suggestion
从 v7.6.0 开始，BR 支持粗粒度打散 Region 的方式来进行恢复，以避免在 Region 过多的场景中，打散 Region 成为瓶颈的问题，通过指定 `--granularity=coarse-grained` 的方式即可开启。
```

2024-01-05 03:38 UTC, Oreoxmt commented on br/br-snapshot-guide.md
> +从 v7.6.0 开始，BR 支持粗粒度打散 Region 的方式来进行恢复，以避免在 Region 过多的场景中，打散 Region 成为瓶颈的问题，通过指定 `--granularity=coarse-grained` 的方式即可开启。
```suggestion
为了解决在 Region 过多的情况下，打散 Region 可能成为恢复过程中的瓶颈问题，BR 从 v7.6.0 开始支持粗粒度打散 Region 的方式进行恢复。你可以通过指定 `--granularity=coarse-grained` 启用该方式。
```

2024-01-05 06:39 UTC, BornChanger approved these changes

2024-01-08 09:09 UTC, Oreoxmt approved these changes

2024-01-08 09:09 UTC, Oreoxmt approved these changes

2024-01-08 09:09 UTC, Oreoxmt commented on br/br-snapshot-guide.md
> +为了解决在 Region 过多的情况下，打散 Region 可能成为恢复过程中的瓶颈问题，BR 从 v7.6.0 开始支持粗粒度打散 Region 的方式进行恢复。你可以通过指定 `--granularity=coarse-grained` 启用该方式。
```suggestion
为了解决 Region 数量时，打散 Region 可能成为恢复过程中的瓶颈问题，BR 从 v7.6.0 开始支持粗粒度打散 Region 的方式进行恢复（实验特性）。你可以通过指定 `--granularity=coarse-grained` 启用该方式。
```

2024-01-09 03:50 UTC, Oreoxmt commented
/verify

2024-01-09 06:55 UTC, Oreoxmt commented on br/br-snapshot-guide.md
> +
```suggestion
```

2024-01-09 10:16 UTC, qiancai commented on br/br-snapshot-guide.md
> +    --granularity "coarse-grained" \
L202 写的是 `--granularity=coarse-grained`，哪个是对的呢，需要改成一致的吗 (release notes 里也有这个问题）

2024-01-09 10:16 UTC, qiancai commented on br/br-snapshot-guide.md
> +为了解决 Region 数量时，打散 Region 可能成为恢复过程中的瓶颈问题，BR 从 v7.6.0 开始支持粗粒度打散 Region 的方式进行恢复（实验特性）。你可以通过指定 `--granularity=coarse-grained` 启用该方式。
```suggestion
为了解决大规模 Region 场景下，打散 Region 可能成为恢复过程中的瓶颈问题，BR 从 v7.6.0 开始支持以粗粒度打散 Region 的方式进行恢复（实验特性）。你可以通过指定 `--granularity=coarse-grained` 启用该方式。
```

2024-01-09 10:16 UTC, qiancai commented on br/br-snapshot-guide.md
> +- 从 v7.6.0 开始，BR 提供了一个实验性特性，允许通过指定命令行参数 `--granularity=coarse-grained` 启用粗细粒度结合的 Region 打散算法。此外，可以使用 `--tikv-max-restore-concurrency` 设置单 TiKV 节点的下载任务并发度，充分利用每个 TiKV 节点的所有资源实现并行快速恢复。在实际案例中，大规模 Region
v7.6 release notes https://github.com/pingcap/docs-cn/pull/15667/files 里写的是，`--tikv-max-restore-concurrency` 设置单 TiKV 节点的恢复任务并发度，需要两边统一下吗

2024-01-09 10:28 UTC, 3pointer commented on br/br-snapshot-guide.md
> +    --granularity "coarse-grained" \
--granularity="coarse-grained" 和 --granularity "coarse-grained" 两个都是一样的效果

2024-01-09 10:29 UTC, 3pointer commented on br/br-snapshot-guide.md
> +- 从 v7.6.0 开始，BR 提供了一个实验性特性，允许通过指定命令行参数 `--granularity=coarse-grained` 启用粗细粒度结合的 Region 打散算法。此外，可以使用 `--tikv-max-restore-concurrency` 设置单 TiKV 节点的下载任务并发度，充分利用每个 TiKV 节点的所有资源实现并行快速恢复。在实际案例中，大规模 Region
统一成下载任务好一点

2024-01-09 15:11 UTC, qiancai commented on br/br-snapshot-guide.md
> +为了解决大规模 Region 场景下，打散 Region 可能成为恢复过程中的瓶颈问题，BR 从 v7.6.0 开始支持以粗粒度打散 Region 的方式进行恢复（实验特性）。你可以通过指定 `--granularity=coarse-grained` 启用该方式。
这里写的是 “以粗粒度打散”，L202 写的是 “粗细粒度结合的 Region 打散“，哪个更准确呢，要改成一致的吗

2024-01-11 07:14 UTC, 3pointer commented on br/br-snapshot-guide.md
> +为了解决大规模 Region 场景下，打散 Region 可能成为恢复过程中的瓶颈问题，BR 从 v7.6.0 开始支持以粗粒度打散 Region 的方式进行恢复（实验特性）。你可以通过指定 `--granularity=coarse-grained` 启用该方式。
fixed

2024-01-19 03:45 UTC, qiancai approved these changes

2024-01-19 05:36 UTC, Oreoxmt commented
/verify

2024-01-19 05:47 UTC, Oreoxmt commented
/approve

2024-01-19 05:48 UTC, merged