titan doc update
pingcap/docs-cn pull request #15954
Opened 2023-12-29 22:40 UTC by tonyxuqqi

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v7.6 (TiDB 7.6 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.4 (TiDB 7.4 versions)
- [ ] v7.3 (TiDB 7.3 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2024-01-02 09:25 UTC, Connor1996 commented on storage-engine/titan-configuration.md
> +3. [可选]数据整理结束后，通过 **TiKV-Details**/**Titan - kv** 监控面板确认 **Blob file count** 指标降为 0。
```suggestion
3. 数据整理结束后，通过 **TiKV-Details**/**Titan - kv** 监控面板确认 **Blob file count** 指标降为 0。
```

2024-01-02 09:25 UTC, Connor1996 commented on storage-engine/titan-overview.md
> +以上可见当行宽是2K时，Titan在所有指标上都超过了RocksDB。而当行宽是1KB时，Titan仅仅在scan10000上落后15%左右，但在update上大幅领先50%以上。因此`min-blob-size`默认值为1KB时比较合理的.
```suggestion
以上可见当行宽是2K时，Titan在所有指标上都超过了RocksDB。而当行宽是1KB时，Titan仅仅在scan10000上落后15%左右，但在update上大幅领先50%以上。因此 `min-blob-size` 默认值为1KB是比较合理的。用户可根据实际的负载偏好，来调整 `min-blob-size` 的大小。
```

2024-01-02 09:25 UTC, Connor1996 commented on storage-engine/titan-configuration.md
> +开启 Titan 以后，原有的数据并不会马上移入 Titan 引擎，而是随着前台写入和 RocksDB compaction 的进行，逐步进行 key-value 分离并写入 Titan。同样，全量、增量恢复或者Lightning导入的SST都是RocksDB格式，数据不会直接导入Titan。在Compaction过程中做数据搬迁到Titan。可以通过观察 **TiKV Details** -
```suggestion
开启 Titan 以后，原有的数据并不会马上移入 Titan 引擎，而是随着前台写入和 RocksDB compaction 的进行，逐步进行 key-value 分离并写入 Titan。同样，全量、增量恢复或者Lightning导入的SST都是RocksDB格式，数据不会直接导入Titan。随着Compaction的进行，大 value 会慢慢的分离到 Titan 中。可以通过观察 **TiKV Details** - **Titan kv** - **blob file size** 监控面版确认数据保存在 Titan 中部分的大小。
```

2024-01-02 09:25 UTC, Connor1996 commented on storage-engine/titan-overview.md
> +### min-blob-size的选择及其性能影响
这个放到 min-blob-size 配置那部分吧

2024-01-02 09:25 UTC, Connor1996 commented on storage-engine/titan-overview.md
> +### RocksDB和Titan之间的数据转换
这个放到开启/关闭 titan 配置那部分吧，就不放到原理里说了

2024-01-02 09:52 UTC, lilinghai commented on storage-engine/titan-configuration.md
>  - 当设置为 `read-only` 时，新写入的 value 不论大小均会写入 RocksDB。
https://docs.pingcap.com/zh/tidb/stable/tikv-configuration-file#blob-run-mode 这里配置是 read_only，需要统一一下

2024-01-02 09:52 UTC, lilinghai commented on storage-engine/titan-configuration.md
> +如果现有数据和未来数据均不再需要 Titan，可执行以下步骤完全关闭 Titan。然而一般情况下只需要执行以下步骤1和步骤4即可，步骤2、3会影响用户SQL的性能。在Compaction过程中会将数据从Titan移回RocksDB。
实测，没有步骤 2 对前台业务影响也较大

2024-01-02 09:52 UTC, lilinghai commented on storage-engine/titan-configuration.md
> ++ Titan 中 value 所使用的压缩算法。默认情况下，Titan 中压缩是以 value 为单元的。因此Titan的压缩率低于RocksDB相比。以Json内容为例，Titan的store size可能比RocksDB高30%至50%。 用户可以通过设置zstd_dict_size（比如16KB）启用字典ZSTD以大幅提高压缩率（实际Store Size可以低于RocksDB），但字典Z
这个是不是要把 json 和完全随机的情况下的压缩率都说明一下？

2024-01-04 05:04 UTC, Connor1996 reviewed
需要说明 v7.6 之后新集群默认开启，老集群升级上来仍然不会默认开启

2024-01-04 23:15 UTC, tonyxuqqi commented on storage-engine/titan-configuration.md
> ++ Titan 中 value 所使用的压缩算法。默认情况下，Titan 中压缩是以 value 为单元的。因此Titan的压缩率低于RocksDB相比。以Json内容为例，Titan的store size可能比RocksDB高30%至50%。 用户可以通过设置zstd_dict_size（比如16KB）启用字典ZSTD以大幅提高压缩率（实际Store Size可以低于RocksDB），但字典Z
完全随机的Value在实际系统里很少出现，而且如果是完全随机的话titan和rocksdb也没区别，用户也就不用关心压缩算法了。

2024-01-05 00:01 UTC, tonyxuqqi commented on storage-engine/titan-configuration.md
>  - 当设置为 `read-only` 时，新写入的 value 不论大小均会写入 RocksDB。
好的，应该是read-only，那里要改一下。

2024-01-05 00:08 UTC, tonyxuqqi commented on storage-engine/titan-configuration.md
> +如果现有数据和未来数据均不再需要 Titan，可执行以下步骤完全关闭 Titan。然而一般情况下只需要执行以下步骤1和步骤4即可，步骤2、3会影响用户SQL的性能。在Compaction过程中会将数据从Titan移回RocksDB。
@lilinghai 大概影响多大？主要是什么原因 @Connor1996

2024-01-05 00:11 UTC, tonyxuqqi commented on storage-engine/titan-overview.md
> +### min-blob-size的选择及其性能影响
这个内容太多了，配置部分仅仅是简单介绍，这里还有一个表格，还是单独说明一下更好。

2024-01-05 03:26 UTC, lilinghai commented
行数据长度小于 255 字节，那么会被存储 write 列中，否则的话该行数据会被存入到 default 列中。需要提示一下，用户数据如果行宽小于 255，又想开启 titan 的话，如何做

2024-01-05 07:05 UTC, hfxsd commented on storage-engine/titan-overview.md
> +基于向后兼容的考虑，TiKV在扩缩容时的Snapshot仍然是RocksDB的格式。因此扩容后的节点由于一开始全部来自RocksDB，因此会显式RocksDB的特征，比如压缩率会高于老的TiKV节点、Store Size会较小、同时Compaction的写放大会相对较大。后续这些RocksDB格式的SST参与Compaction之后逐步转换为Titan格式。
```suggestion
### 扩容与缩容

基于向后兼容的考虑，TiKV 在扩缩容时的 Snapshot 仍然是 RocksDB 的格式。因此扩容后的节点由于一开始全部来自RocksDB，因此会显示 RocksDB 的特征，比如压缩率会高于老的 TiKV 节点、Store Size 会较小、同时 Compaction 的写放大会相对较大。后续这些 RocksDB 格式的 SST 参与 Compaction 之后逐步转换为 Titan 格式。
```

2024-01-05 07:05 UTC, hfxsd commented on storage-engine/titan-overview.md
> +`min-blob-size` 是一个Value是否用Titan存储的依据。如果Value大于等于`min-blob-size`会用Titan存储，反之则用RocksDB原生的格式。当`min-blob-size`太小或太大都会导致性能下降。
```suggestion
`min-blob-size` 是一个 Value 是否用 Titan 存储的依据。如果 Value 大于或等于 `min-blob-size`，会用 Titan 存储，反之则用 RocksDB 原生的格式。当 `min-blob-size` 太小或太大都会导致性能下降。
```

2024-01-05 07:05 UTC, hfxsd commented on storage-engine/titan-overview.md
> +scan100是指scan 100条记录，scan10000指scan 10000条记录。
```suggestion
> **注意：**
>
> scan100 是指 scan 100 条记录，scan10000 指 scan 10000 条记录。
```

2024-01-05 07:05 UTC, hfxsd commented on storage-engine/titan-overview.md
> +以上可见当行宽是2K时，Titan在所有指标上都超过了RocksDB。而当行宽是1KB时，Titan仅仅在scan10000上落后15%左右，但在update上大幅领先50%以上。因此`min-blob-size`默认值为1KB是比较合理的.
行宽用 K 还是 KB？两处不一致。
```suggestion
以上可见当行宽是 2K 时，Titan 在所有指标上都超过了 RocksDB。而当行宽是 1KB 时，Titan 仅仅在 scan10000 上落后15% 左右，但在 update 上大幅领先 50% 以上。因此 `min-blob-size` 默认值为 1KB 是比较合理的。
```

2024-01-05 07:05 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 默认值：7.5及更老的版本false。 在7.6或更高版本，新建集群默认是true，已有集群升级到7.6或更高版本则会维持原有的配置。
```suggestion
+ 默认值：v7.5.0 及更早的版本为 `false`。 从 v7.6.0 开始，新建集群默认是 `true`，已有集群升级到 v7.6.0 或更高版本则会维持原有的配置。
```

2024-01-05 07:05 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 推荐值: 建议在数据库稳定运行后，根据监控把 RocksDB block cache (`storage.block-cache.capacity`) 设置为能刚好维持接近95%以上的Block Cache命中率，`blob-cache-size` 设置为 `内存大小 * 50% 再减去 block cache 的大小`。这是为了保证 block cache 足够缓存整个 RocksDB 的
```suggestion
+ 推荐值：建议在数据库稳定运行后，根据监控把 RocksDB block cache (`storage.block-cache.capacity`) 设置为能刚好维持接近 95% 以上的 Block Cache 命中率，`blob-cache-size` 设置为 `内存大小 * 50% 再减去 block cache 的大小`。这是为了保证 block cache 足够缓存整个 RocksDB 的前提下，blob cache 尽量大。但 Blob cache 的值不应该设置过大，否则会导致 block cache 命中率大幅下降。
```

2024-01-05 07:30 UTC, lilinghai commented on storage-engine/titan-configuration.md
> +如果现有数据和未来数据均不再需要 Titan，可执行以下步骤完全关闭 Titan。然而一般情况下只需要执行以下步骤1和步骤4即可，步骤2、3会影响用户SQL的性能。在Compaction过程中会将数据从Titan移回RocksDB。
![image](https://github.com/pingcap/docs-cn/assets/7677963/92895865-8fd7-4c62-bf20-ae8ff836a047)

2024-01-05 07:32 UTC, lilinghai commented on storage-engine/titan-configuration.md
> ++ Titan 中 value 所使用的压缩算法。默认情况下，Titan 中压缩是以 value 为单元的。因此Titan的压缩率低于RocksDB相比。以Json内容为例，Titan的store size可能比RocksDB高30%至50%。 用户可以通过设置zstd_dict_size（比如16KB）启用字典ZSTD以大幅提高压缩率（实际Store Size可以低于RocksDB），但字典Z
但是当时的确是出现了 rocksdb 数据低于 titan 几百个 GB，或者把这个现象给用户解释一下也好

2024-01-05 18:36 UTC, tonyxuqqi commented
> 行数据长度小于 255 字节，那么会被存储 write 列中，否则的话该行数据会被存入到 default 列中。需要提示一下，用户数据如果行宽小于 255，又想开启 titan 的话，如何做

小于255用户不应该开启titan，任何情况下都不应该。

2024-01-05 18:41 UTC, tonyxuqqi commented on storage-engine/titan-configuration.md
> ++ Titan 中 value 所使用的压缩算法。默认情况下，Titan 中压缩是以 value 为单元的。因此Titan的压缩率低于RocksDB相比。以Json内容为例，Titan的store size可能比RocksDB高30%至50%。 用户可以通过设置zstd_dict_size（比如16KB）启用字典ZSTD以大幅提高压缩率（实际Store Size可以低于RocksDB），但字典Z
我看看怎么写比较好。这个很难解释，随机其实也不是真的完全随机，每个value之间还是有相似性的，不然rocksdb也没法压缩。
之前测试出现这个问题的情况是每个value本身不大，也内部缺乏相似性，但是不同value之间有一些相似点，放一起也能压缩一些。

2024-01-05 18:53 UTC, tonyxuqqi commented on storage-engine/titan-configuration.md
> ++ Titan 中 value 所使用的压缩算法。默认情况下，Titan 中压缩是以 value 为单元的。因此Titan的压缩率低于RocksDB相比。以Json内容为例，Titan的store size可能比RocksDB高30%至50%。 用户可以通过设置zstd_dict_size（比如16KB）启用字典ZSTD以大幅提高压缩率（实际Store Size可以低于RocksDB），但字典Z
已添加的配置文档中。

2024-01-08 06:49 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> 在7.6.0开始，新建集群默认打开Titan，已有集群升级到7.6.0则会维持原有的配置, 没有显式配置titan的，则仍然会使用RocksDB。
```suggestion
如果需要加速数据移入 Titan，可以通过 tikv-ctl 执行一次全量 compaction，请参考[手动 compact](/tikv-control.md#手动-compact-整个-tikv-集群的数据)。由于 RocksDB 有 Block Cache，且转成 Titan 时的数据访问是连续的，因此Block Cache 能有很好的命中率。在测试中，一个 670 GiB 的 TiKV 节点数据，通过 tikv-ctl 全量 compaction 转成 Titan，只需 1 小时。

> **注意：**
>
> 在 v7.6.0 开始，新建集群默认打开 Titan。已有集群升级到 v7.6.0 则会维持原有的配置，如果没有显式配置 Titan，则仍然会使用 RocksDB。
```

2024-01-08 06:50 UTC, hfxsd commented on storage-engine/titan-configuration.md
> ++ Titan 中 value 所使用的压缩算法。在7.6版本开始，默认采用zstd压缩算法。
```suggestion
+ Titan 中 value 所使用的压缩算法。从 v7.6.0 开始，默认采用 `zstd` 压缩算法。
```

2024-01-08 06:53 UTC, hfxsd commented on storage-engine/titan-configuration.md
> ++ 默认情况下, zstd-dict-size为 0KB , 表示Titan中压缩的是单个value值，而RocksDB压缩以Block(默认 32KB )为单位。因此当value平均小于 32KB 时，Titan的压缩率低于RocksDB。以Json内容为例，Titan的store size可能比RocksDB高30%至50%。实际压缩率还取决于value内容是否适合压缩，以及不同value之
```suggestion
+ 默认情况下，`zstd-dict-size` 为 `0KB` , 表示 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB`）为单位。因此当 value 平均小于 32KB 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB 高 30% 至 50%。实际压缩率还取决于 value 内容是否适合压缩，以及不同 value 之间的相似性。你可以通过设置 `zstd-dict-size`（比如 `16KB` ）启用 `zstd` 字典压缩以大幅提高压缩率（实际 Store Size 可以低于 RocksDB）。但 `zstd` 字典压缩在有些负载下会有 10% 左右的性能损失。
```

2024-01-08 06:54 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +如果现有数据和未来数据均不再需要 Titan，可执行以下步骤完全关闭 Titan。然而一般情况下只需要执行以下步骤1和步骤3、4即可，步骤2会加快数据迁移速度，但会严重影响用户SQL的性能。事实上即便跳过步骤2，由于在Compaction过程中会将数据从Titan迁移到RocksDB，会占用额外的 IO 和 CPU 资源，因此仍然可以观察到一定的性能损失，在资源紧张的情况下吞吐可以下降 50%
```suggestion
如果现有数据和未来数据均不再需要 Titan，可执行以下步骤完全关闭 Titan。然而一般情况下只需要执行以下步骤 1 和步骤 3、步骤 4 即可，步骤 2 会加快数据迁移速度，但会严重影响用户 SQL 的性能。事实上即便跳过步骤 2，由于在Compaction 过程中会将数据从 Titan 迁移到 RocksDB，会占用额外的 IO 和 CPU 资源，因此仍然可以观察到一定的性能损失，在资源紧张的情况下吞吐可以下降 50% 以上。
```

2024-01-08 06:55 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +    > discardable-ratio在磁盘空间不足以同时保持titan和rocksdb数据时应该维持默认值。一般来说如果磁盘可用空间小于50%时推荐使用默认值。因为当discardable-ratio = 1.0时, Rocksdb数据一方面在不断增加，同时titan原有的blob文件回收需要该文件所有数据都迁移至RocksDB才会发生，这个过程会比较缓慢。discardable-ra
```suggestion
    > `discardable-ratio` 在磁盘空间不足以同时保持 Titan 和 RocksDB 数据时应该维持默认值。一般来说，如果磁盘可用空间小于 50% 时，推荐使用默认值。因为当 `discardable-ratio = 1.0` 时，RocksDB 数据一方面在不断增加，同时 Titan 原有的 blob 文件回收需要该文件所有数据都迁移至 RocksDB 才会发生，这个过程会比较缓慢。`discardable-ratio = 1.0` 带来的好处是减小 compaction 过程中 Blob 文件自身的 GC，节省了带宽。
```

2024-01-08 06:56 UTC, hfxsd commented on storage-engine/titan-overview.md
> +基于向后兼容的考虑，TiKV 在扩缩容时的 Snapshot 仍然是 RocksDB 的格式。因此扩容后的节点由于一开始全部来自RocksDB，因此会显示 RocksDB 的特征，比如压缩率会高于老的 TiKV 节点、Store Size 会较小、同时 Compaction 的写放大会相对较大。后续这些 RocksDB 格式的 SST 参与 Compaction 之后逐步转换为 Titan 格式
```suggestion
基于向后兼容的考虑，TiKV 在扩缩容时的 Snapshot 仍然是 RocksDB 的格式。因此扩容后的节点由于一开始全部来自 RocksDB，因此会显示 RocksDB 的特征，比如压缩率会高于老的 TiKV 节点、Store Size 会较小、同时 Compaction 的写放大会相对较大。后续这些 RocksDB 格式的 SST 参与 Compaction 之后逐步转换为 Titan 格式。
```

2024-01-08 06:57 UTC, hfxsd commented on storage-engine/titan-overview.md
> +### min-blob-size的选择及其性能影响
```suggestion
### `min-blob-size` 的选择及其性能影响
```

2024-01-08 06:57 UTC, hfxsd commented on storage-engine/titan-overview.md
> +> scan100 是指 scan 100 条记录，scan10000 指 scan 10000 条记录。
```suggestion
> `scan100` 是指 scan 100 条记录，`scan10000` 指 scan 10000 条记录。
```

2024-01-08 06:58 UTC, hfxsd commented on storage-engine/titan-overview.md
> +以上可见当行宽是 2KB 时，Titan在所有指标上都超过了RocksDB。而当行宽是 1KB 时，Titan仅仅在scan10000上落后15%左右，但在update上大幅领先50%以上。因此`min-blob-size`默认值为 1KB 是比较合理的.
```suggestion
以上可见，当行宽是 2KB 时，Titan 在所有指标上都超过了 RocksDB。而当行宽是 1KB 时，Titan 仅仅在 `scan10000` 上落后 15% 左右，但在 `UPDATE` 上大幅领先 50% 以上。因此 `min-blob-size` 默认值为 1KB 是比较合理的。
```

2024-01-08 07:00 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 指定zstd字典大小，默认为 0KB 表示关闭zstd字典压缩，也就是说Titan中压缩的是单个value值，而RocksDB压缩以Block(默认 32KB )为单位。因此当关闭字典压缩时且value平均小于 32KB 时，Titan的压缩率低于RocksDB。以Json内容为例，Titan的store size可能比RocksDB高30%至50%。实际压缩率还取决于value内容是否适合
```suggestion
+ 指定  ZSTD字典大小，默认为 `0KB`，表示关闭 ZSTD 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB` ）为单位。因此当关闭字典压缩、且 value 平均小于 32KB 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB 高 30% 至 50%。实际压缩率还取决于 value 内容是否适合压缩，以及不同 value 之间的相似性。你可以通过设置 `zstd-dict-size`（比如 `16KB` ）启用 ZSTD 字典以大幅提高压缩率（实际 Store Size 可以低于 RocksDB），但  ZSTD 字典压缩在有些负载下会有 10% 左右的性能损失。
```

2024-01-08 07:08 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +    当写入的 value 小于这个值时，value 会保存在 RocksDB 中，反之则保存在 Titan 的 blob file 中。根据 value 大小的分布，增大这个值可以使更多 value 保存在 RocksDB，读取这些小 value 的性能会稍好一些；减少这个值可以使更多 value 保存在 Titan 中，进一步减少 RocksDB compaction。经过[测试](/st
```suggestion
    当写入的 value 小于这个值时，value 会保存在 RocksDB 中，反之则保存在 Titan 的 blob file 中。根据 value 大小的分布，增大这个值可以使更多 value 保存在 RocksDB，读取这些小 value 的性能会稍好一些；减少这个值可以使更多 value 保存在 Titan 中，进一步减少 RocksDB compaction。经过[测试](/storage-engine/titan-overview.md#min-blob-size-的选择及其性能影响)，1 KB是一个比较折中的值。如果发现系统磁盘占用过大可以进一步调高这个值。
```

2024-01-08 07:15 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +开启 Titan 以后，原有的数据并不会马上移入 Titan 引擎，而是随着前台写入和 RocksDB compaction 的进行，逐步进行 key-value 分离并写入 Titan。同样，全量、增量恢复或者 TiDB Lightning 导入的 SST 都是 RocksDB 格式，数据不会直接导入Titan。随着 Compaction 的进行，被处理过的 SST 中的大 value 会分离
```suggestion
开启 Titan 以后，原有的数据并不会马上移入 Titan 引擎，而是随着前台写入和 RocksDB compaction 的进行，逐步进行 key-value 分离并写入 Titan。同样，全量、增量恢复或者 TiDB Lightning 导入的 SST 都是 RocksDB 格式，数据不会直接导入 Titan。随着 Compaction 的进行，被处理过的 SST 中的大 value 会分离到 Titan 中。可以通过观察 **TiKV Details** - **Titan kv** - **blob file size** 监控面版确认数据保存在 Titan 中部分的大小。
```

2024-01-08 08:00 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +如果需要加速数据移入 Titan，可以通过 tikv-ctl 执行一次全量 compaction，请参考[手动 compact](/tikv-control.md#手动-compact-整个-tikv-集群的数据)。由于 RocksDB 有 Block Cache，且转成 Titan 时的数据访问是连续的，因此Block Cache 能有很好的命中率。在测试中，一个 670 GiB 的 TiKV
```suggestion
如果需要加速数据移入 Titan，可以通过 tikv-ctl 执行一次全量 compaction，请参考[手动 compact](/tikv-control.md#手动-compact-整个-tikv-集群的数据)。由于 RocksDB 有 Block Cache，且转成 Titan 时的数据访问是连续的，因此 Block Cache 能有很好的命中率。在测试中，一个 670 GiB 的 TiKV 节点数据，通过 tikv-ctl 全量 compaction 转成 Titan，只需 1 小时。
```

2024-01-08 10:25 UTC, hfxsd commented on storage-engine/titan-configuration.md
> ++ 默认情况下，`zstd-dict-size` 为 `0KB` , 表示 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB`）为单位。因此当 value 平均小于 32KB 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB 高 30% 至 50%。实际压缩率
```suggestion
+ 默认情况下，`zstd-dict-size` 为 `0KB`，表示 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB`）为单位。因此当 value 平均小于 32KB 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB 高 30% 至 50%。实际压缩率还取决于 value 内容是否适合压缩，以及不同 value 之间的相似性。你可以通过设置 `zstd-dict-size`（比如 `16KB` ）启用 ZSTD 字典压缩以大幅提高压缩率（实际 Store Size 可以低于 RocksDB）。但  ZSTD 字典压缩在有些负载下会有 10% 左右的性能损失。
```

2024-01-08 11:03 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +如果现有数据和未来数据均不再需要 Titan，可执行以下步骤完全关闭 Titan。然而一般情况下只需要执行以下步骤 1 和步骤 3、步骤 4 即可，步骤 2 会加快数据迁移速度，但会严重影响用户 SQL 的性能。事实上即便跳过步骤 2，由于在Compaction 过程中会将数据从 Titan 迁移到 RocksDB，会占用额外的 IO 和 CPU 资源，因此仍然可以观察到一定的性能损失，在资源紧
```suggestion
如果现有数据和未来数据均不再需要 Titan，可执行以下步骤完全关闭 Titan。然而一般情况下只需要执行以下步骤 1 和步骤 3、步骤 4 即可，步骤 2 会加快数据迁移速度，但会严重影响用户 SQL 的性能。事实上即便跳过步骤 2，由于在 Compaction 过程中会将数据从 Titan 迁移到 RocksDB，会占用额外的 IO 和 CPU 资源，因此仍然可以观察到一定的性能损失，在资源紧张的情况下吞吐可以下降 50% 以上。
```

2024-01-08 11:12 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +由于 Titan Blob 文件中的 Value 是不连续的，而且 Titan 的 Cache 是 Value 级别，因此 Blob Cache 无法帮助 compaction。从 Titan 转到 RocksDB 速度相比 RocksDB 转 Titan 会慢一个数量级。在测试中，一个 800 GiB 的 TiKV 节点Titan 数据通过 tikv-ctl 做全量 compaction 转成
```suggestion
由于 Titan Blob 文件中的 Value 是不连续的，而且 Titan 的 Cache 是 Value 级别，因此 Blob Cache 无法帮助 compaction。从 Titan 转到 RocksDB 速度相比 RocksDB 转 Titan 会慢一个数量级。在测试中，一个 800 GiB 的 TiKV 节点 Titan 数据通过 tikv-ctl 做全量 compaction 转成 RocksDB，需要 12 个小时。
```

2024-01-08 11:25 UTC, hfxsd commented on storage-engine/titan-overview.md
> +`min-blob-size` 是一个 Value 是否用 Titan 存储的依据。如果 Value 大于或等于 `min-blob-size`，会用 Titan 存储，反之则用 RocksDB 原生的格式。当 `min-blob-size` 太小或太大都会导致性能下降。
```suggestion
`min-blob-size` 是一个 Value 是否用 Titan 存储的依据。如果 Value 大于或等于 `min-blob-size`，会用 Titan 存储，反之则用 RocksDB 原生的格式。当 `min-blob-size` 太小或太大都会导致性能下降。下表是不同负载下 `min-blob-size` 的性能的测试结果。
```

2024-01-08 11:29 UTC, hfxsd commented on storage-engine/titan-overview.md
> +以上可见，当行宽是 2KB 时，Titan 在所有指标上都超过了 RocksDB。而当行宽是 1KB 时，Titan 仅仅在 `scan10000` 上落后 15% 左右，但在 `UPDATE` 上大幅领先 50% 以上。因此 `min-blob-size` 默认值为 1KB 是比较合理的。
```suggestion
以上可见，当行宽是 2KB 时，Titan 在所有指标上都超过了 RocksDB。而当行宽是 1KB 时，Titan 仅仅在 `scan10000` 上落后 15% 左右，但在 `UPDATE` 上大幅领先 50% 以上。因此 `min-blob-size` 默认值为 1KB 是比较合理的。你可以根据实际负载设置 `min-blob-size` 的值。
```

2024-01-08 11:33 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 指定  ZSTD字典大小，默认为 `0KB`，表示关闭 ZSTD 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB` ）为单位。因此当关闭字典压缩、且 value 平均小于 32KB 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB 高
```suggestion
+ 指定  zstd 字典大小，默认为 `0KB`，表示关闭 zstd 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB` ）为单位。因此当关闭字典压缩、且 value 平均小于 32KB 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB 高 30% 至 50%。实际压缩率还取决于 value 内容是否适合压缩，以及不同 value 之间的相似性。你可以通过设置 `zstd-dict-size`（比如 `16KB` ）启用 zstd 字典以大幅提高压缩率（实际 Store Size 可以低于 RocksDB），但 zstd 字典压缩在有些负载下会有 10% 左右的性能损失。
```

2024-01-08 11:40 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 默认值: 0
```suggestion
+ 默认值: `"0KB"`
```

2024-01-08 13:26 UTC, hfxsd commented on storage-engine/titan-overview.md
> +| 行宽(Bytes)      | pointget | pointget(titan)| scan100 | scan100(titan)| scan10000 | scan10000(titan)| update | update titan |
```suggestion
| 行宽 (Bytes)      | pointget | pointget (Titan)| scan100 | scan100 (Titan)| scan10000 | scan10000 (Titan)| `UPDATE` | `UPDATE` (Titan) |
```

2024-01-08 13:26 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 默认值：v7.5.0 及更早的版本为 `false`。 从 v7.6.0 开始，新建集群默认是 `true`，已有集群升级到 v7.6.0 或更高版本则会维持原有的配置。
```suggestion
+ 默认值：v7.5.0 及更早的版本为 `false`。从 v7.6.0 开始，新建集群默认是 `true`，已有集群升级到 v7.6.0 或更高版本则会维持原有的配置。
```

2024-01-08 13:27 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 指定 zstd 字典大小，默认为 `0KB`，表示关闭 zstd 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB` ）为单位。因此当关闭字典压缩、且 value 平均小于 `32KB` 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB
```suggestion
+ 指定 zstd 字典大小，默认为 `0KB`，表示关闭 zstd 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB`）为单位。因此当关闭字典压缩、且 value 平均小于 `32KB` 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB 高 30% 至 50%。实际压缩率还取决于 value 内容是否适合压缩，以及不同 value 之间的相似性。你可以通过设置 `zstd-dict-size`（比如 `16KB`）启用 zstd 字典以大幅提高压缩率（实际 Store Size 可以低于 RocksDB），但 zstd 字典压缩在有些负载下会有 10% 左右的性能损失。
```

2024-01-09 01:07 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +    > `discardable-ratio` 在磁盘空间不足以同时保持 Titan 和 RocksDB 数据时应该维持默认值。一般来说，如果磁盘可用空间小于 50% 时，推荐使用默认值。因为当 `discardable-ratio = 1.0` 时，RocksDB 数据一方面在不断增加，同时 Titan 原有的 blob 文件回收需要该文件所有数据都迁移至 RocksDB 才会发生，这个过
```suggestion
    > `discardable-ratio` 在磁盘空间不足以同时保持 Titan 和 RocksDB 数据时应该维持默认值 `0.5`。一般来说，如果磁盘可用空间小于 50% 时，推荐使用默认值。因为当 `discardable-ratio = 1.0` 时，RocksDB 数据一方面在不断增加，同时 Titan 原有的 blob 文件回收需要该文件所有数据都迁移至 RocksDB 才会发生，这个过程会比较缓慢。`discardable-ratio = 1.0` 带来的好处是减小 compaction 过程中 Blob 文件自身的 GC，节省了带宽。
```

2024-01-09 02:02 UTC, hfxsd commented on storage-engine/titan-overview.md
> +`min-blob-size` 是一个 Value 是否用 Titan 存储的依据。如果 Value 大于或等于 `min-blob-size`，会用 Titan 存储，反之则用 RocksDB 原生的格式。当 `min-blob-size` 太小或太大都会导致性能下降。下表是不同负载下 `min-blob-size` 的性能的测试结果。
```suggestion
`min-blob-size` 是决定一个 Value 是否用 Titan 存储的依据。如果 Value 大于或等于 `min-blob-size`，会用 Titan 存储，反之则用 RocksDB 原生的格式。当 `min-blob-size` 太小或太大时，都会导致性能下降。下表是不同负载下 `min-blob-size` 的性能测试结果。
```

2024-01-09 02:03 UTC, hfxsd commented on storage-engine/titan-overview.md
> +| 行宽 (Bytes)      | pointget | pointget (Titan)| scan100 | scan100 (Titan)| scan10000 | scan10000 (Titan)| `UPDATE` | `UPDATE` (Titan) |
```suggestion
| 行宽 (Bytes)      | `Point_Get` |  `Point_Get` (Titan)| scan100 | scan100 (Titan)| scan10000 | scan10000 (Titan)| `UPDATE` | `UPDATE` (Titan) |
```

2024-01-15 04:18 UTC, Connor1996 approved these changes
LGTM

2024-01-15 07:18 UTC, ran-huang commented on storage-engine/titan-overview.md
> +> `scan100` 是指 scan 100 条记录，`scan10000` 指 scan 10000 条记录。
```suggestion
> `scan100` 是指扫描 100 条记录，`scan10000` 指扫描 10000 条记录。
```

2024-01-15 07:18 UTC, ran-huang commented on tikv-configuration-file.md
> +### `zstd-dict-size`
这里建议按字母顺序排列

2024-01-22 02:43 UTC, benmaoer commented on storage-engine/titan-configuration.md
由于 Titan 默认开启了，建议在这里增加上如果通过 TiDB-Operator 开启/关闭 Titan 的说明

2024-01-22 03:32 UTC, benmaoer commented on storage-engine/titan-configuration.md
```suggestion

+ 方法三：编辑 TiDB-Operator 的 ${cluster_name}/tidb-cluster.yaml 配置文件，编辑示例如下：
  
    {{< copyable "" >}}

    ``` yaml
      tikv:
        ## Base image of the component
        baseImage: pingcap/tikv

        ## tikv-server configuration
        ## Ref: https://docs.pingcap.com/tidb/stable/tikv-configuration-file
        config: |
          log-level = "info"      

          [rocksdb]
            [rocksdb.titan]
              enabled = true
    ```

    应用配置时默认会触发在线滚动重启 TiDB 集群让配置生效：

     {{< copyable "shell-regular" >}}

    ```shell
    kubectl apply -f ${cluster_name} -n ${namespace}
    ```   

    更多信息可参考[在 Kubernetes 中配置 TiDB 集群](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/configure-a-tidb-cluster)。

```

2024-01-22 03:59 UTC, benmaoer commented on storage-engine/titan-configuration.md
> +开启 Titan 以后，原有的数据并不会马上移入 Titan 引擎，而是随着前台写入和 RocksDB compaction 的进行，逐步进行 key-value 分离并写入 Titan。同样，全量、增量恢复或者 TiDB Lightning 导入的 SST 都是 RocksDB 格式，数据不会直接导入 Titan。随着 Compaction 的进行，被处理过的 SST 中的大 value 会分
```suggestion
开启 Titan 以后，原有的数据并不会马上迁移到 Titan 引擎，而是随着前台写入和 RocksDB Compaction 的进行，逐步进行 key-value 分离并写入 Titan。同样的，无论是通过 [BR 快照/日志恢复](/br/backup-and-restore-overview.md) 的数据，还是通过 [TiDB Lightning](/tidb-lightning/tidb-lightning-overview.md) 逻辑/物理导入的数据，都是先写入 RocksDB，再通过 RocksDB Compaction 的进行，逐步分离超过 [32KB](tikv-configuration-file.md#min-blob-size) 的大 value 到 Titan 中。用户可以通过观察 **TiKV Details** - **Titan kv** - **blob file size** 监控面版中文件的大小来确认存储在 Titan 中的数据大小。
```

2024-01-22 04:13 UTC, benmaoer commented on storage-engine/titan-configuration.md
> +如果需要加速数据移入 Titan，可以通过 tikv-ctl 执行一次全量 compaction，请参考[手动 compact](/tikv-control.md#手动-compact-整个-tikv-集群的数据)。由于 RocksDB 有 Block Cache，且转成 Titan 时的数据访问是连续的，因此 Block Cache 能有很好的命中率。在测试中，TiKV 节点上 670 GiB
```suggestion
如果希望加快数据迁移到 Titan 的过程，可以通过 tikv-ctl 执行一次全量 Compaction，请参考[手动 compact](/tikv-control.md#手动-compact-整个-tikv-集群的数据)。由于 RocksDB 有 Block Cache，且转成 Titan 时的数据访问是连续的，因此 Block Cache 能有很好的命中率。在测试中，仅需要 1 个小时即可通过 tikv-ctl 完成单个TiKV 节点上 670 GiB 的数据的全量 Compaction。
```

2024-01-22 04:16 UTC, benmaoer commented on storage-engine/titan-configuration.md
> +    当写入的 value 小于这个值时，value 会保存在 RocksDB 中，反之则保存在 Titan 的 blob file 中。根据 value 大小的分布，增大这个值可以使更多 value 保存在 RocksDB，读取这些小 value 的性能会稍好一些；减少这个值可以使更多 value 保存在 Titan 中，进一步减少 RocksDB compaction。经过[测试](/st
@tonyxuqqi @Connor1996 这里我们还推荐 1KB 的 min-blob-size 么？

2024-01-22 05:37 UTC, benmaoer commented on storage-engine/titan-configuration.md
> +> 在 v7.6.0 开始，新建集群默认打开 Titan。已有集群升级到 v7.6.0 则会维持原有的配置，如果没有显式配置 Titan，则仍然会使用 RocksDB。
```suggestion
> - 从 TiDB v7.6.0 开始，新创建的集群将默认启用 Titan。写入的数据中，超过 [`min-blob-size`](tikv-configuration-file.md#min-blob-size)  的 value 将被存储在 Titan 中，而其他数据则继续存储在 RocksDB 中。
> - 对于已存在的集群，如果在升级到 TiDB v7.6.0 或更高版本之前未启用 Titan，则升级后将保持原有配置，继续使用 RocksDB，不会启用 Titan。
> - 对于已存在的集群，如果在升级到 TiDB v7.6.0 或更高版本之前已经启用了 Titan，则升级后将维持原有配置，保持启用 Titan 引擎，并保留升级前 [`min-blob-size`](tikv-configuration-file.md#min-blob-size)  的配置，可以是原默认 1KB ，也可以是用户定义的其他值。
```

2024-01-22 05:47 UTC, benmaoer commented on storage-engine/titan-configuration.md
> +> 在 v7.6.0 开始，新建集群默认min-blob-size改成了`32KB`, 避免扫描性能产生回退。但对已有集群升级到 v7.6.0 则会维持原有的配置，即便没有显式配置min-blob-size，仍然会使用`1KB`的旧默认值。
建议和之前的升级默认开启 Titan 的说明放在一起

2024-01-22 05:49 UTC, benmaoer requested changes
add how to enable titan through operator
add description of upgrade

2024-01-22 06:01 UTC, benmaoer commented on tikv-configuration-file.md
```suggestion

    > **注意**
    >
    > TiDB v7.5.0 及更早的版本，默认值为 `false`，即默认不开启 Titan。从 TiDB v7.6.0 版本开始，默认值变更为 `true`，即默认开启 Titan。
```

2024-01-22 06:06 UTC, benmaoer commented on tikv-configuration-file.md
> ++ 默认值：v7.5.0 及更早的版本为 `false`。从 v7.6.0 开始，新建集群默认是 `true`，已有集群升级到 v7.6.0 或更高版本则会维持原有的配置。
```suggestion
+ 默认值：`true`
```

2024-01-22 06:06 UTC, benmaoer commented on tikv-configuration-file.md
> +> **注意：**
```suggestion
> **警告**
```

2024-01-22 06:08 UTC, benmaoer commented on tikv-configuration-file.md
> +> titan只在defaultcf打开有意义，不支持在writecf打开。
```suggestion
>  仅支持在 rocksdb.defaultcf 启用 Titan，不支持在 rocksdb.writecf 启用 Titan。
```

2024-01-22 06:49 UTC, benmaoer commented on tikv-configuration-file.md
> +> 当该值设置为小于默认值时，TiKV大范围扫描性能会有回退。但如果负载是重写和点查为主，则可以适当向下调整min-blob-size，最少可以调成1KB。因此，从TiDB7.6开始，新建集群默认值为`32KB`, 但对于已有集群升级到7.6版本，为保持行为上的连续性，当用户没有显式的设置`min-blob-size`时则维持使用旧版本的默认值`1KB`。
```suggestion
> - 为了提高宽表和 JSON 数据写入和点查性能，TiDB 从 v7.6.0 版本起默认启用 Titan，并将写入 Titan 的阈值参数 `min-blob-size`的默认值从之前版本的 `1KB` 调整为 `32KB`，即当数据的 value 超过 `32KB` 时，将存储在 Titan 中，而其他数据则继续存储在 RocksDB 中。同时，为了保证配置的连续性，已有集群升级到 TiDB v7.6.0 版本或者更高版本后，如果升级前用户未显式设置 `min-blob-size` ，则维持使用旧版本的默认值 `1KB`，以确保升级后集群配置的稳定性。

> - 当参数被设置为小于 `32KB` 时，TiKV大范围扫描性能会受到一些影响。然而，如果负载主要是写入和点查为主，用户可以适当降低 `min-blob-size` 的设置来获取更好的写入和点查性能。

```

2024-01-22 06:51 UTC, benmaoer commented on tikv-configuration-file.md
```suggestion
> TiDB v7.5.0 及更早的版本，参数默认值为 `lz4`；TiDB v7.6.0 及更高版本，参数默认值调整为 `zstd`。
```

2024-01-22 06:52 UTC, benmaoer requested changes
add warnings of titan for tikv-configuration-file

2024-01-22 13:45 UTC, hfxsd commented on tikv-configuration-file.md
> +> titan只在defaultcf打开有意义，不支持在writecf打开。
```suggestion
> Titan 只有在 `defaultcf` 打开才有意义，不支持在 `writecf` 打开。
```

2024-01-22 13:45 UTC, hfxsd commented on tikv-configuration-file.md
> +> 当该值设置为小于默认值时，TiKV大范围扫描性能会有回退。但如果负载是重写和点查为主，则可以适当向下调整min-blob-size，最少可以调成1KB。因此，从TiDB7.6开始，新建集群默认值为`32KB`, 但对于已有集群升级到7.6版本，为保持行为上的连续性，当用户没有显式的设置`min-blob-size`时则维持使用旧版本的默认值`1KB`。
```suggestion
> 当该值设置为小于默认值时，TiKV 大范围扫描性能会有回退。但如果负载是重写和点查为主，则可以适当调小该值，最小可以设置为 `1KB`。因此，从 TiDB v7.6.0 开始，新建集群默认值为 `32KB`，但对于已有集群升级到 v7.6.0 版本的情况，为保持行为上的连续性，如果你没有显式设置 `min-blob-size`，则保持旧版本的默认值 `1KB` 不变。
```

2024-01-22 13:45 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> 在 v7.6.0 开始，新建集群默认min-blob-size改成了`32KB`, 避免扫描性能产生回退。但对已有集群升级到 v7.6.0 则会维持原有的配置，即便没有显式配置min-blob-size，仍然会使用`1KB`的旧默认值。
```suggestion
```

2024-01-22 13:45 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> 在 v7.6.0 开始，新建集群默认打开 Titan。已有集群升级到 v7.6.0 则会维持原有的配置，如果没有显式配置 Titan，则仍然会使用 RocksDB。
```suggestion
> - 从 v7.6.0 开始，新建集群默认打开 Titan。已有集群升级到 v7.6.0 则会维持原有的配置，如果没有显式配置 Titan，则仍然会使用 RocksDB。
 > - 从 v7.6.0 开始，新建集群的 `min-blob-size` 默认值由 `1KB` 改为 `32KB`，避免扫描性能产生回退。但已有集群升级到 v7.6.0，则会维持原有的配置，即如果没有显式配置 `min-blob-size`，则保持旧版本的默认值 `1KB` 不变。
```

2024-01-22 17:34 UTC, tonyxuqqi commented on storage-engine/titan-configuration.md
@benmaoer 这个和TiDB-Operator有什么关系呢，如果要增加tidb-operator的说明，可以在另外的PR里。另外，我也不知道tidb-operator的用法

2024-01-22 17:45 UTC, tonyxuqqi commented on storage-engine/titan-configuration.md
> +> 在 v7.6.0 开始，新建集群默认min-blob-size改成了`32KB`, 避免扫描性能产生回退。但对已有集群升级到 v7.6.0 则会维持原有的配置，即便没有显式配置min-blob-size，仍然会使用`1KB`的旧默认值。
嗯，上面已经集中说明了。

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> **注意**
```suggestion
> **注意：**
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> - 从 TiDB v7.6.0 开始，新集群将默认启用 Titan，并将阈值[`min-blob-size`](/tikv-configuration-file.md#min-blob-size)的默认值从之前版本的`1KB` 调整为`32KB`。
```suggestion
> - 从 TiDB v7.6.0 开始，新集群将默认启用 Titan，并将阈值 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size)的默认值由之前的 `1KB` 调整为 `32KB`。
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> - 如果集群在升级到 TiDB v7.6.0 或更高版本之前已经启用了 Titan，则升级后将维持原有配置，保持启用 Titan，并保留升级前[`min-blob-size`](/tikv-configuration-file.md#min-blob-size)的配置。如果升级前没有显式配置该值，则升级后仍然保持了老版本默认值`1KB`，以确保升级后集群配置的稳定性。
```suggestion
> - 如果集群在升级到 TiDB v7.6.0 或更高版本之前已经启用了 Titan，则升级后将维持原有配置，保持启用 Titan，并保留升级前 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 的配置。如果升级前没有显式配置该值，则升级后仍然保持老版本的默认值 `1KB`，以确保升级后集群配置的稳定性。
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +
```suggestion
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +    应用配置时，触发在线滚动重启 TiDB 集群让配置生效：
```suggestion

    应用配置时，触发在线滚动重启 TiDB 集群让配置生效：
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> **警告**
```suggestion
> **警告：**
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> 在不开启 Titan 功能的情况下，RocksDB 无法读取已经迁移到 Titan 的数据。如果在打开过 Titan 的 TiKV 实例上错误地关闭了 Titan（误设置 `rocksdb.titan.enabled = false`），启动 TiKV 会失败，TiKV log 中出现 `You have disabled titan when its data directory is n
```suggestion
> 在关闭 Titan 功能的情况下，RocksDB 无法读取已经迁移到 Titan 的数据。如果在打开过 Titan 的 TiKV 实例上错误地关闭了 Titan（误设置 `rocksdb.titan.enabled = false`），启动 TiKV 会失败，TiKV log 中出现 `You have disabled titan when its data directory is not empty` 的错误。如需要关闭 Titan，参考[关闭 Titan](#关闭-titan) 。
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +开启 Titan 以后，原有的数据并不会马上迁移到 Titan 引擎，而是随着前台写入和 RocksDB Compaction 的进行，**逐步进行 key-value 分离并写入 Titan**。同样的，无论是通过 [BR](/br/backup-and-restore-overview.md) 快照/日志恢复的数据，还是通过 [TiDB Lightning](/tidb-lightning/
```suggestion
开启 Titan 以后，原有的数据并不会马上迁移到 Titan 引擎，而是随着前台写入和 RocksDB Compaction 的进行，**逐步进行 key-value 分离并写入 Titan**。同样的，无论是通过 [BR](/br/backup-and-restore-overview.md) 快照或日志恢复的数据，还是通过 [TiDB Lightning](/tidb-lightning/tidb-lightning-overview.md) 逻辑导入模式或物理导入模式导入的数据，都会首先写入 RocksDB。然后，随着 RocksDB Compaction 的进行，超过 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 默认值 `32KB` 的大 value 会逐步分离到 Titan 中。你可以通过观察 **TiKV Details** - **Titan kv** - **blob file size** 监控面版中文件的大小来确认存储在 Titan 中的数据大小。
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +[`discardable-ratio`](/tikv-configuration-file.md#discardable-ratio)和[`max-background-gc`](/tikv-configuration-file.md#max-background-gc)的设置对于 Titan 的读性能和垃圾回收过程都有重要影响。当一个 blob file 中无用数据（相应的 key 已经被更
```suggestion
[`discardable-ratio`](/tikv-configuration-file.md#discardable-ratio) 和 [`max-background-gc`](/tikv-configuration-file.md#max-background-gc) 的设置对于 Titan 的读性能和垃圾回收过程都有重要影响。当一个 blob file 中无用数据（相应的 key 已经被更新或删除）比例超过 [`discardable-ratio`](/tikv-configuration-file.md#discardable-ratio) 设置的阈值时，将会触发 Titan GC。减少这个阈值可以减少空间放大，但是会造成 Titan 更频繁 GC；增加这个值可以减少 Titan GC，减少相应的 I/O 带宽和 CPU 消耗，但是会增加磁盘空间占用。当从 TiKV Details - Thread CPU - RocksDB CPU 监控中观察到 Titan GC 线程长期处于满负荷状态时，应该考虑调整  [`max-background-gc`](/tikv-configuration-file.md#max-background-gc) 增加 Titan GC 线程池大小。
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +最后，通过调整[`rate-bytes-per-sec`](/tikv-configuration-file.md#rate-bytes-per-sec)，我们能够限制 RocksDB compaction 的 I/O 速率，从而在高流量时减少对前台读写性能的影响。
```suggestion
最后，通过调整 [`rate-bytes-per-sec`](/tikv-configuration-file.md#rate-bytes-per-sec)，可以限制 RocksDB compaction 的 I/O 速率，从而在高流量时减少对前台读写性能的影响。 
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +下面是一个 Titan 配置文件的样例，更多的参数说明，请参考[TiKV 配置文件描述](/tikv-configuration-file.md)。我们可以使用 TiUP 来[修改配置参数](/maintain-tidb-using-tiup.md#修改配置参数)，也可以通过 [在 Kubernetes 中配置 TiDB 集群](https://docs.pingcap.com/zh/tidb-
```suggestion
下面是一个 Titan 配置文件的样例，更多的参数说明，请参考 [TiKV 配置文件描述](/tikv-configuration-file.md)。你可以使用 TiUP [修改配置参数](/maintain-tidb-using-tiup.md#修改配置参数)，也可以通过[在 Kubernetes 中配置 TiDB 集群](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/configure-a-tidb-cluster) 修改配置参数。
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +    {{< copyable "" >}}
```suggestion
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +    > **注意**
```suggestion
    > **注意：**
```

2024-01-23 04:40 UTC, hfxsd commented on storage-engine/titan-overview.md
> +> `scan100` 是指扫描 100 条记录，`scan10000` 指扫描 10000 条记录。
```suggestion
> `scan100` 是指扫描 100 条记录，`scan10000` 是指扫描 10000 条记录。
```

2024-01-23 04:40 UTC, hfxsd commented on tikv-configuration-file.md
> +> - 为了提高宽表和 JSON 数据写入和点查性能，TiDB 从 v7.6.0 版本起默认启用 Titan，并将写入 Titan 的阈值参数 `min-blob-size`的默认值从之前版本的 `1KB` 调整为 `32KB`，即当数据的 value 超过 `32KB` 时，将存储在 Titan 中，而其他数据则继续存储在 RocksDB 中。
```suggestion
> - 为了提高宽表和 JSON 数据写入和点查性能，TiDB 从 v7.6.0 版本起默认启用 Titan，并将写入 Titan 的阈值参数 `min-blob-size` 的默认值从之前版本的 `1KB` 调整为 `32KB`，即当数据的 value 超过 `32KB` 时，将存储在 Titan 中，而其他数据则继续存储在 RocksDB 中。
```

2024-01-23 04:40 UTC, hfxsd commented on tikv-configuration-file.md
> +> - 为了保证配置的连续性，已有集群升级到 TiDB v7.6.0 版本或者更高版本后，如果升级前用户未显式设置`min-blob-size` ，则维持使用老版本默认值 `1KB`，以确保升级后集群配置的稳定性。
```suggestion
> - 为了保证配置的连续性，已有集群升级到 TiDB v7.6.0 版本或者更高版本后，如果升级前用户未显式设置 `min-blob-size` ，则维持使用老版本默认值 `1KB`，以确保升级后集群配置的稳定性。
```

2024-01-23 04:40 UTC, hfxsd commented on tikv-configuration-file.md
> +> - 当参数被设置为小于 `32KB` 时，TiKV大范围扫描性能会受到一些影响。然而，如果负载主要是写入和点查为主，用户可以适当降低 `min-blob-size` 的设置来获取更好的写入和点查性能。
```suggestion
> - 当参数被设置为小于 `32KB` 时，TiKV 大范围扫描性能会受到一些影响。然而，如果负载主要是写入和点查为主，你可以适当调小 `min-blob-size` 的值以获取更好的写入和点查性能。
```

2024-01-23 04:40 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 当`enable-compaction-filter`为false时GC线程个数。 <span class="version-mark">从 v7.6 版本开始引入</span>
```suggestion
+ 当 `enable-compaction-filter` 为 `false` 时 GC 线程个数。 <span class="version-mark">从 v7.6.0 版本开始引入</span>
```

2024-01-23 05:43 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +为了更快地将数据转移到 Titan，建议使用 tikv-ctl 工具执行一次全量 Compaction，以提高迁移速度。具体的操作步骤可以查阅[手动 compact](/tikv-control.md#手动-compact-整个-tikv-集群的数据)。由于 RocksDB 具备 Block Cache，并且在将数据从 RocksDB 迁移到 Titan 时，数据访问是连续的，这使得在迁移过程中
```suggestion
为了更快地将数据转移到 Titan，建议使用 tikv-ctl 工具执行一次全量 Compaction，以提高迁移速度。具体操作步骤请参考[手动 compact](/tikv-control.md#手动-compact-整个-tikv-集群的数据)。由于 RocksDB 具备 Block Cache，并且在将数据从 RocksDB 迁移到 Titan 时，数据访问是连续的，这使得在迁移过程中 Block Cache 能够更有效地提升迁移速度。在我们的测试中，仅需 1 小时，就能够通过 tikv-ctl 在单个 TiKV 节点上执行全量 Compaction，成功将 670 GiB 的数据迁移到 Titan。
```

2024-01-23 05:50 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 设置 TiKV 启动周期性全量数据整理 (Compaction) 的时间。你可以在数组中指定一个或多个时间计划。例如，`periodic-full-compact-start-times = ["03:00", "23:00"]` 表示 TiKV 基于 TiKV 节点的本地时区，在每天凌晨 3 点和晚上 11 点进行全量数据整理。`periodic-full-compact-start-ti
```suggestion
+ 设置 TiKV 启动周期性全量数据整理 (Compaction) 的时间。你可以在数组中指定一个或多个时间计划。例如：
    + `periodic-full-compact-start-times = ["03:00", "23:00"]` 表示 TiKV 基于 TiKV 节点的本地时区，在每天凌晨 3 点和晚上 11 点进行全量数据整理。
    + `periodic-full-compact-start-times = ["03:00 +0000", "23:00 +0000"]` 表示 TiKV 在每天 UTC 时间的凌晨 3 点和晚上 11 点进行全量数据整理。
```

2024-01-23 05:51 UTC, hfxsd commented on tikv-configuration-file.md
> +> - 从 TiDB v7.6.0 开始，参数默认值从`false`变更为`true`，即新集群默认开启 Titan。
```suggestion
> - 从 TiDB v7.6.0 开始，参数默认值从 `false` 变更为 `true`，即新集群默认开启 Titan。
```

2024-01-23 06:22 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 当 `enable-compaction-filter` 为 `false` 时 GC 线程个数。 <span class="version-mark">从 v7.6.0 版本开始引入</span>
```suggestion
### `num-threads` <span class="version-mark">从 v7.6.0 版本开始引入</span>

+ 当 `enable-compaction-filter` 为 `false` 时 GC 线程个数。
```

2024-01-23 08:23 UTC, ran-huang commented on storage-engine/titan-configuration.md
> +``` toml
```suggestion
```toml
```

2024-01-23 08:23 UTC, ran-huang commented on tikv-configuration-file.md
> +> - 如果集群在升级到 TiDB v7.6.0 或更高版本之前已经启用了 Titan，则升级后将维持原有配置，保持启用 Titan 引擎，并保留升级前[`min-blob-size`](/tikv-configuration-file.md#min-blob-size)的配置。如果升级前没有显式配置该值，则升级后仍然保持了老版本默认值`1KB`，以确保升级后集群配置的稳定性。
```suggestion
> - 如果集群在升级到 TiDB v7.6.0 或更高版本之前已经启用了 Titan，则升级后将维持原有配置，保持启用 Titan 引擎，并保留升级前 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 的配置。如果升级前没有显式配置该值，则升级后仍然保持了老版本默认值 `1KB`，以确保升级后集群配置的稳定性。
```

2024-01-23 09:44 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +    ``` yaml
```suggestion
    ```yaml
```

2024-01-23 11:44 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 指定 zstd 字典大小，默认为 `0KB`，表示关闭 zstd 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB`）为单位。因此当关闭字典压缩、且 value 平均小于 `32KB` 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 store size 可能比 RocksDB
```suggestion
+ 指定 zstd 字典大小，默认为 `0KB`，表示关闭 zstd 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB`）为单位。因此当关闭字典压缩、且 value 平均小于 `32KB` 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 Store Size 可能比 RocksDB 高 30% 至 50%。实际压缩率还取决于 value 内容是否适合压缩，以及不同 value 之间的相似性。你可以通过设置 `zstd-dict-size`（比如 `16KB`）启用 zstd 字典以大幅提高压缩率（实际 Store Size 可以低于 RocksDB），但 zstd 字典压缩在有些负载下会有 10% 左右的性能损失。
```

2024-01-23 11:44 UTC, hfxsd commented on tikv-configuration-file.md
> ++ 默认值：zstd
```suggestion
+ Blob 文件所使用的压缩算法，可选值：`no`、`snappy`、`zlib`、`bz2`、`lz4`、`lz4hc`、`zstd`。
+ 默认值：`zstd`
```

2024-01-23 12:10 UTC, Connor1996 commented on storage-engine/titan-configuration.md
> +开启 Titan 以后，原有的数据并不会马上迁移到 Titan 引擎，而是随着前台写入和 RocksDB Compaction 的进行，**逐步进行 key-value 分离并写入 Titan**。同样的，无论是通过 [BR](/br/backup-and-restore-overview.md) 快照或日志恢复的数据，还是通过 [TiDB Lightning](/tidb-lightning/
是不是也要说下 region snapshot 也是只有 titan，所以对于新加的节点，搬过去的数据都不在 titan 中

2024-01-23 12:10 UTC, Connor1996 commented on storage-engine/titan-overview.md
> +| 256 | 156198 | 153487 | 15961 |6489 |269 |119 |30047 |35181 |
这些需要更新下了

2024-01-24 02:45 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +> - 从 TiDB v7.6.0 开始，新集群将默认启用 Titan，并将阈值 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 的默认值由之前的 `1KB` 调整为 `32KB`。
```suggestion
> - 从 TiDB v7.6.0 开始，新集群将默认启用 Titan，以更好地支持 TiDB 宽表写入场景，特别是在支持 JSON 之后。阈值 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 的默认值也由之前的 `1KB` 调整为 `32KB`。
```

2024-01-24 02:47 UTC, lilinghai commented on storage-engine/titan-configuration.md
> +开启 Titan 以后，原有的数据并不会马上迁移到 Titan 引擎，而是随着前台写入和 RocksDB Compaction 的进行，**逐步进行 key-value 分离并写入 Titan**。同样的，无论是通过 [BR](/br/backup-and-restore-overview.md) 快照或日志恢复的数据，还是通过 [TiDB Lightning](/tidb-lightning/
lightning 逻辑导入应该是 sql 写入的形式

2024-01-24 03:14 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +你可以通过设置 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 来调整 value 的大小阈值，决定哪些数据保存在 RocksDB 中，哪些数据保存在 Titan 的 blob file 中。经过[测试](/storage-engine/titan-overview.md#min-blob-size-的选择及其性能影响)，
```suggestion
你可以通过设置 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 来调整 value 的大小阈值，决定哪些数据保存在 RocksDB 中，哪些数据保存在 Titan 的 blob file 中。经过[测试](/storage-engine/titan-overview.md#min-blob-size-的选择及其性能影响)，`32KB` 是个折中的值。如果你想进一步提升写性能，并能接受扫描性能的下降，你可以将该值调整为 `1KB`。
```

2024-01-24 03:17 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +要注意的是，[`blob-cache-size`](/tikv-configuration-file.md#blob-cache-size) 控制 Titan 中 value 的缓存大小。更大的缓存能提高 Titan 读性能，但过大的缓存会造成 OOM。建议在数据库稳定运行后，根据监控把 RocksDB block cache (`storage.block-cache.capacity`) 设
```suggestion
可以使用 [`blob-cache-size`](/tikv-configuration-file.md#blob-cache-size) 控制 Titan 中 value 的缓存大小。更大的缓存能提高 Titan 读性能，但过大的缓存会造成 OOM。建议在数据库稳定运行后，根据监控把 RocksDB block cache (`storage.block-cache.capacity`) 设置为 store size 减去 blob file size 的大小，`blob-cache-size` 设置为内存大小 * 50% 减去 block cache 的大小。这是为了保证 block cache 足够缓存整个 RocksDB 的前提下，blob cache 尽量大。
```

2024-01-24 03:32 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +通过调整 [`rate-bytes-per-sec`](/tikv-configuration-file.md#rate-bytes-per-sec)，你可以限制 RocksDB compaction 的 I/O 速率，从而在高流量时减少对前台读写性能的影响。
```suggestion
### `rate-bytes-per-sec`

通过调整 [`rate-bytes-per-sec`](/tikv-configuration-file.md#rate-bytes-per-sec)，你可以限制 RocksDB compaction 的 I/O 速率，从而在高流量时减少对前台读写性能的影响。
```

2024-01-24 03:35 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +[`discardable-ratio`](/tikv-configuration-file.md#discardable-ratio) 和 [`max-background-gc`](/tikv-configuration-file.md#max-background-gc) 的设置对于 Titan 的读性能和垃圾回收过程都有重要影响。当一个 blob file 中无用数据（相应的 key 已
```suggestion
[`discardable-ratio`](/tikv-configuration-file.md#discardable-ratio) 和 [`max-background-gc`](/tikv-configuration-file.md#max-background-gc) 的设置对于 Titan 的读性能和垃圾回收过程都有重要影响。

当一个 blob file 中无用数据（相应的 key 已经被更新或删除）比例超过 [`discardable-ratio`](/tikv-configuration-file.md#discardable-ratio) 设置的阈值时，将会触发 Titan GC。减少这个阈值可以减少空间放大，但是会造成 Titan 更频繁 GC；增加这个值可以减少 Titan GC，减少相应的 I/O 带宽和 CPU 消耗，但是会增加磁盘空间占用。
```

2024-01-24 03:38 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +当从 TiKV Details - Thread CPU - RocksDB CPU 监控中观察到 Titan GC 线程长期处于满负荷状态时，应该考虑调整  [`max-background-gc`](/tikv-configuration-file.md#max-background-gc) 增加 Titan GC 线程池大小。
```suggestion
若果你通过**TiKV Details** - **Thread CPU** - **RocksDB CPU** 监控中观察到 Titan GC 线程长期处于满负荷状态时，应该考虑调整 [`max-background-gc`](/tikv-configuration-file.md#max-background-gc) 增加 Titan GC 线程池大小。
```

2024-01-24 03:54 UTC, hfxsd commented on tikv-configuration-file.md
> +> - 从 TiDB v7.6.0 开始，参数默认值从 `false` 变更为 `true`，即新集群默认开启 Titan。
```suggestion
> - 从 TiDB v7.6.0 开始，参数默认值从 `false` 变更为 `true`，即新集群默认开启 Titan，以更好地支持 TiDB 宽表写入场景和 JSON。
```

2024-01-24 03:59 UTC, hfxsd commented on tikv-configuration-file.md
> ++ `false`
```suggestion
+ `true`
```

2024-01-24 04:07 UTC, hfxsd commented on tikv-configuration-file.md
> +> **警告：**
```suggestion
> **注意：**
```

2024-01-24 06:03 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +你可以通过设置 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 来调整 value 的大小阈值，决定哪些数据保存在 RocksDB 中，哪些数据保存在 Titan 的 blob file 中。经过[测试](/storage-engine/titan-overview.md#min-blob-size-的选择及其性能影响)，
```suggestion
你可以通过设置 [`min-blob-size`](/tikv-configuration-file.md#min-blob-size) 来调整 value 的大小阈值，决定哪些数据保存在 RocksDB 中，哪些数据保存在 Titan 的 blob file 中。经过测试，`32KB` 是个折中的值。如果你想进一步提升写性能，并能接受扫描性能的下降，你可以将该值调整为 `1KB`。
```

2024-01-24 07:34 UTC, hfxsd commented on storage-engine/titan-configuration.md
> +通过合理配置 Titan 参数，可以有效提升数据库性能和资源利用率。
```suggestion
通过合理配置 Titan 参数，可以有效提升数据库性能和资源利用率。本节介绍了一些常见的参数。
```

2024-01-24 07:41 UTC, Oreoxmt commented on tikv-configuration-file.md
> +    空间放大上界 = 1 / (1 - discardable_ratio)
```suggestion
    写放大上界 = 1 / discardable-ratio

    空间放大上界 = 1 / (1 - discardable-ratio)
```

2024-01-24 07:50 UTC, hfxsd commented on tikv-configuration-file.md
>      + "normal"：value size 超过 min-blob-size 的数据会写入到 blob 文件。
```suggestion
    + "normal"：value size 超过 [`min-blob-size`](#min-blob-size) 的数据会写入到 blob 文件。
```

2024-01-24 08:41 UTC, Oreoxmt commented on tikv-configuration-file.md
> ++ 指定 zstd 字典大小，默认为 `0KB`，表示关闭 zstd 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB`）为单位。因此当关闭字典压缩、且 value 平均小于 `32KB` 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 Store Size 可能比 RocksDB
```suggestion
+ 指定 zstd 字典大小，默认为 `"0KB"`，表示关闭 zstd 字典压缩，也就是说 Titan 中压缩的是单个 value 值，而 RocksDB 压缩以 Block（默认值为 `32KB`）为单位。因此当关闭字典压缩、且 value 平均小于 `32KB` 时，Titan 的压缩率低于 RocksDB。以 JSON 内容为例，Titan 的 Store Size 可能比 RocksDB 高 30% 至 50%。实际压缩率还取决于 value 内容是否适合压缩，以及不同 value 之间的相似性。你可以通过设置 `zstd-dict-size`（比如 `16KB`）启用 zstd 字典以大幅提高压缩率（实际 Store Size 可以低于 RocksDB），但 zstd 字典压缩在有些负载下会有 10% 左右的性能损失。
```

2024-01-24 08:41 UTC, Oreoxmt commented on tikv-configuration-file.md
> ++ Titan 后台 GC 的线程个数，当从 **TiKV Details** - **Thread CPU** - **RocksDB CPU** 监控中观察到 Titan GC 线程长期处于满负荷状态时，应该考虑增加 Titan GC 线程池大小。
```suggestion
+ Titan 后台 GC 的线程个数，当从 **TiKV Details** > **Thread CPU** > **RocksDB CPU** 监控中观察到 Titan GC 线程长期处于满负荷状态时，应该考虑增加 Titan GC 线程池大小。
```

2024-01-24 08:41 UTC, Oreoxmt commented on tikv-configuration-file.md
> +
```suggestion
```

2024-01-24 08:43 UTC, Oreoxmt commented on storage-engine/titan-overview.md
> +从 TiDB 7.6.0 开始，对 Titan 性能进行了优化，可以把 Titan 作为默认的存储引擎。由于 TiKV 在 Value 较小时会直接存在 RocksDB 中，因此即便是小 Value 也可以打开 Titan。
```suggestion
从 v7.6.0 开始，TiDB 对 Titan 性能进行了优化，并将 Titan 作为默认的存储引擎。由于 TiKV 在 Value 较小时会直接存在 RocksDB 中，因此即便是小 Value 也可以打开 Titan。
```

2024-01-24 09:01 UTC, hfxsd approved these changes

2024-01-24 09:14 UTC, Oreoxmt commented on storage-engine/titan-configuration.md
> +下面是一个 Titan 配置文件的样例，更多的参数说明，请参考 [TiKV 配置文件描述](/tikv-configuration-file.md)。你可以使用 TiUP [修改配置参数](/maintain-tidb-using-tiup.md#修改配置参数)，也可以通过[在 Kubernetes 中配置 TiDB 集群](https://docs.pingcap.com/zh/tidb-in
```suggestion
下面是一个 Titan 配置文件的样例，更多的参数说明，请参考 [TiKV 配置文件描述](/tikv-configuration-file.md)。你可以使用 TiUP [修改配置参数](/maintain-tidb-using-tiup.md#修改配置参数)，也可以通过[在 Kubernetes 中配置 TiDB 集群](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/configure-a-tidb-cluster)修改配置参数。
```

2024-01-24 09:25 UTC, hfxsd commented on tikv-configuration-file.md
> +    空间放大上界 = 1 / (1 - discardable-ratio)
```suggestion
    写放大上界 = 1 / `discardable-ratio`

    空间放大上界 = 1 / (1 - `discardable-ratio`)
```

2024-01-24 09:40 UTC, Oreoxmt approved these changes

2024-01-25 00:51 UTC, hfxsd commented
/approve

2024-01-25 00:52 UTC, merged

2024-01-25 00:53 UTC, benmaoer approved these changes
LGTM