basic-features.md: add the column for v7.6.0
pingcap/docs-cn pull request #16060
Opened 2024-01-09 06:16 UTC by qiancai

### What is changed, added or deleted? (Required)

Add the column for v7.6.0

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v7.6 (TiDB 7.6 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.4 (TiDB 7.4 versions)
- [ ] v7.3 (TiDB 7.3 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2024-01-09 10:32 UTC, songrijie commented on basic-features.md
> +| [执行计划管理 (SPM)](/sql-plan-management.md) |  Y  |  Y  | Y | Y | Y | Y | Y | Y | Y | Y | Y |
LGTM

2024-01-22 08:53 UTC, benmaoer commented on basic-features.md
> +| [读已提交隔离](/transaction-isolation-levels.md) |  Y  |  Y  | Y | Y | Y | Y | Y | Y | Y | Y | Y |
| [`tidb_idle_transaction_timeout`](/system-variables.md#tidb_idle_transaction_timeout-从-v760-版本开始引入) | Y | N | N | N | N | N | N | N | N | N | N |

2024-01-22 09:10 UTC, benmaoer requested changes
add idle transaction timeout

2024-01-22 09:11 UTC, benmaoer requested changes
add idle txn timeout

2024-01-22 09:20 UTC, Oreoxmt commented on basic-features.md
> +| [读已提交隔离](/transaction-isolation-levels.md) |  Y  |  Y  | Y | Y | Y | Y | Y | Y | Y | Y | Y |
```suggestion
| [读已提交隔离](/transaction-isolation-levels.md) |  Y  |  Y  | Y | Y | Y | Y | Y | Y | Y | Y | Y |
| [自动终止长时间未提交的空闲事务](/system-variables.md#tidb_idle_transaction_timeout-从-v760-版本开始引入) | Y | N | N | N | N | N | N | N | N | N | N |
```

2024-01-23 01:03 UTC, hfxsd commented on basic-features.md
```suggestion
| [DM](/dm//dm-overview.md) 支持迁移 MySQL 8.0  | Y | E | E | E | E | N | N | N | N | N | N |
```

2024-01-23 01:27 UTC, hfxsd commented on basic-features.md
```suggestion
| [TiDB DDL V2 架构](/ddl-v2.md) | E | N | N | N | N | N | N | N | N | N | N |

```

2024-01-23 03:51 UTC, qiancai commented on basic-features.md
/dm/dm-overview.md

2024-01-23 04:01 UTC, qiancai commented on basic-features.md
preview: https://pingcap-docsite-preview-git-v760-release-notes-qiancai.vercel.app/zh/tidb/dev/basic-features

2024-01-24 02:21 UTC, hfxsd approved these changes

2024-01-24 02:42 UTC, Oreoxmt approved these changes

2024-01-24 02:44 UTC, Oreoxmt commented on basic-features.md
>  ## 管理，可视化和工具
```suggestion

## 管理，可视化和工具
```

2024-01-25 07:12 UTC, qiancai commented
/approve

2024-01-25 07:14 UTC, qiancai commented on basic-features.md
> +| [跨数据库执行计划绑定 (Cross-DB Binding)](/sql-plan-management.md#跨数据库执行计划绑定-cross-db-binding) |  Y  |  N  | N | N | N | N | N | N | N | N | N |
```suggestion
| [跨数据库执行计划绑定 (Cross-DB Binding)](/sql-plan-management.md#跨数据库绑定执行计划-cross-db-binding) |  Y  |  N  | N | N | N | N | N | N | N | N | N |
```

2024-01-25 07:15 UTC, qiancai commented on basic-features.md
> +| 通过系统变量 [`pd_enable_follower_handle_region`](/system-variables.md#pd_enable_follower_handle_region-从-v760-版本开始引入) 控制 [Active PD Follower](/tune-region-performance.md#通过-active-pd-follower-提升-pd-regi
```suggestion
| 通过系统变量 [`pd_enable_follower_handle_region`](/system-variables.md#pd_enable_follower_handle_region-从-v760-版本开始引入) 控制 [Active PD Follower](/tune-region-performance.md#通过-active-pd-follower-提升-pd-region-信息查询服务的扩展能力) 功能 | E | N | N | N | N | N | N | N | N | N | N |
```

2024-01-25 07:26 UTC, qiancai commented
/verify

2024-01-25 07:30 UTC, qiancai commented
/verify

2024-01-25 07:45 UTC, merged