Add the description of load schema snapshot
pingcap/docs-cn pull request #19421
Opened 2024-12-30 05:55 UTC by Frank945946

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

Add the description of load schema snapshot 

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [ ] master (the latest development version)
- [ ] v9.0 (TiDB 9.0 versions)
- [ ] v8.5 (TiDB 8.5 versions)
- [ ] v8.4 (TiDB 8.4 versions)
- [ ] v8.3 (TiDB 8.3 versions)
- [ ] v8.2 (TiDB 8.2 versions)
- [ ] v8.1 (TiDB 8.1 versions)
- [ ] v7.5 (TiDB 7.5 versions)
- [ ] v7.1 (TiDB 7.1 versions)
- [ ] v6.5 (TiDB 6.5 versions)
- [ ] v6.1 (TiDB 6.1 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2024-12-31 07:02 UTC, hfxsd commented on tidb-binlog/tidb-binlog-configuration-file.md
> +* 在配置drainer时，需要根据实际需求来选择是否直接读取 checkpoint ts 时的表信息。如果需要确保数据的完整性和一致性，且不介意处理大量的 DDL 变更，建议设置为 false。如果更注重效率和性能，且能够确保 checkpoint ts 在 GC 安全点之后，建议设置为 true。
```suggestion
- 配置 Drainer 时，应根据实际需求选择是否直接读取 checkpoint TS 时的表信息。如果需要确保数据的完整性和一致性，且能接受处理大量 DDL 变更，建议设置为 `false`。如果更注重效率和性能，并能确保 checkpoint TS 在 GC 安全点之后，建议设置为 `true`。
- 当设置为 `false` 时，Drainer 会通过重播历史中的所有 DDL 操作，推导出特定 schema version 时各张表的 table schema。这种方式需要处理从初始状态到目标 schema version 之间的所有 DDL 变更，可能涉及大量的数据处理和重放。
- 当设置为 `true` 时，Drainer 会直接读取 checkpoint TS 时的 table info。由于直接读取特定时间点的表信息，这种方式通常更加高效。但它受到 GC 机制的限制，因为 GC 可能会删除旧的数据版本。如果 checkpoint TS 过旧，可能导致对应时间点的表信息已被 GC 删除，从而无法直接读取。
- 默认值为 `false`。
```

2024-12-31 07:41 UTC, hfxsd commented on tidb-binlog/tidb-binlog-configuration-file.md
> +- 默认值为 `false`。
```suggestion
- 用于设置 Drainer 加载表信息的方式。
- 当设置为 `false` 时，Drainer 会通过重播历史中的所有 DDL 操作，推导出特定 schema version 时各张表的 table schema。这种方式需要处理从初始状态到目标 schema version 之间的所有 DDL 变更，可能涉及大量的数据处理和重放。
- 当设置为 `true` 时，Drainer 会直接读取 checkpoint TS 时的表信息。由于直接读取特定时间点的表信息，这种方式通常更加高效。但它受到 GC 机制的限制，因为 GC 可能会删除旧的数据版本。如果 checkpoint TS 过旧，可能导致对应时间点的表信息已被 GC 删除，从而无法直接读取。
- 配置 Drainer 时，应根据实际需求选择是否直接读取 checkpoint TS 时的表信息。如果需要确保数据的完整性和一致性，且能接受处理大量 DDL 变更，建议设置为 `false`。如果更注重效率和性能，并能确保 checkpoint TS 在 GC 安全点之后，建议设置为 `true`。
- 默认值为 `false`。
```

2025-01-02 06:11 UTC, kennytm requested changes

2025-01-02 06:11 UTC, kennytm commented on tidb-binlog/tidb-binlog-configuration-file.md
> +### load-schema-snapshot
in the config file, `load-schema-snapshot` is inside the `[syncer]` section rather than top-level. please put it between the `safe-mode` and `syncer.to` items and use a 4th level header (`#### `).

2025-01-02 06:12 UTC, kennytm commented
hey bot that's not even an LGTM 😒

2025-01-02 07:03 UTC, hfxsd commented on tidb-binlog/tidb-binlog-configuration-file.md
> +-
```suggestion

```

2025-01-02 07:04 UTC, hfxsd commented on tidb-binlog/tidb-binlog-configuration-file.md
> +- 默认值为 `false`。
```suggestion
- 默认：`false`
```

2025-01-02 07:04 UTC, hfxsd commented on tidb-binlog/tidb-binlog-configuration-file.md
> +- 默认：`false`
```suggestion
- 默认：`false`

```

2025-01-02 07:05 UTC, hfxsd commented on tidb-binlog/tidb-binlog-configuration-file.md
> +### load-schema-snapshot
Updated as suggested.

2025-01-02 07:07 UTC, hfxsd approved these changes

2025-01-02 07:41 UTC, hfxsd commented on tidb-binlog/tidb-binlog-configuration-file.md
> +- 配置 Drainer 时，应根据实际需求选择是否直接读取 checkpoint TS 时的表信息。如果需要确保数据的完整性和一致性，且能接受处理大量 DDL 变更，建议设置为 `false`。如果更注重效率和性能，并能确保 checkpoint TS 在 GC 安全点之后，建议设置为 `true`。
```suggestion
- 当设置为 `true` 时，Drainer 会直接读取 checkpoint TS 时的表信息。由于直接读取特定时间点的表信息，这种方式通常更加高效。但它受到 GC 机制的限制，因为 GC 可能会删除旧的数据版本。如果 checkpoint TS 过旧，对应时间点的表信息可能已被 GC 删除，导致无法直接读取。
- 配置 Drainer 时，应根据实际需求选择是否直接读取 checkpoint TS 时的表信息。如果需要确保数据的完整性和一致性，且能接受处理大量 DDL 变更，建议设置为 `false`。如果优先考虑效率和性能，并能确保 checkpoint TS 在 GC 安全点之后，建议设置为 `true`。
```

2025-01-02 07:57 UTC, kennytm approved these changes

2025-01-02 09:36 UTC, hfxsd commented
/approve

2025-01-02 09:40 UTC, merged