Update pd-recover.md
pingcap/docs-cn pull request #4291
Opened 2020-08-18 15:14 UTC by nolouch

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

2020-08-19 03:28 UTC, TomShawn requested changes

2020-08-19 03:28 UTC, TomShawn commented on pd-recover.md
> +#### 从 PD 监控中获取最大的 alloc id （推荐）
```suggestion
#### 从 PD 监控中获取最大的 alloc id（推荐）
```

2020-08-19 03:28 UTC, TomShawn commented on pd-recover.md
> +在 PD 监控面板下的 Cluster 栏目下，可以找到 `Current ID allocation`, 代表当前已经分配出去的 id 的最大值。
`栏目`是指`面板`吗？
```suggestion
在 PD 监控面板下的 Cluster 栏目下，可以找到 `Current ID allocation`, 代表当前已经分配出去的 ID 的最大值。
```

2020-08-19 03:28 UTC, TomShawn commented on pd-recover.md
> +其中 max-alloc-id 是从日志中或者监控上找到的一个已经分配出去的最大的 alloc id，为了安全，可以将找出来的 id 加个安全的访问，比如加 1000000.
`加个安全访问`为什么加的是一个数字？
```suggestion
其中 `max-alloc-id` 是从日志或者监控中找到的一个已经分配出去的最大的 `alloc id`。出于安全考虑，可以将找出来的 ID 加个安全的访问，比如加 `1000000`。

```

2020-08-19 03:30 UTC, TomShawn commented
@nolouch Please also involve a technical review.

2020-08-19 09:42 UTC, nolouch commented
PTAL @rleungx

2020-08-24 02:46 UTC, TomShawn commented
@nolouch Looks like this PR is duplicated with https://github.com/pingcap/docs-cn/pull/4261.

2020-08-24 03:11 UTC, closed without merging