sql-statements: add statement reference for ROLES
pingcap/docs-cn pull request #4313
Opened 2020-08-21 04:54 UTC by Joyinqin

update docs and some examples associated with ROLES (RBAC).
### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [x] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs/pull/3198
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

2020-08-21 04:55 UTC, Joyinqin commented
/label needs-cherry-pick-3.0, needs-cherry-pick-3.1, needs-cherry-pick-4.0, status/PTAL, translation/from-docs

2020-08-21 04:56 UTC, Joyinqin commented
/cc TomShawn, bb7133

2020-08-24 06:26 UTC, TomShawn commented on sql-statements/sql-statement-set-default-role.md
> +`SET DEFAULT ROLE` 语句不会自动 `GRANT` 用户相关角色。若尝试为 `jennifer` 尚未授予的角色启用 `SET DEFAULT ROLE` 会导致以下错误：
```suggestion
`SET DEFAULT ROLE` 语句不会自动将相关角色授予 (`GRANT`) 用户。若尝试为 `jennifer` 尚未被授予的角色执行 `SET DEFAULT ROLE` 会导致以下错误：
```

2020-08-24 10:50 UTC, TomShawn commented
@bb7133 PTAL, thanks!

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-create-role.md
> +owners.
This part could be removed.

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-create-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
ditto

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-create-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
ditto

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-drop-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
This part could be removed.

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-drop-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
ditto

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-drop-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
ditto

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-drop-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
ditto

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-drop-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-drop-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-grant-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-grant-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-grant-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-grant-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-revoke-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-revoke-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-revoke-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-revoke-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-revoke-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-revoke-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-set-default-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-set-default-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-set-default-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 02:36 UTC, imtbkcat commented on sql-statements/sql-statement-set-default-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 11:20 UTC, TomShawn commented on sql-statements/sql-statement-create-role.md
> +Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```suggestion
```

2020-08-26 11:24 UTC, TomShawn commented
LGTM
@imtbkcat PTAL again

2020-08-28 03:46 UTC, lilin90 requested changes
@Joyinqin Please fix errors. @TomShawn FYI.

2020-08-28 03:46 UTC, lilin90 commented on TOC.md
> +      - [`SHOW DEFAULT ROLE`](/sql-statements/sql-statement-set-default-role.md)
```suggestion
```

2020-08-28 03:46 UTC, lilin90 commented on TOC.md
>        - [`SELECT`](/sql-statements/sql-statement-select.md)
```suggestion
      - [`SELECT`](/sql-statements/sql-statement-select.md)
      - [`SET DEFAULT ROLE`](/sql-statements/sql-statement-set-default-role.md)
```

2020-08-28 12:20 UTC, lilin90 commented on sql-statements/sql-statement-set-role.md
> +`SET ROLE` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](/report-issue.md)。
```suggestion
`SET ROLE` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](https://github.com/pingcap/tidb/issues/new/choose)。
```

2020-08-28 12:20 UTC, lilin90 commented on sql-statements/sql-statement-set-default-role.md
> +`SET DEFAULT ROLE` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](/report-issue.md)。
```suggestion
`SET DEFAULT ROLE` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](https://github.com/pingcap/tidb/issues/new/choose)。
```

2020-08-28 12:20 UTC, lilin90 commented on sql-statements/sql-statement-revoke-role.md
> +`REVOKE <role>` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](/report-issue.md)。
```suggestion
`REVOKE <role>` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](https://github.com/pingcap/tidb/issues/new/choose)。
```

2020-08-28 12:20 UTC, lilin90 commented on sql-statements/sql-statement-grant-role.md
> +`GRANT <role>` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](/report-issue.md)。
```suggestion
`GRANT <role>` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](https://github.com/pingcap/tidb/issues/new/choose)。
```

2020-08-28 12:20 UTC, lilin90 commented on sql-statements/sql-statement-drop-role.md
> +`DROP ROLE` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](/report-issue.md)。
```suggestion
`DROP ROLE` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](https://github.com/pingcap/tidb/issues/new/choose)。
```

2020-08-28 12:20 UTC, lilin90 commented on sql-statements/sql-statement-create-role.md
> +`CREATE ROLE` 语句与 MySQL 8.0 的角色功能完全兼容。如有任何其他兼容性差异，请在 GitHub 上提交 [issue](/report-issue.md)。
- @Joyinqin I see that you hasn't address @TomShawn's comment but marked it as resolved. Also for other files in this PR. Please check.
- Please use the filing issue link of the tidb repo: https://github.com/pingcap/tidb/issues/new/choose

2020-08-31 03:29 UTC, imtbkcat approved these changes
LGTM

2020-09-01 06:19 UTC, lilin90 approved these changes
LGTM

2020-09-01 06:31 UTC, merged