update doc for explain analyze
pingcap/docs-cn pull request #4655
Opened 2020-10-10 12:11 UTC by crazycs520

Signed-off-by: crazycs520 <crazycs520@gmail.com>

### What is changed, added or deleted? (Required)

update docs for excute information in `explain analyze` statement.

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- Other reference link(s): https://github.com/pingcap/tidb/issues/18663

### Do your changes match any of the following descriptions?

- [ ] Change aliases
- [ ] Have version specific changes

2020-10-12 06:47 UTC, crazycs520 commented
@zz-jason @qw4990 PTAL

2020-10-12 06:52 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +`IndexJoin` 算子有 1 个 outer worker 和 N 个 inner worker 并行执行，其 join 结果的顺序和 outer table 的顺序一致，具体执行流程如下：
这里的英文翻译可以直接用代码注释，我基本是根据注释直接翻译的：

```sql
// IndexJoin employs one outer worker and N innerWorkers to execute concurrently.
// It preserves the order of the outer table and support batch lookup.
//
// The execution flow is:
// 1. outerWorker read N outer rows, build a task and send it to result channel and inner worker channel.
// 2. The innerWorker receives the task, builds key ranges from outer rows and fetch inner rows, builds inner row hash map.
// 3. main thread receives the task, waits for inner worker finish handling the task.
// 4. main thread join each outer row by look up the inner rows hash map in the task.
```

2020-10-12 06:53 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +`IndexHashJoin` 算子和 `IndexJoin` 算子执行流程类似，也有 1 个 outer worker 和 N 个 inner worker 并行执行，但是其 join 结果的顺序是不和 outer table 一致。具体执行流程如下：
```
// IndexHashJoin employs one outer worker and N inner workers to
// execute concurrently. The output order is not promised.
//
// The execution flow is very similar to IndexLookUpReader:
// 1. The outer worker reads N outer rows, builds a task and sends it to the
// inner worker channel.
// 2. The inner worker receives the tasks and does 3 things for every task:
//    1. builds hash table from the outer rows
//    2. builds key ranges from outer rows and fetches inner rows
//    3. probes the hash table and sends the join result to the main thread channel.
//    Note: step 1 and step 2 runs concurrently.
// 3. The main thread receives the join results.
```

2020-10-15 06:15 UTC, qw4990 commented on sql-statements/sql-statement-explain-analyze.md
> +- `ResolveLock:{num_rpc:22076, total_time:124.644857ms}`：读数据遇到锁后，进行 resolve lock 的时间。一般在读写冲突的场景下会出现。
这个 point_get 的 `num_rpc` 为啥会这么高，看起来有点不正常？

2020-10-15 06:17 UTC, qw4990 commented on sql-statements/sql-statement-explain-analyze.md
> +`Pint_get` 算子可能包含以下执行信息：
有些拼写错误 Pint_get -> Point_get

2020-10-15 06:29 UTC, qw4990 commented on sql-statements/sql-statement-explain-analyze.md
> +- `ResolveLock:{num_rpc:22076, total_time:124.644857ms}`：读数据遇到锁后，进行 resolve lock 的时间。一般在读写冲突的场景下会出现。
不正常的话，可以换一个小点正常的，免得吓到用户。

2020-10-15 06:35 UTC, qw4990 commented on sql-statements/sql-statement-explain-analyze.md
> +`IndexJoin` 算子有 1 个 outer worker 和 N 个 inner worker 并行执行，其 join 结果的顺序和 outer table 的顺序一致，具体执行流程如下：
`worker`  的概念相当于内部实现了，这里暴露出来不确定是不是对用户不太友好，@SunRunAway 觉得呢。
不过不暴露的话，一些字段又不是很好解释清楚。

2020-10-15 06:43 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +`Pint_get` 算子可能包含以下执行信息：
```suggestion
`Point_get` 算子可能包含以下执行信息：
```

2020-10-15 08:26 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +- `ResolveLock:{num_rpc:22076, total_time:124.644857ms}`：读数据遇到锁后，进行 resolve lock 的时间。一般在读写冲突的场景下会出现。
Great, done.

2020-10-15 08:28 UTC, crazycs520 commented
@SunRunAway  PTAL

2020-10-15 08:31 UTC, SunRunAway commented on sql-statements/sql-statement-explain-analyze.md
> +### IndexJoin
感觉和这个PR冲突了： https://github.com/pingcap/docs/pull/3922

2020-10-19 11:43 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +### IndexJoin
和 Morgan 讨论过了，先 merge 这个 PR 吧，后面 Morgan 重构时再移。

2020-10-19 11:45 UTC, SunRunAway reviewed
LGTM

2020-10-20 10:42 UTC, qw4990 approved these changes
LGTM

2020-10-20 11:00 UTC, crazycs520 commented
@TomShawn PTAL

2020-10-22 05:00 UTC, yikeke approved these changes
Rest LGTM

2020-10-22 05:03 UTC, yikeke requested changes
Please merge https://github.com/pingcap/docs/pull/4071/ first as it is the source PR. @crazycs520

2020-11-03 06:21 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +1. Outer worker 读取 N 行 out table 的数据，然后包装成一个 task 发送给 result channel 和 inner worker channel。
```suggestion
1. Outer worker 读取 N 行 outer table 的数据，然后包装成一个 task 发送给 result channel 和 inner worker channel。
```

2020-11-03 06:41 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +1. Outer worker 读取 N 行 out table 的数据，然后包装成一个 task 发送给 inner worker channel。
out table 还是 outer table 呢？

2020-11-03 07:21 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +- `region`：执行 `lock_keys` 操作涉及的 region 数量。
```suggestion
- `region`：执行 `lock_keys` 操作涉及的 Region 数量。
```

2020-11-03 07:42 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +- `write_byte`：事务中写入 `key/value` 的总字节数量，单位是 byte。
`/` means `OR`. Is `OR` what you mean here?
```suggestion
- `write_byte`：事务中写入 `key-value` 的总字节数量，单位是 byte。
```

2020-11-03 08:06 UTC, TomShawn commented
@crazycs520 Please be aware of the differences in https://github.com/pingcap/docs/pull/4071 (I've already commented on them) and make sure the two versions are consistent.

2020-11-05 05:10 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +1. Outer worker 读取 N 行 out table 的数据，然后包装成一个 task 发送给 inner worker channel。
outer

2020-11-06 07:10 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +`IndexJoin` 算子有 1 个 outer worker 和 N 个 inner worker 并行执行，其 join 结果的顺序和 outer table 的顺序一致，具体执行流程如下：
See https://github.com/pingcap/docs/pull/4071/files#r516439733.

2020-11-06 07:11 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +2. Inner worker 从 inner worker channel 里面接收 task，然后根据 task 读取 inner table 相应范围的行数据，并生成一个 inner table row 的 hash table。
See the [docs PR comment](https://github.com/pingcap/docs/pull/4071/files#r516447555).

2020-11-06 07:16 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +    b. 根据 task 生成 key 的范围后，读取 inner table 相应范围的行数据。
[英文版](https://github.com/pingcap/docs/pull/4071/files#diff-037e26630bdc79f5de0298bb380d3698cd33e3ab10d063f67bec4aa6088c8127R177)是 `builds key ranges from outer rows and fetches inner rows`。请确认二者是否一致。

2020-11-06 07:36 UTC, TomShawn commented
[Line 31](https://github.com/pingcap/docs-cn/pull/4655/files#diff-037e26630bdc79f5de0298bb380d3698cd33e3ab10d063f67bec4aa6088c8127R31) 需要根据[英文 PR 对应的地方](https://github.com/pingcap/docs/pull/4071/files#diff-037e26630bdc79f5de0298bb380d3698cd33e3ab10d063f67bec4aa6088c8127R31)进行改动。

2020-11-09 05:17 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +    b. 根据 task 生成 key 的范围后，读取 inner table 相应范围的行数据。
是一致的

2020-11-09 05:20 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +2. Inner worker 从 inner worker channel 里面接收 task，然后根据 task 读取 inner table 相应范围的行数据，并生成一个 inner table row 的 hash table。
改了相应了英文 doc

2020-11-09 05:23 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +`IndexJoin` 算子有 1 个 outer worker 和 N 个 inner worker 并行执行，其 join 结果的顺序和 outer table 的顺序一致，具体执行流程如下：
done. 改了英文 doc

2020-11-09 09:31 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +- `check_insert`：这个信息一般出现在 `insert ignore` 和 `insert on duplicate` 语句中，包含冲突检查和写入 TiDB 内存的耗时。注意，这个耗时不包含事务提交的耗时。具体包含以下信息：
`写入 TiDB 内存` or `写入 TiDB 事务缓存`？

2020-11-09 09:33 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +2. Inner worker 从 inner worker channel 里面接收 task，然后根据 task 读取 inner table 相应范围的行数据，并生成一个 inner table row 的 hash table。
看起来还是不太一样。我先合英文哈。

2020-11-09 09:33 UTC, TomShawn commented on sql-statements/sql-statement-explain-analyze.md
> +4. `IndexJoin` 的主线程用 outer table rows 和 inner table rows 的 hash table 做 join 。
这里英文用的是`hash map`。

2020-11-09 12:48 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +4. `IndexJoin` 的主线程用 outer table rows 和 inner table rows 的 hash table 做 join 。
改了英文 doc

2020-11-09 12:49 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +- `check_insert`：这个信息一般出现在 `insert ignore` 和 `insert on duplicate` 语句中，包含冲突检查和写入 TiDB 内存的耗时。注意，这个耗时不包含事务提交的耗时。具体包含以下信息：
写入 TiDB 事务缓存

2020-11-09 12:54 UTC, crazycs520 commented on sql-statements/sql-statement-explain-analyze.md
> +2. Inner worker 从 inner worker channel 里面接收 task，然后根据 task 读取 inner table 相应范围的行数据，并生成一个 inner table row 的 hash table。
重新调整了下中文。

2020-11-16 03:06 UTC, TomShawn commented
@yikeke The docs PR has been merged. PTAL.

2020-11-16 03:19 UTC, yikeke approved these changes

2020-11-16 03:19 UTC, yikeke commented on sql-statements/sql-statement-explain-analyze.md
> +`execution info` 信息除了基本的 `time` 和 `loop` 信息外，还包含算子特有的执行信息，主要包含了该算子发送 RPC 的耗时信息以及其他步骤的耗时。
```suggestion
`execution info` 信息除了基本的 `time` 和 `loop` 信息外，还包含算子特有的执行信息，主要包含了该算子发送 RPC 请求的耗时信息以及其他步骤的耗时。
```

2020-11-16 03:19 UTC, yikeke commented on sql-statements/sql-statement-explain-analyze.md
> +- `regionMiss_backoff:{num:11, total_time:2010 ms},tikvRPC_backoff:{num:11, total_time:10691 ms}`：发送 RPC 请求失败后会等待 backoff 的时间后重试，包括了 backoff 的类型（如 regionMiss，tikvRPC），backoff 等待的总时间 (total_time) 和 ba
```suggestion
- `regionMiss_backoff:{num:11, total_time:2010 ms},tikvRPC_backoff:{num:11, total_time:10691 ms}`：RPC 请求失败后，会在等待 backoff 的时间后重试，包括了 backoff 的类型（如 regionMiss，tikvRPC），backoff 等待的总时间 (total_time) 和 backoff 的总次数 (num)。
```

2020-11-19 05:35 UTC, merged