update:quick-start-with-tidb.md
pingcap/docs-cn pull request #4742
Opened 2020-10-27 03:25 UTC by yanjingfan

### What is changed, added or deleted? (Required)
修改了quick-start-with-tidb.md

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:https://github.com/pingcap/docs-cn/issues/4720
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts

2020-10-27 03:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pingcap/docs-cn?pullRequest=4742) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/docs-cn?pullRequest=4742) before we can accept your contribution.<br/><hr/>**yanfgan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/docs-cn?pullRequest=4742) it.</sub>

2020-10-27 06:18 UTC, TomShawn commented
@yanjingfan Thanks for making a contribution! Could you please use a GitHub user account to create a PR and sign the [CLA](https://github.com/pingcap/docs-cn/pull/4742#issuecomment-716954467)?

2020-11-19 06:53 UTC, kissmydb requested changes

2020-11-19 06:53 UTC, kissmydb commented on quick-start-with-tidb.md
> +    + 首先安装mysql客户端，安装过mysql客户端的则可跳过这一小步骤
```suggestion
    + 首先安装 MySQL 客户端，安装过 MySQL 客户端的则可跳过这一小步骤
```

2020-11-19 06:53 UTC, kissmydb commented on quick-start-with-tidb.md
> +    + 使用mysql客户端连接TiDB
```suggestion
    + 使用 MySQL 客户端连接 TiDB
```

2020-11-19 06:53 UTC, kissmydb commented on quick-start-with-tidb.md
> +    + 安装mysql客户端，安装过mysql客户端的则可跳过这一小步骤
```suggestion
    + 安装 MySQL 客户端，安装过 MySQL 客户端的则可跳过这一小步骤
```

2020-11-23 03:14 UTC, TomShawn commented
@yanjingfan This PR is migrated to https://github.com/pingcap/docs-cn/pull/4943.

2020-11-23 03:14 UTC, closed without merging