Add incompatibility caused by deprecated features in mysql-compatibility.md
pingcap/docs-cn pull request #5378
Opened 2021-01-22 13:36 UTC by Joyinqin

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)
- [x] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs/pull/4590
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2021-01-22 14:00 UTC, Joyinqin commented
/label needs-cherry-pick-3.1, needs-cherry-pick-4.0, needs-cherry-pick-5.0

2021-01-25 02:56 UTC, Joyinqin commented
/cc ichn-hu, TomShawn

2021-01-25 10:23 UTC, TomShawn commented on mysql-compatibility.md
> +TiDB 不支持在 MySQL 中标记为弃用的功能。包括：
```suggestion
TiDB 不支持 MySQL 中标记为弃用的功能，包括：
```

2021-01-25 10:23 UTC, TomShawn commented on mysql-compatibility.md
> +* `ZEROFILL` 属性。 MySQL 8.0 [弃用](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html)了此功能，建议改在应用程序中填充数字值。
```suggestion
* `ZEROFILL` 属性。 MySQL 8.0 [弃用](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html)了此功能，建议改在业务应用中填充数字值。
```

2021-01-25 10:32 UTC, ichn-hu commented on mysql-compatibility.md
> +TiDB 不支持 MySQL 中标记为弃用的功能，包括：
TiDB 不会修复因为已经被 MySQL 标记为弃用状态的功能导致的不兼容问题，包括：

2021-01-25 10:33 UTC, ichn-hu requested changes

2021-01-25 10:33 UTC, ichn-hu commented on mysql-compatibility.md
> +TiDB 不支持 MySQL 中标记为弃用的功能，包括：
```suggestion
TiDB 不会修复已经被 MySQL 标记为弃用状态的功能导致的不兼容问题，包括：
```

2021-01-25 10:39 UTC, ichn-hu approved these changes

2021-01-25 10:42 UTC, merged