update tiup document (non-5.0)
pingcap/docs-cn pull request #5765
Opened 2021-03-18 04:18 UTC by lucklove

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2021-03-18 07:02 UTC, TomShawn commented
/label needs-cherry-pick-5.0

2021-03-18 07:02 UTC, TomShawn commented
/label needs-cherry-pick-4.0

2021-03-18 07:03 UTC, TomShawn commented
/status PTAL
/size large
/translation doing
/cc @AstroProfundis @King-Dylan @9547

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-cluster-topology-reference.md
> +- `external_alertmanagers`：配置 Prometheus 将报警通知到集群之外的 alertmanager，该字段为一个数组，数组的元素为每个外部的 alertmanager，由 `host` 和 `web_port` 字段构成
```suggestion
- `external_alertmanagers`：配置 Prometheus 将报警通知到集群之外的 Alertmanager，该字段为一个数组，数组的元素为每个外部的 Alertmanager，由 `host` 和 `web_port` 字段构成
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-cluster-topology-reference.md
> +      - url: http://127.0.0.1:8003/read
这里也添加上 `external_alertmanagers` 的配置吧

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-cluster-check.md
> +指定要关闭自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第一列。
```suggestion
指定要检查的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第一列。
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-cluster-check.md
> +指定要关闭自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第二列。
```suggestion
指定要检查的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第二列。
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-cluster-template.md
> +在不指定任何选项的情况下，输出默认模版：
```suggestion
在不指定任何选项的情况下，输出默认模版，包含下面的角色：
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-cluster-template.md
> +- 1 个 prometheus
```suggestion
- 1 个 Prometheus
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-cluster-template.md
> +- 1 个 grafana
```suggestion
- 1 个 Grafana
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-cluster-template.md
> +- 1 个 alertmanager
```suggestion
- 1 个 Alertmanager
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-cluster-template.md
> +根据指定选项输出拓扑模版，可重定向到拓扑文件中用于部署。
```suggestion
根据指定选项输出拓扑模版到标准输出，可重定向到拓扑文件中用于部署。
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-disable.md
> +### -N, --node（strings，默认为 []，未选中任何节点）
```suggestion
### -N, --node（strings，默认为 []，表示所有节点）
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-disable.md
> +### -R, --role strings（strings，默认为 []，未选中任何角色）
```suggestion
### -R, --role strings（strings，默认为 []，表示所有角色）
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-enable.md
> +### -N, --node（strings，默认为 []，未选中任何节点）
```suggestion
### -N, --node（strings，默认为 []，表示所有节点）
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-enable.md
> +### -R, --role strings（strings，默认为 []，未选中任何角色）
```suggestion
### -R, --role strings（strings，默认为 []，表示所有角色）
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-patch.md
> +声明当前集群处于停止状态。指定该选项时，TiUP DM 仅原地替换集群组件的二进制文件，不重启服务。
```suggestion
声明当前集群处于离线状态。指定该选项时，TiUP DM 仅原地替换集群组件的二进制文件，不重启服务。
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-template.md
> +- 1 个 prometheus
```suggestion
- 1 个 Prometheus
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-template.md
> +- 1 个 grafana
```suggestion
- 1 个 Grafana
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-template.md
> +- 1 个 alertmanager
```suggestion
- 1 个 Alertmanager
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-template.md
> +根据指定选项输出拓扑模版，可重定向到拓扑文件中用于部署。
```suggestion
根据指定选项输出拓扑模版到标准输出，可重定向到拓扑文件中用于部署。
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-component-dm-upgrade.md
> +声明当前集群处于停止状态。指定该选项时，TiUP DM 仅原地替换集群组件的二进制文件，不重启服务。
```suggestion
声明当前集群处于离线状态。指定该选项时，TiUP DM 仅原地替换集群组件的二进制文件，不重启服务。
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-dm-topology-reference.md
> +- `external_alertmanagers`：配置 Prometheus 将报警通知到集群之外的 alertmanager，该字段为一个数组，数组的元素为每个外部的 alertmanager，由 `host` 和 `web_port` 字段构成
```suggestion
- `external_alertmanagers`：配置 Prometheus 将报警通知到集群之外的 Alertmanager，该字段为一个数组，数组的元素为每个外部的 Alertmanager，由 `host` 和 `web_port` 字段构成
```

2021-03-21 09:37 UTC, 9547 commented on tiup/tiup-dm-topology-reference.md
> +      - url: http://127.0.0.1:8003/read
please append the `external_alertmanagers`

2021-04-14 06:14 UTC, AstroProfundis approved these changes

2021-04-19 02:25 UTC, TomShawn commented
/rebase

2021-04-19 02:45 UTC, TomShawn commented
/cc @lilyjazz

2021-04-20 04:22 UTC, lilyjazz commented
/lgtm

2021-04-20 04:23 UTC, lilyjazz reviewed
/lgtm

2021-04-20 11:51 UTC, TomShawn commented
/cc @qiancai

2021-04-21 06:46 UTC, TomShawn commented on tiup/tiup-dm-topology-reference.md
> +    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
```suggestion
- `remote_config`：用于支持将 Prometheus 数据写到远端，或从远端读取数据。详细信息见 [`<remote_write>`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) 和 [`<remote_read>`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read)
```

2021-04-21 08:10 UTC, TomShawn commented on tiup/tiup-component-dm-disable.md
> +```sh
```suggestion
```shell
```

2021-04-21 08:10 UTC, TomShawn commented on tiup/tiup-component-dm-enable.md
> +指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-dm-display.md)表格的第一列。
comment 同 tiup/tiup-component-cluster-check.md 的 comment。

2021-04-21 08:10 UTC, TomShawn commented on tiup/tiup-component-dm-replay.md
> +title: tiup dm replay
comment 同 tiup/tiup-component-cluster-replay.md 的 comment

2021-04-21 08:10 UTC, TomShawn commented on tiup/tiup-component-dm-template.md
> +title: tiup dm template
同 tiup/tiup-component-cluster-template.md 的 comment

2021-04-21 08:10 UTC, TomShawn commented on tiup/tiup-dm-topology-reference.md
> +- `external_alertmanagers`：配置 Prometheus 将报警通知到集群之外的 Alertmanager，该字段为一个数组，数组的元素为每个外部的 Alertmanager，由 `host` 和 `web_port` 字段构成
```suggestion
- `external_alertmanagers`：若配置 Prometheus 了，TiUP 会将配置行为报警通知到集群外的 Alertmanager。该字段为一个数组，数组的元素为每个外部的 Alertmanager，由 `host` 和 `web_port` 字段构成
```

2021-04-21 08:10 UTC, TomShawn commented on tiup/tiup-component-dm-disable.md
> +> 若同时指定了 `-N, --node`，那么将关闭它们的交集中的服务自启。
ditto

2021-04-21 09:06 UTC, qiancai requested changes

2021-04-21 09:06 UTC, qiancai commented on tiup/tiup-component-dm-patch.md
> +- 通过以上步骤之后，`/tmp/${component}-hotfix-${os}-${arch}.tar.gz` 就可以用于 patch 命令了
```suggestion

完成以上操作后，`/tmp/${component}-hotfix-${os}-${arch}.tar.gz` 就可以作为 `<package-path>` 用于 patch 命令中。
```

2021-04-23 04:23 UTC, lucklove commented on tiup/tiup-cluster-topology-reference.md
> +    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
这不太好，原文的意思是 remote_config 下面可以配置 remote_write 和 remote_read 两个字段，改动之后的内容看不出来应该咋配了

2021-04-23 04:25 UTC, lucklove commented on tiup/tiup-cluster-topology-reference.md
> +- `external_alertmanagers`：配置 Prometheus 将报警通知到集群之外的 Alertmanager，该字段为一个数组，数组的元素为每个外部的 Alertmanager，由 `host` 和 `web_port` 字段构成
改动之后意思不对。

Prometheus 是发动通知的主体（而非 TiUP），这个配置是告诉 prometheus 将报警通知到集群外的 alertmanager

2021-04-23 04:26 UTC, lucklove commented on tiup/tiup-component-cluster-check.md
> +### -N, --node（strings，默认为 []，表示所有节点）
括号里的好像还是需要的

2021-04-23 04:31 UTC, lucklove commented on tiup/tiup-component-cluster-template.md
> +输出详细的拓扑模版。默认输出最简单的拓扑模版，打开该选项后，输出详细的拓扑模版，以注释的形式带上可配置的参数。
原文的意思是：输出详细的拓扑模版，（该详细的模版会）以注释的形式带上可配置的参数

2021-04-23 04:33 UTC, lucklove commented on tiup/tiup-dm-topology-reference.md
> +    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
ditto

2021-04-23 04:33 UTC, lucklove commented on tiup/tiup-dm-topology-reference.md
> +- `external_alertmanagers`：配置 Prometheus 将报警通知到集群之外的 Alertmanager，该字段为一个数组，数组的元素为每个外部的 Alertmanager，由 `host` 和 `web_port` 字段构成
ditto，改变了原来的意思

2021-04-23 06:18 UTC, lucklove commented on tiup/tiup-cluster-topology-reference.md
> +    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
因为 prometheus 官方的文档是按这种形式来介绍的：https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write

2021-04-23 06:35 UTC, TomShawn commented on tiup/tiup-component-cluster-template.md
> +输出详细的拓扑模版。默认输出最简单的拓扑模版，打开该选项后，输出详细的拓扑模版，以注释的形式带上可配置的参数。
已修改 comment。

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-cluster-check.md
>  ### --enable-cpu（boolean，默认 false）
```suggestion
### --enable-cpu
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-cluster-enable.md
> +### -N, --node（strings，默认为 []，表示所有节点）
```suggestion
### -N, --node
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-cluster-enable.md
> +### -R, --role strings（strings，默认为 []，表示所有角色）
```suggestion
### -R, --role strings
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-cluster-replay.md
> +### -h, --help（boolean，默认 false）
```suggestion
### -h, --help
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-cluster-template.md
> +### --full（boolean，默认 false）
```suggestion
### --full
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-cluster-template.md
> +### --multi-dc（boolean，默认 false）
```suggestion
### --multi-dc
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-cluster-template.md
> +### -h, --help（boolean，默认 false）
```suggestion
### -h, --help
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-disable.md
> +### -N, --node（strings，默认为 []，表示所有节点）
```suggestion
### -N, --node
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-disable.md
> +### -R, --role strings（strings，默认为 []，表示所有角色）
```suggestion
### -R, --role strings
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-disable.md
> +### -h, --help（boolean，默认 false）
```suggestion
### -h, --help
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-enable.md
> +### -N, --node（strings，默认为 []，表示所有节点）
```suggestion
### -N, --node
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-enable.md
> +### -R, --role strings（strings，默认为 []，表示所有角色）
```suggestion
### -R, --role strings
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-enable.md
> +### -h, --help（boolean，默认 false）
```suggestion
### -h, --help
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-patch.md
> +## --offline（boolean，默认 false）
```suggestion
## --offline
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-patch.md
>  ### -h, --help（boolean，默认 false）
```suggestion
### -h, --help
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-replay.md
> +### -h, --help（boolean，默认 false）
```suggestion
### -h, --help
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-template.md
> +### --full（boolean，默认 false）
```suggestion
### --full
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-template.md
> +### -h, --help（boolean，默认 false）
```suggestion
### -h, --help
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-upgrade.md
> +## --offline（boolean，默认 false）
```suggestion
## --offline
```

2021-04-23 06:46 UTC, lucklove commented on tiup/tiup-component-dm-upgrade.md
>  ### -h, --help（boolean，默认 false）
```suggestion
### -h, --help
```

2021-04-23 07:01 UTC, lucklove commented on tiup/tiup-cluster-topology-reference.md
> +    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
```suggestion
- `remote_config`：用于支持将 Prometheus 数据写到远端，或从远端读取数据，该字段下有两个配置：
    - `remote_write`：[ - [<remote_write>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) ... ]
    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
```

2021-04-23 07:01 UTC, lucklove commented on tiup/tiup-dm-topology-reference.md
> +    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
```suggestion
- `remote_config`：用于支持将 Prometheus 数据写到远端，或从远端读取数据，该字段下有两个配置：
    - `remote_write`：[ - [<remote_write>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) ... ]
    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
```

2021-04-26 06:43 UTC, TomShawn commented on tiup/tiup-component-cluster-disable.md
> +### -R, --role strings
```suggestion
### -R, --role
```

2021-04-26 06:43 UTC, TomShawn commented on tiup/tiup-component-cluster-enable.md
> +### -R, --role strings
```suggestion
### -R, --role
```

2021-04-26 06:45 UTC, TomShawn commented on tiup/tiup-component-dm-template.md
> +```sh
```suggestion
```shell
```

2021-04-26 06:45 UTC, TomShawn commented on tiup/tiup-component-dm-replay.md
> +```sh
```suggestion
```shell
```

2021-04-26 06:46 UTC, TomShawn commented on tiup/tiup-component-dm-enable.md
> +### -R, --role strings
```suggestion
### -R, --role
```

2021-04-26 06:46 UTC, TomShawn commented on tiup/tiup-component-cluster-check.md
> +### -R, --role strings
```suggestion
### -R, --role
```

2021-04-26 06:46 UTC, TomShawn commented on tiup/tiup-component-dm-disable.md
> +### -R, --role strings
```suggestion
### -R, --role
```

2021-04-26 06:52 UTC, lucklove commented on tiup/tiup-component-cluster-replay.md
> +```sh
```suggestion
```shell
```

2021-04-26 06:52 UTC, lucklove commented on tiup/tiup-component-cluster-template.md
> +```sh
```suggestion
```shell
```

2021-04-26 06:52 UTC, lucklove commented on tiup/tiup-component-dm-enable.md
> +```sh
```suggestion
```shell
```

2021-04-26 07:08 UTC, lucklove commented on tiup/tiup-component-cluster-check.md
> +指定要检查的角色。该选项的值为以逗号分割的节点角色列表，角色为 [`tiup-component-cluster-display`](/tiup/tiup-component-cluster-display.md) 命令返回的集群状态表格的第二列。
```suggestion
### -R, --role

- 指定要检查的角色。该选项的值为以逗号分割的节点角色列表，角色为 [`tiup-component-cluster-display`](/tiup/tiup-component-cluster-display.md) 命令返回的集群状态表格的第二列。
- 数据类型：`STRINGS`
- 如果不指定该选项，默认检查所有角色。
```

2021-04-26 07:08 UTC, lucklove commented on tiup/tiup-component-cluster-disable.md
>  指定要关闭自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第一列。
```suggestion
- 指定要关闭自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第一列。
- 数据类型：`STRINGS`
- 如果不指定该选项，默认检查所有节点。
- 
```

2021-04-26 07:08 UTC, lucklove commented on tiup/tiup-component-cluster-disable.md
>  指定要关闭自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第二列。
```suggestion
### -R, --role

- 指定要关闭自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第二列。
- 数据类型：`STRINGS`
- 如果不指定该选项，默认 disable 所有角色。
```

2021-04-26 07:08 UTC, lucklove commented on tiup/tiup-component-cluster-enable.md
>  指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第一列。
```suggestion
- 指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第一列。
- 数据类型：`STRINGS`
- 如果不指定该选项，默认 enable 所有节点。
```

2021-04-26 07:08 UTC, lucklove commented on tiup/tiup-component-cluster-enable.md
>  指定要开启自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第二列。
```suggestion
### -R, --role

- 指定要开启自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第二列。
- 数据类型：`STRINGS`
- 如果不指定该选项，默认 enable 所有角色。
```

2021-04-26 07:08 UTC, lucklove commented on tiup/tiup-cluster-topology-reference.md
> +- `external_alertmanagers`：若配置了 `external_alertmanagers`，Prometheus 会将配置行为报警通知到集群外的 Alertmanager。该字段为一个数组，数组的元素为每个外部的 Alertmanager，由 `host` 和 `web_port` 字段构成
```suggestion
- `remote_config`：用于支持将 Prometheus 数据写到远端，或从远端读取数据，该字段下有两个配置：
    - `remote_write`：参考 Prometheus [<remote_write>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) 文档
    - `remote_read`：参考 Prometheus [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) 文档
- `external_alertmanagers`：若配置了 `external_alertmanagers`，Prometheus 会将配置行为报警通知到集群外的 Alertmanager。该字段为一个数组，数组的元素为每个外部的 Alertmanager，由 `host` 和 `web_port` 字段构成
```

2021-04-26 08:46 UTC, TomShawn commented on tiup/tiup-component-cluster-disable.md
> +-
```suggestion
```

2021-04-26 09:39 UTC, TomShawn commented on tiup/tiup-cluster-topology-reference.md
> +    - `remote_write`：参考 Prometheus [<remote_write>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) 文档
```suggestion
    - `remote_write`：参考 Prometheus [`<remote_write>`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) 文档
```

2021-04-26 09:39 UTC, TomShawn commented on tiup/tiup-cluster-topology-reference.md
> +    - `remote_read`：参考 Prometheus [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) 文档
```suggestion
    - `remote_read`：参考 Prometheus [`<remote_read>`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) 文档
```

2021-04-26 09:39 UTC, TomShawn commented on tiup/tiup-component-cluster-disable.md
> +- 指定要关闭自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第一列。
```suggestion
- 指定要关闭自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为 [`tiup-component-cluster-display`](/tiup/tiup-component-cluster-display.md) 命令返回的集群状态表格的第一列。
```

2021-04-26 09:39 UTC, TomShawn commented on tiup/tiup-component-cluster-disable.md
> +- 指定要关闭自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第二列。
```suggestion
- 指定要关闭自启的角色，该选项的值为以逗号分割的节点角色列表，角角色为 [`tiup-component-cluster-display`](/tiup/tiup-component-cluster-display.md) 命令返回的集群状态表格的第二列。
```

2021-04-26 09:39 UTC, TomShawn commented on tiup/tiup-component-cluster-enable.md
> +- 指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第一列。
```suggestion
- 指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，角色为 [`tiup-component-cluster-display`](/tiup/tiup-component-cluster-display.md) 命令返回的集群状态表格的第一列。
```

2021-04-26 09:39 UTC, TomShawn commented on tiup/tiup-component-cluster-enable.md
>  指定要开启自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-cluster-display.md)表格的第二列。
```suggestion
- 指定要开启自启的角色，该选项的值为以逗号分割的节点角色列表，角色为 [`tiup-component-cluster-display`](/tiup/tiup-component-cluster-display.md) 命令返回的集群状态表格的第二列。
- 数据类型：`STRINGS`
- 如果不指定该选项，默认关闭所有角色的自启。
```

2021-04-26 09:39 UTC, TomShawn commented on tiup/tiup-component-cluster-template.md
> +输出详细的拓扑模版。如果不指定该选项，默认输出最简单的拓扑模版。通过在命令中添加该选项，可开启该选项，输出详细的拓扑模版，该详细的模版会以注释的形式带上可配置的参数。
```suggestion
输出详细的拓扑模版。如果不指定该选项，默认输出最简单的拓扑模版。通过在命令中添加该选项，可开启该选项，输出详细的拓扑模版。该详细的模版会以注释的形式带上可配置的参数。
```

2021-04-26 09:41 UTC, TomShawn commented on tiup/tiup-component-dm-disable.md
> +指定要关闭自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-dm-display.md)表格的第一列。
建议复用 https://github.com/pingcap/docs-cn/pull/5765#discussion_r620120305
还有：
```
- 数据类型：`STRINGS`
- 如果不指定该选项，默认开启所有节点的自启。
```

2021-04-26 09:43 UTC, TomShawn commented on tiup/tiup-component-dm-disable.md
> +指定要关闭自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-dm-display.md)表格的第二列。
建议复用 https://github.com/pingcap/docs-cn/pull/5765#discussion_r620120564
还有：
```
- 数据类型：`STRINGS`
- 如果不指定该选项，默认关闭所有角色的自启。
```

2021-04-26 09:43 UTC, TomShawn commented on tiup/tiup-component-dm-enable.md
> +指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-dm-display.md)表格的第一列。
建议复用 https://github.com/pingcap/docs-cn/pull/5765#discussion_r620121872

2021-04-26 09:46 UTC, TomShawn commented on tiup/tiup-component-dm-enable.md
> +指定要开启自启的角色，该选项的值为以逗号分割的节点角色列表，角色为[集群状态](/tiup/tiup-component-dm-display.md)表格的第二列。
建议复用 https://github.com/pingcap/docs-cn/pull/5765#discussion_r620121872

2021-04-26 09:47 UTC, TomShawn commented on tiup/tiup-component-dm-replay.md
> +在执行升级/重启集群等操作时，有可能因为环境的原因导致偶然失败，这时如果重新执行操作，会从头开始，如果集群规模较大，会比较浪费时间。使用 `tiup dm replay` 命令，可以重试刚才失败的命令，并且跳过已经成功的步骤。
```suggestion
对集群执行升级或重启等操作时，操作有可能因为环境的原因而偶然失败。这时如果重新执行操作，需要从头开始所有步骤。如果集群规模较大，会耗费较长时间。此时可以使用 `tiup dm replay` 命令，命令重试刚才失败的命令，并且跳过已经成功的步骤。
```

2021-04-26 09:48 UTC, TomShawn commented on tiup/tiup-component-dm-replay.md
> +- `<audit-id>` 代表要重试的命令对应的 audit-id，历史命令及其 audit-id 可以通过命令 [tiup dm audit](/tiup/tiup-component-dm-audit.md) 查看
```suggestion
- `<audit-id>` 代表要重试的命令对应的 `audit-id`。使用 [`tiup dm audit`](/tiup/tiup-component-dm-audit.md) 可查看历史命令及其 `audit-id`。
```

2021-04-26 09:54 UTC, TomShawn commented on tiup/tiup-component-dm-template.md
> +部署集群之前，需要准备一份集群的[拓扑文件](/tiup/tiup-dm-topology-reference.md)，TiUP 内置了拓扑文件的模版，用户可以通过修改模版来生成最终的拓扑文件。命令 `tiup dm template` 用于输出 TiUP 内置的模版内容。
```suggestion
部署集群之前，需要准备一份集群的[拓扑文件](/tiup/tiup-dm-topology-reference.md)。TiUP 内置了拓扑文件的模版，用户可以通过修改模版来生成最终的拓扑文件。命令 `tiup dm template` 用于输出 TiUP 内置的模版内容。
```

2021-04-26 09:54 UTC, TomShawn commented on tiup/tiup-component-dm-template.md
> +- 3 个 DM Worker
```suggestion
- 3 个 DM-master 节点
- 3 个 DM-worker 节点
```

2021-04-26 09:54 UTC, TomShawn commented on tiup/tiup-component-dm-template.md
> +在不指定任何选项的情况下，输出默认模版：
```suggestion
在不指定任何选项的情况下，输出默认模版：
```
```suggestion
如果不指定该选项，输出的默认模版包含以下角色：
```

2021-04-26 09:54 UTC, TomShawn commented on tiup/tiup-component-dm-template.md
> +输出详细的拓扑模版。默认输出最简单的拓扑模版，打开该选项后，输出详细的拓扑模版，以注释的形式带上可配置的参数。
```suggestion
输出详细的拓扑模版。如果不指定该选项，默认输出最简单的拓扑模版。通过在命令中添加该选项，可开启该选项，输出详细的拓扑模版。该详细的模版会以注释的形式带上可配置的参数。
```

2021-04-26 09:54 UTC, TomShawn commented on tiup/tiup-dm-topology-reference.md
> +    - `remote_read`：[ - [<remote_read>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) ... ]
```suggestion
    - `remote_write`：参考 Prometheus [<remote_write>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) 文档
    - `remote_read`：参考 Prometheus [`<remote_read>`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read) 文档
```

2021-04-26 10:57 UTC, TomShawn approved these changes
Rest LGTM

2021-04-26 10:57 UTC, TomShawn commented on tiup/tiup-component-cluster-disable.md
> +- 如果不指定该选项，默认检查所有节点。
```suggestion
- 如果不指定该选项，默认关闭所有节点的自启。
```

2021-04-26 10:57 UTC, TomShawn commented on tiup/tiup-component-dm-enable.md
> +指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-dm-display.md)表格的第一列。
```suggestion
- 指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-dm-display.md)表格的第一列。
- 数据类型：`STRINGS`
- 如果不指定该选项，默认关闭所有节点的自启。
```

2021-04-26 10:59 UTC, TomShawn commented on tiup/tiup-dm-topology-reference.md
> +    - `remote_write`：参考 Prometheus [<remote_write>](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) 文档
```suggestion
    - `remote_write`：参考 Prometheus [ `<remote_write>` ](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write) 文档
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-cluster-enable.md
> +- 指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，角色为 [`tiup-component-cluster-display`](/tiup/tiup-component-cluster-display.md) 命令返回的集群状态表格的第一列。
```suggestion
- 指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为 [`tiup-component-cluster-display`](/tiup/tiup-component-cluster-display.md) 命令返回的集群状态表格的第一列。
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-cluster-replay.md
> +对集群执行升级或重启等操作时，操作有可能因为环境的原因而偶然失败。这时如果重新执行操作，需要从头开始所有步骤。如果集群规模较大，会耗费较长时间。此时可以使用 `tiup cluster replay` 命令重试刚才失败的命令，并且跳过已经成功的步骤。
```suggestion
对集群进行升级或重启等操作时，操作有可能因为环境的原因而偶然失败。这时如果重新进行操作，需要从头开始执行所有步骤。如果集群规模较大，会耗费较长时间。此时可以使用 `tiup cluster replay` 命令重试刚才失败的命令，并且跳过已经成功的步骤。
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-cluster-template.md
> +部署集群之前，需要准备一份集群的[拓扑文件](/tiup/tiup-cluster-topology-reference.md)。TiUP 内置了拓扑文件的模版，用户可以通过修改该模版来生成最终的拓扑文件。命令 `tiup cluster template` 用于输出 TiUP 内置的模版内容。
```suggestion
部署集群之前，需要准备一份集群的[拓扑文件](/tiup/tiup-cluster-topology-reference.md)。TiUP 内置了拓扑文件的模版，用户可以通过修改该模版来生成最终的拓扑文件。使用 `tiup cluster template` 命令可以输出 TiUP 内置的模版内容。
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-cluster-template.md
> +如果不指定该选项，输出的默认模版包含以下角色：
关于"输出的默认模版包含以下角色"，请问以下这些是“角色”吗？

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-cluster-template.md
> +输出详细的拓扑模版。如果不指定该选项，默认输出最简单的拓扑模版。通过在命令中添加该选项，可开启该选项，输出详细的拓扑模版。该详细的模版会以注释的形式带上可配置的参数。
```suggestion
- 输出详细的拓扑模版，该模版会以注释的形式带上可配置的参数。在命令中添加该选项，可开启该选项。
- 如果不指定该选项，默认输出最简单的拓扑模版。
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-cluster-template.md
> +输出多数据中心的拓扑模版。如果不指定该选项，默认输出单地单机房的拓扑模版。通过在命令中添加该选项，可开启该选项，输出多数据中心的配置用例。
```suggestion
- 输出多数据中心的拓扑模版。在命令中添加该选项，可开启该选项。
- 如果不指定该选项，默认输出单地单机房的拓扑模版。
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-dm-enable.md
> +- 如果不指定该选项，默认关闭所有角色的自启。
```suggestion
- 如果不指定该选项，默认开启所有角色的自启。
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-dm-enable.md
> +指定要开启自启的节点，该选项的值为以逗号分割的节点 ID 列表，节点 ID 为[集群状态](/tiup/tiup-component-dm-display.md)表格的第一列。
这行后面缺失了如下内容？
- 数据类型：`STRINGS` 
- 如果不指定该选项，默认开启所有节点的自启

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-dm-replay.md
> +对集群执行升级或重启等操作时，操作有可能因为环境的原因而偶然失败。这时如果重新执行操作，需要从头开始所有步骤。如果集群规模较大，会耗费较长时间。此时可以使用 `tiup dm replay` 命令，命令重试刚才失败的命令，并且跳过已经成功的步骤。
```suggestion
对集群进行升级或重启等操作时，操作有可能因为环境的原因而偶然失败。这时如果重新进行操作，需要从头开始执行所有步骤。如果集群规模较大，会耗费较长时间。此时可以使用 `tiup dm replay` 命令，命令重试刚才失败的命令，并且跳过已经成功的步骤。
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-dm-template.md
> +部署集群之前，需要准备一份集群的[拓扑文件](/tiup/tiup-dm-topology-reference.md)。TiUP 内置了拓扑文件的模版，用户可以通过修改模版来生成最终的拓扑文件。命令 `tiup dm template` 用于输出 TiUP 内置的模版内容。
```suggestion
部署集群之前，需要准备一份集群的[拓扑文件](/tiup/tiup-dm-topology-reference.md)。TiUP 内置了拓扑文件的模版，用户可以通过修改模版来生成最终的拓扑文件。使用 `tiup dm template` 命令可以输出 TiUP 内置的模版内容。
```

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-dm-template.md
> +如果不指定该选项，输出的默认模版包含以下角色：
关于 “角色” 的疑问，以下这些都是角色吗？

2021-04-26 11:51 UTC, qiancai commented on tiup/tiup-component-dm-template.md
> +输出详细的拓扑模版。如果不指定该选项，默认输出最简单的拓扑模版。通过在命令中添加该选项，可开启该选项，输出详细的拓扑模版。该详细的模版会以注释的形式带上可配置的参数。
```suggestion
- 输出详细的拓扑模版，该模版会以注释的形式带上可配置的参数。在命令中添加该选项，可开启该选项。
- 如果不指定该选项，默认输出最简单的拓扑模版。
```

2021-04-26 11:59 UTC, lucklove commented on tiup/tiup-component-dm-template.md
> +如果不指定该选项，输出的默认模版包含以下角色：
是的

2021-04-26 11:59 UTC, lucklove commented on tiup/tiup-component-dm-template.md
> +- 1 个 Alertmanager
```suggestion
- 3 个 DM-master 实例
- 3 个 DM-worker 实例
- 1 个 Prometheus 实例
- 1 个 Grafana 实例
- 1 个 Alertmanager 实例
```

2021-04-27 01:20 UTC, qiancai commented on tiup/tiup-component-dm-template.md
> +如果不指定该选项，输出的默认模版包含以下角色：
这里的“角色”就是下面提到的“实例”吗？如果是，可否改成“输出的默认模版包含以下实例：”呢？

2021-04-27 01:20 UTC, qiancai commented on tiup/tiup-component-cluster-template.md
> +如果不指定该选项，输出的默认模版包含以下角色：
这里的“角色”就是下面提到的“实例”吗？如果是，可否改成“输出的默认模版包含以下实例：”呢？

2021-04-27 01:20 UTC, qiancai commented on tiup/tiup-component-cluster-template.md
> +- 1 个 Alertmanager
tiup/tiup-component-dm-template.md 文件同样的位置，在以下各项末尾说明了是 “实例”， 所以这里也可以说明是“实例”？
```suggestion
- 1 个 Prometheus 实例
- 1 个 Grafana 实例
- 1 个 Alertmanager 实例
```

2021-04-27 02:46 UTC, lucklove commented on tiup/tiup-component-cluster-template.md
> +如果不指定该选项，输出的默认模版包含以下角色：
```suggestion
如果不指定该选项，输出的默认模版包含以下实例：
```

2021-04-27 02:46 UTC, lucklove commented on tiup/tiup-component-dm-template.md
> +如果不指定该选项，输出的默认模版包含以下角色：
```suggestion
如果不指定该选项，输出的默认模版包含以下实例：
```

2021-04-27 05:34 UTC, TomShawn commented
/lgtm

2021-04-27 05:46 UTC, qiancai commented
/lgtm

2021-04-27 06:00 UTC, TomShawn commented
/merge

2021-04-27 06:01 UTC, merged

2021-04-27 06:09 UTC, TomShawn commented
/assign Joyinqin

2021-04-29 03:02 UTC, Joyinqin commented
/translation done
/remove-translation doing