releases: add tidb 5.0.1 release notes
pingcap/docs-cn pull request #6061
Opened 2021-04-19 09:28 UTC by TomShawn

### What is changed, added or deleted? (Required)
Add tidb 5.0.1 release notes

### Which TiDB version(s) do your changes apply to? (Required)

- [ ] master (the latest development version)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs/pull/5392
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2021-04-19 09:30 UTC, TomShawn commented
/label needs-cherry-pick-5.0
/translation from-docs
/hold

2021-04-19 10:00 UTC, TomShawn commented
/assign @solotzg @5kbpers

2021-04-19 11:02 UTC, TomShawn commented
/assign @overvenus @nolouch

2021-04-20 05:19 UTC, 5kbpers commented on releases/release-5.0.1.md
> +
+ TiKV
    - 使用 `zstd` 压缩 Region Snapshot [#10005](https://github.com/tikv/tikv/pull/10005)

2021-04-20 05:27 UTC, 5kbpers commented on releases/release-5.0.1.md
> +## Bug 修复
```suggestion
## Bug 修复

+ TiKV
    - 修复了 coprocessor 的 IN 表达式未正确处理 unsigned/signed int 类型数据的问题 [#10018](https://github.com/tikv/tikv/pull/10018)
    - 修复了在 batch ingest SST 之后产生大量空 Region 的问题 [#10015](https://github.com/tikv/tikv/pull/10015)
    - 修复了 `cast_string_as_time` 输入非法的 UTF-8 值之和导致 panic 的问题 [#9995](https://github.com/tikv/tikv/pull/9995)
    - 修复了“文件目录”文件损坏之后 TiKV 无法启动的问题 [#9992](https://github.com/tikv/tikv/pull/9992)

```

2021-04-20 05:56 UTC, winoros commented on releases/release-5.0.1.md
> +## Bug 修复
```suggestion
## Bug 修复

+ TiDB
    - 修复投影消除在投影结果为空时执行结果可能错误的问题 [#24093](https://github.com/pingcap/tidb/pull/24093)
    - 修复某些情况下列允许为 NULL 时执行结果可能错误的问题 [#24063](https://github.com/pingcap/tidb/pull/24063)
    - 当有虚拟列参与运算时不允许生成 MPP 计划 [#24058](https://github.com/pingcap/tidb/pull/24058)
    - 修复 Plan Cache 中对 PointGet 和 TableDual 错误的重复使用 [#24043](https://github.com/pingcap/tidb/pull/24043)
    - IndexMerge 算子需要保留聚簇索引的输出 [#24042](https://github.com/pingcap/tidb/pull/24042)
    - 修复 BIT 类型相关的错误的类型推导 [#24027](https://github.com/pingcap/tidb/pull/24027)
    - 修复某些优化器 hint 在 PointGet 算子存在时无法生效的问题 [#23685](https://github.com/pingcap/tidb/pull/23685)
    - 修复某些情况下 DDL job 在将状态设置外 rolling back 时可能的参数解析失败的问题 [#24080](https://github.com/pingcap/tidb/pull/24080)
    - Fix range building for binary literal [#24041](https://github.com/pingcap/tidb/pull/24041)
    - 修复某些情况下 IN 语句执行结果可能错误的问题 [#24023](https://github.com/pingcap/tidb/pull/24023)
    - 修复某些字符串函数返回结果错误的问题 [#23879](https://github.com/pingcap/tidb/pull/23879)
    - 执行 REPLACE 语句需要用户同时拥有 INSERT 和 DELETE 的权限 [#23939](https://github.com/pingcap/tidb/pull/23939)
    - 修复点差时的性能回退 [#24070](https://github.com/pingcap/tidb/pull/24070)
```

2021-04-20 06:04 UTC, TomShawn commented
/unassign @overvenus 
/assign @3pointer

2021-04-20 08:46 UTC, solotzg commented on releases/release-5.0.1.md
> +## Bug 修复
+ TiFLash

    - 修复存储引擎无法删除某些范围数据的问题
    - 修复 `time` 转换为 `int` 时产生错误结果的问题
    - 修复 `receiver` 可能无法在 10 秒内找到对应任务的问题
    - 修复 `cancelMPPQuery` 中可能存在无效迭代器的问题
    - 修复 `bitwise` 操作和 TiDB 行为不一致的问题
    - 修复当使用 `prefix key` 时出现范围重叠报错的问题
    - 修复字符串转换为 `int` 时产生错误结果的问题
    - 修复连续快速写入可能导致 TiFlash OOM 的问题
    - 修复列名重复会引发报错的问题
    - 修复 MPP 执行计划无法被解析的问题
    - 修复 Table GC 时会引发空指针的问题
    - 修复向已被删除的表写数据时 TiFlash 进程崩溃的问题
    - 修复当使用 BR Restore 时 TiFlash 进程崩溃的问题

2021-04-20 09:35 UTC, 3pointer commented on releases/release-5.0.1.md
> +
```suggestion
+ Tools

 - BR
	         * 修复备份时设置 ratelimit 不生效的问题. [#1026](https://github.com/pingcap/br/pull/1026)
	         * 修复备份时不能容忍少部分 TiKV 节点挂掉的问题. [#1019](https://github.com/pingcap/br/pull/1019)    
	          
	    - TiCDC
	         * 修复 unified sorter 中的并发问题，以及改进日志. [#1678](https://github.com/pingcap/ticdc/pull/1678)
	         * 修复同步到 minio s3 时，避免重复创建 object 导致同步失败的问题. [#1672]
	         * 默认打开 session 变量 `explicit_defaults_for_timestamp`，使得 mysql 和上游 TiDB 行为一致 . [#1659](https://github.com/pingcap/ticdc/pull/1659)
	         * 修复错误的处理 io.EOF 问题，导致同步中断的问题. [#1648](https://github.com/pingcap/ticdc/pull/1648)
	        * 修复 TiKV CDC endpoint CPU 统计信息. [#1645](https://github.com/pingcap/ticdc/pull/1645)
	        * 增加 defaultBufferChanSize 来避免某些情况下同步阻塞的问题 [#1632](https://github.com/pingcap/ticdc/pull/1632)
```

2021-04-20 09:37 UTC, 3pointer commented on releases/release-5.0.1.md
> +
+Tools
	   - BR
	       * 删除 summary 日志中一些容易误解的信息. [#1009](https://github.com/pingcap/br/pull/1009)

2021-04-21 11:38 UTC, nolouch commented on releases/release-5.0.1.md
> +
```suggestion
+ PD

    - 改善 Region 分数公式使其更适用异构集群问题 [#1009](https://github.com/pingcap/br/pull/1009)
    - 避免在添加 `scatter range` 后的非预期统计行为 [#3602](https://github.com/pingcap/pd/pull/3602)
```

2021-04-22 10:09 UTC, 5kbpers commented
/lgtm

2021-04-22 10:17 UTC, solotzg commented
lgtm

2021-04-22 12:10 UTC, winoros commented on releases/release-5.0.1.md
> +    - 修复因错误比较二进制与字节导致的错误 `TableDual` 计划
```suggestion
    - 修复因错误比较二进制与字节导致的错误 `TableDual` 计划 [#23918](https://github.com/pingcap/tidb/pull/23918)
```

2021-04-23 02:19 UTC, 3pointer commented
/lgtm

2021-04-23 04:26 UTC, qiancai requested changes

2021-04-23 04:26 UTC, qiancai commented on releases/release-5.0.1.md
> +        - 修复备份时不能容忍少部分 TiKV 节点不可用的问题 [#1019](https://github.com/pingcap/br/pull/1019)
“不能容忍” 看起来有些奇怪。依据原 PR，修改的点是实现 ignore all ‘failed to connect to store’ errors during backup. 请看看是否可以进行如下修改，如果可以，请在英文版也做出对应修改。

```suggestion
        - 修复少数 TiKV 节点不可用时备份报错的问题 [#1019](https://github.com/pingcap/br/pull/1019)
```

2021-04-23 04:26 UTC, qiancai commented on releases/release-5.0.1.md
> +        - 修复 Unified Sorter 中的并发问题并改进无用的错误消息 [#1678](https://github.com/pingcap/ticdc/pull/1678)
"改进无用的错误消息"看起来有歧义, 是 “屏蔽无用的错误消息”的意思呢， 还是 “提供有用的错误消息”的意思？可能需要请研发帮忙确认下？

2021-04-23 05:18 UTC, TomShawn commented on releases/release-5.0.1.md
> +    - 修复了 Coprocessor 的 `IN` 表达式未正确处理有符号整数或无符号整数类型数据的问题 [#10018](https://github.com/tikv/tikv/pull/10018)
@5kbpers @lzmhhh123 PTAL

2021-04-23 05:19 UTC, TomShawn commented on releases/release-5.0.1.md
> +        - 修复备份时不能容忍少部分 TiKV 节点不可用的问题 [#1019](https://github.com/pingcap/br/pull/1019)
@3pointer PTAL

2021-04-23 06:14 UTC, TomShawn commented on releases/release-5.0.1.md
> +    - 修复 `bitwise` 操作和 TiDB 行为不一致的问题
是的
```suggestion
    - 修复 `bitwise` 算子和 TiDB 行为不一致的问题
```

2021-04-23 06:29 UTC, TomShawn commented on releases/release-5.0.1.md
> +        - 修复 Unified Sorter 中的并发问题并改进无用的错误消息 [#1678](https://github.com/pingcap/ticdc/pull/1678)
根据 https://github.com/pingcap/ticdc/pull/1678 这个 PR，似乎是【过滤无用的错误消息】

2021-04-23 06:29 UTC, TomShawn commented on releases/release-5.0.1.md
> +        - 修复 Unified Sorter 中的并发问题并改进无用的错误消息 [#1678](https://github.com/pingcap/ticdc/pull/1678)
```suggestion
        - 修复 Unified Sorter 中的并发问题并过滤无用的错误消息 [#1678](https://github.com/pingcap/ticdc/pull/1678)
```

2021-04-23 06:31 UTC, 3pointer commented on releases/release-5.0.1.md
> +        - 修复备份时不能容忍少部分 TiKV 节点不可用的问题 [#1019](https://github.com/pingcap/br/pull/1019)
lgtm

2021-04-23 06:34 UTC, TomShawn commented on releases/release-5.0.1.md
> +        - 修复备份时不能容忍少部分 TiKV 节点不可用的问题 [#1019](https://github.com/pingcap/br/pull/1019)
@qiancai 根据 @3pointer ，下面的说法更准确
```suggestion
        - 修复备份期间少数节点挂掉导致的备份中断问题 [#1019](https://github.com/pingcap/br/pull/1019)
```

2021-04-23 06:40 UTC, lzmhhh123 commented on releases/release-5.0.1.md
> +    - 修复了 Coprocessor 的 `IN` 表达式未正确处理有符号整数或无符号整数类型数据的问题 [#10018](https://github.com/tikv/tikv/pull/10018)
LGTM

2021-04-23 06:51 UTC, TomShawn commented on releases/release-5.0.1.md
> +    - 修复了 Coprocessor 的 `IN` 表达式未正确处理有符号整数或无符号整数类型数据的问题 [#10018](https://github.com/tikv/tikv/pull/10018)
英文已修改 https://github.com/pingcap/docs/pull/5392/files#r618980195.

2021-04-23 07:06 UTC, TomShawn commented on releases/release-5.0.1.md
> +    - 调整 Region 分数公式使其更适用于异构集群 [#1009](https://github.com/pingcap/br/pull/1009)
```suggestion
    - 调整 Region 分数公式使其更适用于异构集群 [#3605](https://github.com/pingcap/br/pull/3605)
```

2021-04-23 07:22 UTC, qiancai commented
/lgtm

2021-04-23 07:24 UTC, TomShawn commented on releases/release-5.0.1.md
> +    - 修复了在 `cast_string_as_time` 中输入非法的 UTF-8 字节后导致 panic 的问题 [#9995](https://github.com/tikv/tikv/pull/9995)
```suggestion
    - 修复了在 `cast_string_as_time` 中输入非法的 UTF-8 字节后导致崩溃的问题 [#9995](https://github.com/tikv/tikv/pull/9995)
```

2021-04-24 22:25 UTC, TomShawn commented on releases/release-5.0.1.md
> +发版日期：2021 年 4 月 23 日
```suggestion
发版日期：2021 年 4 月 24 日
```

2021-04-24 22:26 UTC, TomShawn commented
/unhold
/label require-LGT1

2021-04-24 22:26 UTC, TomShawn commented
/merge

2021-04-24 22:29 UTC, merged