fix typo error by zhlint(zh.md)
pingcap/docs-cn pull request #6634
Opened 2021-07-06 09:18 UTC by WPH95

2021-07-06 09:21 UTC, TomShawn requested changes

2021-07-06 09:21 UTC, TomShawn commented on encryption-at-rest.md
> +# 静态加密<span class="version-mark">从 v4.0.0 版本开始引入</span>
```suggestion
# 静态加密 <span class="version-mark">从 v4.0.0 版本开始引入</span>
```

2021-07-06 09:21 UTC, TomShawn commented on encryption-at-rest.md
> +## TiFlash 静态加密<span class="version-mark">从 v4.0.5 版本开始引入</span>
```suggestion
## TiFlash 静态加密 <span class="version-mark">从 v4.0.5 版本开始引入</span>
```

2021-07-07 13:08 UTC, TomShawn commented on exporting-grafana-snapshots.md
> +可以通过访问 <https://metricstool.pingcap.com> 来使用 MetricsTool。它主要提供以下三种功能：
如果文档中出现非闭合的标签，CircleCI 会报错
```suggestion
可以通过访问 `<https://metricstool.pingcap.com>` 来使用 MetricsTool。它主要提供以下三种功能：
```

2021-07-07 13:09 UTC, TomShawn commented on garbage-collection-overview.md
> +3. Do GC. 该阶段每个 TiKV 节点将会各自扫描该节点上的数据，并对每一个 key 删除其不再需要的旧版本。
这里还是应当视作中文句子。
```suggestion
1. Resolve Locks。该阶段会对所有 Region 扫描 safe point 之前的锁，并清理这些锁。
2. Delete Ranges。该阶段快速地删除由于 `DROP TABLE`/`DROP INDEX` 等操作产生的整区间的废弃数据。
3. Do GC。该阶段每个 TiKV 节点将会各自扫描该节点上的数据，并对每一个 key 删除其不再需要的旧版本。
```

2021-07-07 13:10 UTC, TomShawn commented on generate-self-signed-certificates.md
> +也可以参考 OpenSSL 官方的[下载文档](https://www.openssl.org/source)进行安装。
经验证确实有斜线
```suggestion
也可以参考 OpenSSL 官方的[下载文档](https://www.openssl.org/source/)进行安装。
```

2021-07-07 13:11 UTC, TomShawn commented on literal-values.md
> +例：
```suggestion
例如：
```

2021-07-07 13:13 UTC, TomShawn commented on mysql-compatibility.md
> +- TiDB 100% 兼容 MySQL 5.7 协议、MySQL 5.7 常用的功能及语法。MySQL 5.7 生态中的系统工具 (PHPMyAdmin, Navicat, MySQL Workbench, mysqldump, Mydumper/Myloader)、客户端等均适用于 TiDB。
这里也可视作中文句内
```suggestion
- TiDB 100% 兼容 MySQL 5.7 协议、MySQL 5.7 常用的功能及语法。MySQL 5.7 生态中的系统工具 (PHPMyAdmin、Navicat,、MySQL Workbench、 mysqldump、Mydumper/Myloader)、客户端等均适用于 TiDB。
```

2021-07-07 13:13 UTC, TomShawn commented on mysql-compatibility.md
> +- `foreign_key_checks`:
```suggestion
- `foreign_key_checks`：
```

2021-07-07 13:13 UTC, TomShawn commented on mysql-compatibility.md
> +- SQL mode:
```suggestion
- SQL mode：
```

2021-07-07 13:13 UTC, TomShawn commented on mysql-compatibility.md
> +- `lower_case_table_names`:
```suggestion
- `lower_case_table_names`：
```

2021-07-07 13:13 UTC, TomShawn commented on mysql-compatibility.md
> +- `explicit_defaults_for_timestamp`:
```suggestion
- `explicit_defaults_for_timestamp`：
```

2021-07-07 13:15 UTC, TomShawn commented on pd-control.md
> +### `--detach`/`-d`
不建议改标题，因为可能让已有锚点变得无效
```suggestion
### `--detach` / `-d`
```

2021-07-07 13:16 UTC, TomShawn commented on pd-control.md
> +### `--help`/`-h`
```suggestion
### `--help` / `-h`
```

2021-07-11 16:08 UTC, WPH95 commented on garbage-collection-overview.md
> +3. Do GC. 该阶段每个 TiKV 节点将会各自扫描该节点上的数据，并对每一个 key 删除其不再需要的旧版本。
这里的判断是因为前半句是英文 所以被识别成了英语句子。

2021-07-11 16:09 UTC, WPH95 commented on garbage-collection-overview.md
> +3. Do GC. 该阶段每个 TiKV 节点将会各自扫描该节点上的数据，并对每一个 key 删除其不再需要的旧版本。
```suggestion
1. "Resolve Locks" 阶段会对所有 Region 扫描 safe point 之前的锁，并清理这些锁。
2. "Delete Ranges" 阶段快速地删除由于 `DROP TABLE`/`DROP INDEX` 等操作产生的整区间的废弃数据。
3. "Do GC" 阶段每个 TiKV 节点将会各自扫描该节点上的数据，并对每一个 key 删除其不再需要的旧版本。
```

2021-07-11 16:09 UTC, WPH95 commented on garbage-collection-overview.md
> +3. Do GC. 该阶段每个 TiKV 节点将会各自扫描该节点上的数据，并对每一个 key 删除其不再需要的旧版本。
这样会不会更好

2021-07-11 16:10 UTC, WPH95 commented on generate-self-signed-certificates.md
> +也可以参考 OpenSSL 官方的[下载文档](https://www.openssl.org/source)进行安装。
我去优化zhmd 去识别这种情况。这个是一个误判

2021-07-11 16:12 UTC, WPH95 commented on mysql-compatibility.md
> +- TiDB 100% 兼容 MySQL 5.7 协议、MySQL 5.7 常用的功能及语法。MySQL 5.7 生态中的系统工具 (PHPMyAdmin, Navicat, MySQL Workbench, mysqldump, Mydumper/Myloader)、客户端等均适用于 TiDB。
```suggestion
- TiDB 100% 兼容 MySQL 5.7 协议、MySQL 5.7 常用的功能及语法。MySQL 5.7 生态中的系统工具（例如：PHPMyAdmin、Navicat、MySQL Workbench、 mysqldump、Mydumper/Myloader）、客户端等均适用于 TiDB。
```

2021-07-12 02:12 UTC, TomShawn commented on garbage-collection-overview.md
> +3. Do GC. 该阶段每个 TiKV 节点将会各自扫描该节点上的数据，并对每一个 key 删除其不再需要的旧版本。
是的👍

2021-07-15 03:49 UTC, TomShawn commented on pd-control.md
> +    示例：将 `flow-round-by-digit` 的值设为 `4`
```suggestion
    示例：将 `flow-round-by-digit` 的值设为 `4`：
```

2021-07-15 03:49 UTC, TomShawn commented on pd-control.md
> +用于显示 Region 信息。使用 jq 格式化输出请参考[jq-格式化-json-输出示例](#jq-格式化-json-输出示例)。示例如下。
```suggestion
用于显示 Region 信息。使用 jq 格式化输出请参考 [jq-格式化-json-输出示例](#jq-格式化-json-输出示例)。示例如下。
```

2021-07-15 03:50 UTC, TomShawn commented on pd-control.md
> +用于显示 store 信息或者删除指定 store。使用 jq 格式化输出请参考[jq-格式化-json-输出示例](#jq-格式化-json-输出示例)。示例如下。
```suggestion
用于显示 store 信息或者删除指定 store。使用 jq 格式化输出请参考 [jq-格式化-json-输出示例](#jq-格式化-json-输出示例)。示例如下。
```

2021-07-15 03:50 UTC, TomShawn commented on post-installation-check.md
> +其中，`${tidb_server_host_IP_address}`是在[初始化集群拓扑文件](/production-deployment-using-tiup.md#第-3-步初始化集群拓扑文件)时为 `tidb_servers` 配置的 IP 地址之一，例如 `10.0.1.7`。
```suggestion
其中，`${tidb_server_host_IP_address}` 是在[初始化集群拓扑文件](/production-deployment-using-tiup.md#第-3-步初始化集群拓扑文件)时为 `tidb_servers` 配置的 IP 地址之一，例如 `10.0.1.7`。

```

2021-07-15 03:51 UTC, TomShawn commented on scale-tidb-using-tiup.md
> +        > 如果集群中有多个 PD 实例，只需在以上命令中指定一个活跃 PD 实例的IP:端口即可。
```suggestion
        > 如果集群中有多个 PD 实例，只需在以上命令中指定一个活跃 PD 实例的 IP:端口即可。
```

2021-07-15 03:51 UTC, TomShawn commented on scale-tidb-using-tiup.md
> +        > 如果集群中有多个 PD 实例，只需在以上命令中指定一个活跃 PD 实例的IP:端口即可。
```suggestion
        > 如果集群中有多个 PD 实例，只需在以上命令中指定一个活跃 PD 实例的 `IP:端口`即可。
```

2021-07-15 03:51 UTC, TomShawn commented on schedule-replicas-by-topology-labels.md
> +比如集群的拓扑结构分成三层：机房 (zone)-> 机架 (rack)-> 主机(host)，就可以使用这 3 个标签来设置 TiKV 的位置。
```suggestion
比如集群的拓扑结构分成三层：机房 (zone) -> 机架 (rack) -> 主机 (host)，就可以使用这 3 个标签来设置 TiKV 的位置。
```

2021-07-15 03:52 UTC, TomShawn commented on statistics.md
> +<!-- zhlint ignore -->
```suggestion
```

2021-07-15 03:52 UTC, TomShawn commented on system-variables.md
> +>>>>>>> Stashed changes
```suggestion
```

2021-07-15 03:52 UTC, TomShawn commented on system-variables.md
> +<<<<<<< Updated upstream
```suggestion
```

2021-07-15 03:53 UTC, TomShawn commented on table-filter.md
> +* [BR](/br/backup-and-restore-tool.md):
```suggestion
* [BR](/br/backup-and-restore-tool.md)：
```

2021-07-15 03:53 UTC, TomShawn commented on table-filter.md
> +* [Dumpling](/backup-and-restore-using-dumpling-lightning.md):
```suggestion
* [Dumpling](/backup-and-restore-using-dumpling-lightning.md)：
```

2021-07-15 03:53 UTC, TomShawn commented on table-filter.md
> +* [TiDB Lightning](/tidb-lightning/tidb-lightning-overview.md):
```suggestion
* [TiDB Lightning](/tidb-lightning/tidb-lightning-overview.md)：
```

2021-07-15 03:53 UTC, TomShawn commented on table-filter.md
> +* TiDB Lightning:
```suggestion
* TiDB Lightning：
```

2021-07-15 03:53 UTC, TomShawn commented on table-filter.md
> +* [TiCDC](/ticdc/ticdc-overview.md):
```suggestion
* [TiCDC](/ticdc/ticdc-overview.md)：
```

2021-07-15 03:54 UTC, TomShawn commented on tidb-storage.md
> +<!-- zhlint ignore -->
```suggestion
```

2021-07-15 03:55 UTC, TomShawn commented on tidb-troubleshooting-map.md
> +- 7.1.1 `GC life time is shorter than transaction duration.`事务执行时间太长，超过了 GC lifetime（默认为 10 分钟），可以通过修改系统变量 [`tidb_gc_life_time`](/system-variables.md#tidb_gc_life_time-从-v50-版本开始引入) 来延长 life time，通常情
```suggestion
- 7.1.1 `GC life time is shorter than transaction duration`。事务执行时间太长，超过了 GC lifetime（默认为 10 分钟），可以通过修改系统变量 [`tidb_gc_life_time`](/system-variables.md#tidb_gc_life_time-从-v50-版本开始引入) 来延长 life time，通常情况下不建议修改，因为延长时限可能导致大量老版本数据的堆积（如果有大量 `UPDATE` 和 `DELETE` 语句）。
```

2021-07-15 03:56 UTC, TomShawn commented on tidb-troubleshooting-map.md
> +- 7.1.2 `txn takes too much time.` 事务太长时间（超过 590s）没有提交，准备提交的时候报该错误。可以通过调大 `[tikv-client] max-txn-time-use = 590` 参数，以及调大 `GC life time` 来绕过该问题（如果确实有这个需求）。通常情况下，建议看看业务是否真的需要执行这么长时间的事务。
```suggestion
- 7.1.2 `txn takes too much time`。 事务太长时间（超过 590s）没有提交，准备提交的时候报该错误。可以通过调大 `[tikv-client] max-txn-time-use = 590` 参数，以及调大 `GC life time` 来绕过该问题（如果确实有这个需求）。通常情况下，建议看看业务是否真的需要执行这么长时间的事务。
```

2021-07-15 03:56 UTC, TomShawn commented on tidb-troubleshooting-map.md
> +    - `send request is cancelled.` 请求发送阶段超时，可以排查监控 **Grafana** -> **TiDB** -> **Batch Client**/`Pending Request Count by TiKV` 是否大于 128，确定是否因发送远超 KV 处理能力导致发送堆积。如果 Pending Request 不多，需要排查日志确认是否因为对应 KV
```suggestion
    - `send request is cancelled`。 请求发送阶段超时，可以排查监控 **Grafana** -> **TiDB** -> **Batch Client**/`Pending Request Count by TiKV` 是否大于 128，确定是否因发送远超 KV 处理能力导致发送堆积。如果 Pending Request 不多，需要排查日志确认是否因为对应 KV 有运维变更，导致短暂报出；否则非预期，[需报 bug](https://github.com/pingcap/tidb/issues/new?labels=type%2Fbug&template=bug-report.md)。
```

2021-07-15 03:56 UTC, TomShawn commented on tidb-troubleshooting-map.md
> +    - `wait response is cancelled.` 请求发送到 TiKV 后超时未收到 TiKV 响应。需要排查对应地址 TiKV 的响应时间和对应 Region 在当时的 PD 和 KV 日志，确定为什么 KV 未及时响应。
```suggestion
    - `wait response is cancelled`。请求发送到 TiKV 后超时未收到 TiKV 响应。需要排查对应地址 TiKV 的响应时间和对应 Region 在当时的 PD 和 KV 日志，确定为什么 KV 未及时响应。
```

2021-07-15 03:56 UTC, TomShawn commented on tikv-configuration-file.md
> ++ gRPC 消息的压缩算法，取值：none, deflate, gzip。
```suggestion
+ gRPC 消息的压缩算法，取值：none，deflate，gzip。
```

2021-07-15 03:58 UTC, TomShawn commented on troubleshoot-cpu-issues.md
> +* PD panic. 请[提交 bug](https://github.com/tikv/pd/issues/new?labels=kind/bug&template=bug-report.md)。
```suggestion
* PD panic。请[提交 bug](https://github.com/tikv/pd/issues/new?labels=kind/bug&template=bug-report.md)。

```

2021-07-15 03:58 UTC, TomShawn commented on tune-tikv-thread-performance.md
> +* Raftstore 线程池是 TiKV 最为复杂的一个线程池，默认大小 (`raftstore.store-pool-size`)为 2，所有的写请求都会先在 Raftstore 线程 fsync 的方式写入 RocksDB（除非手动将 `raftstore.sync-log` 设置为 false；而 `raftstore.sync-log` 设置为 false，可以提升一部分写性能，但也会
```suggestion
* Raftstore 线程池是 TiKV 最为复杂的一个线程池，默认大小 (`raftstore.store-pool-size`) 为 2，所有的写请求都会先在 Raftstore 线程 fsync 的方式写入 RocksDB（除非手动将 `raftstore.sync-log` 设置为 false；而 `raftstore.sync-log` 设置为 false，可以提升一部分写性能，但也会增加在机器故障时数据丢失的风险）。
```

2021-07-15 03:58 UTC, TomShawn commented on tune-tikv-thread-performance.md
> +* UnifyReadPool 负责处理所有的读取请求。默认配置 (`readpool.unified.max-thread-count`)大小为机器 CPU 数的 80% （如机器为 16 核，则默认线程池大小为 12）。
```suggestion
* UnifyReadPool 负责处理所有的读取请求。默认配置 (`readpool.unified.max-thread-count`) 大小为机器 CPU 数的 80% （如机器为 16 核，则默认线程池大小为 12）。
```

2021-07-15 03:59 UTC, TomShawn commented on views.md
> +示例；
```suggestion
示例：
```

2021-07-15 04:00 UTC, TomShawn approved these changes
LGTM

2021-07-15 04:01 UTC, TomShawn commented
/merge

2021-07-15 04:01 UTC, TomShawn commented
/merge

2021-07-15 04:05 UTC, merged