Update TiSpark documentation
pingcap/docs-cn pull request #8985
Opened 2022-04-14 05:12 UTC by Oreoxmt

### What is changed, added or deleted? (Required)
- Delete get-started-with-tispark.md
- Update  tispark-overview.md

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [ ] v6.0 (TiDB 6.0 versions)
- [ ] v5.4 (TiDB 5.4 versions)
- [ ] v5.3 (TiDB 5.3 versions)
- [ ] v5.2 (TiDB 5.2 versions)
- [ ] v5.1 (TiDB 5.1 versions)
- [ ] v5.0 (TiDB 5.0 versions)
- [ ] v4.0 (TiDB 4.0 versions)
- [ ] v3.1 (TiDB 3.1 versions)
- [ ] v3.0 (TiDB 3.0 versions)
- [ ] v2.1 (TiDB 2.1 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs/pull/6459
https://github.com/pingcap/docs/pull/8205
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [x] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-04-15 10:18 UTC, xuanyu66 requested changes

2022-04-15 10:18 UTC, xuanyu66 commented on tispark-overview.md
> +> 由于 TiSpark 直接访问 TiKV，所以 TiDB Server 使用的访问控制机制并不适用于 TiSpark。
可以加上目前 TiSpark 实现了部分鉴权与授权功能，具体请看`安全` 那一章

2022-04-18 12:59 UTC, shichun-0415 commented on tispark-overview.md
> +TiSpark 深度整合了 Spark Catalyst 引擎，可以对计算进行精确地控制，使 Spark 能够高效地读取 TiKV 中的数据。TiSpark 还提供了索引支持以实现高速的点查。
```suggestion
TiSpark 深度整合了 Spark Catalyst 引擎，可以对计算进行精确地控制，使 Spark 能够高效地读取 TiKV 中的数据。TiSpark 还提供索引查找，帮助实现高速点查。
```
```suggestion
TiSpark 深度整合了 Spark Catalyst 引擎，可以对计算进行精确地控制，使 Spark 能够高效地读取 TiKV 中的数据。TiSpark 还提供了索引支持以实现高速的点查。
```

2022-04-18 12:59 UTC, shichun-0415 commented on tispark-overview.md
> +TiSpark 深度整合了 Spark Catalyst 引擎，可以对计算进行精确地控制，使 Spark 能够高效地读取 TiKV 中的数据。TiSpark 还提供了索引支持以实现高速的点查。
```suggestion
TiSpark 深度整合了 Spark Catalyst 引擎，可以对计算进行精确地控制，使 Spark 能够高效地读取 TiKV 中的数据。TiSpark 还提供索引查找，帮助实现高速点查。
```
```suggestion
TiSpark 深度整合了 Spark Catalyst 引擎，可以对计算进行精确地控制，使 Spark 能够高效地读取 TiKV 中的数据。TiSpark 还提供了索引支持以实现高速的点查。
```

2022-04-18 13:01 UTC, shichun-0415 commented on tispark-overview.md
> +TiSpark 通过将计算下推到 TiKV 中提升了数据查询的效率，减少了 Spark SQL 需要处理的数据大小，通过利用 TiDB 内置的统计信息选择更优的查询计划。
```suggestion
TiSpark 通过将计算下推到 TiKV 中提升了数据查询的效率，减少了 Spark SQL 需要处理的数据量，通过利用 TiDB 内置的统计信息选择最优查询计划。
```

2022-04-19 05:16 UTC, shichun-0415 commented on tispark-overview.md
> +如果你不需要 Hadoop 支持，请选择 Spark **2.4.x** 版本、带有任意版本 Hadoop 依赖的预编译二进制包，例如 `spark-2.4.8-bin-hadoop2.7.tgz`。如果需要使用 Hadoop 集群（如 Hadoop 2.6 版本），则选择相应的 Hadoop 版本号，例如 `spark-2.4.8-bin-hadoop2.6.tgz`。对于 Hadoop 2.
原文是 hadoop 2.7

2022-04-19 05:16 UTC, shichun-0415 commented on tispark-overview.md
> +其中 `spark.tispark.pd.addresses` 允许输入按逗号 (',') 分隔的多个 PD 服务器，请指定每个服务器的端口号。例如，当你的多个 PD 服务器在 `10.16.20.1,10.16.20.2,10.16.20.3` 的 2379 端口上时，将配置 `spark.tispark.pd.addresses` 为 `10.16.20.1:2379,10.16.20.2:
```suggestion
其中 `spark.tispark.pd.addresses` 允许输入按逗号 (',') 分隔的多个 PD 服务器，请指定每个服务器的端口号。例如，当你有多个 PD 服务器在 `10.16.20.1,10.16.20.2,10.16.20.3` 的 2379 端口上时，将配置 `spark.tispark.pd.addresses` 为 `10.16.20.1:2379,10.16.20.2:2379,10.16.20.3:2379`。
```

2022-04-19 05:16 UTC, shichun-0415 commented on tispark-overview.md
> +./bin/beeline jdbc:hive2://localhost:10000
英文下面还有这一行：Beeline version 1.2.2 by Apache Hive

2022-04-19 08:35 UTC, Oreoxmt commented on tispark-overview.md
> +本部分描述了 TiKV 与 TiSpark 集群分开部署、Spark 与 TiSpark 集群独立部署，以及TiKV 与 TiSpark 集群混合部署的建议配置。
@shichun-0415 https://github.com/pingcap/docs/blob/master/tispark-overview.md?plain=1 跟这里的版本是一致的

2022-04-19 08:39 UTC, Oreoxmt commented on tispark-overview.md
> +如果你不需要 Hadoop 支持，请选择 Spark **2.4.x** 版本、带有任意版本 Hadoop 依赖的预编译二进制包，例如 `spark-2.4.8-bin-hadoop2.7.tgz`。如果需要使用 Hadoop 集群（如 Hadoop 2.6 版本），则选择相应的 Hadoop 版本号，例如 `spark-2.4.8-bin-hadoop2.6.tgz`。对于 Hadoop 2.
> 原文是 hadoop 2.7

这里我添加了一个 Hadoop 2.6 的示例是想要让“如果需要使用 Hadoop 集群，则选择相应的 Hadoop 版本号” 这句话比较容易理解，也就是需要使用的 Hadoop 的版本号体现在 `spark-2.4.8-bin-hadoop2.6.tgz` 上。
因为前一句的示例是 `spark-2.4.8-bin-hadoop2.6.tgz`，为了区分所以我用了 2.6

2022-04-19 09:15 UTC, shichun-0415 approved these changes
LGTM

2022-04-19 09:23 UTC, xuanyu66 approved these changes

2022-04-19 09:24 UTC, xuanyu66 commented
@shiyuhang0 PTAL

2022-04-19 10:03 UTC, shiyuhang0 reviewed
TiSpark 2.5 推荐使用 catalog 的方式，TiSpark 未来版本将强制使用 catalog。
建议这个文档中也加入 catalog 模式的使用方式

2022-04-19 10:41 UTC, Oreoxmt commented on tispark-overview.md
>  {{< copyable "shell-regular" >}}
@shiyuhang0 {{< copyable "shell-regular" >}} 是文档站前端渲染程序需要的 code snippet，在渲染时会自动在代码块前添加命令前缀（$、#等），以及用户可以通过点击 Copy 方式复制代码块。

2022-04-20 03:07 UTC, shiyuhang0 approved these changes

2022-04-20 05:45 UTC, shichun-0415 approved these changes
LGTM

2022-04-20 06:22 UTC, shichun-0415 commented
/remove status LGT1
/status LGT2

2022-04-20 06:25 UTC, shichun-0415 commented
/merge

2022-04-20 06:26 UTC, merged