Docs tiem: add compatible upgrade to 1.0.1
pingcap/docs-cn pull request #9542
Opened 2022-05-19 10:08 UTC by haiboumich

### First-time contributors' checklist 

- [ ] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

tiem: add docs for compatible upgrade to 1.0.1 

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v6.1 (TiDB 6.1 versions)
- [x] v6.0 (TiDB 6.0 versions)
- [x] v5.4 (TiDB 5.4 versions)
- [x] v5.3 (TiDB 5.3 versions)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: N/A
- Other reference link(s): N/A

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-05-19 10:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pingcap/docs-cn?pullRequest=9542) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/docs-cn?pullRequest=9542) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/docs-cn?pullRequest=9542) it.</sub>

2022-05-24 07:26 UTC, haiboumich commented
/merge

2022-05-24 07:27 UTC, haiboumich commented
/assign @TomShawn

2022-05-25 00:35 UTC, zhoubasten approved these changes
LGTM

2022-05-25 13:22 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
+ 开源后用户仍需要从 TiEM 产品团队处获取吗？我理解的是，开源后，直接就从开源仓库中自行下载了。

2022-05-25 13:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    sudo sh em-enterprise-server-v1.0.1-linux-amd64/prepare_upgrade.sh <user> <TiEM 中控机 IP> <cluster-name>
执行这个命令，会自动备份旧版本集群 TiEM 的数据吗？

2022-05-25 13:25 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
>      参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
哪里能找到 update.sh 呢？还是内置在安装包中的呢？

2022-05-25 13:25 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    sudo sh em-enterprise-server-v1.0.1-linux-amd64/prepare_upgrade.sh <user> <TiEM 中控机 IP> <cluster-name>
同上，哪里能找到 prepare_upgrade.sh 呢？还是内置在安装包中的呢？

2022-05-26 02:33 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +> 如果您现在安装的是 TiEM 1.0.0 及以下版本，请参见[兼容性升级 TiEM 1.0.1](#兼容性升级-tiem-101)，先升级到 TiEM 1.0.1 版本，再参考本小节做常规升级。
* 是的，我修改一下。如果按照官方对外的话，的确只有 1.0.0，这里考虑了之前试用的 beta 版本
* 同样我也删除掉，这里描述不严谨，目前的确只有 1.0.0 1.0.1 两个版本，后面发新版本再更新文档。

2022-05-26 02:38 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +由于 TiEM 1.0.1 与 1.0.0 版本存在一些不兼容，不能直接通过常规的升级方式进行升级，故在此特别提供了兼容性升级步骤。
对，我改成了 anchor 方式

2022-05-26 02:41 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +    参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
最终形态和你说的一样。但开源下载这个工作目前还在推进，在前期过程中可能会存在临时解决方案，这一步是和之前的「## 升级 TiEM」描述保持一致。你看如何？

2022-05-26 02:42 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +    sudo sh em-enterprise-server-v1.0.1-linux-amd64/prepare_upgrade.sh <user> <TiEM 中控机 IP> <cluster-name>
> 执行这个命令，会自动备份旧版本集群 TiEM 的数据吗？

会的

2022-05-26 02:42 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +    sudo sh em-enterprise-server-v1.0.1-linux-amd64/prepare_upgrade.sh <user> <TiEM 中控机 IP> <cluster-name>
> 同上，哪里能找到 prepare_upgrade.sh 呢？还是内置在安装包中的呢？

对的，在内置的安装包里

2022-05-26 02:42 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
>      参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
> 哪里能找到 update.sh 呢？还是内置在安装包中的呢？

对，都在内置的安装包里，这些脚本都会开源

2022-05-26 13:38 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
那等可以从仓库下载的时候，请再更新这一部分文档吧。

2022-05-26 13:41 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +我们此次升级的总体步骤为：备份 TiEM 数据、销毁原有 TiEM、重新部署新的 TiEM、恢复 TiEM 数据。并需要用户在执行完上述操作后，在 TiEM 界面操作重启其管理的 TiDB 集群，以使得集群日志功能生效。
是否可以强调一下，这里的数据备份是自动进行的，否则用户会觉得要自己手动去备份。

2022-05-26 13:41 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +2. 做升级 TiEM 之前的准备。
可否提到这里是在做自动数据备份呢？

2022-05-26 13:43 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +## 兼容性升级 TiEM 1.0.1
其实这里非常尴尬。上面刚说完 TiEM 的升级方法，紧接着又说上面的方法不适用于当前唯一可升级的版本。

2022-05-26 13:44 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +我们此次升级的总体步骤为：备份 TiEM 数据、销毁原有 TiEM、重新部署新的 TiEM、恢复 TiEM 数据。并需要用户在执行完上述操作后，在 TiEM 界面操作重启其管理的 TiDB 集群，以使得集群日志功能生效。
这里的「总体步骤」能否和下面的实际步骤对应起来呢？表述能否一致？

2022-05-27 08:46 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +## 兼容性升级 TiEM 1.0.1
> 其实这里非常尴尬。上面刚说完 TiEM 的升级方法，紧接着又说上面的方法不适用于当前唯一可升级的版本。

已经把 [升级 TiEM] 的原有表述去掉了，然后将原有 [兼容性升级 TiEM] 改成了 [升级 TiEM]

2022-05-27 08:52 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +    参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
好的

2022-05-27 08:53 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +我们此次升级的总体步骤为：备份 TiEM 数据、销毁原有 TiEM、重新部署新的 TiEM、恢复 TiEM 数据。并需要用户在执行完上述操作后，在 TiEM 界面操作重启其管理的 TiDB 集群，以使得集群日志功能生效。
比较不太好对应起来，已经把上边的文字描述删除，改成了在每一步中详述

2022-05-27 08:53 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +2. 做升级 TiEM 之前的准备。
好的，在这里描述了

2022-06-01 10:04 UTC, istudies approved these changes
LGTM

2022-06-01 13:29 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +本节适用于已经安装过 TiEM 并打算升级 TiEM 的用户。如首次安装可跳过本节，参考[离线部署 TiEM](#离线部署-tiem) 安装 TiEM 1.0.2。
```suggestion
本节适用于已经安装过 TiEM 并打算升级 TiEM 的用户。如首次安装可跳过本节。
```

2022-06-01 13:29 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +> 如果您现在安装的是 TiEM 1.0.1 版本，请直接参考本小节升级到 TiEM 1.0.2。
```suggestion
> - 本节介绍的方法仅适用于从 TiEM v1.0.1 升级至 v1.0.2 及以上版本，不适用于从 v1.0.0 升级至 v1.0.1 及以上版本。
> - 如果你已安装 TiEM v1.0.0 版本，想要升级至 v1.0.1 及以上版本，则需要先参考[升级 TiEM v1.0.0 至 v1.0.1](#升级-tiem-v100-至-v101) 进行升级，再从 v1.0.1 升级至较新的目标版本。
```

2022-06-01 13:29 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
>      TIUP_HOME=/home/tidb/.em tiup em upgrade <cluster-name> <version>
```suggestion
    TIUP_HOME=/home/tidb/.em tiup em upgrade <cluster-name> <version>
    ```
```

2022-06-01 13:30 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
>  ## 升级 TiEM
```suggestion
## 升级 TiEM v1.0.1 至 v1.0.2 及以上版本
```

2022-06-01 13:50 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
「通过 TiEM 产品团队获得最新 TiEM 离线包」这里需要 @zhoubasten 来更新。

2022-06-01 13:52 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
下面一行命令具体是执行什么操作呢？执行上面所有的操作？

2022-06-01 14:21 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    有些用户可能之前部署 TiEM 1.0.0 时对于 config.yaml 文件做了自定义修改，所以请查看原来的配置文件 config.yaml 和 新的配置文件 config-v1.0.1.yaml 的内容生效部分的区别是否仅为 db_path 那一行。若是请跳过本步骤，若不是请手动执行以下操作。
```suggestion
    如果你在部署 TiEM v1.0.0 时对 `config.yaml` 文件做了自定义修改，请查看原配置文件 `config.yaml` 和新配置文件 `config-v1.0.1.yaml` 生效部分内容的区别是否仅为 `db_path` 那一行。如果 `db_path` 一行为仅有的差别，请跳过本步骤。如果差别不仅仅为 `db_path` 一行，请手动执行以下操作：
```

2022-06-01 14:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +        db_path: "/home/tidb/em-backup-20220511-154415/em.db"
不建议在一个代码块里包含多条命令多个步骤。建议用正文子步骤的形式呈现。一条步骤描述后跟一条命令。

2022-06-02 03:43 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +    参考[离线部署 TiEM](#离线部署-tiem) 中第 1-3 步：通过 TiEM 产品团队获得最新 TiEM 离线包，发送 TiEM 离线安装包至目标集群的 TiEM 中控机，解压离线包。执行更新 TiEM 离线包命令。
> 下面一行命令仅仅是更新离线包吗？还是执行上面所有的操作？

我改了下描述，避免误会

2022-06-02 04:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    1. 切换到 tidb 账号下
```suggestion
    1. 切换至 `tidb` 账号。
```

2022-06-02 04:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +       查看内容生效部分的区别是否仅为 `db_path` 那一行。若是则可跳过本步骤，无须继续后续子步骤，若不是请继续执行后续子步骤。
```suggestion
       对比 `config.ymal` 和 `config-v1.0.1.yaml` 生效内容的差异。如果差异仅为 `db_path` 所在行，则可跳过本步骤，无须执行后续子步骤（备份 `db_path` 以及更新 `config-v1.0.1.yaml`），可直接进入删除 TiEM v1.0.0 的步骤。如果差异不止 `db_path` 所在行，还存在其它差异，则需要继续执行后续子步骤（备份 `db_path` 以及更新 `config-v1.0.1.yaml`）。
```

2022-06-02 04:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +       `db_path` 这一栏是为了在你部署 TiEM v1.0.1 时能够将原先 TiEM v1.0.0 备份的数据恢复回去。
db_path 是不是就是 v1.0.0 备份数据的路径呢？

2022-06-02 04:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +       将子步骤 3 中备份的 `db_path` 填写至 `config-v1.0.1.yaml` ，注意空格的缩进，下面是个例子。
```suggestion
       将子步骤 3（备份 `db_path`）中备份的 `db_path` 填写至 `config-v1.0.1.yaml` ，注意空格的缩进。示例如下：。
```

2022-06-02 04:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    # 注释 db_path，如果不注释，后续对 em 的重启，扩容等操作可能会将数据变更还原
```suggestion
    # 将 db_path 注释掉。如果不注释，后续对 em 进行重启、扩容等操作时 TiEM 可能会将数据变更还原
```

2022-06-02 06:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +        对比 `config.ymal` 和 `config-v1.0.1.yaml` 生效内容的差异。如果差异仅为 `db_path` 所在行，则可跳过本步骤，无须执行后续子步骤（备份 `db_path` 以及更新 `config-v1.0.1.yaml`），可直接进入删除 TiEM v1.0.0 的步骤。如果差异不仅有 `db_path` 所在行，还存在其它差异，则需要继续执行后续子
```suggestion
        对比 `config.yaml` 和 `config-v1.0.1.yaml` 生效内容的差异。如果差异仅为 `db_path` 所在行，则可跳过本步骤，无须执行后续子步骤（备份 `db_path` 以及更新 `config-v1.0.1.yaml`），可直接进入删除 TiEM v1.0.0 的步骤。如果差异不仅有 `db_path` 所在行，还存在其它差异，则需要继续执行后续子步骤（备份 `db_path` 以及更新 `config-v1.0.1.yaml`）。
```

2022-06-02 06:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    3. 记下并拷贝 `db_path`。
```suggestion
    3. 记下 config-v1.0.1.yaml` 中的数据备份路径 `db_path`。
```

2022-06-02 06:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +       `db_path` 为 TiEM v1.0.0 备份数据的路径。在“升级 TiEM 之前的准备”这一步骤时 TiEM 已经自动在 `config-v1.0.1.yaml` 中写好了备份路径，这样部署 TiEM v1.0.1 时能够将备份的 v1.0.0 数据恢复到 v1.0.1。
```suggestion
       `db_path` 为 TiEM 备份数据的路径。在“升级 TiEM 之前的准备”这一步中 TiEM 已经自动在 `config-v1.0.1.yaml` 中写好了默认的 v1.0.1 数据备份路径，此前已备份的 v1.0.0 数据将恢复到该路径下。
```

2022-06-02 06:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +        查看 `config-v1.0.1.yaml` 中 `db_path` 那一行的内容，记下并拷贝该行，示例如下：
```suggestion
        查看 `config-v1.0.1.yaml` 中的 `db_path`，记下该行内容，在以下子步骤 5 中更新 `config-v1.0.1.yaml` 时需要用到该行内容。示例如下：
```

2022-06-02 06:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +       将部署 TiEM v1.0.0 的 `config.yaml` 文件复制一份到 `config-v1.0.1.yaml`。
```suggestion
       将 TiEM v1.0.0 的 `config.yaml` 文件复制一份并覆盖 v1.0.1 的 `config-v1.0.1.yaml`。
```

2022-06-02 06:24 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +       将子步骤 3（备份 `db_path`）中拷贝的 `db_path` 填写至 `config-v1.0.1.yaml`，注意空格的缩进。示例如下：。
```suggestion
        覆盖配置文件后，将子步骤 3 中拷贝的 `db_path` 填写至 `config-v1.0.1.yaml`，注意空格的缩进。示例如下：。
```

2022-06-02 06:28 UTC, haiboumich commented on tiem/tiem-install-and-maintain.md
> +       `db_path` 这一栏是为了在你部署 TiEM v1.0.1 时能够将原先 TiEM v1.0.0 备份的数据恢复回去。
> db_path 是不是就是 v1.0.0 备份数据的路径呢？

是的

2022-06-02 06:32 UTC, TomShawn commented on tiem/tiem-install-and-maintain.md
> +    3. 记下 config-v1.0.1.yaml` 中的数据备份路径 `db_path`。
```suggestion
    3. 记下 `config-v1.0.1.yaml` 中的数据备份路径 `db_path`。
```

2022-06-02 06:39 UTC, TomShawn approved these changes
LGTM

2022-06-02 07:21 UTC, Yuiham requested changes

2022-06-02 07:21 UTC, Yuiham commented on tiem/tiem-release-1.0.2.md
> +- 增加密码过期的功能，优化修改密码的体验
```suggestion
- 增加修改密码功能，首次安装后必须修改密码才能完成登录
```

2022-06-02 08:00 UTC, Yuiham commented
LGTM

2022-06-02 11:12 UTC, Yuiham approved these changes
LGTM

2022-06-02 12:58 UTC, TomShawn commented
/remove-status LGT1
/status LGT3

2022-06-02 12:59 UTC, TomShawn commented
/merge

2022-06-02 13:00 UTC, merged