[Update] Add TiSpark telemetry
pingcap/docs-cn pull request #9659
Opened 2022-06-05 03:20 UTC by Daemonxiao

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-cn) that's required for repo owners to accept my contribution.

### What is changed, added or deleted? (Required)

- TiSpark has telemetry in master branch and will have release the telemetry function in the next version. So we should add TiSpark telemetry instructions in telemtry.md.

### Which TiDB version(s) do your changes apply to? (Required)

**Tips for choosing the affected version(s):**

By default, **CHOOSE MASTER ONLY** so your changes will be applied to the next TiDB major or minor releases. If your PR involves a product feature behavior change or a compatibility change, **CHOOSE THE AFFECTED RELEASE BRANCH(ES) AND MASTER**.

For details, see [tips for choosing the affected versions (in Chinese)](https://github.com/pingcap/docs-cn/blob/master/CONTRIBUTING.md#版本选择指南).

- [x] master (the latest development version)
- [x] v6.1 (TiDB 6.1 versions)
- [x] v6.0 (TiDB 6.0 versions)
- [x] v5.4 (TiDB 5.4 versions)
- [x] v5.3 (TiDB 5.3 versions)
- [x] v5.2 (TiDB 5.2 versions)
- [x] v5.1 (TiDB 5.1 versions)
- [x] v5.0 (TiDB 5.0 versions)
- [x] v4.0 (TiDB 4.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s): [TiSpark Telemetry](https://github.com/pingcap/tispark/blob/master/docs/telemetry.md)

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2022-06-06 06:45 UTC, xuanyu66 requested changes

2022-06-06 06:45 UTC, xuanyu66 commented on telemetry.md
> +当 TiSpark 遥测功能开启时，Spark 在使用 TiSpark 时会发送会将使用情况信息分享给 PingCAP，包括（但不限于）：
Please list the detail message, not `包括（但不限于）`

2022-06-07 05:28 UTC, Daemonxiao commented on telemetry.md
> +当 TiSpark 遥测功能开启时，Spark 在使用 TiSpark 时会发送会将使用情况信息分享给 PingCAP，包括（但不限于）：
Hmmm, but I should follow the format above, such as TiDB, and TiUP. It seems a simple summary is better here.

2022-06-07 08:19 UTC, xuanyu66 commented on telemetry.md
> +当 TiSpark 遥测功能开启时，Spark 在使用 TiSpark 时会发送会将使用情况信息分享给 PingCAP，包括（但不限于）：
LGTM

2022-06-07 08:19 UTC, xuanyu66 approved these changes

2022-06-07 08:53 UTC, TomShawn commented
/label needs-cherry-pick-release-6.1

2022-06-20 08:24 UTC, Daemonxiao commented on telemetry.md
> +当 TiSpark 被使用时，可以通过查看 Spark 日志来了解 TiSpark 收集的使用情况信息内容，需要把 Spark 日志级别调至 INFO 或更低，例如：
@shichun-0415 Thanks for your review. I have commit suggestion.

2022-06-20 08:25 UTC, shichun-0415 approved these changes
LGTM

2022-06-20 08:25 UTC, shichun-0415 commented
/remove status LGT1
/status LGT2

2022-06-20 09:34 UTC, shichun-0415 commented
/merge

2022-06-20 09:40 UTC, merged